### PR TITLE
 Next.js Documentation are Added Under Official Docs

### LINKED ISSUE #1141: [Add] I want to add Nextjs Doc
### Site URL

https://nextjs.org/

### Description of the above provided site

**The Next.js Documentation Website: Your comprehensive resource for building modern, server-rendered React applications with blazing-fast performance and a rich ecosystem.**

### Category

Frontend

### Sub Category

N/A

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Nishitbaria**
Next.js Documentation are Added in Official Docs in Resources

## Fixes Issue
Closes  #1141

## Changes proposed

Offical Documentation for Django is added under Offical Docs Section

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@rupali-codes Please Review and  Merge my PR

**Comment by Nishitbaria** [comment]
@rupali-codes Please Review and Merge my PR

**Comment by rupali-codes** [comment]
@Nishitbaria could you please update the description because it looks kinda similar to others

**Comment by Nishitbaria** [comment]
**@rupali-codes**  Please review my PR

**Review by rupali-codes — APPROVED** [review]

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Pull request merged**
