### PR TITLE
Search

### LINKED ISSUE #903: [BUG] <Changing the search button design and color>
### Description

I want to change the search button design and it's color scheme to match with the main website
@CBID2 @rupali-codes Please assign me in this

### Screenshots

_No response_

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Soumyajit2825**
## Fixes Issue
Screenshot 2023-06-03 002008
<br>
Fixes this issue 😄 

This closes #903 

## Changes proposed
Changed the button style and the color scheme of the search button

## Screenshots
Screenshot 2023-06-03 002235
<br>
Screenshot 2023-06-03 002227

## Note to reviewers
Please say if any more changes needed

### CODE REVIEW

**Comment by CBID2** [comment]
Hold on @Soumyajit2825. I want to see @rupali-codes' review first.

**Comment by Soumyajit2825** [comment]
> Hold on @Soumyajit2825. I want to see @rupali-codes' review first.

@CBID2 Okay sure!

**Comment by Soumyajit2825** [comment]
@rupali-codes Please let me know if more changes needed!!

**Comment by rupali-codes** [comment]
Wait @Soumyajit2825. @CBID2 we have already made this changes in a sperate PR na , checkout [this](https://github.com/rupali-codes/LinksHub/pull/901)

🤷‍♀️🤷‍♀️
image

**Comment by Soumyajit2825** [comment]
> Wait @Soumyajit2825. @CBID2 we have already made this changes in a sperate PR na , checkout [this](https://github.com/rupali-codes/LinksHub/pull/901)
> 
> 🤷‍♀️🤷‍♀️ image

He he 😄 
It's already done
Then please close this issue as well as this PR

**Comment by CBID2** [comment]
> > Wait @Soumyajit2825. @CBID2 we have already made this changes in a sperate PR na , checkout [this](https://github.com/rupali-codes/LinksHub/pull/901)
> 
> > 
> 
> > 🤷‍♀️🤷‍♀️ image
> 
> 
> 
> He he 😄 
> 
> It's already done
> 
> Then please close this issue as well as this PR

Oops

**Pull request closed without merging**
