### PR TITLE
chore: added Hoppscotch

### PR DESCRIPTION
**Pull request by Toyin5**
Added hoppscotch to backend - testing

### CODE REVIEW

**Comment by Toyin5** [comment]
@CBID2 @Anmol-Baranwal @rupali-codes 
Pls review

**Review by CBID2 — APPROVED** [review]
Hi [Contributor Name]! :) Well done! :) As you continue your open source journey, always fill out every section of the pull request form. It helps maintainers and others understand how to go about reviewing your contribution. For more tips, check out [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hi @Toyin5! I just realized that one of the commits from your other PR has made it to this PR(it’s this one: https://github.com/rupali-codes/LinksHub/pull/1892/commits/a304555f330d82bab42e41b8b5a09400c8b702e0). You can remove it by doing `git revert`. Learn more about it in this article here: https://www.cloudbees.com/blog/git-revert-explained

**Comment by Anmol-Baranwal** [comment]
@Toyin5 
Raise a fresh PR, and don't edit other files.

**Pull request closed without merging**
