### PR TITLE
added resource for web3-metaverse under Youtube

### LINKED ISSUE #1113: [Add] youtube playlist for blockchain & Web 3
### Site URL

https://www.youtube.com/playlist?list=PLsyeobzWxl7oY6tZmnZ5S7yTDxyu4zDW-

### Description of the above provided site

This is course by Telusko for Web3 and Blockchain

### Category

Youtube

### Sub Category

Web3 & Metaverse

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Swapnil-Singh-99**
## Fixes Issue
Closes #1113 

## Changes proposed

Added Telukso course for Web3 Metaverse

## Screenshots
image

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by rupali-codes — CHANGES_REQUESTED** [review]
@Swapnil-Singh-99 Please don't over-do anything, keep the changes to your issue specifically 

Kindly remove the external changes you've made. And feel free to raise new issues for the improvements :)

Thanks

**Review by k-deepak04 — APPROVED** [review]

**Comment by Swapnil-Singh-99** [comment]
@rupali-codes I have updated the following changes asked by you 
Please review them

**Review by rupali-codes — COMMENTED** [review]
Please format your code

**Comment by Swapnil-Singh-99** [comment]
@rupali-codes I have formated the code

**Comment by Swapnil-Singh-99** [comment]
@rupali-codes Please review this

**Pull request merged**
