### PR TITLE
feat: add suggestions to search bar

### LINKED ISSUE #600: [Feature] <adding suggestions to search bar>
### Description

I want to add the nearest word suggestions to the search bar , can you please add it to the GSSOC'2023

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by k-deepak04**
## Screenshots

image

image

image

https://github.com/rupali-codes/LinksHub/assets/96341431/18015129-647e-4e23-8b66-b767de3bcfc2

### CODE REVIEW

**Comment by k-deepak04** [comment]
@CBID2 @rupali-codes please review and merge this one.

**Comment by k-deepak04** [comment]
i have added few words for recommend , we can add more if you want.

**Review by CBID2 — DISMISSED** [review]
LGTM

**Comment by k-deepak04** [comment]
@rupali-codes review and merge so that i can work on some other issue.

**Review by rupali-codes — CHANGES_REQUESTED** [review]
its looks nice though, but currently its looping these static categories, could you please loop through the subcategories instead? You may all these subcategories in [./types/index.ts](https://github.com/rupali-codes/LinksHub/blob/main/types/index.ts) file. Let me know if you need any kinda help

**Comment by k-deepak04** [comment]
> its looks nice though, but currently its looping these static categories, could you please loop through the subcategories instead? You may all these subcategories in [./types/index.ts](https://github.com/rupali-codes/LinksHub/blob/main/types/index.ts) file. Let me know if you need any kinda help

okay sure......actually i didn't knew where the categories were there i will do it and add commit

**Comment by k-deepak04** [comment]
@rupali-codes i tried using the data from types/index.ts and was unable to do that so i commented the code and for now replaced the thing with updated array.
i will try to fix that and see what's going wrong, if you can uncomment it at your end and see it would be great.
i was getting TypeError: Cannot read properties of undefined (reading 'forEach').
i guess for the time being we can proceed with this till i find an possible solution to my error and integrate that.
please review and merge it
Thanks :)

**Review by rupali-codes — COMMENTED** [review]
This is not gonna work as when category will gets updated this won't work, or the contributor will have to add the sites here as well

**Comment by k-deepak04** [comment]
@rupali-codes check this again, i guess now it is working and user won't have to add things twice.
i have changed type to const and now whole things is working, please let me know if it's okay

**Comment by k-deepak04** [comment]
not creating any error anywhere, i have tested and all things are working properly

**Comment by k-deepak04** [comment]
@CBID2 @rupali-codes please add the labels, otherwise this pr won't be considered in gssoc

**Pull request merged**
