### PR TITLE
Fix searchbar query persist even after clearing the searchbar

### PR DESCRIPTION
**Pull request by Ameya02**
## Fixes Issue
Closes Issue #1518 

## Changes proposed
When searchbar is cleared it go back to the home page if  the url contain a query tag or it will remain on the same page if a query tag isn't present

## Screenshots

https://github.com/rupali-codes/LinksHub/assets/65841021/6c58e7ea-fce5-4d0b-9617-281400662d11

### CODE REVIEW

**Comment by CBID2** [comment]
@Ameya02, can you provide a screenshot of your contribution? It'll add more context to your pull request.

**Comment by Ameya02** [comment]
Done

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

@Ameya02 
> Just tell me on one thing,

Where is this used? `SEARCH_ERROR_MSG`

**Comment by CBID2** [comment]
Thanks for contributing @Ameya02! 😄  It was wonderful working with you! 😄 If you want to stay updated on LinksHub, join our [Discord community](https://discord.com/invite/NvK67YnJX5)! :) We'd love to have you! :)

**Comment by Anmol-Baranwal** [comment]
@Ameya02 
Make sure to properly check whether you have linked issue, there are predefined keywords for the same. I've done it for you. Please make sure to do it properly next time as linked issues are not closed due to this.
Thanks for the contribution.

**Comment by Ameya02** [comment]
Thanks for that I will properly mention the  issue next time

**Pull request merged**
