### PR TITLE
Create php.json

### LINKED ISSUE #2077: [Feature] <write a small description here>
### Description

I think there we can add a new file in JSON for PHP language. It can be very help full.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by Alisha-786**
## Fixes Issue
resolves #2077 

- I have added a new file in JSON for the PHP language. It can be beneficial. It fixes the above-mentioned issue.
## Note to reviewers
Please review my code and if there is any issue, Let me know :).

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@Alisha-786 
Following the PR template is a must. It includes special words like 'fixes' or 'resolves' that connect your issue to the PR, as explained in the official docs.

If you don't link the issue correctly, even after the PR is merged, the issue might stay open, causing huge problems.

> You can see here.
image


I'm doing it for you this time. Please ensure it next time.

Just a heads-up to help you link issue properly next time. Have a great day!

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
@Alisha-786 
The subcategory won't be created by just adding a php json. Follow the contributing guidelines.

**Comment by rupali-codes** [comment]
@Alisha-786 are you still working on this PR?

**Comment by Alisha-786** [comment]
Sorry for the delay. I have made changes can you please check and if there is some problem then tell me.

**Comment by Anmol-Baranwal** [comment]
@Alisha-786 
Is it deploying locally?

**Comment by Anmol-Baranwal** [comment]
@Alisha-786 
I'm closing this issue due to inactivity. Please feel free to reopen it if you'd like to contribute or have further discussions.

**Pull request closed without merging**
