### PR TITLE
Feat: Sync overlay transition with sidebar transition in mobile view

### LINKED ISSUE #1007: [Style] Sync overlay transition with sidebar transition in mobile view
### What would you like to share or ask?

When in mobile view, one has to click the hamburger to open the sidebar. And when the sidebar is open, there is dark background overlay. But the transitioning of this overlay is not in sync with the transitioning of the sidebar, and it kind of feels sudden. So I think it would slightly enhance the UI if the background overlay properly transitions-in in sync with the transitioning of the sidebar.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by JakubChorzepa**
## Fixes Issue
Closes #1007

## Note to reviewers
Used existing react-transition-state library with useTransition hook.

### CODE REVIEW

**Review by CBID2 — COMMENTED** [review]
Looks ok

**Review by rupali-codes — COMMENTED** [review]
could you please describe what changes you've made?

**Comment by JakubChorzepa** [comment]
> could you please describe what changes you've made?

Yeah, I've added status and toggle function at component mount using react-transition-state so that now when Backdrop is entering it is transparent and when it is entered it changes its to full visibility.

It allows to add transition so now when side bar is opening the backdrop does not appear instantly after hamburger menu click, it enters with delay and smooth transition.

The transition is optional if we don't pass transition in Backdrop class name while using component it won't have it.

**Comment by rupali-codes** [comment]
> > could you please describe what changes you've made?
> 
> Yeah, I've added status and toggle function at component mount using react-transition-state so that now when Backdrop is entering it is transparent and when it is entered it changes its to full visibility.
> 
> It allows to add transition so now when side bar is opening the backdrop does not appear instantly after hamburger menu click, it enters with delay and smooth transition.
> 
> The transition is optional if we don't pass transition in Backdrop class name while using component it won't have it.

thanks

**Review by rupali-codes — APPROVED** [review]
lgtm

**Review by k-deepak04 — APPROVED** [review]

**Comment by k-deepak04** [comment]
@rupali-codes plz merge this, i'm not getting the option to do so.

**Pull request merged**
