### PR TITLE
#2071 Pagination buttons added at top-right corner

### PR DESCRIPTION
**Pull request by nayansinghal23**
## Fixes Issue
I have worked on Issue#2071

## Changes proposed

1) Added the pagination buttons at the top-right corner of the page without removing them from the bottom.
2) Maintained site's responsiveness while fixing this.

## Screenshots
img-1
img-2

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
This seems to be similar to #2181 right?

**Comment by CBID2** [comment]
> @rupali-codes 
> 
> This seems to be similar to #2181 right?

Yeah it is @Anmol-Baranwal. How should we go about fixing this? 😊

**Comment by Anmol-Baranwal** [comment]
> > @rupali-codes
> > This seems to be similar to #2181 right?
> 
> Yeah it is @Anmol-Baranwal. How should we go about fixing this? 😊

This will eventually be closed. I explained you on discord @nayansinghal23 

You need to create an issue and allow us to assign you the issue before you start working and submit a PR. Not following this process will require us to close your pull request.

This is outlined in the contributing guidelines.
image

You need to follow a predefined flow in order to contribute to Open Source. You may be new, so it is important to understand this. Most of the maintainers will mark it as spam and close it.

**Comment by rupali-codes** [comment]
hey @nayansinghal23 we appreciate your contributions and the efforts you put in making these changes, but we already have a PR regarding this issue. So, we're closing your PR, please follow the contributing guidelines before starting to work on any issue. 

You can look for unassigned issues, or create new issues in order to contribute. 
Thanks.

**Pull request closed without merging**
