### PR TITLE
Added official documentation to resource section

### LINKED ISSUE #824: [ADD] <Official Docs>
### Category Name

Resources 

### Subcategory Name

Official Docs

## Suggestion

Official documentation plays a pivotal role in a developer's journey, as it provides comprehensive and authoritative information about the language's syntax, libraries, frameworks, and best practices.
By including links to official documentation in the resource section, developers using LinksHub would have easy access to the most up-to-date and reliable information for their preferred programming languages.

## Preview of what I'm suggesting

Screenshot 2023-05-30 at 12 41 55 AM

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by manasi-jain**
## Fixes Issue
Closes #824

## Changes proposed

Add official documentation to resource section

This commit adds official documentation for different programming languages to the resource section. Official documentation is a valuable resource for developers and will greatly enhance the usefulness of LinksHub. Users can now easily access and refer to official documentation while exploring resources on LinksHub.

## Changes made

- Added official docs subcategory under resource category
- Added official documentation links for various programming languages.
- Organized the documentation links under the resource section.

## Screenshots

Screenshot 2023-05-30 at 12 41 55 AM

## Note to reviewers
Any kind of feedback would be appreciated

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Comment by rupali-codes** [comment]
@manasi-jain i'm unable to review the PR, its saying 0 files changed, have you deleted the files after commining?

image

**Review by rupali-codes — CHANGES_REQUESTED** [review]
hey, it looks good though, but could you please rename the file to _official-docs.json_?

**Review by CBID2 — DISMISSED** [review]
Git Merge GIF

**Comment by manasi-jain** [comment]
> hey, it looks good though, but could you please rename the file to _official-docs.json_?

Hey @rupali-codes I have made the changes and renamed the file to official-docs.json.

**Comment by manasi-jain** [comment]
> Hey ! It appears that there are merge conflicts within your changes. Please resolve these conflicts !!

Hey! I have resolved the merge conflicts within the changes.

**Review by rupali-codes — APPROVED** [review]
looks great to me

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Pull request merged**
