### PR TITLE
Added 'Open Source Contributions' to 'OPENSOURCE'

### PR DESCRIPTION
**Pull request by Rutujeet**
## Screenshots

image

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks good @Rutujeet! 😊 LGTM! 😊

**Review by rupali-codes — APPROVED** [review]
looks good

**Comment by rupali-codes** [comment]
@Rutujeet could you please resolve merge conflicts?

**Comment by Rutujeet** [comment]
@rupali-codes What do I do?
Screenshot 2023-05-23 at 12 50 02 PM

**Comment by Rutujeet** [comment]
Made another PR #670 by resolving conflicts. Do check it out once.

**Comment by Rutujeet** [comment]
> @Rutujeet could you please resolve merge conflicts?

Made another PR https://github.com/rupali-codes/LinksHub/pull/670 by resolving conflicts. Do check it out once.

**Comment by rupali-codes** [comment]
> > @Rutujeet could you please resolve merge conflicts?
> 
> Made another PR #670 by resolving conflicts. Do check it out once.

You dont have to create a sperate PR,

**Comment by Rutujeet** [comment]
> > > @Rutujeet could you please resolve merge conflicts?
> 
> > 
> 
> > Made another PR #670 by resolving conflicts. Do check it out once.
> 
> 
> 
> You dont have to create a sperate PR, 

Understood 👍🏽

**Pull request merged**
