### PR TITLE
Added typewriter effect in home page to show all categories we have

### PR DESCRIPTION
**Pull request by pramodreddypandiri**
## Changes proposed
Added one more div in Home page that tells about categories(ex : colors, validation, blogs) we have and guides to use menu to navigate.

## Screenshots

TypeWiterEffect
TypewriterEffect2

## Note to reviewers

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
Hi, Thank you so much, It looks perfect. But could you please package-lock.json from this PR?

**Comment by pramodreddypandiri** [comment]
> Hi, Thank you so much, It looks perfect. But could you please package-lock.json from this PR?

Sorry, I did not get it . Can you elaborate more.

**Comment by rupali-codes** [comment]
> > Hi, Thank you so much, It looks perfect. But could you please package-lock.json from this PR?
> 
> Sorry, I did not get it . Can you elaborate more.

Could you remove package-lock.json from this PR?

**Comment by pramodreddypandiri** [comment]
Ok, will do that and let you know

**Comment by pramodreddypandiri** [comment]
Hello, I removed package-lock.json

**Review by rupali-codes — COMMENTED** [review]
Hi, can you please close this PR and create a new one, cz if we will merge this PR then it's gonna delete package-lock.json from the repo. So just create a new PR and commit only `index.jsx` and `package.json`

**Comment by pramodreddypandiri** [comment]
ok

**Pull request closed without merging**
