### PR TITLE
added: arduino under internet_of_things

### LINKED ISSUE #2042: [ADD] New link for internet_of_things
### Category Name

internet_of_things

### Subcategory Name

arduino

### Additional Context

# Description 
The subcategory contains link to Introduction to IOT with Arduino course for beginners by freecodecamp which is helpful for the beginners to start their career in field of IOT.

# Link to the course
https://www.freecodecamp.org/news/create-your-own-electronics-with-arduino-full-course

# Category
internet_of_things

# Sub Category
arduino

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by subhayudutta**
## Fixes Issue
Closes #2042

## Changes proposed

Added Arduino under internet_of_things category

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@subhayudutta 
You haven't created an issue. Please create an issue, and tag me.

Please review the contributing guidelines. Once we approve and assign you to this issue, your pull request will be reopened. 

You need to follow a predefined flow in order to contribute to Open Source. You may be new, so it is important to understand this. Most of the maintainers will mark it as spam and close it. I'm converting this into a draft for now.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal sir, I have created an issue for the pull request. Please check.

reference it in the pr description as per the template: fixes `#issuenumber`

and can you let me know which issue is that.

**Comment by subhayudutta** [comment]
@Anmol-Baranwal sir, You have assigned me issue #2042. Please review my PR and allow it to merge.

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
You need to create structure in other files as mentioned in contributing guidelines.

Please follow it and check locally if the subcategory is visible.

image

**Comment by subhayudutta** [comment]
@Anmol-Baranwal sir, I have updated the changes that you told. Please review my PR and allow it to merge.

**Review by rupali-codes — CHANGES_REQUESTED** [review]
@subhayudutta can you please add a few more resouces?

**Comment by subhayudutta** [comment]
@rupali-codes I don't have other resources. Please review and merge.

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
@subhayudutta 
Please add a description.

image

Category descriptions file would be in TopBar component

**Comment by Anmol-Baranwal** [comment]
@subhayudutta 
Why did you delete the branch?

**Pull request closed without merging**
