### PR TITLE
Spellcheck

### LINKED ISSUE #1080: [Feature] GitHub Action to catch spelling errors
## Problem 
Throughout my experience reviewing the sources contributors want to add to LinksHub, there has been something that's been recurring: misspellings in the descriptions section. 
## Possible Solution
Easier one: Creating a workflow based on this [GitHub action](https://github.com/marketplace/actions/check-spelling) <--- This is what I'm leaning towards. 
Possibly hard: Adding this [spell checker](https://www.npmjs.com/package/spelling).

## Additional information
I'm willing to collaborate with any contributor on this issue.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by k-deepak04**
## Issues
Closes #1080 

## Changes proposed

The GitHub Action will now automatically run codespell on your JSON files every time you push to the main branch or open a new pull request. If it detects any spelling errors, the Action will fail, indicating that you need to fix the identified issues.

### CODE REVIEW

**Comment by k-deepak04** [comment]
@CBID2 have a look at this once.
tried this for you 🙌

**Comment by CBID2** [comment]
> @CBID2 have a look at this once.
> 
> tried this for you 🙌

Have you ran it locally? That's the problem I had

**Comment by k-deepak04** [comment]
> > @CBID2 have a look at this once.
> > tried this for you 🙌
> 
> Have you ran it locally? That's the problem I had

yep tried i have attached the ss in the issue one kindly check

**Comment by CBID2** [comment]
> > > @CBID2 have a look at this once.
> 
> > > tried this for you 🙌
> 
> > 
> 
> > Have you ran it locally? That's the problem I had
> 
> 
> 
> yep tried i have attached the ss in the issue one kindly check

Ok

**Comment by CBID2** [comment]
> > > @CBID2 have a look at this once.
> 
> > > tried this for you 🙌
> 
> > 
> 
> > Have you ran it locally? That's the problem I had
> 
> 
> 
> yep tried i have attached the ss in the issue one kindly check

I don't see it

**Comment by k-deepak04** [comment]
check #1174 for ss, i have moulded this one for testing the JSON file only as the contributors write's description mainly in that file.

**Comment by CBID2** [comment]
So should I close this one?

**Comment by k-deepak04** [comment]
> So should I close this one?

guess so by merging this pr, it will detect the errors most probably, pmeanwhile you can close that issue and assign me add label to this pr :)

**Review by CBID2 — DISMISSED** [review]
LGTM

**Comment by k-deepak04** [comment]
@rupali-codes please review this one too

**Comment by k-deepak04** [comment]
@CBID2 please add tags on this pr :)

**Review by rupali-codes — COMMENTED** [review]
@k-deepak04 we had some issues previously, hope you've tested it well?

**Comment by rupali-codes** [comment]
@k-deepak04 please remove the commit of your another PR (adding new maintainer)

**Comment by k-deepak04** [comment]
> @k-deepak04 please remove the commit of your another PR (adding new maintainer)

okay

**Comment by k-deepak04** [comment]
@rupali-codes check now

**Comment by k-deepak04** [comment]
@rupali-codes please check and merge

**Pull request merged**
