### PR TITLE
feat: add missing subcategories in order

### LINKED ISSUE #1060: [BUG] add missing subcategories
### Description

`types/index.ts` is missing some subcategories.

I would like to add the missing ones in sorted order.

It lacks subcategories such as `React`, `c-programming`, and several others.

Code:
```typescript
export type SubCategory =
  | 'images'
  | 'icons'
  | 'illustrations'
  | 'colors'
  | 'css'
  | 'fonts'
  | 'animations'
  | 'testing'
  | 'themes-templates'
  | 'design-inspiration'
  | 'validation'
  | 'security'
  | 'authentication'
  | 'caching'
  | 'ui-generators'
  | 'validation'
  | 'security'
  | 'authentication'
  | 'caching'
  | 'system-design'
  | 'ml'
  | 'data-science'
  | 'deep-learning'
  | 'online-code-editors'
  | 'web-development'
  | 'machine-learning'
  | 'tensorflow'
  | 'dsa'
  | 'android'
  | 'blogs'
  | 'hosting'
  | 'web3-metaverse'
  | 'Github'
  | 'devtools'
  | 'javascript'
  | 'python'
  | 'golang'
  | 'open-source-blogs'
  | 'open-source-projects'
  | 'open-source-tools'
  | 'officialdocs'
  | 'fintech'
export type SubCategories = {
  name: string
  url: string
}
```

### Screenshots

_No response_

### Any additional information?

I believe this is important and would like to create a quick PR to fix the missing subcategories in `types/index.ts`.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
> To prevent merge conflicts, please merge this pull request only after merging #1062

## Fixes Issue

Closes #1060 

## Changes proposed

- Remove duplicate categories and subcategories.
- Add missing subcategories.
- Arrange them in a specific order and add comments to indicate the category for future convenience.

### CODE REVIEW

**Review by CBID2 — DISMISSED** [review]
LGTM!

**Comment by ujjawaltyagii** [comment]
Please resolve merge conflicts as you linked PR has been merged !

**Comment by Anmol-Baranwal** [comment]
> Please resolve merge conflicts as you linked PR has been merged !

Hi, I believe this would be a Level 2 contribution because one has to go through the entire codebase and understand it. This is not a visual error that anyone can spot from the live website. So, please consult and change the label accordingly.

**Comment by CBID2** [comment]
> > Please resolve merge conflicts as you linked PR has been merged !
> 
> Hi, I believe this would be a Level 2 contribution because one has to go through the entire codebase and understand it. This is not a visual error that anyone can spot from the live website. So, please consult and change the label accordingly.

I think it could be both! :)

**Review by rupali-codes — DISMISSED** [review]
thanks

**Comment by rupali-codes** [comment]
@Anmol-Baranwal can you please resolve merge conflicts?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal can you please resolve merge conflicts?

Don't merge yet, let me fix duplicate names

**Comment by rupali-codes** [comment]
> > @Anmol-Baranwal can you please resolve merge conflicts?
> 
> Done, please don't merge any other PRs involving new categories before this.
> 
> > Also, I will update the contributing guidelines on June 20th after the exam. Until then, please ask someone to write the descriptions for all the subcategories that are already present in the file and codebase.

sure, thanks

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please tell me when you will merge this PR so that I can resolve any conflicts at that time. This way, I won't have to deal with resolving additional conflicts, as I mentioned the reason earlier.

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
