### PR TITLE
Revert 1 feat/added kubernetes youtube resource

### LINKED ISSUE #2086: [Add] <Kubernetes Youtube tutorial>
### Site URL

https://youtu.be/X48VuDVv0do?si=VUaShrqe0PuMrfl4

### Description of the above provided site

This link contains a comprehensive and beginner-friendly resource for Kubernetes by a well-known tutor Nana.

### Category

DevOps

### Sub Category

Kubernetes

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by rover07**
<h3 dir="auto">Site URL</h3>
<p dir="auto"><a href=" https://youtu.be/X48VuDVv0do?si=VUaShrqe0PuMrfl4" rel="nofollow">https://youtu.be/X48VuDVv0do?si=VUaShrqe0PuMrfl4</a></p>
<h3 dir="auto">Description of the above provided site</h3>
<p dir="auto">This video is a comprehensive resource from a well reputed tutor available for DevOps.</p>
<h3 dir="auto">Category</h3>
<p dir="auto">Youtube</p>
<h3 dir="auto">Sub Category</h3>
<p dir="auto">Kubernetes</p>
<h3 dir="auto">Checklist</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input id="" class="task-list-item-checkbox" checked="checked" disabled="disabled" type="checkbox" />&nbsp;I have checked the existing issues</li>
<li class="task-list-item"><input id="" class="task-list-item-checkbox" checked="checked" disabled="disabled" type="checkbox" />&nbsp;I have read the&nbsp;<a href="https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md">Contributing Guidelines</a></li>
<li class="task-list-item"><input id="" class="task-list-item-checkbox" checked="checked" disabled="disabled" type="checkbox" />&nbsp;I am willing to work on this issue (optional)</li>
<li class="task-list-item"><input id="" class="task-list-item-checkbox" checked="checked" disabled="disabled" type="checkbox" />&nbsp;I am participating in Hacktoberfest 2023</li>
</ul>
Closes #2086

### CODE REVIEW

**Comment by CBID2** [comment]
@rover07, please raise an issue and wait until it's approved and assigned to you before submitting a pull request.

**Comment by CBID2** [comment]
@rover07, it seems that you merged this resource already: https://github.com/rover07/LinksHub/pull/1
Can you explain why you made another PR for this resource?

**Comment by rover07** [comment]
The previous one was drafted as I did not create an issue before raising PR so I raised a PR again after issue.

**Comment by rover07** [comment]
I was unsure of how drafts work, sorry for the inconvenience.

**Comment by CBID2** [comment]
> I was unsure of how drafts work, sorry for the inconvenience.

You're welcome @rover07. PRs in draft mode means that a contributor is still working on it. Now, that's settled, I'm going to close this PR.

**Pull request closed without merging**
