### PR TITLE
feat: add contributors page

### LINKED ISSUE #980: [Feature] Contributors Section
### Description

- I would like to add a category called Contributors that displays contributors with a similar card structure as the existing resources. - To be included in this category, contributors should meet a minimum threshold of 5 or more contributions. 
- To automate the process and avoid manual entry, I will implement an automatic mechanism.
- Each card in the category will include the following details:
   - Profile Avatar
   - Profile Name (not username)
   - Commit history
- The contributors will be displayed in descending order based on their contribution count.

> This is an exciting feature, and I would love to try to contribute this major section.

@rupali-codes  
Please review this idea. It is taking a while to merge the pull requests or even assign the issues. Should I start working on the task without an assigned issue?

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Resolves #980 

## Note

- You can click on `Open Source Community` in the footer on the deployed link to view this page.
- I have used the name from a different API fetch call. The reference for this call is provided at the very bottom of the file, using the custom login value obtained from the first fetch call.

## Screenshots

image

## Note to reviewers

@rupali-codes 
I was planning to add the complete design, but I opened this early because it seems like you are available on Sunday. Could you please provide a quick review of the design and the code so that I can complete it today? I am aware of the existing problems in it and will fix them accordingly.

Also, will the maintainers be included in this? I am aware that a maintainers page is also being created, right?

@CBID2 
Please give your review as well, on what can I change.

### CODE REVIEW

**Comment by rupali-codes** [comment]
HIi, how can i access the page on website?

**Comment by Anmol-Baranwal** [comment]
> HIi, how can i access the page on website?

I clearly mentioned this: to avoid any confusion.

> Image
image

**Comment by rupali-codes** [comment]
@Anmol-Baranwal it looks fine though, can we make it 3 cards in a row for desktop, 2 for tablet devices and 1 for mobile devices?

**Comment by rupali-codes** [comment]
> > @Anmol-Baranwal it looks fine though, can we make it 3 cards in a row for desktop, 2 for tablet devices and 1 for mobile devices?
> 
> I did it originally, but due to responsiveness, I removed it. Will do it in a couple of days. I will attach both the codes for easy reviewing.

Sure, take your time and wishing you luck for your exams :)

**Comment by ujjawaltyagii** [comment]
It looks really good tbh 💯

**Review by CBID2 — DISMISSED** [review]
LGTM

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I have changed the padding of the buttons accordingly to avoid them overlapping, and I believe this is the best value we can use. 

Please review and let me know if it looks good.

I have used:
```typescript
  const buttonStyles =
    'bg-violet-600 hover:bg-transparent text-white px-4 py-2 md:px-3 text-sm tracking-[.6px] rounded-md border border-dashed border-transparent duration-100 hover:border-violet-400 hover:text-violet-500 dark:hover:text-violet-400'

  const linkProps = {
    target: '_blank',
    rel: 'noopener noreferrer',
    className: buttonStyles,
  }

AND used spread operator

{...linkProps} in the Link
```

We can also this:

```typescript
const ButtonLink: FC<{ href: string; text: string }> = ({ href, text }) => (
  <Link
    href={href}
    target="_blank"
    rel="noopener noreferrer"
    className="bg-violet-600 hover:bg-transparent text-white px-4 py-2 md:px-3 text-sm tracking-[.6px] rounded-md border border-dashed border-transparent duration-100 hover:border-violet-400 hover:text-violet-500 dark:hover:text-violet-400"
  >
    {text}
  </Link>
)
```

**Review by rupali-codes — COMMENTED** [review]
it looks nice though, but there's an delay in fetching data, can we add something like a loader to show that the data is still loading and render that when it gets loaded completely?

**Comment by Anmol-Baranwal** [comment]
> it looks nice though, but there's an delay in fetching data, can we add something like a loader to show that the data is still loading and render that when it gets loaded completely?

Yes, I am looking into it. It is okay when we reload again.

**Comment by rupali-codes** [comment]
> > it looks nice though, but there's an delay in fetching data, can we add something like a loader to show that the data is still loading and render that when it gets loaded completely?
> 
> Yes, I am looking into it. It is okay when we reload again.

everything is loading perfectly fine except name of contributors

**Comment by Anmol-Baranwal** [comment]
> > > it looks nice though, but there's an delay in fetching data, can we add something like a loader to show that the data is still loading and render that when it gets loaded completely?
> > 
> > 
> > Yes, I am looking into it. It is okay when we reload again.
> 
> everything is loading perfectly fine except name of contributors

Hi @rupali-codes,

To solve this problem, I utilized `getStaticProps`. However, due to the high volume of requests, it is necessary to authenticate it with `Authorization`. 

The challenge is finding a suitable storage location for the required Personal Access Token (PAT) since using `.env` files is not advisable. I'm seeking guidance on where to securely store this token, considering the numerous individuals who will be making requests on the deployed application and the need for proper authorization. 

Should I use `.env` file for the same, since all the cloud managing services do no offer a free tier.

I will update you with the same, if I found a solution.

> Image
image
image

**Comment by Anmol-Baranwal** [comment]
> > > it looks nice though, but there's an delay in fetching data, can we add something like a loader to show that the data is still loading and render that when it gets loaded completely?
> > 
> > 
> > Yes, I am looking into it. It is okay when we reload again.
> 
> everything is loading perfectly fine except name of contributors

I have fixed it. Kindly check.

**Comment by rupali-codes** [comment]
@Anmol-Baranwal thanks, i just realized something, its not the list of all contributors? 👀

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal thanks, i just realized something, its not the list of all contributors? 👀

To address the concern mentioned in the issue, it would be helpful to filter contributors who have made at least 6 contributions. This will discourage the submission of spammy pull requests just to be listed. If you prefer a different minimum contribution threshold, please let me know.
> Image
image


This happens due to the following code:
> Image
image

**Review by k-deepak04 — APPROVED** [review]

**Comment by k-deepak04** [comment]
@rupali-codes please merge this pr, ujjwal review is pending but i guess he is busy in exams

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Comment by CBID2** [comment]
> @rupali-codes please merge this pr, ujjwal review is pending but i guess he is busy in exams

Way ahead of you @k-deepak04! :)

**Comment by Anmol-Baranwal** [comment]
Very happy for it to be finally live 😅

**Pull request merged**
