### PR TITLE
feat: Add C# Projects in resources category

### LINKED ISSUE #1748: [Add] C# Projects
### Site URL

https://www.interviewbit.com/blog/c-sharp-projects/

### Description of the above provided site

This website provides free fifteen beginner to advanced level C# projects with source code.
Kindly can I please get the hactoberfest label.

### Category

Resources

### Sub Category

Project Ideas

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by SargamPuram**
## Fixes Issue
Closes #1748 

## Changes proposed
It adds C# projects in project-ideas of resources .

## Screenshots
c#
C#1

## Note to reviewers
Kindly add the hactoberfest accepted label.

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@SargamPuram 
Stick to the PR template, because the issue is not linked here. It's good that you are experimenting, but just see if it works.

There are specific keywords for the same, predefined which you can read at the docs. Please, take care of this in future version.

image

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Comment by SargamPuram** [comment]
> @SargamPuram Stick to the PR template, because the issue is not linked here. It's good that you are experimenting, but just see if it works.
> 
> There are specific keywords for the same, predefined which you can read at the docs. Please, take care of this in future version.
> 
> image

@Anmol-Baranwal , I'm sorry about the blunder. I'll make sure not to repeat it in the future. I've updated it to Closes # 1748 now as per docs.

**Review by CBID2 — APPROVED** [review]
Looks good to me! :)

**Comment by CBID2** [comment]
Congratulations @SargamPuram! You just made your first contribution! 🥳 It was wonderful working with you! 😄 If you want to stay updated on LinksHub, join our [Discord community](https://discord.com/invite/NvK67YnJX5)! :) We'd love to have you! :)

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal , I'm sorry about the blunder. I'll make sure not to repeat it in the future. I've updated it to Closes # 1748 now as per docs.

I was just letting you know so that you can improve next time, between I edited it so there was no need for you to edit. 
Still, thanks for the same.

**Comment by SargamPuram** [comment]
> > @Anmol-Baranwal , I'm sorry about the blunder. I'll make sure not to repeat it in the future. I've updated it to Closes # 1748 now as per docs.
> 
> I was just letting you know so that you can improve next time, between I edited it so there was no need for you to edit. Still, thanks for the same.

I'm sorry I thought you meant the Fixes issue description 😅. And yes I'll make sure to stick to  the PR template in the docs for commit messages henceforth. Thanks!

**Pull request merged**
