### PR TITLE
added game dev link

### LINKED ISSUE #1230: [Add] Game Dev course video
### Site URL

https://www.youtube.com/watch?v=S8lMTwSRoRg

### Description of the above provided site

Learn how to use the Godot game engine to create your own platformer game. Throughout the course, you'll learn everything from setting up your first 2D scene and animating the player, to designing enemies, incorporating UI elements, and implementing game-saving features.

### Category

Youtube

### Sub Category

game-development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by anshulsoni4**
## Fixes Issue
adding one more link to the resouces

Closes #1230

## Changes proposed
Added one more game dev link

### CODE REVIEW

**Comment by anshulsoni4** [comment]
review pls

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Comment by anshulsoni4** [comment]
@k-deepak04 can you review this

**Comment by anshulsoni4** [comment]
still not merge ??

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
