### PR TITLE
Design of 3 cards in a row achieved

### LINKED ISSUE #789: [OTHER] Implementing 3 link cards instead of 2 in each row
### What would you like to share or ask?

A lot of space is left if 2 cards consisting of links to various websites are displayed. We can go in for 3 cards in a single row to utilise the space so that the user can see more resources in a single go.

image

As there is an ample space this design will be much more suitable.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by raaksss**
## Fixes Issue
Closes #789 

## Changes proposed
3 cards in a row instead of 2.

## Screenshots
Screenshot 2023-06-14 182814

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM!

**Comment by raaksss** [comment]
Hi @CBID2, I was resolving the merge conflicts and then committed it once I had resolved them. I don't know why this dismissed message is coming up here. I hope it ain't an issue. Please tell me if I have done something wrong so that I can amend it. Sorry for the inconvenience caused.

Screenshot 2023-06-15 012108

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by CBID2** [comment]
> Hi @CBID2, I was resolving the merge conflicts and then committed it once I had resolved them. I don't know why this dismissed message is coming up here. I hope it ain't an issue. Please tell me if I have done something wrong so that I can amend it. Sorry for the inconvenience caused.
> 
> 
> 
> Screenshot 2023-06-15 012108
> 
> 

No worries. I just reviewed it again :)

**Review by ujjawaltyagii — COMMENTED** [review]
It looks good to me but while changing screen size I notices these gaps between words and lines
can we do something about them ?

image

**Comment by raaksss** [comment]
I have made the changes and checked the responsiveness too.
https://github.com/rupali-codes/LinksHub/assets/102184647/0cad7c80-888f-42fe-afac-344cbbef2555

**Review by CBID2 — DISMISSED** [review]
LGTM!

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Hi, thanks, could you please make it display 2 cards for middle screens?

**Comment by raaksss** [comment]
I have made the changes.

https://github.com/rupali-codes/LinksHub/assets/102184647/225101e3-6232-448f-90a7-8e4cd70eda28

**Review by rupali-codes — APPROVED** [review]
lgtm :)

**Review by CBID2 — APPROVED** [review]
LGTM

**Pull request merged**
