### PR TITLE
fix copytoclipboard button gap issue #2230

### LINKED ISSUE #2230: Modal UI Improvement: Add Space Between Title and Copy Button
### Description

Issue:
The current modal layout displays the title and copy button without proper spacing, causing them to stick together.

### Screenshots

Screenshot from 2024-01-05 17-06-58
Untitled design

### Any additional information?

Contributor Guidelines:

Ensure that the changes do not affect the responsiveness of the modal.
Test the modifications across different screen sizes to guarantee a consistent user experience.

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by lokeshvasnik**
This PR closes #2230 

## Changes proposed

Added margin for the copytoclipboard button 

## Screenshots

Screenshot from 2024-01-07 19-23-16
Screenshot from 2024-01-07 19-21-19

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks great to me! :) What do you think @Anmol-Baranwal and @aftabrehan?

**Comment by CBID2** [comment]
@rupali-codes, can you approve this deployment please?

**Review by rupali-codes — APPROVED** [review]
lgtm

**Review by aftabrehan — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
