### PR TITLE
chore: nextui added to frontend ui-librariries

### PR DESCRIPTION
**Pull request by tanpreetjolly**
## Changes proposed
fixes : #2126 
New UI Library NEXT UI added to the database of frontend ui- libraries

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@tanpreetjolly 
We are neglecting this now, but in the future, you need to create an issue and allow us to assign you the issue before you start working and submit a PR. Not following this process will require us to close your pull request.

This is outlined in the contributing guidelines.
image

You need to follow a predefined flow in order to contribute to Open Source. You may be new, so it is important to understand this. Most of the maintainers will mark it as spam and close it. I'm converting this into a draft for now. 

create a issue, and tag me.

**Comment by tanpreetjolly** [comment]
I apologise for this.Its a newbie mistake from my side as I have just started contributing to Open Source. I will create an issue and tag you

**Comment by tanpreetjolly** [comment]
@Anmol-Baranwal I have created the issue #2126. Not able to tag you over there as it says convo is limited to collaborators in issues

**Comment by Anmol-Baranwal** [comment]
tag me after referencing the issue, otherwise I won't get a notification.

**Comment by tanpreetjolly** [comment]
@Anmol-Baranwal I have referenced the issue in PR

**Comment by Anmol-Baranwal** [comment]
@tanpreetjolly 
Thanks so much. Please follow this flow, whenever you are contributing. Even in big organizations. 😄

It will help you avoid unnecessary issues.

**Comment by tanpreetjolly** [comment]
For Sure! Thank you for this learning experience

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
