### PR TITLE
Add Accessibility Improvements to Links

### LINKED ISSUE #1978: [Feature] Enhanced Accessibility Features for Improved User Experience
### Description

This issue is raised to propose enhancements regarding the website's accessibility, ensuring an inclusive experience for all users, including those with disabilities. Key areas of improvement may include implementing keyboard navigation, enhancing screen reader compatibility, optimizing color contrast, and ensuring proper focus management. 

_Note: I am eager to contribute to this issue and would appreciate it if you could assign it to me for Hacktoberfest 2023._

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by supunsathsara**
## Fixes Issue
Closes #1978 

## Changes proposed

- Changed `aria-label` attributes of category links for better screen reader accessibility.
- Added `aria-label` attributes of subcategory links for better screen reader accessibility.

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Well done @supunsathsara! :) @Anmol-Baranwal, @rupali-codes, you're up! :)

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
Fix this as well.

image

It is from your deployed link

**Comment by supunsathsara** [comment]
> Fix this as well.
> 
> image
> 
> It is from your deployed link

I believe the issue here lies in the fact that, even though it has a clear `aria-label`, automated test results might interpret "Open Source Community" as referring to the entire open-source community, rather than just contributors in LinksHub. Changing it to a more specific term could resolve this, but I opted not to alter the website's content. 

If it is acceptable to make this change, I am open to doing so. Additionally, if you can think of any other reasons why this issue might occur, please feel free to suggest. Appreciate your understanding.

**Comment by Anmol-Baranwal** [comment]
> ### This branch was successfully deployed
> 1 active deployment

I will check it, and let you know. The reason you mentioned is correct.

**Comment by CBID2** [comment]
@Anmol-Baranwal and @rupali-codes, can you review this please?

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
