### PR TITLE
chore:add-Picular-site-in-color-section

### LINKED ISSUE #1212: [Add] Picular site to colors section
### Site URL

https://picular.co/

### Description of the above provided site

Picular is a color search engine that generates color palettes based on keywords. You can enter a specific term, and it will generate a set of colors associated with that keyword, offering a creative way to explore color possibilities.

### Category

Frontend

### Sub Category

Colors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by URVESH1121**
## Fixes Issue

Closes #1212 

## Screenshots

image

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by Anmol-Baranwal** [comment]
LGTM

@CBID2 You can merge this. 

> Very interesting resource.

**Review by Anmol-Baranwal — APPROVED** [review]
LGTM

@CBID2 You can merge this. 

> Very interesting resource.

**Comment by Anmol-Baranwal** [comment]
I have merged it. I'm using the app, so I did it.

**Pull request merged**
