### PR TITLE
freshersworld-added

### LINKED ISSUE #2290: [Add] Freshersworld
### Site URL

https://www.freshersworld.com/

### Description of the above provided site

It is the best platform to get the job and preparation for job interview.

### Category

Frontend

### Sub Category

Cat - Placement_prep , Subcat - jobportals

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by parma1111**
## Fixes Issue

Closes #2290 

## Changes proposed

It is the best platform to get the job and preparation for job interview.

## Screenshots

Screenshot (905)

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks good to me

**Comment by CBID2** [comment]
Your turn @Anmol-Baranwal

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by aftabrehan — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
