### PR TITLE
Added pagination to CardsList.tsx

### LINKED ISSUE #1125: [Feature] Add Pagination to the Resources Cards
### Description

- Pagination could look better on the resources' cards.
- We could show no more than 9 cards on the page and load the others when user wants to switch it.
- Pagination could make it more professional and user friendly. 

### Screenshots

image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by siddarthdayala**
## Fixes Issue 
Closes #1125 

## Changes proposed

Added Ant Design Pagination to the CardsList.tsx

## Screenshots
image

image

### CODE REVIEW

**Review by CBID2 — COMMENTED** [review]
Looks pretty good

**Comment by ujjawaltyagii** [comment]
@siddarthdayala Deployment is getting failed could you remove the merge conflicts first !

**Comment by siddarthdayala** [comment]
hey @ujjawaltyagii resolved the conflicts.. Could you please check?

**Comment by rupali-codes** [comment]
@siddarthdayala can you please fix the following errors

image

**Comment by siddarthdayala** [comment]
@rupali-codes I've changed the code in the file. It resolves the error. Could you please check?

**Comment by rupali-codes** [comment]
@siddarthdayala it doesn't, please checkout this

image

**Comment by siddarthdayala** [comment]
How about now? @rupali-codes Actually, I couldn't view the errors on Vercel, it shows 404 page. But the code is updated now.

**Comment by k-deepak04** [comment]
@rupali-codes please let me know the error so i can help @siddarthdayala

**Review by rupali-codes — COMMENTED** [review]
Hey, it looks nice, but there are a few things we would like to add:
* when clicked on button, it should move user to top
* (optional) can you add something like an animation when the page changes? it would be more better for UX
* selected button's text and bg color (blue & white) doesn't match with LinksHub theme, so kindly update that.

Other than this, it looks great to me :)
let us know if you need any kinda help

**Comment by k-deepak04** [comment]
@siddarthdayala please update the change rupali said.

**Comment by siddarthdayala** [comment]
Sure @rupali-codes I'll try the specified changes

**Comment by siddarthdayala** [comment]
@rupali-codes Made a new commit with few changes once check it

**Comment by CBID2** [comment]
> @rupali-codes I've made a new commit with few changes once check it

@siddarthdayala, there seems to be a deployment issue.

**Comment by rupali-codes** [comment]
@siddarthdayala here

image

**Review by rupali-codes — COMMENTED** [review]
@siddarthdayala could you please resolve this error?

image

**Comment by siddarthdayala** [comment]
@rupali-codes I resolved the conflicts

**Comment by k-deepak04** [comment]
@siddarthdayala the deployment is failing plz check

**Comment by siddarthdayala** [comment]
> @siddarthdayala the deployment is failing plz check

Could you please post the error here? I can't see the errors

**Comment by k-deepak04** [comment]
@rupali-codes can you help him with it?

**Review by rupali-codes — COMMENTED** [review]
Hi, i'm sorry for being late, can u please resolve this

image

**Comment by CBID2** [comment]
@siddarthdayala, can you fix this, please?

**Comment by CBID2** [comment]
Closing this PR due to inactivity

**Pull request closed without merging**
