### PR TITLE
feat: Improved Cards structure

### LINKED ISSUE #337: [Feature] Improve Cards structure
### Description

Hi! I think we should to improve the cards related components.

- Add `CardsList`, `CardsListItem` and `Card` components to the Cards folder.
- Add a separate component to the `Coming Soon` message.
- The subcategory page should get the DB data and display the `CardsList` or `ComingSoon` component in a wrapper `div`.
- Add types to the DB data filtering functions.

### Screenshots

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by zvolcsey**
@rupali-codes @CBID2 Hi! I improved the cards related components and added types to the DB data filtering functions.

## Fixes Issue

Closes #337

## Changes proposed

- Added `CardsList`, `CardsListItem` and `Card` components to the Cards folder.
- Added a separate component to the `Coming Soon` message.
- The subcategory page gets the DB data and displays the `CardsList` or `ComingSoon` component in the wrapper `div`.

- Added `IUseFilterDBResponse` type and modified `category` and `subcategory` properties of the `IData` type. `IData` type was not use anywhere in the app. I added this to the Cards related components.
- Changed types in `Popup` and `UseDelayUnmount` components.
- Added types to the `UseFilterDB` and `database/data.ts` components.

### CODE REVIEW

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hmmm, I think you should use `<article>`instead of`<div>` to make the code more semantic @zvolcsey.

**Comment by zvolcsey** [comment]
> Hmmm, I think you should use `<article>`instead of`<div>` to make the code more semantic @zvolcsey. 

@CBID2 Thank you for the feedback! Working on it.

**Comment by zvolcsey** [comment]
@CBID2 @rupali-codes  Hi! In my latest commits, I made the following improvements.

- Merged the latest commit.
- Added `article`, `header`, and `footer` tags to the  `Card` and `Popup` component.
- Removed the unnecessary `div` from `ComingSoon` component.

**Review by CBID2 — APPROVED** [review]
LGTM! 😄

**Review by CBID2 — APPROVED** [review]
LGTM! 👍🏾

**Comment by rupali-codes** [comment]
Hey, can u please one more time resolve the conflicts

**Comment by zvolcsey** [comment]
@rupali-codes @CBID2 @Eugene44-hub Hi! Thank you for the feedback! I resolved the merge conflicts.

**Review by rupali-codes — COMMENTED** [review]
Hey, looks good though, but it's showing this overflowed text, could you please fix that? 
image

**Comment by zvolcsey** [comment]
> Hey, looks good though, but it's showing this overflowed text, could you please fix that? image

Thanks for the feedback! Working on it.

**Comment by zvolcsey** [comment]
@rupali-codes Hi! In my latest commit, I fixed the Card component.

**Review by CBID2 — APPROVED** [review]
Looks pretty good! :)

**Review by rupali-codes — APPROVED** [review]
Looks perfect, thanks a lot ✨✨

**Pull request merged**
