### PR TITLE
added negative space for stock images

### LINKED ISSUE #1723: [Add] Added Negative Space
### Site URL

https://negativespace.co/

### Description of the above provided site

Beautiful free images for personal and commercial use.

### Category

Frontend

### Sub Category

images

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by dfordp**
## Fixes Issue

Closes #1723

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Well done @dfordp! :)

**Comment by CBID2** [comment]
> I was asked by @CBID2 to create this pull request again after she assigned me this issue 

Just approved it! :) Now, you need another approval from a different maintainer. If you get "Changes Requested", you'll get specific feedback on how to do so. Once those changes are made, tag [one of the maintainers](https://www.linkshub.dev/contributors) so you get another review.

**Comment by dfordp** [comment]
ok bro thank you so much 
can you please assign me issues #1729 and #1731

**Comment by CBID2** [comment]
> ok bro thank you so much 
> 
> can you please assign me issues #1729 and #1731 

Let's focus on finishing this one first @dfordp.

**Pull request merged**
