### PR TITLE
feat: animate backToTop btn

### LINKED ISSUE #166: [Feature] animate the to-top button
### Description

Jus add a fade animation when the button appear/disappear on scrolling will be more user friendly.

### Screenshots

Capture d’écran 2023-02-09 164023

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Lourvens**
Closes #166
# Animate backToTop buttons

- make the BackToTop animated when appearing on the screen 
- add a transition library to make it possible 

## Screenshots
chrome-capture-2023-1-10 (2)

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
Could you please resolve this issue?

image

**Comment by Lourvens** [comment]
now think the problem was resolved the first package doesn't support react.18 I replaced it by another

**Comment by rupali-codes** [comment]
Could you please resolve merge conflicts?

**Comment by Lourvens** [comment]
I resolved the merge conflict

**Review by rupali-codes — CHANGES_REQUESTED** [review]
I have encountered some issues:
1. backToTop buttons shows up when there's nothing to scroll

image

2. footer should not overlap the button

image

**Review by rupali-codes — COMMENTED** [review]
Also, could you add transition on `hover` too?

**Review by rupali-codes — APPROVED** [review]
Thank you so much

**Comment by Lourvens** [comment]
you are welcome

**Pull request merged**
