### PR TITLE
fixing the spelling mistakes

### PR DESCRIPTION
**Pull request by AbhineshJha**
## Fixes Issue : Corrected the spelling mistakes and CONTRIBUTION.md
Fixes : #1861

### CODE REVIEW

**Comment by AbhineshJha** [comment]
please review and add hacktoberfest label

**Comment by CBID2** [comment]
Hi @AbhineshJha. Welcome to LinksHub! :) We don't accept spam pull requests, so I'm putting yours in draft mode for now. Refer to our [Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#how-to-contribute-) to learn how to effectively contribute to the project. In the future, please raise an issue and wait until it has been approved and assigned to you before you submit a pull request. Happy Contributing! 😊

**Review by CBID2 — APPROVED** [review]
Great job @AbhineshJha! 😄 As you continue making contributions during and after Hacktoberfest, consider working on issues beyond revising typos as they don't often enhance projects.  If you need more suggestions, check out the blog post, [Hacktoberfest 2023: Beyond Green Squares](https://dev.to/opensauced/hacktoberfest-2023-beyond-green-squares-4d6j). Now, you just need another approved review by @rupali-codes or @Anmol-Baranwal before it gets merged.

**Review by Anmol-Baranwal — APPROVED** [review]
@AbhineshJha 

This is the last time, I'm approving the PR for typos. It maybe important but not necessary.

@CBID2 
Please avoid assigning issues to these types of issues. It is our responsibility to force them to improve.

**Pull request merged**
