### PR TITLE
feat: Added Web Development YouTube Video Details in web-development.json File 

### LINKED ISSUE #1340: [Add]: Add SCALER YouTube Channel Link for Full Stack Web Development Course [Recently POSTED - 3 Days Ago]
### Site URL

https://www.youtube.com/watch?v=yjmfoR2LSRM&t=2s

### Description of the above provided site

- Add SCALER YouTube Channel Link for Full Stack Web Development Course provided by SCALER ACADEMY.
- This Course is Recently Uploaded  and It's Good Start for Who can Learning Full Stack Web Development as a Beginner's Level 

### Category

Youtube

### Sub Category

web-development

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by NarendraKoya999**
## Fixes Issue:
Closes #1340 #1341 #1342 #1343 #1344 

## Changes proposed

- Added `Web Development Video` Details in `web-development.json` File
- YouTube channels named as `Simplilearn, Intellipaat, EDUREKA(Web Dev), SuperSimpleDev and SCALER`
## Note to reviewers

- ` I have combined 5 Issues related to Web Development  with this PR.`
- `Please Notify Them` @rupali-codes

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Hi @NarendraKoya999! :) I made a few tweaks to your PR, but other than that, it looks good! :)

**Review by k-deepak04 — COMMENTED** [review]
@NarendraKoya999 won't this be too redundant, if you will add all the links of the same topic, this website is to deliver top resources that you have refereed while learning & think would be great if people visit and learn from them. 
not just a dump website where you can throw content

**Comment by NarendraKoya999** [comment]
> @NarendraKoya999 won't this be too redundant, if you will add all the links of the same topic, this website is to deliver top resources that you have refereed while learning & think would be great if people visit and learn from them. not just a dump website where you can throw content

Ok @k-deepak04 . What Can I Do? . I did not understand your words. Please Clarify Me

**Comment by k-deepak04** [comment]
> > @NarendraKoya999 won't this be too redundant, if you will add all the links of the same topic, this website is to deliver top resources that you have refereed while learning & think would be great if people visit and learn from them. not just a dump website where you can throw content
> 
> Ok @k-deepak04 . What Can I Do? . I did not understand your words. Please Clarify Me

Sure, let me explain it in simple words:

When creating a website like Links Hub, the goal is to provide valuable and helpful resources for people to learn from. However, it's essential to avoid making the website redundant. Redundancy means adding the same information or links multiple times, which can be confusing and not very useful.

Instead, the website should focus on delivering the best resources that @NarendraKoya999 has personally used and found helpful during their learning journey. These resources are like valuable gems that can help others learn too.

The aim is to avoid turning the website into a dumping ground for any random content. By carefully selecting and sharing only the most valuable and reliable resources, the website becomes a trustworthy place for people to visit and learn from.

In summary, the website should be a curated collection of top-notch resources, not a cluttered mess of duplicate or irrelevant content. This way, it can truly serve its purpose of helping others learn and grow.

**Comment by NarendraKoya999** [comment]
> > > @NarendraKoya999 won't this be too redundant, if you will add all the links of the same topic, this website is to deliver top resources that you have refereed while learning & think would be great if people visit and learn from them. not just a dump website where you can throw content
> > 
> > 
> > Ok @k-deepak04 . What Can I Do? . I did not understand your words. Please Clarify Me
> 
> Sure, let me explain it in simple words:
> 
> When creating a website like Links Hub, the goal is to provide valuable and helpful resources for people to learn from. However, it's essential to avoid making the website redundant. Redundancy means adding the same information or links multiple times, which can be confusing and not very useful.
> 
> Instead, the website should focus on delivering the best resources that @NarendraKoya999 has personally used and found helpful during their learning journey. These resources are like valuable gems that can help others learn too.
> 
> The aim is to avoid turning the website into a dumping ground for any random content. By carefully selecting and sharing only the most valuable and reliable resources, the website becomes a trustworthy place for people to visit and learn from.
> 
> In summary, the website should be a curated collection of top-notch resources, not a cluttered mess of duplicate or irrelevant content. This way, it can truly serve its purpose of helping others learn and grow.

Ok I understand your Words. So, Is Any Resources I want to Delete in this PR?. If any suggest, I can remove that Content? @k-deepak04

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
