### PR TITLE
Enhancement

### PR DESCRIPTION
**Pull request by MadhuMPandurangi**
## Fixes 1st point of the issue

Addresses Issue #409  

## Changes proposed

Alignment of items - aligning the cards to the center will be a better visual experience , the space on the right creates an unnecessary void
image

## Screenshots

Updated to the below format
image

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
thanks, but it's only working for big screens, can we fix this for each?

**Comment by MadhuMPandurangi** [comment]
to do that for changing window size, will be complicated. 
If that is the case then I think alignment to the center would look good. If it's fine then I'll push this align center changes.

image

**Comment by rupali-codes** [comment]
> to do that for changing window size, will be complicated. If that is the case then I think alignment to the center would look good. If it's fine then I'll push this align center changes.
> 
> image

Okay, you can push and let's see

**Comment by rupali-codes** [comment]
Looks nice tho, but kinda looks weird when there's only single card in the row

**Comment by MadhuMPandurangi** [comment]
Yes. I'll try. If I'm able to do it I'll push the changes. But not sure.

**Comment by rupali-codes** [comment]
> Yes. I'll try. If I'm able to do it I'll push the changes. But not sure.

Yeah okay, let us know if you need any help

**Comment by MadhuMPandurangi** [comment]
I tried working on it. It is either coming to the centre or left. So, I don't know how to make it work as you asked.

**Comment by MadhuMPandurangi** [comment]
@rupali-codes, I think my work didn't resolve the issue. I'm sorry for that.

**Comment by rupali-codes** [comment]
> @rupali-codes, I think my work didn't resolve the issue. I'm sorry for that.

You don't have to be sorry, In simple words, we just want to center its parent _div_ not the _elements_. And let's see what @CBID2 have to say

**Comment by rupali-codes** [comment]
> Maybe a margin could be added?

Won't work for all screens

**Comment by rupali-codes** [comment]
@MadhuMPandurangi are you still working on this?

**Comment by MadhuMPandurangi** [comment]
No @rupali-codes, Not able to do it.

**Review by CBID2 — APPROVED** [review]
LGTM!

**Comment by MadhuMPandurangi** [comment]
@rupali-codes Will this be merged?

**Comment by rupali-codes** [comment]
> @rupali-codes Will this be merged?

looks good though, but when there's only single element in the last row it's putting that into center which is not looking good. I guess we can put these elements into a parent div and then give that a width of _95%_ and also _mx-auto_. Maybe it would work

**Comment by rupali-codes** [comment]
I guess it's better the way it is for now.

**Pull request closed without merging**
