### PR TITLE
Added Fintech Section Under Youtube

### PR DESCRIPTION
**Pull request by sangdeepganvir**
## Fixes Issue

Closes : #727 

## Changes proposed

I added new subcategory for Fintech under Youtube section. In Fintech I have added new links for 5 youtube channels which i had mentioned earlier in my issue.

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM!

**Comment by sangdeepganvir** [comment]
While checking the deployment of the site, I discovered that the links I added in the "fintect.json" file are not appearing in the deployment.
linksHub

Hey @CBID2 Can you help me in solving the issue.

**Review by ujjawaltyagii — COMMENTED** [review]
The issue I can see is you haven't exported the sub-category correctly ! 

There are two things I would suggest :

1st export the sub-category in `index.ts`
2nd you should cross-check all the defined paths while exporting the sub-category

I hope that resolve your issue !

**Review by CBID2 — APPROVED** [review]
LGTM!

**Review by rupali-codes — COMMENTED** [review]
lgtm

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
