### PR TITLE
fix: pagination component overlapping cards #1833

### PR DESCRIPTION
**Pull request by Akanksha-202**
## Issue
Relates to #1833 

## Changes proposed

Vertical Pagination applied.

## Screenshots

image

## Note to reviewers

Still have issues with small screens.

### CODE REVIEW

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
Please check if it's even working or not, because neither it is working on clicking the arrow icons, nor it is on clicking the page number

**Comment by Akanksha-202** [comment]
Oh sorry about that, it was working for me, ig I pushed the wrong code , sorry about it, will soon make amends

**Comment by Anmol-Baranwal** [comment]
@Akanksha-202 
Sorry, it's not caused by this. I was wondering, the files were not even changed.

Let others review this.

**Review by rupali-codes — COMMENTED** [review]
@Akanksha-202 it looks even more weird 😅

can you please do one thing, place it back to the bottom and make it look like this. Please let us know if you need any kinda assistance :)

image

Thanks

**Comment by Akanksha-202** [comment]
Okay, will do the changes asap !

**Comment by Akanksha-202** [comment]
https://jam.dev/c/b4bcdd90-1502-4630-b73c-bfd9a49cd4c8 
Is this fine @rupali-codes ?

**Comment by rupali-codes** [comment]
> https://jam.dev/c/b4bcdd90-1502-4630-b73c-bfd9a49cd4c8 Is this fine @rupali-codes ?

Yes looks perfect, just make the text light for dark mode and align it to the bottom

**Comment by Akanksha-202** [comment]
https://jam.dev/c/c0f27d66-a7dd-4be1-971b-3fe31494b8e9
@rupali-codes did the changes !

**Comment by Anmol-Baranwal** [comment]
@Akanksha-202 
Who is this?

image

**Review by Anmol-Baranwal — COMMENTED** [review]
I checked the logic. Whenever we are going from 2nd page to 1st page, the scroll position is maintained.

So, if someone wants to see the 10th resource.

He will first go to bottom, then click 2nd page number, and then go to top for seeing the page.

I'm not sure, if we want this flow. While going from 3rd to 2nd works absolutely fine. Let @CBID2 & @rupali-codes review this.

After their opinions, feel free to adjust the logic.

**Comment by Akanksha-202** [comment]
> @Akanksha-202 
> Who is this?
> 
> image
> 

I did it from the wrong GitHub Id , it's me only

**Comment by Akanksha-202** [comment]
> I checked the logic. Whenever we are going from 2nd page to 1st page, the scroll position is maintained.
> 
> So, if someone wants to see the 10th resource.
> 
> He will first go to bottom, then click 2nd page number, and then go to top for seeing the page.
> 
> I'm not sure, if we want this flow. While going from 3rd to 2nd works absolutely fine. Let @CBID2 & @rupali-codes review this.
> 
> After their opinions, feel free to adjust the logic.

Hmm, that seems logical

**Comment by Anmol-Baranwal** [comment]
> I did it from the wrong GitHub Id , it's me only

If he is someone else, let me know. I will assign him too. You will get a co-authored commit.

**Comment by Akanksha-202** [comment]
> > I did it from the wrong GitHub Id , it's me only
> 
> If he is someone else, let me know. I will assign him too. You will get a co-authored commit.

It's me only anmol, my work ID for college stuff, i forgot to sign out

**Review by CBID2 — DISMISSED** [review]
It looks good on my end @Akanksha-202 and @Anmol-Baranwal.

**Review by rupali-codes — CHANGES_REQUESTED** [review]
@Akanksha-202 can you please scroll to top when the user clicks on page button?

**Comment by Akanksha-202** [comment]
@rupali-codes 
https://jam.dev/c/79213fad-598c-4d20-9b1a-e17283bf62e2

**Comment by Anmol-Baranwal** [comment]
> @Akanksha-202 you did it very well, just a little issue, when clicked on `prev` button, the position remains constant. So just fix this one and we are good to go!

you can test it, whenever we go from page 2 to page 1 using prev option.

**Comment by Akanksha-202** [comment]
Reference: https://jam.dev/c/14f3271d-ec6c-4ee2-bee8-ff2480b8892e
@rupali-codes @Anmol-Baranwal

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by CBID2 — APPROVED** [review]
Looks great! :)

**Review by rupali-codes — APPROVED** [review]
Thank you so much @Akanksha-202 

Looks good to me!

**Pull request merged**
