### PR TITLE
Update Searchbar.tsx

### LINKED ISSUE #600: [Feature] <adding suggestions to search bar>
### Description

I want to add the nearest word suggestions to the search bar , can you please add it to the GSSOC'2023

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by tarunprakashporam**
adding feature of drop-down suggestion for searchbar

Closes #600 
## Changes proposed

added drop down search suggestions as you suggested.
## Screenshots

LinksHub - Google Chrome 22-05-2023 18_51_07

### CODE REVIEW

**Comment by rupali-codes** [comment]
@tarunprakashporam Firstly, you don't have to create new PR everytime, you can just push to the same branch. 

Secondly, it's showing the list but the elements are not clickable, what we basically need is, when user starts typing it will show them a list of matching characters, and when user clicks on any element of the list then it would **clear the searchbar** and **render the content on right panel**. Let us know if you need any kinda help :)

**Comment by tarunprakashporam** [comment]
thankyou mam for reply , mam if i am correct whenever user press the suggestion that page on right side should come directly.If any changes required in my idea please let me know .

**Comment by rupali-codes** [comment]
> thankyou mam for reply , mam if i am correct whenever user press the suggestion that page on right side should come directly.If any changes required in my idea please let me know .

yes you are right. check out [this](https://developer.mozilla.org/en-US/) searchbar for reference :)

**Review by CBID2 — APPROVED** [review]
Looks great @tarunprakashporam! :) LGTM! :)

**Comment by tarunprakashporam** [comment]
Hi mam , @rupali-codes @CBID2  Actually I am trying to add the page links to the suggestion , but I cannot make it. Sorry to say that I have not time to contribute , as my end semester exams are from tommorrow . Can you please assign this issue to any one and thankyou for your guidance.

**Comment by CBID2** [comment]
> Hi mam , @rupali-codes @CBID2 Actually I am trying to add the page links to the suggestion , but I cannot make it. Sorry to say that I have not time to contribute , as my end semester exams are from tommorrow . Can you please assign this issue to any one and thankyou for your guidance.

**Comment by CBID2** [comment]
Sure no problem @tarunprakashporam! :) Good luck on your exams! :)

> > Hi mam , @rupali-codes @CBID2 Actually I am trying to add the page links to the suggestion , but I cannot make it. Sorry to say that I have not time to contribute , as my end semester exams are from tommorrow . Can you please assign this issue to any one and thankyou for your guidance.

Sure no problem @tarunprakashporam! :) Good luck with your exams! :)

**Pull request closed without merging**
