### PR TITLE
Created a pre-commit hook to avoid duplicate links

### LINKED ISSUE #408: Add link checker to avoid addition of duplicate links
@sonylomo Sure ! It is indeed a credible idea. One way to implement this would be to have the system check the links that users enter against the existing links in the database. If a user tries to add a link that already exists in the database, the system can then display a message or warning that the resource has already been added. To implement this you could write a script that checks the link or related date to the entered data.

_Originally posted by @ujjawaltyagii in https://github.com/rupali-codes/LinksHub/issues/397#issuecomment-1500200000_

### PR DESCRIPTION
**Pull request by Isha988**
## Fixes Issue
Closes #408 

## Changes proposed

A pre-commit hook is created using husky

## Screenshots
Screenshot (164)
Screenshot (162)

### CODE REVIEW

**Comment by rupali-codes** [comment]
@Isha988 your vercel deployment is getting failed bcz of the following issues

image

**Comment by Isha988** [comment]
> @Isha988 your vercel deployment is getting failed bcz of the following issues
> 
> image

@rupali-codes resolved👍

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by ujjawaltyagii — COMMENTED** [review]
Looks pretty good to me ! 👍  
(just asking how the error will be shown to the user who is trying to add duplicate link directly via github)

**Comment by Isha988** [comment]
> Looks pretty good to me ! 👍 (just asking how the error will be shown to the user who is trying to add duplicate link directly via github)

@ujjawaltyagii Please look at the screenshot in PR description .

**Comment by Isha988** [comment]
Hey, @rupali-codes  and @ujjawaltyagii  any updates on this?

**Review by CBID2 — APPROVED** [review]
LGTM!

**Review by CBID2 — APPROVED** [review]
LGTM!

**Comment by ujjawaltyagii** [comment]
@rupali-codes could you have a look at this PR 👀

**Comment by Isha988** [comment]
@ujjawaltyagii 

1. This script is only looking for those staged files which are having JSON extension, and are present in a subfolder inside the database folder.

2. Yes, the script treats url as case-sensitive.

3. It is not checking for duplicates across all files. What exactly it does is,  extract the URLs from a selected staged file and check for duplicates within those URLs if any duplicates are present it prints them, and then moves to another file and so on

**Review by ujjawaltyagii — APPROVED** [review]

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
