### PR TITLE
fixed#260

### LINKED ISSUE #260: [BUG] Title Header shifting down in mobile view.
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

In mobile view or small screen size title header is moving down.

### Screenshots

image

### Any additional information?

I will be working on it.

### What browser are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by pramodreddypandiri**
## Fixes Issue

Screenshot 2023-02-25 at 7 36 32 PM

### CODE REVIEW

**Comment by pramodreddypandiri** [comment]
Hey @rupali-codes,  please review it . I have not changed font-size at all, also added truncate.
The earlier merge conflict was because you merged other PR (which changed same file).
Please review it before merging other PR.

**Comment by rupali-codes** [comment]
@pramodreddypandiri when you get conflicts closing the PR is not the right solution, just keep the changes you've made and remove others.

**Review by rupali-codes — CHANGES_REQUESTED** [review]
It's shifting icons to right side, could you please fix it?
image

**Comment by pramodreddypandiri** [comment]
Hey @rupali-codes , in small screen , i want to propose this kind of UI.
image

**Comment by rupali-codes** [comment]
> Hey @rupali-codes , in small screen , i want to propose this kind of UI. image

it's not looking that good to me, let's what @Eugene44-hub have to say

**Comment by pramodreddypandiri** [comment]
Hey @rupali-codes , as we discussed in the issue chat/thread . i changed code , please review again

**Comment by pramodreddypandiri** [comment]
Hey @Eugene44-hub , please review this PR. I changed code as we discussed in issue #260 thread.

**Review by Eugene44-hub — COMMENTED** [review]
So i looked at it. so i think it's still ok leaving the social media handles above on the page. User can access the social media handle easily because there is a scroll to top button. 
it still looks okay this way. Thanks for the suggestion @pramodreddypandiri 

image

**Review by Eugene44-hub — COMMENTED** [review]
image
image

You can help to take the title off on the home screen and also fix the modal on mobile and also fix the padding issue on the modal. That will be nice @pramodreddypandiri

**Comment by pramodreddypandiri** [comment]
In mobile view, social icons and Title header doesn't seem good. Do after discussing with @rupali-codes I have implemented this (screen shots in #260). Darkmode toggle is available in all screen sizes.
I think this is best implementation for now.

**Comment by pramodreddypandiri** [comment]
And About modal, I did not implement that, please contact the right person for it .
@Eugene44-hub , I think you can merge my code as we discussed in (#260 ) it looks good.

**Comment by rupali-codes** [comment]
Hi @pramodreddypandiri. thanks for your time and efforts but we don't see this to be a nice solution. let's leave the icons as they are for now. maybe in future we might work on it. still appreciate your time and patience. tysm.

**Comment by pramodreddypandiri** [comment]
Hey @rupali-codes and @Eugene44-hub . Looks like you have implemented my idea which you have rejected back then. 
Anyways, I hope this project is going good.

**Comment by rupali-codes** [comment]
Hey, the project is been nice, and yeah we've put the icons into the sidebar

**Pull request closed without merging**
