### PR TITLE
The Competitive programming dropdown fixed

### LINKED ISSUE #1548: [BUG] Competitive programming dropdown icon not visible
### Description

as the Competitive programming name is too large for the sidebar it's name has covered quite a lot space and the dropdown is not visible  in large screens in small one it is visible.

### Screenshots

image

image

### Any additional information?

solutions - Competitive programming is also known as "CP" so we can replace that.
or find a similar word or we can use "CP - competitive pro......" like this

### What browser are you seeing the problem on?

Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by k-deepak04**
## Fixes Issue
Closes #1548 

## Changes proposed
changed the database file where we were adding the categoried and their respective links also, changed the main categories from where the data is fetched.

## Screenshots
now
image

earlier
image

### CODE REVIEW

**Comment by k-deepak04** [comment]
@rupali-codes @CBID2 please review this too
full and final :)
my last PR of gssoc'23 i guess
Thanks for the support with this i wish i would come in top 25 atleast

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by CBID2** [comment]
> @rupali-codes @CBID2 please review this too
> 
> full and final :)
> 
> my last PR of gssoc'23 i guess
> 
> Thanks for the support with this i wish i would come in top 25 atleast

Thanks for your help @k-deepak04! :) It's been great working with you and watching you grow. Also, even if you don't make it to the Top 25, you've gained skills that you can apply to whatever aspect of tech you're pursuing career-wise. That's priceless my friend! :)

**Comment by k-deepak04** [comment]
> > @rupali-codes @CBID2 please review this too
> > full and final :)
> > my last PR of gssoc'23 i guess
> > Thanks for the support with this i wish i would come in top 25 atleast
> 
> Thanks for your help @k-deepak04! :) It's been great working with you and watching you grow. Also, even if you don't make it to the Top 25, you've gained skills that you can apply to whatever aspect of tech you're pursuing career-wise. That's priceless my friend! :)

You're very welcome! I appreciate your kind words and support throughout our journey together. It's been a pleasure assisting you and witnessing your progress as well.😊🫶
Also i will continue to maintain this repo even after the event ends, and hope to build many exciting things with you @rupali-codes in coming days :)

**Comment by k-deepak04** [comment]
> > > > @rupali-codes @CBID2 please review this too
> > 
> > 
> > > > full and final :)
> > 
> > 
> > > > my last PR of gssoc'23 i guess
> > 
> > 
> > > > Thanks for the support with this i wish i would come in top 25 atleast
> > 
> > 
> > > 
> > 
> > 
> > > Thanks for your help @k-deepak04! :) It's been great working with you and watching you grow. Also, even if you don't make it to the Top 25, you've gained skills that you can apply to whatever aspect of tech you're pursuing career-wise. That's priceless my friend! :)
> > 
> > 
> > You're very welcome! I appreciate your kind words and support throughout our journey together. It's been a pleasure assisting you and witnessing your progress as well.😊🫶
> > Also i will continue to maintain this repo even after the event ends, and hope to build many exciting things with you @rupali-codes in coming days :)
> 
> Absolutely and I just followed you on Twitter

oh...i'm not that active there but i'll try to be :)
following you back

**Comment by CBID2** [comment]
> > > > > @rupali-codes @CBID2 please review this too
> 
> > > 
> 
> > > 
> 
> > > > > full and final :)
> 
> > > 
> 
> > > 
> 
> > > > > my last PR of gssoc'23 i guess
> 
> > > 
> 
> > > 
> 
> > > > > Thanks for the support with this i wish i would come in top 25 atleast
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Thanks for your help @k-deepak04! :) It's been great working with you and watching you grow. Also, even if you don't make it to the Top 25, you've gained skills that you can apply to whatever aspect of tech you're pursuing career-wise. That's priceless my friend! :)
> 
> > > 
> 
> > > 
> 
> > > You're very welcome! I appreciate your kind words and support throughout our journey together. It's been a pleasure assisting you and witnessing your progress as well.😊🫶
> 
> > > Also i will continue to maintain this repo even after the event ends, and hope to build many exciting things with you @rupali-codes in coming days :)
> 
> > 
> 
> > Absolutely and I just followed you on Twitter
> 
> 
> 
> oh...i'm not that active there but i'll try to be :)
> 
> following you back 

Great! You'll find my Twitter on my GitHub profile

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
