### PR TITLE
Added transition property to social-links in navbar

### LINKED ISSUE #604: [UI ENHANCEMENT] Adding transition properties at the social media links when hovered
We can add the transition properties at the links as they change their background color without any delay when hovered, so it  makes the UI less attractive.
I can work on that and this is related to gssoc'23.

### PR DESCRIPTION
**Pull request by raghav1030**
## Fixes Issue 

Closes #604 

## Changes proposed

added transition property to all 3 social icons for discord, twitter and github.

## Note to reviewers

regarding gssoc'23

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks good! :) LGTM! :)

**Review by rupali-codes — CHANGES_REQUESTED** [review]
could you also do the same for _theme icon_

**Comment by rupali-codes** [comment]
@raghav1030 are you still working on this?

**Comment by raghav1030** [comment]
Oh yes. I'll be making changes into it.

Actually my exams were going on so I was not active here.

**Comment by rupali-codes** [comment]
> Oh yes. I'll be making changes into it.
> 
> Actually my exams were going on so I was not active here.

okay, no issues

**Comment by raghav1030** [comment]
I have made the required changes , Please review them

**Review by rupali-codes — APPROVED** [review]
looks perfect, thanks

**Pull request merged**
