### PR TITLE
Fix: fix alignment of TopBar component's elements

### LINKED ISSUE #148: [Bug] Fix alignment of the TopBar component's elements
### Description

Hi! There is little space for the long subcategory text. We can use `flex-col` in smaller size. In bigger size can stay the `flex-row`.

### Screenshots

TopBar1
TopBar2
TopBar3

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by zvolcsey**
@rupali-codes Hi! I fixed the alignment of TopBar component's elements issue.

## Fixes Issue

Closes #148 

## Changes proposed

- I fixed the alignment of TopBar component's elements.
- I changed the order of CSS classes.
- `GeneralLayout` component has the `px-4` instead of `[subcategory].tsx`'s section. So the `# Home` also has this padding on the main page.

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
HI @zvolcsey Thank you very much!
can we add `top-padding` to icons?  It looks like too close to header
image

**Comment by zvolcsey** [comment]
> HI @zvolcsey Thank you very much!
> can we add `top-padding` to icons?  It looks like too close to header
> image
> 

@rupali-codes Okay, I'll fix it.

**Comment by zvolcsey** [comment]
@rupali-codes Thanks for the feedback. I fixed it. I added `pt-4` in smaller size to the icons container. From `md` breakpoint the TopBar container has `py-4`.

**Review by rupali-codes — APPROVED** [review]
Thank you

**Pull request merged**
