### PR TITLE
fix/2085 footer fixed to bottom

### LINKED ISSUE #2085: [BUG] Footer should be fixed to the bottom
### Description

The footer should be fixed in the bottom, but when the number of items/link to show are less, it comes up

### Screenshots

Screenshot 2023-10-24 at 12 08 31 AM

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by yashnirmal**
## Fixes Issue
Closes #2085

## Changes proposed

Minor change in the style of `layout/GeneralLayout.tsx`

## Screenshots

Screenshot 2023-10-24 at 12 19 23 PM

### CODE REVIEW

**Comment by yashnirmal** [comment]
Hey @CBID2, can you review the changes?

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> Works as mentioned.

**Review by CBID2 — APPROVED** [review]
Looks great

**Review by rupali-codes — APPROVED** [review]
Lgtm

**Pull request merged**
