### PR TITLE
Add a category for hosting

### LINKED ISSUE #157: [Feature] Adding a section on Hosting
### Description

A hosting section could be added to the current sections, which would cover well-known hosting websites such as GitHub Pages and Vercel. If it is okay to include this section, I would like to work on it. 

### Screenshots

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Mani-mk-mk**
closes #157
Hosting Section:

Added Hosting section in the sidebar

This section encompasses two sub-categories:
  - resources for hosting static websites
  - resources for hosting server-side websites.
The changes are depicted in the provided screenshots.

Screenshots

image

image

### CODE REVIEW

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Hi, we just added a new category named `Resources` so can u out this in there as subcategory named `Hosting`. And we can describe if it's either static or dynamic in the description

**Comment by Mani-mk-mk** [comment]
Cool

**Comment by Mani-mk-mk** [comment]
Hey @rupali-codes, I have made the requested changes. I am attaching the snip of the same below.

image

**Review by rupali-codes — APPROVED** [review]
Thank you so much!

**Pull request merged**
