### PR TITLE
fix: vertical overflow issue in the home page

### LINKED ISSUE #161: [BUG] vertiacal overflow issue in the home page
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The home page has a scroll due to which the top bar is getting out of screen after scrolled

### Screenshots

image

### Any additional information?

I suggest we make the TopBar fixed
Because this will be an issue on every page when there will be more cards 

Screenshot from 2023-02-09 10-40-29

### What browser are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by dev-phantom**
## Fixes Issue

Closes #161 
## Changes proposed

made the topbar sticky on both theme

## Screenshots

image

### CODE REVIEW

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Looks good. but it's delaying or taking some time when changing the theme. Could you please fix that?

**Comment by dev-phantom** [comment]
> Looks good. but it's delaying or taking some time when changing the theme. Could you please fix that?

thanks for catching that 
i think one way to fix it is to add transition to the topbar 
i'll add this in my next commit

**Comment by dev-phantom** [comment]
@rupali-codes i've fix this.

**Comment by rupali-codes** [comment]
> @rupali-codes i've fix this.
> 
> Also noticed the same issue on the side nav scroll bar
> 
> Should I open an issue on it

Thanks, yes you can create another issue for that

**Pull request merged**
