### PR TITLE
add: animted-fluent-emojis in db

### LINKED ISSUE #580: [Add] Animated Fluent Emojis
### Site URL

https://animated-fluent-emoji.vercel.app/

### Description of the above provided site

Super cool emojis which are animated and great to use for Readme files or Websites. 
Here's the example of emojis. 

Screenshot 2023-05-20 at 23 59 29

### Category

Frontend

### Sub Category

"icons", "emojis"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by dhruvdabhi101**
## Fixes Issue
Closes #580 

## Changes proposed
- Added new icons resource

## Screenshots
Screenshot 2023-05-21 at 19 18 54
hots

### CODE REVIEW

**Comment by rupali-codes** [comment]
Hey, can you please add _Closes_ right before _#580_ :)

**Comment by dhruvdabhi101** [comment]
> Hey, can you please add _Closes_ right before _#580_ :)

Done ma'am

**Comment by rupali-codes** [comment]
@dhruvdabhi101 the site is kinda crashing, also i'm not able to download any icons from there :)

**Comment by dhruvdabhi101** [comment]
Angry Face with Horns

Bomb

Backhand Index Pointing Left

I have pasted some random emoji from it here. I hope it will work.

**Review by rupali-codes — APPROVED** [review]
thanks, looks good

**Review by CBID2 — APPROVED** [review]
Looks awesome @dhruvdabhi101! 😊 LGTM! 😊

**Pull request merged**
