### PR TITLE
[fix] Revised CODEOWNERS file

### LINKED ISSUE #864: [OTHER] Revising CodeOwners file
### What would you like to share or ask?

Now that @ujjawaltyagii is on the maintainer team, I'm going to add his name to our CODEOWNERS file. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by CBID2**
## Fixes Issue
Closes #864 

## Changes proposed

I added @ujjawaltyagii to the CODEOWNERS file 
## Note to reviewers

@ujjawaltyagii and @rupali-codes, a couple of errors came up, so helping me solve them would be greatly appreciated.

### CODE REVIEW

**Comment by ujjawaltyagii** [comment]
Could you please provide more details about the errors that came up ?

**Comment by CBID2** [comment]
> Could you please provide more details about the errors that came up ?

Hi @ujjawaltyagii. I figured out the error. The file is valid now! :)

**Comment by rupali-codes** [comment]
> > Could you please provide more details about the errors that came up ?
> 
> Hi @ujjawaltyagii. I figured out the error. The file is valid now! :)

is it ready to merge :)

**Comment by rupali-codes** [comment]
@ujjawaltyagii @CBID2 👀

**Comment by ujjawaltyagii** [comment]
@CBID2 just to confirm are you done with the changes ? so that we can proceed to merge this PR

**Review by rupali-codes — APPROVED** [review]
lgtm 👀✨

**Review by ujjawaltyagii — APPROVED** [review]
Looks good to me !

**Pull request merged**
