### PR TITLE
feat: redirect to the corresponding section based on options in empty page screen

### LINKED ISSUE #1735: [Feature] redirect to the corresponding section based on options in empty page screen
### Description

So, these options would be clickable such as `Online Code Editors` and would redirect the users to the corresponding section.

I wanted to contribute this, but I would open issues for others to grab.

@rupali-codes @CBID2 
What do you think?

If you agree, then add `up for grabs`, and `hacktoberfest` labels.

### Screenshots

> I hope you get the idea
image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Ameya02**
## Fixes Issue
Closes #1735 

## Changes proposed
Added Link to wrap over the Typewriter component to redirect to the particular section page when click on the text
Removed autostart and loop as it causes the text to repeat twice

## Screenshots
linkshub

### CODE REVIEW

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> @Ameya02 Well done!

**Review by rupali-codes — COMMENTED** [review]
Previously, the typewriter was clearing the subcategory letter-by-letter but now its clearing it all together, can we fix this?

**Comment by Ameya02** [comment]
So I was trying to make sure that the typewriter works as before but as  i was adding category one at a time for it link to the corresponding url it was rendering same text twice. so i had to remove loop props.

**Comment by Anmol-Baranwal** [comment]
> So I was trying to make sure that the typewriter works as before but as i was adding category one at a time for it link to the corresponding url it was rendering same text twice. so i had to remove loop props to make sure text render only once.

Can you show a video or jam of that? It would be great.

**Comment by Ameya02** [comment]
linkshub2

**Review by CBID2 — APPROVED** [review]
Well done @Ameya02! :)

**Pull request merged**
