### PR TITLE
chore(dep):  migrated to pnpm 

### PR DESCRIPTION
**Pull request by priyankarpal**
- Removed npm from the code
- Added pnpm
- Updated documentation

Solved #372

### CODE REVIEW

**Comment by rupali-codes** [comment]
Hey Priyankar, it's giving the following erros

image

**Comment by priyankarpal** [comment]
> Hey Priyankar, it's giving the following erros
> 
> image
> 

Ok ok trying to fix

**Comment by priyankarpal** [comment]
@rupali-codes I think there is no command related to `pnpm run all` so that it's giving following error.

**Comment by priyankarpal** [comment]
> > @rupali-codes I think there is no command related to `pnpm-run-all` so it's giving the following error.
> 
> Hey, what should we do then? Should we change it back to yarn instead?

it's fixed. Just need to solve the conflict error.

**Comment by rupali-codes** [comment]
> > > @rupali-codes I think there is no command related to `pnpm-run-all` so it's giving the following error.
> > 
> > 
> > Hey, what should we do then? Should we change it back to yarn instead?
> 
> it's fixed. Just need to solve the conflict error.

Awesome, thanks

**Comment by priyankarpal** [comment]
I will die if I go to solve the conflicts. 😆 😢 Going to Open a new PR.

**Pull request closed without merging**
