### PR TITLE
added errorpage

### LINKED ISSUE #723: [Feature] <Add 404 error page >
### Description

@rupali-codes  error page not added to project i am intrested to contribute please assign it to me

### Screenshots

Screenshot (60)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by sagnik-p**
Added error page

## Fixes Issue
Closes #723

## Changes proposed

Added an error page
>simple design
>Back to homepage button

### CODE REVIEW

**Review by rupali-codes — CHANGES_REQUESTED** [review]
hi, where and how can i access this page?

**Comment by sagnik-p** [comment]
Hi
This error page can be viewed easily
By using a browser to open the .html file
I have kept all the stylings inside the html file itself to reduce complications
Please run the errorpage.html file which i have pushed
Thanks

**Comment by sagnik-p** [comment]
If you want I can send screenshot/screen recording
Thanks

**Comment by CBID2** [comment]
> If you want I can send screenshot/screen recording
> Thanks

That would be helpful @sagnik-p

**Comment by sagnik-p** [comment]
https://github.com/rupali-codes/LinksHub/assets/130753205/c5fefed8-44f1-46cf-86d7-8744181dea74

This is the screen recording

**Review by ujjawaltyagii — COMMENTED** [review]
Page looks good to me ! But you just created an html file in main folder shouldn't we move it to component folder and second thing @rupali-codes will confirm that should we keep this page like this or should we create this page in typescript ? 👀

**Comment by sagnik-p** [comment]
Oh
So should I create some folder, please tell me how it should be , i will change it.
And one more thing, I am not familiar with typescript😓. Is this good? I have kept it simple and clean
Thanks

**Comment by rupali-codes** [comment]
> Oh So should I create some folder, please tell me how it should be , i will change it. And one more thing, I am not familiar with typescript😓. Is this good? I have kept it simple and clean Thanks

It does not follow the code structure actually, i'm still confused how and when we going to access this page. You have just created a page and didn't attach or reference it anywhere. 

As @ujjawaltyagii said, it should be under _components_ folder and needs a proper logic for when the page should be displayed. 

@sagnik-p don't scare of typescript, do you know react or next.js? if so, then we can try helping you building the logic, otherwise we will have to close the PR unfortunitely.

**Comment by sagnik-p** [comment]
Oh
I understand now, I had to create the logic for redirecting to the error page if a particular page is not found, I completely forgot about the linking part sorry.
Sorry but I Dont have any idea about next.js and I am a beginner in React so I don't think I will be able to do it properly with react. Sorry for the inconvenience. I am closing the PR.
Thanks for the opportunity! 😊

**Pull request closed without merging**
