### PR TITLE
feat: add Game Development subcategory under YouTube

### LINKED ISSUE #890: [ADD] Game Development under YouTube
### Category Name

none

### Subcategory Name

Game Development

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #890

## Screenshots

game development

## Note

- I can remove the empty json resource

### CODE REVIEW

**Review by rupali-codes — CHANGES_REQUESTED** [review]
just the remove the empty links, or add some data to it :)

**Comment by Anmol-Baranwal** [comment]
> just the remove the empty links, or add some data to it :)

I will remove the values, but it is not possible to remove the `json` file completely because it would result in an error, as indicated by the TypeScript code of the component.

image

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Could you please review this pull request :)

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
