### PR TITLE
[Feature] Search enhancement

### LINKED ISSUE #769: [Feature] Enhance Search Functionality
### Description

The current search functionality only filters subcategories, but I would like to enhance it to enable searching for individual resources. Although categories can also be included, it is not necessary at the moment due to the limited number of categories available.

Additionally, I don't believe it will impact the suggestion functionality that is currently assigned in an issue.

### Screenshots

image

while Replit is already present:
image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- []I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor (note: assigné in not in GSSOC)

### PR DESCRIPTION
**Pull request by MUK-Dev**
## Fixes Issue 
fixes #769

## Changes proposed
- Ability to search resources inside the subcategories
- Show results of the search on the right side
- Show respective subcategories on the left side

## Screenshots

image
image

### CODE REVIEW

**Review by CBID2 — COMMENTED** [review]
Looks good! :)

**Review by rupali-codes — COMMENTED** [review]
It looks much good though, but can you please open the dropdown for initial category or for the results rendered first? that would be much better for the user :)

just like this
image

**Comment by MUK-Dev** [comment]
So do you mean instead of taking the user to the search page I should instead go to the first subcategory page?

**Comment by rupali-codes** [comment]
> So, do you mean instead of taking the user to the search page I should instead go to the first subcategory page?

No no, that's all working fine, i'm just asking you to to open the respective subcategory for which you're rendering results on right side at first

**Comment by MUK-Dev** [comment]
Ok, will look into it in a while.

**Comment by MUK-Dev** [comment]
Ok, I have updated it.
Categories are expanded by default when the user searches.

**Comment by rupali-codes** [comment]
Hey, its nice though, can you please tell me how are u rendering these results at first? 
image

**Comment by MUK-Dev** [comment]
Sure,
**For the results on the right:** I take the query parameter `query` and just filter the database constant available in data.ts which has all the resources.

image

------

**For opening the sidebar categories:**
The functionality was already there it was just not being used

image

I removed the extra useState here which was being used but was not required as there was already logic to expand it in the parent component.

------

image

I added resources for each subcategory here in the object

image

And then I just filter the resources while searching here to 

if the filtered results length is greater than 0 than that means there is a resource that matches the searched query.
So, then I just redirect to search page where that search query is used to filter and display the results.

**Comment by rupali-codes** [comment]
@MUK-Dev Thanks a lot 🚀🚀🚀

**Review by rupali-codes — APPROVED** [review]

**Comment by rupali-codes** [comment]
@CBID2 & @ujjawaltyagii can guys review this PR please?

**Review by CBID2 — APPROVED** [review]
Looks good

**Comment by MUK-Dev** [comment]
Any other good issues that you can recommend?

**Comment by CBID2** [comment]
> Any other good issues that you can recommend?

Not at the moment @MUK-Dev, but I could use some help with my [PR](https://github.com/rupali-codes/LinksHub/pull/1174)

**Comment by MUK-Dev** [comment]
Ok, i'll check it out.

**Pull request merged**
