### PR TITLE
ref: corrected the dockerfile and updated the contributing.md file

### LINKED ISSUE #2406: [Refactor] Refactored project startup code for improved efficiency.
### File Name

Dockerfile

### Reason for Refactoring the Code

The previous implementation of the project startup code functioned adequately but lacked adherence to best practices for maintainability and efficiency. By refactoring the code, I've replaced the initial approach with a more robust and standardized method, ensuring improved code readability and future scalability. This update aligns with recommended practices, enhancing overall project quality and developer experience.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).

### PR DESCRIPTION
**Pull request by JoshiUtsav**
Closes #2406 

Additionally, @rupali-codes, you need to push the Linkshub Docker image to Docker Hub so that contributors can pull it.

### CODE REVIEW

**Comment by CBID2** [comment]
There' are some merge conflicts that need fixing @JoshiUtsav

**Comment by JoshiUtsav** [comment]
image


@CBID2, Seriously???

**Comment by rupali-codes** [comment]
> image
> 
> @CBID2, seriously??? Isn't there any other way to resolve this merge conflict?

Do not commit `package.json` and `package-lock.json` files

**Comment by JoshiUtsav** [comment]
@rupali-codes, what about the version updates, then?

image

**Comment by rupali-codes** [comment]
> @rupali-codes, what about the version updates, then?
> 
> image

We'll do that in anther PR so it won't cause conflicts for others

**Comment by JoshiUtsav** [comment]
@rupali-codes, Do you know how I can pull that specific commit?

**Comment by JoshiUtsav** [comment]
Wait, this PR has gotten worse. I am creating a new one.

**Pull request closed without merging**
