### PR TITLE
Update api.json

### LINKED ISSUE #1815: [Add] <CryptpCurrecy APi >
### Site URL

https://www.coingecko.com/en/api

### Description of the above provided site

CoinGecko provides a free API that offers comprehensive cryptocurrency data, including real-time and historical prices, market capitalization, trading volume, and more. Developers can use this API to access cryptocurrency information programmatically, allowing for integration into websites, applications, and trading tools. It's a valuable resource for anyone interested in tracking and analyzing cryptocurrency market data. To use the CoinGecko API, you can refer to their official documentation for details on endpoints and data retrieval.

### Category

Backend

### Sub Category

APIs

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by aditya7302**
## Fixes Issue
fixes #1815 

## Changes proposed
added CoinGecko api

updated api.json added CoinGecko api documentation link

## Screenshots
image

### CODE REVIEW

**Comment by CBID2** [comment]
Hey @aditya7302. Can you fill out the rest of the PR form?

**Comment by aditya7302** [comment]
I have updated the rest of the PR form

**Comment by Anmol-Baranwal** [comment]
Following the PR template is a must.

If you don't link the issue correctly, even after the PR is merged, the issue might stay open, causing huge problems.

> You can see here.
image

You are linking a PR rather than an issue.

I'm doing it for you this time. Please ensure it next time.

Just a heads-up to help you link issue properly next time. Have a great day!

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by CBID2 — APPROVED** [review]
Merge time!

**Comment by aditya7302** [comment]
thank you i will keep in mind next time.

**Pull request merged**
