### PR TITLE
add links to rust on languages/rust

### LINKED ISSUE #2324: [ADD] <languages/Rust>
### Category Name

Languages

### Subcategory Name

Rust

### Additional Context

Rust is a systems programming language that focuses on safety, speed, and concurrency. It is designed to be memory-safe, thread-safe, and free of data races.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Mouh1b**
## Fixes Issue
Closes #2324 

## Changes proposed

added link to Actix web framework on languages/Rust
added link to Bevy Game engine on languages/Rust
## Screenshots

image

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM. @aftabrehan or @rupali-codes. Can you review and merge this pull request please?

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by aftabrehan — APPROVED** [review]
Looks good to me! 👍

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
