### PR TITLE
To fix #2254 Breadcrumbs issue

### LINKED ISSUE #2254: [Refactor] Breadcrumbs Component
### File Name

components/breadcrumbs

### Reason for Refactoring the Code

It seems we're using different components or icons for breadcrumb navigation. Also, the component name and path should be fixed. It should be `breadcrumbs` instead of `breadcrumps`.

Screenshot 2024-02-02 at 12 32 24 PM

Screenshot 2024-02-02 at 12 33 34 PM

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [ ] I am willing to work on this issue (optional).

### PR DESCRIPTION
**Pull request by sarava338**
## Changes proposed

1. Renamed Breadscrumb component.
2. The issue with Icon is, there is an **.svg** which was corresponding to the issue while 
   appears whenever we're in sub category

### **Icon we have, as HomeIcon.svg**

```
<svg
      width="18"
      height="18"
      viewBox="0 0 18 18"
      xmlns="http://www.w3.org/2000/svg"
  
    >
      <path
        d="M15.621 6.00825L10.7085 2.07825C9.74851 1.31325 8.24851 1.30575 7.29601 2.07075L2.38351 6.00825C1.67851 6.57075 1.25101 7.69575 1.40101 8.58075L2.34601 14.2357C2.56351 15.5032 3.74101 16.5007 5.02351 16.5007H12.9735C14.241 16.5007 15.441 15.4807 15.6585 14.2282L16.6035 8.57325C16.7385 7.69575 16.311 6.57075 15.621 6.00825ZM9.56101 13.5007C9.56101 13.8082 9.30601 14.0632 8.99851 14.0632C8.69101 14.0632 8.43601 13.8082 8.43601 13.5007V11.2507C8.43601 10.9432 8.69101 10.6882 8.99851 10.6882C9.30601 10.6882 9.56101 10.9432 9.56101 11.2507V13.5007Z"
     fill=""
   />
</svg>
```

### **The Mysterious Icon not able to find in the code. But in the page**

```
<svg 
    stroke="currentColor" 
    fill="currentColor" 
    stroke-width="0" 
    version="1.2" 
    baseProfile="tiny" 
    viewBox="0 0 24 24" 
    height="1em" width="1em" 
    xmlns="http://www.w3.org/2000/svg"
>
    <path d="M22.262 10.468c-3.39-2.854-9.546-8.171-9.607-8.225l-.655-.563-.652.563c-.062.053-6.221 5.368-9.66 8.248-.438.394-.688.945-.688 1.509 0 1.104.896 2 2 2h1v6c0 1.104.896 2 2 2h12c1.104 0 2-.896 2-2v-6h1c1.104 0 2-.896 2-2 0-.598-.275-1.161-.738-1.532zm-8.262 9.532h-4v-5h4v5zm4-8l.002 8h-3.002v-6h-6v6h-3v-8h-3.001c2.765-2.312 7.315-6.227 9.001-7.68 1.686 1.453 6.234 5.367 9 7.681l-3-.001z">
   </path>
</svg>
```

## Note to reviewers

Not completed yet. help needed. 
I could not able to find the icon I mentioned as mysterious ICON. Please let me know if you know this...

### CODE REVIEW

**Review by aftabrehan — DISMISSED** [review]
Looks good to me! 👍

**Comment by Anmol-Baranwal** [comment]
@sarava338 
Hi!
Is that svg icon issue fixed?

Do you need any help.

**Comment by sarava338** [comment]
Hi @Anmol-Baranwal,


That svg icon is not fixed. I need help with that. I was not able to find the icon. Could you assist that?

**Comment by Anmol-Baranwal** [comment]
@sarava338 
It's in `assets\icons\svg\HomeIcon.svg`

**Comment by Anmol-Baranwal** [comment]
Hi @sarava338 
The problem is there are two components. You ultimately have to merge both.

The icon you were saying is in `breadcrumbs`.
image

---

And the other component is `TopBar`. 
The icon that you were not able to find is.
`import { TiHomeOutline } from 'react-icons/ti'` => `<TiHomeOutline />`

image

I hope this helps :D

Let me know if you need anything else.

**Comment by sarava338** [comment]
> Hi @sarava338 The problem is there are two components. You ultimately have to merge both or use same icon.
> 
> The icon you were saying is in `breadcrumbs`. image
> 
> And the other component is `TopBar`. The icon that you were not able to find is. `import { TiHomeOutline } from 'react-icons/ti'` => `<TiHomeOutline />`
> 
> image
> 
> I hope this helps :D
> 
> Let me know if you need anything else.

Thank you @Anmol-Baranwal for find that culprit svg `TiHomeOutline` Icon from `TopBar`. actually, I am not aware that whenever a `subcategory` clicked, it was loading the `TopBar` component.


I am going to use `**HomeIcon.svg**` in both places. So it will looks good.

**Comment by sarava338** [comment]
Completed the issue. But still, there is a small style differentiation inbetween the two components `BreadCrumbs` and `TopBar`. Check it out guys...

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please deploy this :D

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> There is a slight difference in font weight, but that's okay for me.

**Review by aftabrehan — APPROVED** [review]
Looks good to me!

**Review by rupali-codes — APPROVED** [review]
Lgtm

**Pull request merged**
