### PR TITLE
chore: add Awesome Illustrations 4 Projects in frontend/illustrations

### LINKED ISSUE #894: [Add] Awesome Illustrations 4 Projects under frontend/illustrations
### Site URL

https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects

### Description of the above provided site

Discover over 250 professionally curated illustrations from 50+ websites, conveniently organized into four categories. Bring your projects to life with these polished and captivating visuals, trusted by 50+ Product Hunt users.

### Category

Frontend

### Sub Category

Illustrations

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #894 

## Screenshots

image

### CODE REVIEW

**Review by rupali-codes — APPROVED** [review]
lgtm

**Review by ujjawaltyagii — COMMENTED** [review]
Looks good but @Anmol-Baranwal  shouldn't a direct link be included to the illustration page instead of repo ?

**Comment by Anmol-Baranwal** [comment]
> Looks good but @Anmol-Baranwal shouldn't a direct link be included to the illustration page instead of repo ?

I am the author of the repository, and yes, I have created it in a Markdown file. I plan to convert the data into a website using an appropriate tech stack in the future. However, for now, it is in good shape and functions well. I have ensured that it is easy to navigate and locate the desired illustrations.

Furthermore, it contains a larger collection of illustrations compared to many other websites combined.

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Comment by CBID2** [comment]
@rupali-codes, for some reason this PR has not met the successful preview deployment requirement.

**Comment by rupali-codes** [comment]
> @rupali-codes, for some reason, this PR has not met the successful preview deployment requirement.

I have disabled that, new PRs from now won't have this issue

**Pull request merged**
