### PR TITLE
feat: add internationalization

### LINKED ISSUE #131: [Feature] Add internationalization i18n
### Description

Currently, the application supports the English language. It could be appealing to support other languages like Spanish

### Screenshots

image

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by nujovich**
## Changes proposed

Add internationalization support

## Screenshots

New Button on the right side nav bar

image

image

image

## Note to reviewers

English leaved by default. Added spanish support

### CODE REVIEW

**Comment by rupali-codes** [comment]
@nujovich thank you, please resolve these error so we can preview
image

**Comment by nujovich** [comment]
> @nujovich thank you, please resolve these error so we can preview image

Oki! My apologies! Issue is fixed

**Comment by rupali-codes** [comment]
@nujovich could you please resolve merge conflicts?

**Comment by nujovich** [comment]
> @nujovich could you please resolve merge conflicts?

Done! I made sure the new search bar and the new youtube categories work with the i18n

**Review by rupali-codes — COMMENTED** [review]
It's nice, can we add other langs as well?

**Comment by nujovich** [comment]
> It's nice, can we add other langs as well?

Sure, just let me know!

**Comment by rupali-codes** [comment]
@nujovich Thanks for your work. Could you please resolve merge conflicts?

**Review by rupali-codes — CHANGES_REQUESTED** [review]
@nujovich could you please close this PR and create one with only files which you have updated. Thank you

**Pull request closed without merging**
