### PR TITLE
Sidebar Redesign

### LINKED ISSUE #2171: feat: add new header design
> You can view the figma file [here](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?type=design&node-id=17-231&mode=design&t=29U3Qw0LktnVRteR-0).

image

> The design should be responsive. 

---

We recommend updating the styling of existing components, otherwise you can add extra components if there is a need.

- You also have to complete theme toggler

image

> Any changes to the above design are welcome. Please feel free to share your thoughts, and we will discuss them thoroughly.

---
### ⚠️ Make sure to push all the changes into `dev` branch

### PR DESCRIPTION
**Pull request by aftabrehan**
Closes #2171 

### Preview

<div align="center">
 Screenshot 2023-11-12 at 9 49 35 PM

 Screenshot 2023-11-12 at 10 16 10 PM
</div>

## Changes proposed

- [x] Update sidebar design
- [x] Update searchbar component
- [x] Update links design

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks good to me! :) @rupali-codes and @Anmol-Baranwal, what do you think?

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
I've checked the latest deployment with chrome dev tools.

As shown below, the screen size is almost 1800 which is large enough, and the zoom is not even 100%.


So, you need to make it responsive enough to show the same structure on lower screen sizes.
image

In case you feel, I'm wrong. Below are the screenshots with online cross-browser testing.

> Chrome
image

> Edge
image


> Firefox
image

**Comment by aftabrehan** [comment]
@Anmol-Baranwal, Yes you're right. Sure, we can make it responsive for these screens.

**Comment by rupali-codes** [comment]
@aftabrehan & @Anmol-Baranwal any updates guys?

**Comment by aftabrehan** [comment]
> @aftabrehan & @Anmol-Baranwal any updates guys?

I'll work on these adjustments tomorrow or so.

**Comment by CBID2** [comment]
@Anmol-Baranwal @rupali-codes review this please

**Pull request merged**
