### PR TITLE
Adding a sub-category under youtube

### PR DESCRIPTION
**Pull request by raghav1030**

### CODE REVIEW

**Comment by raghav1030** [comment]
I have tried to resolved conflicts that were occurring in the package.json file.
Please review the changes...

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Hi @raghav1030  great work. 
But i can not see this in the sidebar, to show this you will have to add it in `database/data.ts` file, there is a object with category `youtube` please add this web3-metaverse there too. 
Thank you

**Comment by raghav1030** [comment]
Thanks for the feedback... I have fixed all the bugs regarding the newly added sub-category 
Please review it

**Review by rupali-codes — APPROVED** [review]
Looks awesome

**Pull request merged**
