### PR TITLE
Fixed issue #1213 Added new link for image

### PR DESCRIPTION
**Pull request by prem-code-github**

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
I agree, but it seems that @prem-code-github did not confirm that they are in GSSOC’23.

**Review by CBID2 — COMMENTED** [review]
Hi @prem-code-github. It looks wonderful but you didn't follow the PR rules in the Contributing Guide.

**Review by CBID2 — CHANGES_REQUESTED** [review]
See my previous comment

**Comment by Akanksha-202** [comment]
> I agree, but it seems that @prem-code-github did not confirm that they are in GSSOC’23. Also, @Akanksha-202 seemed to want to do this pull request. @rupali-codes, should this PR be merged?

thanks, @CBID2 , I mentioned in my issue that I'm willing to work on this and a GSSoC contributor too!
Appreciate the fairness! <3

@prem-code-github kindly read others' issue thoroughly before making PR! Everything is mentioned clearly in that about my willingness to work over it!

**Comment by CBID2** [comment]
> > I agree, but it seems that @prem-code-github did not confirm that they are in GSSOC’23. Also, @Akanksha-202 seemed to want to do this pull request. @rupali-codes, should this PR be merged?
> 
> 
> 
> thanks, @CBID2 , I mentioned in my issue that I'm willing to work on this and a GSSoC contributor too!
> 
> Appreciate the fairness! <3
> 
> 
> 
> @prem-code-github kindly read others' issue thoroughly before making PR! Everything is mentioned clearly in that about my willingness to work over it!

You’re welcome @Akanksha-202. With that settled, I’m going to close this PR.

**Pull request closed without merging**
