### PR TITLE
Fix bugs and refactor `Searchbar` and `SideNavbar`

### LINKED ISSUE #1358: [BUG] Searchbar doesn't give unique suggestions and other bugs
### Description

1. Searchbar doesn't give unique suggestions.

    Different categories can have common sub-categories (backend/testing and youtube/testing for example). The filtering code here doesn't consider that: https://github.com/rupali-codes/LinksHub/blob/4311806e85b86f935124cb29a1ca1df0e90a8ccc/components/Searchbar/Searchbar.tsx#L37-L40
    As a result, for a given search query, same suggestions are rendered more than once.

    https://github.com/rupali-codes/LinksHub/assets/73361366/c6627f39-61ab-4833-997a-7511fc6118b3

    This also results in the `key`s not being unique, and that reflects in the number of suggestions rendered. There are only 2 'testing' sub-categories, but 5 are rendered in the video.
    https://github.com/rupali-codes/LinksHub/blob/4311806e85b86f935124cb29a1ca1df0e90a8ccc/components/Searchbar/Searchbar.tsx#L101-L109
    
2. Hitting `Enter` doesn't close the suggestions. It is just not handled in the form submit handler. Clicking the search icon works though because of the 'mousedown' handler.
    https://github.com/rupali-codes/LinksHub/blob/4311806e85b86f935124cb29a1ca1df0e90a8ccc/components/Searchbar/Searchbar.tsx#L50-L67

3. The error message rendered when the form is submitted with an empty query isn't removed when the user starts typing a query. I think this is an example of 'impossible state' and should be avoided.

    https://github.com/rupali-codes/LinksHub/assets/73361366/7078f99c-2c54-40b8-a654-f77512e9b13f

4. Closing and re-opening the `SideNavbar` momentarily displays the entire `SideNavbarCategoryList`, not just the ones related to the search query.

    https://github.com/rupali-codes/LinksHub/assets/73361366/d3228b41-652c-4b97-91d8-56f70a7ee331

I'd like work on this. 

### Screenshots

_No response_

### Any additional information?

_No response_

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by abhijithmuthyala**
Closes #1358 

## Changes proposed

- Fix the bugs mentioned in #1358.
- Refactor `SideNavbar` and `Searchbar` components.
- Remove unnecessary react states and effects.
- Use computed values from state.
- Performance optimizations using `memo` and `useMemo` whereever appropriate.

## Screenshots

https://github.com/rupali-codes/LinksHub/assets/73361366/233eab18-a6f5-42b2-b847-cabcb6554f32

## Note to reviewers

**Code style**: I personally prefer using named function declarations over arrow functions, but most of the code base seems to be using arrow functions, so I went with them. In the future, I think it's good to enforce only one form of declaring functions for consistency.

### CODE REVIEW

**Review by k-deepak04 — APPROVED** [review]

**Review by rupali-codes — CHANGES_REQUESTED** [review]
could you please keep your changes specifically to the issue? feel free to raise another issues and PRs for further changes.

**Comment by abhijithmuthyala** [comment]
> could you please keep your changes specifically to the issue?

I have only fixed the bugs mentioned in the linked issue though? Are you referring to the refactor commits? In that case, here's my reasoning:

Unnecessary states, effects and hooks made the code really hard to reason about. If you notice, I mentioned 4 bugs in the issue but there are only 3 fix commits in this PR. The last bug naturally got fixed with the refactor, I didn't do anything specific to fix that. So in my opinion, the refactor itself is a bug fix in this case 😅.

It did strike my mind that I might be stuffing too much into a single PR, but as I said, the refactor itself turned out to be a bug fix, so I thought that should be fine. I'm open to feedback, thanks!

**Comment by abhijithmuthyala** [comment]
I forgot to mention that the debounce logic here doesn't server its purpose.
https://github.com/rupali-codes/LinksHub/blob/0830451643de35579d7998c6d147da355b1f42cc/hooks/useSearch.ts#L4-L20

If I'm not wrong, debouncing is relevant to `SearchbarSuggestions` (the `onChange` event), not to `CardsList` 
 (the `onSubmit` event). But here the debounce is on `CardsList`. If you set the timeout to 2000ms for example, the suggestions are updated *as we type*, but the search results appear 2 seconds *after* submitting the form. 
 
 I removed debouncing from this PR because it isn't functional anyway in its current form. It can be addressed in another PR.

**Review by CBID2 — COMMENTED** [review]
Let's see what @rupali-codes suggests

**Comment by rupali-codes** [comment]
Hi, could you please resolve merge conflicts?

**Comment by abhijithmuthyala** [comment]
Hi @rupali-codes, there is a pre-commit hook error (duplicate URL) preventing the merge commit. Do you want this fixed in a separate PR, or shall I include it in the merge commit?

Error source: Same URL for different resources

https://github.com/rupali-codes/LinksHub/blob/acadde1af039efafed0ce3fbeb4a88cf163dba6d/database/resources/official-docs.json#L73-L75 https://github.com/rupali-codes/LinksHub/blob/acadde1af039efafed0ce3fbeb4a88cf163dba6d/database/resources/official-docs.json#L80-L82

**Review by k-deepak04 — COMMENTED** [review]
resolve the conflicts

**Comment by abhijithmuthyala** [comment]
> there is a pre-commit hook error (duplicate URL) preventing the merge commit. Do you want this fixed in a separate PR, or shall I include it in the merge commit?

@k-deepak04

**Comment by abhijithmuthyala** [comment]
> keep both of them

Sorry, I'm not sure what you mean.

```
$ git commit -m "Merge branch 'main' into searchbar"
Duplicate url values found in database/resources/official-docs.json: https://svelte.dev/docs/introduction
[Error] Duplicates URLs found
husky - pre-commit hook exited with code 1 (error)
```
Git refuses to perform the merge commit. So this issue has to be addresses first. I wanted to know if you are ok with including the fix (updating the url for Express.js) within the merge commit itself, or fix it first in a separate PR and then proceed with this.

**Comment by rupali-codes** [comment]
> > keep both of them
> 
> Sorry, I'm not sure what you mean.
> 
> ```
> $ git commit -m "Merge branch 'main' into searchbar"
> Duplicate url values found in database/resources/official-docs.json: https://svelte.dev/docs/introduction
> [Error] Duplicates URLs found
> husky - pre-commit hook exited with code 1 (error)
> ```
> 
> Git refuses to perform the merge commit. So this issue has to be addresses first. I wanted to know if you are ok with including the fix (updating the url for Express.js) within the merge commit itself, or fix it first in a separate PR and then proceed with this.

it happens sometimes, could you please create a fresh PR?

**Comment by abhijithmuthyala** [comment]
> it happens sometimes, could you please create a fresh PR?

Just confirming - You mean a fresh PR for the duplicate URL issue right?

**Comment by rupali-codes** [comment]
> > it happens sometimes, could you please create a fresh PR?
> 
> Just confirming - You mean a fresh PR for the duplicate URL issue right?

yes, with no conflicts. make sure you update your local repo with `linkshub:main`

**Comment by abhijithmuthyala** [comment]
@CBID2 Have you closed the PR by accident?

**Comment by CBID2** [comment]
> @CBID2 Have you closed the PR by accident?

No @abhijithmuthyala. I thought a new one was going to be made.

**Comment by abhijithmuthyala** [comment]
> I thought a new one was going to be made.

@CBID2 Oh no, the discussion was about a different issue blocking this PR. No worries I'll create a new one sometime later.

**Comment by CBID2** [comment]
> > I thought a new one was going to be made.
> 
> 
> 
> @CBID2 Oh no, the discussion was about a different issue blocking this PR. No worries I'll create a new one sometime later.

Oh ok, so reopen it @abhijithmuthyala?

**Comment by abhijithmuthyala** [comment]
> Oh ok, so should I reopen it @abhijithmuthyala?

Sure, thanks.

**Comment by CBID2** [comment]
> > Oh ok, so should I reopen it @abhijithmuthyala?
> 
> 
> 
> Sure, thanks.

Done @abhijithmuthyala

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by CBID2** [comment]
Now it's your turn @rupali-codes

**Pull request merged**
