### PR TITLE
fix: improve sidenavbar body with opacity

### LINKED ISSUE #1420: [BUG] improve sidebar to make elements visually accessible
### Description

@rupali-codes @CBID2 

I believe this issue is important, so I am going to submit a PR by tomorrow. Let me know what you think.

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #1420 

## Changes proposed

- Fixed the issue mentioned in the issue description

## Screenshots

image

## Note to reviewers

It always feels amusing when such a great issue, which has such a significant impact, is fixed in just one line, even though it takes time to find that one line.

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks pretty good

**Review by rupali-codes — COMMENTED** [review]
ig it looks better the way it is, and also we are not using white anywhere

@k-deepak04 and @CBID2  what do you think about this?

**Comment by Anmol-Baranwal** [comment]
> can you change the color to grayish as we are not using white anywhere

Sure.

**Comment by Anmol-Baranwal** [comment]
> can you change the color to grayish as we are not using white anywhere

> Decreasing opacity
image

> Using gray color, seems to mess with navigation list.
image

@rupali-codes 
What should I do?
White seems to be good for accessibility and visual appeal.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I have done it for general just to correct the opacity. I am not changing any color theme. So, please look into this.

**Review by k-deepak04 — COMMENTED** [review]
@Anmol-Baranwal please share the screenshots after changes requested by @rupali-codes

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal please share the screenshots after changes requested by @rupali-codes

@k-deepak04 
Done.

image

**Review by rupali-codes — APPROVED** [review]
lgtm, thanks

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Pull request merged**
