### PR TITLE
fix: typos and grammatical errors

### LINKED ISSUE #2435: [TYPO] Typo in Header
### Description

GitHub social icon has title `Github`, it should be `GitHub`.
LinkedIn social icon has title `Linkedin`, it should be `LinkedIn`.

Theme toggler has title `Theme dark`, it should be `Dark Theme`.

### Screenshots

_No response_

### Any additional information?

_No response_

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Jay-Karia**
## Issue
Closes #2435

## Changes proposed

This PR fixes typos and grammatical errors in home page and header.
Github -> GitHub
Linkedin -> LinkedIn
Theme dark -> Dark Theme
Theme light -> Light Them

### CODE REVIEW

**Comment by rupali-codes** [comment]
@Jay-Karia could you please attach the issue in the PR description?

**Review by rupali-codes — COMMENTED** [review]
@Jay-Karia could you please fix the below issue?

image

**Comment by Jay-Karia** [comment]
Adding `resolvedTheme?.charAt(0) ...` might work.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
