### PR TITLE
Added new resource DSA playlist

### PR DESCRIPTION
**Pull request by Abhinavcode13**
Added the resource under the youtube section

## Fixes Issue

Closes the issue number #839

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
please review the PR @CBID2 and @rupali-codes 

thankyou

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hi @Abhinavcode13. I found some typos in your description. Also, please refrain from tagging the maintainers multiple times. We will address your pull requests when we can.

**Review by Abhinavcode13 — COMMENTED** [review]
updated

**Review by CBID2 — APPROVED** [review]
LGTM!

**Pull request merged**
