### PR TITLE
Solved hide home screen Title

### LINKED ISSUE #275: [BUG] Hide Home screen Title
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The tilte on the Home Screen should be taken off

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by Niralisj**
## Fixes Issue
 closes #275 [BUG] Hide Home screen Title 

## Changes proposed
changed in the components/TopBar/TopBar.tsx file.

## Screenshots
image

### CODE REVIEW

**Review by Eugene44-hub — CHANGES_REQUESTED** [review]
The tite is not showing on other screens too. Just take the title out from the home screen but it should show on other screens

**Comment by pramodreddypandiri** [comment]
**Hiding Header Title** is Not good, coz if there is no header title on page user does not know what cards he is seeing. 
In large screen he can know that from sideNav bar,
But in mobile view he cannot see it (_**he has to click on menu to see what category/subcategory he is currently watching**_)
@Eugene44-hub , @rupali-codes  what do you say.

**Comment by Eugene44-hub** [comment]
@pramodreddypandiri I meant only on the Homepage I don't mean for all pages

**Comment by Eugene44-hub** [comment]
I will notify @Niralisj to fix this thanks for informing @pramodreddypandiri

**Comment by Eugene44-hub** [comment]
@Niralisj the title should only be hidden on this screen

**Comment by Niralisj** [comment]
> @Niralisj the title should only be hidden on this screen
> 
> 

@Eugene44-hub oh okay I apologize, thank you for letting me know, I will fix this.

**Comment by rupali-codes** [comment]
@Niralisj Hey, are you still working on this?

**Comment by Niralisj** [comment]
> @Niralisj Hey, are you still working on this?

yes, i am, sorry for the late, if i don't solve it by Sunday you can assign it to someone.

**Comment by CBID2** [comment]
Hey @Niralisj. Have you solved the issue yet?

**Comment by rupali-codes** [comment]
This issue was fixed.

**Pull request closed without merging**
