### PR TITLE
Add Font Awesome

### LINKED ISSUE #1108: [Add] Font Resource
### Site URL

https://fontawesome.com/

### Description of the above provided site

Font Awesome is the Internet's icon library and toolkit, used by millions of designers, developers, and content creators.

### Category

Frontend

### Sub Category

fonts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Sriparno08**
## Fixes Issue

Closes #1108

## Changes proposed

I have added a font resource to the website.

## Screenshots

Screenshot 2023-06-25 205039

## Note to reviewers

This PR is part of GSSoC'23.

### CODE REVIEW

**Review by CBID2 — DISMISSED** [review]
LGTM! :) You've been doing great with the descriptions @Sriparno08! 😄 Keep it up! 👍🏾

**Comment by Sriparno08** [comment]
Thanks, @CBID2!

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Can you please format the code?

**Comment by Sriparno08** [comment]
Done, @rupali-codes!

**Review by rupali-codes — APPROVED** [review]
thanks

**Pull request merged**
