### PR TITLE
"Added New Frontend Resource"

### LINKED ISSUE #632: [Add] ColorPick Eyedropper
### Site URL

https://chrome.google.com/webstore/detail/colorpick-eyedropper/ohcpnigalekghcmgcdcenkpelffpdolg

### Description of the above provided site

This is a Google Chrome Extention that has a zoomed eyedropper & color chooser tool that allows you to select color values from webpages.

### Category

Frontend

### Sub Category

"Colors"

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Ishita-Ghosh-25**
Closes #632

## Changes proposed
A new Resource in the frontend Section under the subcategory of Colors is added.

### CODE REVIEW

**Comment by CBID2** [comment]
@Ishita-Ghosh-25, can you solve the conflicts in your branch, please?

**Comment by Ishita-Ghosh-25** [comment]
@CBID2 Should I raise a new Pull Rerquest with the changes you mentioned as the conflicts are not getting reflected on my local?

**Comment by CBID2** [comment]
> @CBID2 Should I raise a new Pull Rerquest with the changes you mentioned as the conflicts are not getting reflected on my local?

Did you try following the Contributing file to get the repo locally @Ishita-Ghosh-25?

**Comment by Ishita-Ghosh-25** [comment]
@CBID2 I resolved the conflicts, could you please check and approve the merge request

**Review by CBID2 — APPROVED** [review]
LGTM! 😀

**Review by rupali-codes — APPROVED** [review]
looks good

**Pull request merged**
