### PR TITLE
fix: search functionality not working as expected

### LINKED ISSUE #2579: [BUG] Search Functionality Not Working as Expected
### Description

The search functionality in the "Frontend" section does not seem to be working correctly. When searching for specific terms (e.g., "frontend"), the results displayed are either incomplete, irrelevant, or not filtered as expected.

### Screenshots

Screenshot 2024-12-02 184455

### Any additional information?

Improving the search functionality would enhance the usability and overall user experience of the application.

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Bugbuster2004**
Closes #2579 

## Fixes Issue

fixed the search functionality behaviour

## Changes proposed

1. added a **searchOptions** function in the **database/data.ts** . This code is creating a flat array of search options from the **sidebarData** by combining the subcategory data with its corresponding category
2. in **Searchbar.tsx** changed the logic of **getFilteredSuggestions** as the **normalisedQuery** was not working as expected

## Screenshots

image
this is how the data is being rendered in the sidebar now

## Note to reviewers

kindly test the PR at your machine and suggest any changes if required

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
Hey @Bugbuster2004, can you please comment out the `console.log`s ?

**Comment by Bugbuster2004** [comment]
hey @rupali-codes  did the changes as suggested.

**Review by rupali-codes — DISMISSED** [review]
Thanks @Bugbuster2004, looks good!

**Comment by Bugbuster2004** [comment]
hey @rupali-codes  so what are the next steps?

**Comment by Bugbuster2004** [comment]
hey @rupali-codes  any updates regarding the PR?

**Comment by rupali-codes** [comment]
@Bugbuster2004 could you please resolve the merge conflicts?

**Comment by Bugbuster2004** [comment]
hey @rupali-codes resolved the conflicts

**Pull request merged**
