### PR TITLE
Add/redis to database

### LINKED ISSUE #1817: [Add] <Add Redis database>
### Site URL

https://redis.io/

### Description of the above provided site

The open source, in-memory data store used by millions of developers as a database, cache, streaming engine, and message broker.

### Category

Backend

### Sub Category

Database

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by Manmit124**
Added Redis to the database
Closes #1817

### CODE REVIEW

**Review by CBID2 — DISMISSED** [review]
Well done @Manmit124! :) 
Future tip: use `git revert` whenever you see commits from another branch come to a new one.

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
@Manmit124 
Why did you add Auth0 here if there is a specific PR #1818 

remove auth0 from here.

**Comment by CBID2** [comment]
> @Manmit124 
> 
> Why did you add Auth0 here if there is a specific PR #1818 
> 
> 
> 
> remove auth0 from here.

Ooh thanks for catching that @Anmol-Baranwal. @Manmit124, make the necessary changes please

**Comment by Anmol-Baranwal** [comment]
@Manmit124 
You made wrong changes, how can you push such a change. It will not even run locally.

**Review by rupali-codes — COMMENTED** [review]
@Manmit124 why have you deleted authentication.json?

**Comment by CBID2** [comment]
Any updates on this @Manmit124?

**Pull request closed without merging**
