### PR TITLE
"Saved" link redirects to home page before navigating to the saved page

### PR DESCRIPTION
**Pull request by drakeRAGE**
This PR resolves the issue where clicking the "Saved" link in the header would first redirect users to the home page before navigating to the `/saved` page.

### Changes Made:

- **Navigation Logic:** Adjusted the `renderLinks` function to ensure that the "Saved" link doesn't trigger an unnecessary home page redirect when clicked.
- **Route Matching:** Updated the route matching logic to properly identify and activate the correct navigation item based on the current URL path.

### Possible Reasons for the Bug:

- **Next.js Partial Rendering:** The issue could also be due to Next.js partially rendering the component instead of performing a full-page render, leading to the unexpected redirection behavior.
- **Route Mismatch:** The route matching logic might have been too general, causing the link to match the home page route before navigating to the correct path.
- **Default Navigation Behavior:** The "Saved" link could have been treated as a default link or fallback, resulting in the browser briefly redirecting to the home page.
- **State Handling:** A potential race condition or state mismanagement could have caused the link to reset to the home page before properly setting the correct route.

### Issue Link:

This PR addresses issue #2428.

### Checklist:

- [x] Verified that the "Saved" link now directly navigates to the `/saved` page without any intermediate redirection.
- [x] Tested across different screen sizes to ensure consistent behavior.

---

### CODE REVIEW

**Review by Jay-Karia — CHANGES_REQUESTED** [review]
It seems that the issue is not solved.
It still redirects to home page and then to saved page

**Comment by drakeRAGE** [comment]
Thanks, I will recheck this.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Comment by rupali-codes** [comment]
> Thanks, I will recheck this.

Is there any update on this?

**Comment by Jay-Karia** [comment]
@drakeRAGE ?

**Comment by rupali-codes** [comment]
Closing the PR due to inactivity

**Pull request closed without merging**
