### PR TITLE
chore: Add DaFont to frontend/font category

### LINKED ISSUE #1204: [Add] <DaFont to the font category>
### Site URL

https://www.dafont.com/

### Description of the above provided site

DaFont is a platform that allows users to download and share fonts. DaFont offers a wide variety of fonts, including both free and commercial fonts.

### Category

Frontend

### Sub Category

fonts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by AhorIsaac**
## Fixes Issue
Closes #1204 

## Changes proposed
I added DaFont to the fonts subcategory of the frontend category.

## Screenshots
Screenshot 2023-07-07 19 29 46

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by k-deepak04 — APPROVED** [review]

**Comment by k-deepak04** [comment]
@CBID2 @rupali-codes please merge this i'm not getting any option to merge

**Comment by CBID2** [comment]
> @CBID2 @rupali-codes please merge this i'm not getting any option to merge 
> 
> 
> 
> image
> 
> 

Unfortunately @k-deepak04, I don't have access to Linkshub's Vercel account so we'll have to wait for @rupali-codes' response.

**Comment by k-deepak04** [comment]
@rupali-codes merge this one too

**Comment by rupali-codes** [comment]
@CBID2 we have resolved this merge issue before, idk why its coming again 👀

**Pull request merged**
