### PR TITLE
[feat] : Error page added

### PR DESCRIPTION
**Pull request by PatilHarshh**
## Fixes Issue
#723

### CODE REVIEW

**Comment by PatilHarshh** [comment]
@rupali-codes @CBID2 please review my work

**Review by CBID2 — COMMENTED** [review]
Looks good

**Review by k-deepak04 — APPROVED** [review]

**Comment by k-deepak04** [comment]
@PatilHarshh  the deployment is failing, please check that
@rupali-codes help him by giving the error message.

**Comment by rupali-codes** [comment]
@PatilHarshh & @k-deepak04 its just showing me this, no such errors

image

**Comment by PatilHarshh** [comment]
yah @k-deepak04  and @rupali-codes it has no errors it showing deployement error because it needs approving to merge i think

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by rupali-codes** [comment]
> LGTM

You shouldn't merge the PR when the preview is getting failed, it will fail the production too. Please be careful

**Comment by rupali-codes** [comment]
@PatilHarshh the production is getting failed, so i'm reverting this PR, could you please raise a new PR for the changes you have made??

**Comment by CBID2** [comment]
> > LGTM
> 
> 
> 
> You shouldn't merge the PR when the preview is getting failed, it will fail the production too. Please be careful

Ooh sorry @rupali-codes. I merged because of [this response](https://github.com/rupali-codes/LinksHub/pull/1233#issuecomment-1626884368)

**Comment by k-deepak04** [comment]
> yah @k-deepak04 and @rupali-codes it has no errors it showing deployement error because it needs approving to merge i think

@PatilHarshh where have you learned this that it shows deployment error and merging this error one will resolve the things?
please don't falsely say things as it will cause problem contribute fairly and nicely.

**Comment by k-deepak04** [comment]
@PatilHarshh would you like to give a try to make the things work?
or else @rupali-codes shall i wind this up by myself ??

**Comment by PatilHarshh** [comment]
> > yah @k-deepak04 and @rupali-codes it has no errors it showing deployement error because it needs approving to merge i think
> 
> @PatilHarshh where have you learned this that it shows deployment error and merging this error one will resolve the things? please don't falsely say things unless confirmed and verified.

Apologize, i will correct my mistake ,

**Comment by PatilHarshh** [comment]
> > LGTM
> 
> You shouldn't merge the PR when the preview is getting failed, it will fail the production too. Please be careful

Apologies

**Comment by PatilHarshh** [comment]
@k-deepak04 I want to cure my mistake , i want to proceed this issue now !! , But i am unsure about why deployment is failing i tried on local it was fine , need some descriptive error @rupali-codes

**Comment by rupali-codes** [comment]
> @k-deepak04 I want to cure my mistake , i want to proceed this issue now !! , But i am unsure about why deployment is failing i tried on local it was fine , need some descriptive error @rupali-codes

Sure, could you please UPDATE your local branch with `linkshub:main`? that might resolve the isssue, if not, then please tag me on our [discord server](https://discord.gg/BkvTxZAW)

**Pull request merged**
