### PR TITLE
Solved the popup responsive modal issue

### LINKED ISSUE #274: [BUG] Modal Responsiveness
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

Modal isn't looking nice on mobile view

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by Pinaka-Pani-18**
## Fixes Issue
Closes #274 [BUG] Modal Responsiveness

## Changes proposed
1. changed in the components/popup/index.tsx file.

## Screenshots
responsive modal issue

responsive issue

### CODE REVIEW

**Review by Eugene44-hub — APPROVED** [review]
Perfect

**Comment by Pinaka-Pani-18** [comment]
> Perfect

Thank you

**Review by rupali-codes — APPROVED** [review]
Nice work, thansks

**Comment by Pinaka-Pani-18** [comment]
> Nice work, thansks

You are welcome

**Pull request merged**
