### PR TITLE
Fix1806 sidebar responsive

### LINKED ISSUE #1806: [BUG] Side navigation bar is not responsive for Samsung Galaxy fold
### Description

Sidebar is not responsive for not responsive for samsung galaxy fold and other folding devices

### Screenshots

Screenshot 2023-10-04 at 11 02 09 PM

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by yashnirmal**
## Fixes Issue

Closes #1806

## Changes proposed

Made the sidebar responsive by adding a new media-query

## Screenshots
Screenshot 2023-10-05 at 12 04 08 PM

## Note to reviewers
None

### CODE REVIEW

**Review by CBID2 — COMMENTED** [review]
I don't have a Samsung so I'm going to keep my feedback general and say it's ok. @Anmol-Baranwal and @rupali-codes, what do you think?

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 


> @CBID2 
> It works, no need to worry.

**Review by CBID2 — APPROVED** [review]
Well done @yashnirmal

**Comment by yashnirmal** [comment]
thanks @CBID2

**Pull request merged**
