### PR TITLE
feat: add theme styled links in the footer

### LINKED ISSUE #1074: [Feature] add theme styling to footer in light mode
### Description

We can highlight the links with a theme color (purple) to make them accessible and distinct in light mode.

### Screenshots

> Dark mode
image

> Light mode
image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Resolves #1074

## Screenshots

> Dark mode
image

> Light mode
image

### CODE REVIEW

**Comment by CBID2** [comment]
Hey @Anmol-Baranwal! :) Have you ran these colors through an accessibility checker? I want ensure that they meet this standard before we merge this PR.

**Comment by Anmol-Baranwal** [comment]
> Hey @Anmol-Baranwal! :) Have you ran these colors through an accessibility checker? I want ensure that they meet this standard before we merge this PR.

No, I believe that we should change the colors all at once after reviewing the final color palette that has been decided. However, I am willing to review and make the changes if you want me to.

**Comment by CBID2** [comment]
> > Hey @Anmol-Baranwal! :) Have you ran these colors through an accessibility checker? I want ensure that they meet this standard before we merge this PR.
> 
> No, I believe that we should change the colors all at once after reviewing the final color palette that has been decided. However, I am willing to review and make the changes if you want me to.

That's a good plan @Anmol-Baranwal! :) I asked this question because I was thinking about #1045.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Review by CBID2 — APPROVED** [review]
LGTM

**Pull request merged**
