### PR TITLE
Update README.md

### LINKED ISSUE #1509: [DOCS] UPDATE README,SECURITY,AND CONTRIBUTING PAGE
### Issue Description

There are a lot of grammatical errors in the README, SECURITY,AND CONTRIBUTING PAGE

### Additional Context

_No response_

### Screenshots or Examples (if applicable)

_No response_

### Proposed Solution (optional)

_No response_

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by abhisar-yadav**
Corrected all the typos in the README
## Fixes 
Closes #1509
Relates to #1554 & #1555

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by CBID2 — COMMENTED** [review]
Hey @abhisar-yadav. Ignore my previous comment, I noticed that you mainly revised the ReadMe file. Can you show me where you made changes to the Security file?

**Review by CBID2 — APPROVED** [review]
Nevermind @abhisar-yadav. I saw the other PRs.

**Comment by abhisar-yadav** [comment]
I corrected all the typos in readme,contributing,and security page

**Pull request merged**
