### PR TITLE
Added CTA And Made Sidebar take whole space

### LINKED ISSUE #1448: Adding A CTA Button & Making The Sidebar Take Full Space
### Description

So, If we add a CTA button in the landing page, We can enforce user to click it and thereafter make the sidebar takes full space So it appears as the main component and not just a side bar. 

Instead we can also create a new page to display categories. 

We need this as because of human psychology, we have been trained to take sidebar as a non important component but our project's main focus is the sidebar. 

A refactoring is necessary 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Souravvmishra**
## Fixes 
Closes #1448 

## Changes proposed

1. Added CTA 
2. Made Sidebar Take Full Space

## Screenshots
Screen Shot 2023-08-09 at 11 13 37

Screen Shot 2023-08-09 at 11 13 44

### CODE REVIEW

**Comment by Souravvmishra** [comment]
@rupali-codes Reviews are appreciated

**Review by CBID2 — CHANGES_REQUESTED** [review]
I could not see the changes when I went to the preview site @Souravvmishra(see screenshot below). Can you fix this?   
no sidebar

**Comment by Souravvmishra** [comment]
This is because it is available only on small screens devices.

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by k-deepak04** [comment]
@rupali-codes @CBID2 as far my experience it's not that much suitable to add full side panel that covers the whole screen

image
image
image

as you can see this big brands also use the 70% ration of the hamburger menu......
rest your call........this is my opinion

**Comment by CBID2** [comment]
Did you do it on a small screen @k-deepak04? That's what it's for.

**Comment by k-deepak04** [comment]
> Did you do it on a small screen @k-deepak04? That's what it's for.

yep christy all the ss are from small screens only
mobile tablets comes under small screens category
and i have added ss of those.......

**Comment by CBID2** [comment]
> > Did you do it on a small screen @k-deepak04? That's what it's for.
> 
> 
> 
> yep christy all the ss are from small screens only
> 
> mobile tablets comes under small screens category
> 
> and i have added ss of those.......

Ah ok. It seemed to work on my phone.

**Comment by rupali-codes** [comment]
@Souravvmishra hi thanks. Can you make it for mobile screens only? not for tablet and all?

**Comment by Souravvmishra** [comment]
Its build as per the design when the sidebar becomes hidden, we show a explore button.

**Comment by Souravvmishra** [comment]
> @rupali-codes @CBID2 as far my experience it's not that much suitable to add full side panel that covers the whole screen
> 
> image
> image
> image
> 
> as you can see this big brands also use the 70% ration of the hamburger menu......
> rest your call........this is my opinion

These Big Brands are using the sidebar as a sidebar for extra options but in our case, our sidebar has all the Focus of the user

**Comment by Souravvmishra** [comment]
can you please merge this

**Comment by CBID2** [comment]
@rupali-codes?

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
It should be for small screen devices only.

Also, can you explain why full screen sidebar is better? I don't want assumptions. Say from the perspective of a user.

**Review by k-deepak04 — CHANGES_REQUESTED** [review]
@Souravvmishra please tell why full screen is needed , as rightly said by anmol also have you did only for mobile not for tabs as requested by rupali?
If not please do it

**Comment by Souravvmishra** [comment]
Apologies for the late reply, I am on a trip.


Why do we need a full screen?
Because a semi sidebar gives the perception of a less important component. True that many big companies use a semi sidebar but they simply use that as a sidebar for some extra things but in our case, Sidebar is the main component. We need maximum importance to that. 

Actually I would Suggest Creating a new page instead of just using the sidebar

These all work for small screens only as in the large screen the sidebar is already visible. So at least the user is aware of it. But in small screen, the user has no idea that they are in sidebar. Yes it is written but who reads?

**Comment by Anmol-Baranwal** [comment]
> Apologies for the late reply, I am on a trip.
> 
> Why do we need a full screen? Because a semi sidebar gives the perception of a less important component. True that many big companies use a semi sidebar but they simply use that as a sidebar for some extra things but in our case, Sidebar is the main component. We need maximum importance to that.
> 
> Actually I would Suggest Creating a new page instead of just using the sidebar
> 
> These all work for small screens only as in the large screen the sidebar is already visible. So at least the user is aware of it. But in small screen, the user has no idea that they are in sidebar. Yes it is written but who reads?

Feel free to reply whenever you have time. No rush!

I don't understand this:
> But in small screen, the user has no idea that they are in sidebar. Yes it is written but who reads?

@rupali-codes @CBID2 @k-deepak04 
What do guys think?

**Comment by CBID2** [comment]
> > Apologies for the late reply, I am on a trip.
> 
> > 
> 
> > Why do we need a full screen? Because a semi sidebar gives the perception of a less important component. True that many big companies use a semi sidebar but they simply use that as a sidebar for some extra things but in our case, Sidebar is the main component. We need maximum importance to that.
> 
> > 
> 
> > Actually I would Suggest Creating a new page instead of just using the sidebar
> 
> > 
> 
> > These all work for small screens only as in the large screen the sidebar is already visible. So at least the user is aware of it. But in small screen, the user has no idea that they are in sidebar. Yes it is written but who reads?
> 
> 
> 
> Feel free to reply whenever you have time. No rush!
> 
> 
> 
> I don't understand this:
> 
> > But in small screen, the user has no idea that they are in sidebar. Yes it is written but who reads?
> 
> 
> 
> @rupali-codes @CBID2 @k-deepak04 
> 
> What do guys think?

I'm lost too @Anmol-Baranwal

**Comment by k-deepak04** [comment]
> > > Apologies for the late reply, I am on a trip.
> > 
> > 
> > > 
> > 
> > 
> > > Why do we need a full screen? Because a semi sidebar gives the perception of a less important component. True that many big companies use a semi sidebar but they simply use that as a sidebar for some extra things but in our case, Sidebar is the main component. We need maximum importance to that.
> > 
> > 
> > > 
> > 
> > 
> > > Actually I would Suggest Creating a new page instead of just using the sidebar
> > 
> > 
> > > 
> > 
> > 
> > > These all work for small screens only as in the large screen the sidebar is already visible. So at least the user is aware of it. But in small screen, the user has no idea that they are in sidebar. Yes it is written but who reads?
> > 
> > 
> > Feel free to reply whenever you have time. No rush!
> > I don't understand this:
> > > But in small screen, the user has no idea that they are in sidebar. Yes it is written but who reads?
> > 
> > 
> > @rupali-codes @CBID2 @k-deepak04
> > What do guys think?
> 
> I'm lost too @Anmol-Baranwal

I think we should have one landing page then one for the categories from where user can go to the resources.
We had a discussion on it too right @rupali-codes ?

**Comment by rupali-codes** [comment]
@k-deepak04 yes we did, but still, how we actually going render resources in there? its not like 5-10 resources that user can directly see on the screen, they will have to scroll. And having a landing page is completely a sperate idea, it was for where we can show other things, like About LinksHub, Contacting us, How people can contribute, showing contributors list etc etc.

Having the sidebar is not a problem, we just need to make it more accessible.

@Anmol-Baranwal & @CBID2 what are your takes on this?

**Review by rupali-codes — COMMENTED** [review]
@Souravvmishra its showing 2 scrollbars in the sidebar, could you please check?

image

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
When I made the PR to fix this searchbar, there was only one sidebar (which was very tough), but I did implement that.

Later, someone must have changed the code which removed that functionality.

See this: https://linkshub-1arqvr3it-rupali-codes.vercel.app/

Like, I did it properly.

**Comment by CBID2** [comment]
> @k-deepak04 yes we did, but still, how we actually going render resources in there? its not like 5-10 resources that user can directly see on the screen, they will have to scroll. And having a landing page is completely a sperate idea, it was for where we can show other things, like About LinksHub, Contacting us, How people can contribute, showing contributors list etc etc.
> 
> 
> 
> Having the sidebar is not a problem, we just need to make it more accessible.
> 
> 
> 
> @Anmol-Baranwal & @CBID2 what are your takes on this?

I agree @rupali-codes

**Comment by CBID2** [comment]
How are we going to move forward with this?

**Comment by Anmol-Baranwal** [comment]
Don't know, @rupali-codes must be active.

**Comment by rupali-codes** [comment]
> Don't know, @rupali-codes must be active.

can we just keep this PR to add CTA and keep the sidebar as it is currently?

**Comment by CBID2** [comment]
> > Don't know, @rupali-codes must be active.
> 
> can we just keep this PR to add CTA and keep the sidebar as it is currently?

That's not a bad idea @rupali-codes. What do you think @Anmol-Baranwal?

**Comment by CBID2** [comment]
Closed due to inactivity

**Pull request closed without merging**
