### PR TITLE
fix: extended gap in title and description

### LINKED ISSUE #1050: [BUG] Fix letter spacing for resource content
### Description

The letter spacing on the content of resources is very high, which makes it appear weird.

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Resolves #1050

## Description

- I have fixed the following bug in title on popup:

| Previous | Current |
|-----------|---------|
| Screenshot 2023-06-16 153006 | image |

## Note to reviewers

@rupali-codes @ujjawaltyagii 
I need your help, so the issue is that the description in the `Card` is slightly longer, and I have properly debug the code on various components. 

> This image shows the problem
image

So, on changing 
```typescript
- className="w-full cursor-pointer transition-all duration-100 ease-in hover:scale-[1.02] md:w-72"
+ className="cursor-pointer transition-all duration-100 ease-in hover:scale-[1.02] md:w-50"
```
in `CardListItem.tsx`

> The gap is fixed as shown below:
image

But this solution doesn't meet my intended goal. Could you provide any ideas or approaches to address this issue?

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
I think this helps

**Comment by rupali-codes** [comment]
@Anmol-Baranwal hi, so for the cards like this, i guess it would be better if we can align the text to left for all cards? what do you you think?

image

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal hi, so for the cards like this, i guess it would be better if we can align the text to left for all cards? what do you you think?
> 
> image
> 

I have already described the issue in the pr comment on what I reached after debugging, so are you suggesting to align it on left but it would still not fix the issue, because i literally added 'hey' in between the gap while testing. Please clarify further.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please provide clarification.

**Comment by rupali-codes** [comment]
> @rupali-codes Please provide clarification.

I guess, it would be better if we add a gap between the words than using _text-justify_ because its adding unnecessary extra space, or let me know what do you think about it

**Comment by Anmol-Baranwal** [comment]
> > @rupali-codes Please provide clarification.
> 
> I guess, it would be better if we add a gap between the words than using _text-justify_ because its adding unnecessary extra space, or let me know what do you think about it

I will complete the remaining PRs after tomorrow's exam, by the 24th.

**Comment by Anmol-Baranwal** [comment]
> > @rupali-codes Please provide clarification.
> 
> I guess, it would be better if we add a gap between the words than using _text-justify_ because its adding unnecessary extra space, or let me know what do you think about it

There is no `text-justify` used in codebase, and it seems that the styles are overlapping each other. As a result, I'm unable to make any significant changes to resolve this issue. This problem may be attributed to the fixed size of the card.

> Can you please look again.

**Comment by rupali-codes** [comment]
> > > @rupali-codes Please provide clarification.
> > 
> > 
> > I guess, it would be better if we add a gap between the words than using _text-justify_ because its adding unnecessary extra space, or let me know what do you think about it
> 
> There is no `text-justify` used in codebase, and it seems that the styles are overlapping each other. As a result, I'm unable to make any significant changes to resolve this issue. This problem may be attributed to the fixed size of the card.
> 
> > Can you please look again.

Its coming from [here](https://github.com/rupali-codes/LinksHub/blob/main/styles/globals.css) actually,

**Review by CBID2 — COMMENTED** [review]
Looking good

**Comment by ujjawaltyagii** [comment]
> Looking good

Ig he is not done with the final changes as i can still see the unusual gaps in resource description

**Comment by CBID2** [comment]
> > Looking good
> 
> 
> 
> Ig he is not done with the final changes as i can still see the unusual gaps in resource description 

Hence why I chose the general comment option 😊

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
On removing it as per your suggestion, the design looks like this. Please let me know if this design is acceptable or if the current one works better.

> Without Removing
image


> Removing
image

**Comment by rupali-codes** [comment]
the second one looks much better to me

**Comment by Anmol-Baranwal** [comment]
> the second one looks much better to me

I have done the changes as per your reference, the problem was styles in `globals.css` was at higher priority, so I changed the tag from `p` to `div`

**Review by rupali-codes — APPROVED** [review]

**Comment by rupali-codes** [comment]
> > the second one looks much better to me
> 
> I have done the changes as per your preference, the problem was styles in `globals.css` was at higher priority, so I changed the tag from `p` to `div`

Thanks, looks nice to me

**Pull request merged**
