### PR TITLE
chore: summarize colors 

### LINKED ISSUE #1372: Making Background Colors Accessible Part 2
I'm thinking to configure all the colors in tailwing.config file, it would be so helpful for us. then you can change it directly. So, should i work on that, bcz its gonna be a bit difficult for you to find where the components are located. @k-deepak04 or @CBID2 you guys can create an issue for it, and assign to me, i'll work on that :)
> 

_Originally posted by @rupali-codes in https://github.com/rupali-codes/LinksHub/issues/1045#issuecomment-1646640103_

### PR DESCRIPTION
**Pull request by rupali-codes**
Hi, I have stored all the color values in _tailwind.config.js_ file

## Fixes Issue

closes #1372 

## Changes proposed
* added colors to tailwind.config.js file
* replaced all color values with newly added variables

## Screenshots

image

## Note to reviewers

Please review carefully and let me know if i missed any spot

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @rupali-codes! :) Can you add me as a co-author since I found the hex codes for the new colors?

**Comment by rupali-codes** [comment]
> Hi @rupali-codes! :) Can you add me as a co-author since I found the hex codes for the new colors?

Do you mean i should assign this issue to both of us?

**Comment by rupali-codes** [comment]
Though i tried to improve the accessibility, you may check once :)

**Comment by CBID2** [comment]
This is what I mean by co-author: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#

**Comment by rupali-codes** [comment]
> Hi @rupali-codes! :) Can you add me as a co-author since I found the hex codes for the new colors?

I see, but these colors are not those chosen by you i guess,

**Comment by CBID2** [comment]
> > Hi @rupali-codes! :) Can you add me as a co-author since I found the hex codes for the new colors?
> 
> 
> 
> I see, but these colors are not those chosen by you i guess, 

Ohhh. I think you should use them @rupali-codes. They make the background more accessible.

**Pull request merged**
