### PR TITLE
chore: Daniel Bourke Youtube Channel

### PR DESCRIPTION
**Pull request by Shiva-Sai-ssb**
## Fixes Issue
#775

## Changes proposed
I have incorporated an additional learning resource for TensorFlow and established a dedicated JSON file to facilitate the inclusion of future resources pertaining to TensorFlow.

## Screenshots
Screenshot (77)

### CODE REVIEW

**Review by rupali-codes — APPROVED** [review]
lgtm

**Review by CBID2 — APPROVED** [review]
Great job @Shiva-Sai-ssb! 😄 LGTM! 😄

**Comment by CBID2** [comment]
@rupali-codes, we need your force push

**Comment by Shiva-Sai-ssb** [comment]
Hello @CBID2, I am wondering why the PR has not been merged yet. Could you please clarify if there are any issues with my contributions?

**Comment by CBID2** [comment]
> Hello @CBID2, I am wondering why the PR has not been merged yet. Could you please clarify if there are any issues with my contributions?

I think a deployment issue happened @Shiva-Sai-ssb. @rupali-codes, we need a force push

**Comment by Shiva-Sai-ssb** [comment]
> > Hello @CBID2, I am wondering why the PR has not been merged yet. Could you please clarify if there are any issues with my contributions?
> 
> I think a deployment issue happened @Shiva-Sai-ssb. @rupali-codes, we need a force push

Thank you for your response. Therefore, it is necessary for @rupali-codes to perform a force push in order to merge this pull request, correct?

**Comment by CBID2** [comment]
> > > Hello @CBID2, I am wondering why the PR has not been merged yet. Could you please clarify if there are any issues with my contributions?
> 
> > 
> 
> > I think a deployment issue happened @Shiva-Sai-ssb. @rupali-codes, we need a force push
> 
> 
> 
> Thank you for your response. Therefore, it is necessary for @rupali-codes to perform a force push in order to merge this pull request, correct?

Yes, she is the owner of this repo so it only works for her

**Comment by rupali-codes** [comment]
> Hello @CBID2, I am wondering why the PR has not been merged yet. Could you please clarify if there are any issues with my contributions?

Please keep patience

**Pull request merged**
