### PR TITLE
chore: added new link

### PR DESCRIPTION
**Pull request by Oyebolade**

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
Hi,
We have restructured the database and the of storing data, kindly check [contributing guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)

**Comment by rupali-codes** [comment]
Also, make sure your PR closes all the issues which belongs to these links

**Comment by Oyebolade** [comment]
Noted

**Comment by Oyebolade** [comment]
design inspiration1
design inspiration2
design inspiration3

**Comment by rupali-codes** [comment]
Didn't get you sorry..

**Comment by Oyebolade** [comment]
I have issue in editing the pull request an closing the issue raised with it.

Or should I delete it and start all over again.

**Pull request closed without merging**
