### PR TITLE
feat: add cassandra db to database.json

### LINKED ISSUE #1998: [Add] Add Apache Cassandra DB to Databases in backend category
### Site URL

https://cassandra.apache.org/

### Description of the above provided site

Apache Cassandra is a free and open-source, distributed, wide column store, NoSQL database management system designed to handle large amounts of data across many commodity servers, providing high availability with no single point of failure. It is used by some of the famous tech giants like Netflix, Twitter and Amazon (Keyspaces).

### Category

Backend

### Sub Category

database

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by p1utoze**
## Fixes Issue

closes #1998 

## Changes proposed

I have listed Apache's Cassandra DB in Databases of Backend category with description.

## Screenshots

[](https://freeimage.host/i/JFqenqB)

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@CBID2 @rupali-codes 

I'm tired of PRs who have unassigned issues😑

@p1utoze 
Make sure to read [contributing guidelines](https://github.com/rupali-codes/LinksHub/blob/375c5bc1985f4376a526c0428d999e190026ec17/CONTRIBUTING.md) on how to go with the flow.

The linked issue is not assigned to you, so I'm converting this pull request to draft for now. Please review the contributing guidelines. Once we approve and assign you to this issue, your pull request will be reopened. 

please do not create PRs when we have not assigned you the issue.

**Comment by p1utoze** [comment]
@Anmol-Baranwal Hello. Can you assign the issue #1998 to me?

**Review by CBID2 — APPROVED** [review]
Looks good to me @Anmol-Baranwal

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
