### PR TITLE
Add PlanetScale Database

### LINKED ISSUE #1995: [Add] Planet scale Database
### Site URL

https://planetscale.com/

### Description of the above provided site

**PlanetScale** is a **MySQL**-compatible server less database that brings you scale, performance, and reliability — without sacrificing developer experience. With PlanetScale, you get the power of horizontal sharding, non-blocking schema changes, and many more powerful database features without the pain of implementing them.

### Category

Backend

### Sub Category

database

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by psykatsamanta**
## Fixes Issue

Closes #1995 

## Changes proposed

Add a new link of Robust, Modern, Scalable My-SQL based Database Platform called **PlanetScale.**

### CODE REVIEW

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Please review this :)

**Review by CBID2 — APPROVED** [review]
Looks great! @rupali-codes, you're up! 😃

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
