### PR TITLE
feat: added devops category

### LINKED ISSUE #521: [Feature] Add a new section for DevOps
### Description

There is no section related to DevOps tools and knowledge such as 
- Linux
- Docker
- Kubernetes
- GitHub Actions
- Jenkins
- IaC (Infrastructure as code)
- Terraform etc.

We can add a new section and then add these topics into the section.

You can assign me :)

### PR DESCRIPTION
**Pull request by shubhsharma19**
## Fixes Issue
closes #521

## Changes proposed
Added `linux.json` into the database repo

### CODE REVIEW

**Review by ujjawaltyagii — COMMENTED** [review]
Hey ! @shubhsharma19  you sure that it's working as mentioned in the issue ? because : 
1. this section/category "DevOps" is not visible
2. and looking from the changes you did in files - you only created a folder named "DevOps" in `database` and in that folder you created a `json` file. If you were trying to create a new category that's not how a new category is created.
(correct me if i am wrong 😅)
Do let me know if you need any help !

attaching snapshot of visible categories in your deployment -
image

**Comment by shubhsharma19** [comment]
> Hey ! @shubhsharma19  you sure that it's working as mentioned in the issue ? because : 
> 1. this section/category "DevOps" is not visible
> 2. and looking from the changes you did in files - you only created a folder named "DevOps" in `database` and in that folder you created a `json` file. If you were trying to create a new category that's not how a new category is created.
> (correct me if i am wrong 😅)
> Do let me know if you need any help !
> 
> attaching snapshot of visible categories in your deployment -
> image
> 
> 

Yes thanks for the mention, can you suggest me what changes I need to do?

**Comment by shubhsharma19** [comment]
Thanks a lot again! 

I think the documentation `contribution guidelines` needs some updates

**Comment by rupali-codes** [comment]
@shubhsharma19 why did you close the PR?

**Comment by shubhsharma19** [comment]
> @shubhsharma19 why did you close the PR?

Actually this PR is not clean and has become a bit confusing I will create a new one with new issue!

**Pull request closed without merging**
