### PR TITLE
Fix : selected subcategory in the sidebar

### PR DESCRIPTION
**Pull request by Vijaykv5**
## Fixes Issue
#1687 

## Changes proposed

Made the Selected category in sidebar highlighted by adding extra adding a path  variable

## Screenshots
Screenshot 2023-10-02 at 5 31 24 PM

## Note to reviewers
Please check 
@Anmol-Baranwal @CBID2

### CODE REVIEW

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by Vijaykv5** [comment]
@Anmol-Baranwal can you add hacktoberfest-accepted in this?

**Comment by Anmol-Baranwal** [comment]
@Vijaykv5 
Is this PR not showing in your dashboard?

The hacktoberfest topics are added to the LinksHub repo, so there is no need of this.

If it isn't there, let us know. It would be a great clarification.

**Comment by Anmol-Baranwal** [comment]
Yeah, it will update. 

This is for the case where the PR gets reverted or something unexpected occurs in a week. Here, it won't matter.

**Pull request merged**
