### PR TITLE
added Chai and Code youtube channel for webdev #hacktoberfest2023

### LINKED ISSUE #2018: [Add] Chai aur Code Youtube Channel
### Site URL

https://www.youtube.com/@chaiaurcode

### Description of the above provided site

This is an underrated youtube channel mainly focussed on full stack development.

### Category

Youtube

### Sub Category

web-development

### Checklist

- [x] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by pratikkumar399**
## Fixes Issue
fixes #2018

## Changes proposed

Added Chai and Code Youtube channel

### CODE REVIEW

**Comment by pratikkumar399** [comment]
hey @Anmol-Baranwal  please check if this pr is fine

**Comment by Anmol-Baranwal** [comment]
@pratikkumar399 
Following the PR template is a must. It includes special words like 'fixes' or 'resolves' that connect your issue to the PR, as explained in the official docs.

If you don't link the issue correctly, even after the PR is merged, the issue might stay open, causing huge problems.

> You can see here.
image

I'm doing it for you this time. Please ensure it next time.

Just a heads-up to help you link issue properly next time. Have a great day!

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by CBID2 — APPROVED** [review]
Looks great! @rupali-codes, please review

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
