### PR TITLE
 Prettier and index file added

### LINKED ISSUE #226: [CHORE] add prettier
### What would you like to share or ask?

As of now, we don't have prettier initialized and it's hard to tell people to format their code before they push it. Your task is to add `prettier` in this project so the code will be formatted. 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Abbeyafolaby**
## Fixes Issue

Closes #226 

## Screenshots

Screenshot (57)
I am sorry for deleting the file without telling you, but it was throwing this error, I changed it to a warning in the `.eslintrc.json` file. I hope that is okay?

### CODE REVIEW

**Review by rupali-codes — APPROVED** [review]
lgtm

**Comment by Abbeyafolaby** [comment]
Hii, this hasn't been merged yet. hope there isn't any issue?

**Comment by rupali-codes** [comment]
> Hii, this hasn't been merged yet. hope there isn't any issue?

Yeah there's no issues, just waiting for other maintainers to approve it. thanks anyways :)

**Comment by Abbeyafolaby** [comment]
> > Hii, this hasn't been merged yet. hope there isn't any issue?
> 
> Yeah there's no issues, just waiting for other maintainers to approve it. thanks anyways :)

Alright! Thanks for the trusting me with me the task :)

**Comment by rupali-codes** [comment]
Hey @Abbeyafolaby , thank you so much for your patience, could you please resolve conflicts so we can merge this PR?

**Comment by Abbeyafolaby** [comment]
> Hey @Abbeyafolaby , thank you so much for your patience, could you please resolve conflicts so we can merge this PR?

Alright, I'd work on that. thanks.

**Pull request closed without merging**
