### PR TITLE
Added NASA's API in  api.json

### LINKED ISSUE #2048: Add NASA's API in api.json
### Category Name
Backend

### Subcategory Name
API

### Additional Context

The NASA API falls under the "backend" category, specifically in the "API" subcategory. This API is a valuable tool for developers, researchers, and space enthusiasts who want to access NASA's vast repository of space-related data and content programmatically. Whether you're building a space-themed app, conducting research, or simply exploring the wonders of the universe, the NASA API offers a wide array of resources and information to assist you.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [x] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by SoulNikhar**
## Fixes Issue 
Closes #2048 

## Changes proposed
This PR adds NASA's API to the `API.json` file.

##

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@SoulNikhar 
We are neglecting this now, but in the future, you need to create an issue and allow us to assign you the issue before you start working and submit a PR. Not following this process will require us to close your pull request.

This is outlined in the contributing guidelines.
image

You need to follow a predefined flow in order to contribute to Open Source. You may be new, so it is important to understand this. Most of the maintainers will mark it as spam and close it. I'm converting this into a draft for now. 

Create an issue and tag me.

**Comment by SoulNikhar** [comment]
@Anmol-Baranwal  Thanks bro for not mark it as spam.

**Comment by SoulNikhar** [comment]
@Anmol-Baranwal  , I created an issue as per what you told me

**Comment by rupali-codes** [comment]
> @Anmol-Baranwal , I created an issue as per what you told me

Thanks, now reference the issue in this PR by editing the description add `closes #your_issue_number

**Comment by SoulNikhar** [comment]
> > @Anmol-Baranwal , I created an issue as per what you told me
> 
> Thanks, now reference the issue in this PR by editing the description add `closes #your_issue_number`

closes #2048

**Comment by SoulNikhar** [comment]
@rupali-codes  and @Anmol-Baranwal   I have answered all the Questions in the Issue section #2048

**Review by CBID2 — APPROVED** [review]
Hi @SoulNikhar! :) There was some missing information in your PR's form, so I made the necessary changes. In the future, follow the comments in the PR template(e.g., they look like this <! -- text -->  to help you fill it out effectively. Other than that, you did good! :) @Anmol-Baranwal and @rupali-codes, it's your turn to review this PR.

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by rupali-codes — APPROVED** [review]
Lgtm

**Pull request merged**
