### PR TITLE
feat: added a section ethical hacking

### LINKED ISSUE #2554: [ADD] ETHICAL HACKING
### Category Name

ETHICAL HACKING

### Subcategory Name

'Cryptography Attacks', 'Social Engineering', 'Wireless Hacking', 'Malware and Payload Development'

### Additional Context

_No response_

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Deepak6204**
## Fixes Issue

Closes #2554 

## Changes proposed
Created a folder ethical_hacking
containing the following files
cryptography_attacks.json
malware_and_payload_development.json
social_engineering.json
wireless_hacking.json

## Note to reviewers
I have successfully added the mentioned files, and merging this repo adds a new field ethical hacking to the database.

### CODE REVIEW

**Comment by VIJAYASRI-M** [comment]
@Deepak6204 can you add relevant links to these topics and import them in data.ts so that Ethical hacking Category can be available in UI

**Review by VIJAYASRI-M — COMMENTED** [review]
Add data in the files to make them available in UI

**Comment by Deepak6204** [comment]
ok i'll do it @VIJAYASRI-M

**Comment by Deepak6204** [comment]
hi, @VIJAYASRI-M I have created a new pull request #2573, you can check it out

**Pull request closed without merging**
