### PR TITLE
Added new blog for react

### PR DESCRIPTION
**Pull request by Abhinavcode13**
Added the blog

## Fixes Issue

closes the issue number #868 

## Changes proposed

Added a new resource under blog section

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
image
deployed successfully !!

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Comment by Abhinavcode13** [comment]
Can you check this PR @rupali-codes please

**Review by rupali-codes — APPROVED** [review]
looks good

**Comment by Abhinavcode13** [comment]
i guess its ready to merge @rupali-codes ?

**Pull request merged**
