### PR TITLE
Add new category-DSA and subcategory-articles

### LINKED ISSUE #1890: [Add] <Want to add DSA articles under subcategory "Articles">
### Site URL

https://medium.com/@mukhopadhyaypushan42/best-way-to-solve-dsa-problems-become-a-pro-ccba897469c1

### Description of the above provided site

Solving Data Structures and Algorithms (DSA) problems on platforms like LeetCode, InterviewBit, and GeeksforGeeks can indeed pose a considerable challenge. These platforms are renowned for refining your coding skills and preparing you for technical interviews. 

### Category

Other

### Sub Category

DSA

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by ayushrakesh**
Closes #1890

## Changes proposed

I have successfully added the DSA category and "articles" subcategory.

### CODE REVIEW

**Review by CBID2 — COMMENTED** [review]
Well done @ayushrakesh. @Anmol-Baranwal or @rupali-codes, you're up.

**Review by Anmol-Baranwal — COMMENTED** [review]
@rupali-codes 
What do you think?

It is good to add this as a category, but like there is placement prep and I'm not sure.

It's up to you to decide.

**Comment by ayushrakesh** [comment]
I think sir, although there may be a section of placement-prep but an another section for DSA will be more benefial, like we can add any materials , videos, courses, articles to it as DSA is very huge topic. It will profit users a lot.

**Comment by rupali-codes** [comment]
> @rupali-codes What do you think?
> 
> It is good to add this as a category, but like there is placement prep and I'm not sure.
> 
> It's up to you to decide.

I think it would be great.

**Review by rupali-codes — COMMENTED** [review]
@ayushrakesh we also have this Data-structure subcategory under youtube section, so can you one thing, take all the resources from there, and make another subcategory named `dsa-tutorials` and those youtube playlists in this category

**Comment by ayushrakesh** [comment]
> @ayushrakesh we also have this Data-structure subcategory under youtube section, so can you one thing, take all the resources from there, and make another subcategory named `dsa-tutorials` and those youtube playlists in this category

Sure mam, so can you merge this PR first then I will do that also with another request.

**Comment by rupali-codes** [comment]
> > @ayushrakesh we also have this Data-structure subcategory under youtube section, so can you one thing, take all the resources from there, and make another subcategory named `dsa-tutorials` and those youtube playlists in this category
> 
> Sure mam, so can you merge this PR first then I will do that also with another request.

You can do it in the same PR, LOL 😂

**Comment by ayushrakesh** [comment]
> > > @ayushrakesh we also have this Data-structure subcategory under youtube section, so can you one thing, take all the resources from there, and make another subcategory named `dsa-tutorials` and those youtube playlists in this category
> > 
> > 
> > Sure mam, so can you merge this PR first then I will do that also with another request.
> 
> You can do it in the same PR, LOL 😂

Ok mam😊, I will do it.

**Comment by rupali-codes** [comment]
> > > > @ayushrakesh we also have this Data-structure subcategory under youtube section, so can you one thing, take all the resources from there, and make another subcategory named `dsa-tutorials` and those youtube playlists in this category
> > > 
> > > 
> > > Sure mam, so can you merge this PR first then I will do that also with another request.
> > 
> > 
> > You can do it in the same PR, LOL 😂
> 
> Ok mam😊, I will do it.

Don't call me mam, its alright 😊

**Comment by ayushrakesh** [comment]
> > > > > @ayushrakesh we also have this Data-structure subcategory under youtube section, so can you one thing, take all the resources from there, and make another subcategory named `dsa-tutorials` and those youtube playlists in this category
> > > > 
> > > > 
> > > > Sure mam, so can you merge this PR first then I will do that also with another request.
> > > 
> > > 
> > > You can do it in the same PR, LOL 😂
> > 
> > 
> > Ok mam😊, I will do it.
> 
> Don't call me mam, its alright 😊

Ok fine. I have done it. Now you can merge.

**Comment by rupali-codes** [comment]
> > > > > > @ayushrakesh we also have this Data-structure subcategory under youtube section, so can you one thing, take all the resources from there, and make another subcategory named `dsa-tutorials` and those youtube playlists in this category
> > > > > 
> > > > > 
> > > > > Sure mam, so can you merge this PR first then I will do that also with another request.
> > > > 
> > > > 
> > > > You can do it in the same PR, LOL 😂
> > > 
> > > 
> > > Ok mam😊, I will do it.
> > 
> > 
> > Don't call me mam, its alright 😊
> 
> Ok fine. I have done it. Now you can merge.

Seems you've missed something :D
image

**Comment by ayushrakesh** [comment]
> > > > > > > @ayushrakesh we also have this Data-structure subcategory under youtube section, so can you one thing, take all the resources from there, and make another subcategory named `dsa-tutorials` and those youtube playlists in this category
> > > > > > 
> > > > > > 
> > > > > > Sure mam, so can you merge this PR first then I will do that also with another request.
> > > > > 
> > > > > 
> > > > > You can do it in the same PR, LOL 😂
> > > > 
> > > > 
> > > > Ok mam😊, I will do it.
> > > 
> > > 
> > > Don't call me mam, its alright 😊
> > 
> > 
> > Ok fine. I have done it. Now you can merge.
> 
> Seems you've missed something :D image

Ohh, I will fix it now.

**Comment by ayushrakesh** [comment]
> > > > > > > > @ayushrakesh we also have this Data-structure subcategory under youtube section, so can you one thing, take all the resources from there, and make another subcategory named `dsa-tutorials` and those youtube playlists in this category
> > > > > > > 
> > > > > > > 
> > > > > > > Sure mam, so can you merge this PR first then I will do that also with another request.
> > > > > > 
> > > > > > 
> > > > > > You can do it in the same PR, LOL 😂
> > > > > 
> > > > > 
> > > > > Ok mam😊, I will do it.
> > > > 
> > > > 
> > > > Don't call me mam, its alright 😊
> > > 
> > > 
> > > Ok fine. I have done it. Now you can merge.
> > 
> > 
> > Seems you've missed something :D image
> 
> Ohh, I will fix it now.

Cool, I have fixed it, now you proceed.

**Comment by CBID2** [comment]
There's still merge conflicts that need fixing @ayushrakesh

**Pull request closed without merging**
