### PR TITLE
Add Documentation

### LINKED ISSUE #2288: [ADD]  Documentation
### Category Name

Resources

### Subcategory Name

Docs

### Additional Context

I would like to add:

- jsDoc
- typedoc
- move Docsify
- move Docusaurus

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by JuanPabloDiaz**
## Fixes Issue

fixes #2288

## Changes proposed

Add Documentation subcategory under resources

## Screenshots
image

## Note to reviewers

In the interest of providing additional context, I've included some further resources.

### CODE REVIEW

**Review by aftabrehan — DISMISSED** [review]
Excellent PR, @JuanPabloDiaz 💪 🚀 💯

**Review by rupali-codes — COMMENTED** [review]
hey @JuanPabloDiaz , could you please rename the category to `Docs Generator` because `docs` looks kinda confusing

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> I don't know if `technical writing/tools` subcategory should be merged with this one. They seem quite similar.

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
