### PR TITLE
Added a new Ui library Url

### LINKED ISSUE #2156: [Add] flowbite react in UI Libraries under frontend category
### Site URL

https://www.flowbite-react.com/

### Description of the above provided site

Flowbite React is an open-source UI component library built on top of Tailwind CSS with React components and based on the Flowbite Design System.

### Category

Frontend

### Sub Category

UI Library

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by Alvis07**
closes #2156
git

Please merge this request under hacktoberfest label

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@Alvis07 
Link correct issue. Have you created an issue?

**Comment by Alvis07** [comment]
Yes issue #2159

**Comment by Anmol-Baranwal** [comment]
> Yes issue #2159

This is a pull request. I'm asking for the issue?

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by CBID2 — APPROVED** [review]
Let's get to merge

**Review by CBID2 — CHANGES_REQUESTED** [review]
Ignore my previous review. There's some merge conflicts that are on your branch

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
