### PR TITLE
add: placement-prep category

### LINKED ISSUE #1631: [ADD] Placement Prep category
### Category Name

Placement prep

### Subcategory Name

Aptitude , Reasoning, verbal, versant , DSA, Interview prep , notes

### Additional Context

It is very useful if the final or pre final year student got the link at one point for their placement preparation and their are lot of content is available for placement prep. and also their should be notes content link that should be help for placement.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Shiva-Sai-ssb**
## Fixes Issue

Closes #1631
## Changes proposed

Hey, I've decided to include the following subcategories to the Placement Preparation category and gave a short description of what resources we can include in them to assist students with their placement preparation.

1. Interview Preparation:

Description: This subcategory should offer a wide range of resources such as articles, videos, and mock interview platforms to help developers hone their interview skills, prepare for technical interviews, and improve their ability to communicate effectively during interviews.

2. Job Portals:

Description :  In this subcategory, you can provide links and information about popular job portals, their features, and tips for effectively using them to find job listings, connect with potential employers, and apply for positions.

3. Coding Challenges Platforms:

Description : This subcategory should include information on various coding challenge platforms, their strengths, and the types of challenges they offer. You can also provide tips and resources to excel in these challenges.

4. Resume and Portfolio Building:

Description: In this subcategory, offer guidance on crafting effective resumes and portfolios, templates, and examples that developers can use as references to make their application materials stand out.

5. Career Guidance:

Description : In this subcategory, provide resources, articles, and advice on career planning, goal setting, and strategies for professional growth. Include information on different career paths within the tech industry and how to navigate them successfully.

6. Certifications:

Description : This subcategory should list popular certifications in the tech field, their requirements, benefits, and how to prepare for them. Include information on online courses, study materials, and practice exams to help developers succeed in certification exams.

## Note to reviewers

I am willing to make further modifications upon your request.

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@Shiva-Sai-ssb 

Good job on the clear descriptions.

@CBID2 @rupali-codes 

What do you think?

1. There are millions of certifications, and out of them reputed professional ones are less but still most of them are paid, so should we include that.
2. For portfolio and resume, we should make different subcategories?
3. What should we include in interview preparation? I think it would be better to add better subcategories rather than a generic one, like GitHub question back repos (5k+ Stars at least). Because Interview preparation can be done in many ways.

Let's discuss and then we can properly move forward.

**Comment by CBID2** [comment]
> @Shiva-Sai-ssb 
> 
> 
> 
> Good job on the clear descriptions.
> 
> 
> 
> @CBID2 @rupali-codes 
> 
> 
> 
> What do you think?
> 
> 
> 
> 1. There are millions of certifications, and out of them reputed professional ones are less but still most of them are paid, so should we include that.
> 
> 2. For portfolio and resume, we should make different subcategories?
> 
> 3. What should we include in interview preparation? I think it would be better to add better subcategories rather than a generic one, like GitHub question back repos (5k+ Stars at least). Because Interview preparation can be done in many ways.
> 
> 
> 
> Let's discuss and then we can properly move forward.

Good question @Anmol-Baranwal. Personally, I think we should mostly stick with the free resources since that's what LinksHub's mission is. For questions 2 and 3, resumes and portfolios(and cover letters too) would be more suited as subcategories for Interview Prep.

**Comment by Shiva-Sai-ssb** [comment]
> @Shiva-Sai-ssb
> 
> Good job on the clear descriptions.
> 
> @CBID2 @rupali-codes
> 
> What do you think?
> 
> 1. There are millions of certifications, and out of them reputed professional ones are less but still most of them are paid, so should we include that.
> 2. For portfolio and resume, we should make different subcategories?
> 3. What should we include in interview preparation? I think it would be better to add better subcategories rather than a generic one, like GitHub question back repos (5k+ Stars at least). Because Interview preparation can be done in many ways.
> 
> Let's discuss and then we can properly move forward.

I'm aware that there are numerous certifications available, but I believe it's beneficial to consider including those that enhance the value of a resume. It's worth noting that many certifications come with a cost, but I firmly believe they can significantly distinguish students during interviews. For instance, certifications like AWS Cloud Architect and AWS Cloud Practitioner are prime examples from my knowledge.

**Comment by Shiva-Sai-ssb** [comment]
> > @Shiva-Sai-ssb
> > Good job on the clear descriptions.
> > @CBID2 @rupali-codes
> > What do you think?
> > 
> > 1. There are millions of certifications, and out of them reputed professional ones are less but still most of them are paid, so should we include that.
> > 2. For portfolio and resume, we should make different subcategories?
> > 3. What should we include in interview preparation? I think it would be better to add better subcategories rather than a generic one, like GitHub question back repos (5k+ Stars at least). Because Interview preparation can be done in many ways.
> > 
> > Let's discuss and then we can properly move forward.
> 
> Good question @Anmol-Baranwal. Personally, I think we should mostly stick with the free resources since that's what LinksHub's mission is. For questions 2 and 3, resumes and portfolios(and cover letters too) would be more suited as subcategories for Interview Prep.

Hey, I believe including paid resources shouldn't be an issue since they can be beneficial for learners. Furthermore, there are currently some paid resources available on Linkshub. The documentation states that Linkshub offers both paid and free resources. 

Screenshot (45)

Nevertheless, the ultimate decision rests with the project maintainers, and I am simply expressing my opinion. I will implement any changes based on your's suggestions.

**Comment by Shiva-Sai-ssb** [comment]
Additionally, to reduce the number of categories on the main page and improve navigation, I suggest moving the "COMPETITIVE PROGRAMMING" subcategories into the "PLACEMENT PREPARATION" category, as they are relevant resources for placement preparation.

**Comment by Anmol-Baranwal** [comment]
> I'm aware that there are numerous certifications available, but I believe it's beneficial to consider including those that enhance the value of a resume. It's worth noting that many certifications come with a cost, but I firmly believe they can significantly distinguish students during interviews. For instance, certifications like AWS Cloud Architect and AWS Cloud Practitioner are prime examples from my knowledge.

I don't know, I have done several certificates from Google, Oracle Academy, University of Michigan, and so many more.

> Yeah it can definitely improve, but there are lots of certificates (even professional ones). 

So, what do you think a criteria should be to add a certification in this subcategory? It shouldn't be based on personal preference right. Just let me know what you think, it will be easier for us to decide which certification should come under this.

**Comment by Anmol-Baranwal** [comment]
> Hey, I believe including paid resources shouldn't be an issue since they can be beneficial for learners. Furthermore, there are currently some paid resources available on Linkshub. The documentation states that Linkshub offers both paid and free resources.
> 
> Screenshot (45)
> 
> Nevertheless, the ultimate decision rests with the project maintainers, and I am simply expressing my opinion. I will implement any changes based on your's suggestions.

Thanks for pointing it out. You seem hesitant sharing your opinion, don't worry we are not bossy maintainers. We values your opinion just as much as ours.

**Comment by Shiva-Sai-ssb** [comment]
> > I'm aware that there are numerous certifications available, but I believe it's beneficial to consider including those that enhance the value of a resume. It's worth noting that many certifications come with a cost, but I firmly believe they can significantly distinguish students during interviews. For instance, certifications like AWS Cloud Architect and AWS Cloud Practitioner are prime examples from my knowledge.
> 
> I don't know, I have done several certificates from Google, Oracle Academy, University of Michigan, and so many more.
> 
> > Yeah it can definitely improve, but there are lots of certificates (even professional ones).
> 
> So, what do you think a criteria should be to add a certification in this subcategory? It shouldn't be based on personal preference right. Just let me know what you think, it will be easier for us to decide which certification should come under this.

I believe the following criteria should be met to include certifications in this subcategory, as they hold value.

Industry Recognition: Certifications from well-known and respected organizations or vendors in the industry tend to carry more weight. For example, certifications from Microsoft, AWS, Cisco, or Google often hold high value.

Validity and Recertification: Some certifications require periodic renewal or recertification to ensure that developers stay up-to-date with evolving technologies. This can be a positive sign of a certification's value.

Global Recognition: Certifications that are recognized globally can be more valuable as they are not limited to a specific region.

**Comment by Shiva-Sai-ssb** [comment]
> > Hey, I believe including paid resources shouldn't be an issue since they can be beneficial for learners. Furthermore, there are currently some paid resources available on Linkshub. The documentation states that Linkshub offers both paid and free resources.
> > Screenshot (45)
> > Nevertheless, the ultimate decision rests with the project maintainers, and I am simply expressing my opinion. I will implement any changes based on your's suggestions.
> 
> Thanks for pointing it out. You seem hesitant sharing your opinion, don't worry we are not bossy maintainers. We values your opinion just as much as ours.

Thanks. I'm a little nervous to share my opinions here, as I'm new to open source contributions and haven't been involved much yet.

**Comment by CBID2** [comment]
> > > I'm aware that there are numerous certifications available, but I believe it's beneficial to consider including those that enhance the value of a resume. It's worth noting that many certifications come with a cost, but I firmly believe they can significantly distinguish students during interviews. For instance, certifications like AWS Cloud Architect and AWS Cloud Practitioner are prime examples from my knowledge.
> 
> > 
> 
> > I don't know, I have done several certificates from Google, Oracle Academy, University of Michigan, and so many more.
> 
> > 
> 
> > > Yeah it can definitely improve, but there are lots of certificates (even professional ones).
> 
> > 
> 
> > So, what do you think a criteria should be to add a certification in this subcategory? It shouldn't be based on personal preference right. Just let me know what you think, it will be easier for us to decide which certification should come under this.
> 
> 
> 
> I believe the following criteria should be met to include certifications in this subcategory, as they hold value.
> 
> 
> 
> Industry Recognition: Certifications from well-known and respected organizations or vendors in the industry tend to carry more weight. For example, certifications from Microsoft, AWS, Cisco, or Google often hold high value.
> 
> 
> 
> Validity and Recertification: Some certifications require periodic renewal or recertification to ensure that developers stay up-to-date with evolving technologies. This can be a positive sign of a certification's value.
> 
> 
> 
> Global Recognition: Certifications that are recognized globally can be more valuable as they are not limited to a specific region.

Wow these are great ideas @Shiva-Sai-ssb! 😁

**Comment by CBID2** [comment]
> > > Hey, I believe including paid resources shouldn't be an issue since they can be beneficial for learners. Furthermore, there are currently some paid resources available on Linkshub. The documentation states that Linkshub offers both paid and free resources.
> 
> > > Screenshot (45)
> 
> > > Nevertheless, the ultimate decision rests with the project maintainers, and I am simply expressing my opinion. I will implement any changes based on your's suggestions.
> 
> > 
> 
> > Thanks for pointing it out. You seem hesitant sharing your opinion, don't worry we are not bossy maintainers. We values your opinion just as much as ours.
> 
> 
> 
> Thanks. I'm a little nervous to share my opinions here, as I'm new to open source contributions and haven't been involved much yet.

For someone who just started, you're doing wonderfully @

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
Please do these changes:

1. There is a issue with long category names due to fixed width of sidebar.

Do it Placement Prep.

image

> We will deal with this issue in another issue.

2. Separate the categories with Names: Resume & Portfolio.

3. Add the descriptions, don't worry about the Title, it is fixed in another PR.

Just see examples from the file, and you need to do this for each subcategory.

For certifications, the points you mentioned in the discussion, maybe include the points in a concise way for its description.

**Comment by Anmol-Baranwal** [comment]
@Shiva-Sai-ssb 
Update your branch, this may not occur.

image

**Comment by Shiva-Sai-ssb** [comment]
> Please do these changes:
> 
> 1. There is a issue with long category names due to fixed width of sidebar.
> 
> Do it Placement Prep.
> 
> image
> 
> > We will deal with this issue in another issue.
> 
> 2. Separate the categories with Names: Resume & Portfolio.
> 3. Add the descriptions, don't worry about the Title, it is fixed in another PR.
> 
> Just see examples from the file, and you need to do this for each subcategory.
> 
> For certifications, the points you mentioned in the discussion, maybe include the points in a concise way for its description.

Should I make any additional changes, or is this everything?

**Comment by Shiva-Sai-ssb** [comment]
> @Shiva-Sai-ssb Update your branch, this may not occur.
> 
> image

Sure, I'll update the branch.

**Comment by Anmol-Baranwal** [comment]
> Should I make any additional changes, or is this everything?

No, that is all the changes you need to make.

**Comment by Shiva-Sai-ssb** [comment]
> Additionally, to reduce the number of categories on the main page and improve navigation, I suggest moving the "COMPETITIVE PROGRAMMING" subcategories into the "PLACEMENT PREPARATION" category, as they are relevant resources for placement preparation.

What about this one? @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
> > Additionally, to reduce the number of categories on the main page and improve navigation, I suggest moving the "COMPETITIVE PROGRAMMING" subcategories into the "PLACEMENT PREPARATION" category, as they are relevant resources for placement preparation.
> 
> What about this one? @Anmol-Baranwal

Not needed, there can be articles, youtube tutorials, and many subcategories under Competitive programming. So, it wouldn't be right.

**Comment by Shiva-Sai-ssb** [comment]
> > > Additionally, to reduce the number of categories on the main page and improve navigation, I suggest moving the "COMPETITIVE PROGRAMMING" subcategories into the "PLACEMENT PREPARATION" category, as they are relevant resources for placement preparation.
> > 
> > 
> > What about this one? @Anmol-Baranwal
> 
> Not needed, there can be articles, youtube tutorials, and many subcategories under Competitive programming. So, it wouldn't be right.

Okay. I'll make the requested changes ASAP.

**Comment by Shiva-Sai-ssb** [comment]
Hey @Anmol-Baranwal, I've implemented the requested changes. Furthermore, I've removed the "Coding Challenges Platforms" subcategory since it already exists within the "COMPETITIVE PROGRAMMING" category. Please let me know if you'd like any further adjustments.

**Review by Anmol-Baranwal — DISMISSED** [review]
🚀 Looks good to me. 

> @Shiva-Sai-ssb Well done!

**Comment by CBID2** [comment]
Hey @rupali-codes, there's a deployment issue. Can you fix it?

**Comment by Shiva-Sai-ssb** [comment]
> Hey @rupali-codes, there's a deployment issue. Can you fix it?

Apologies, I believe I may have made some mistakes here. Yesterday, I encountered some merge conflicts in my pull request, and my attempt to resolve them seems to have caused this situation. Can you confirm if the deployment failure is on my end or with Vercel?

**Comment by CBID2** [comment]
> > Hey @rupali-codes, there's a deployment issue. Can you fix it?
> 
> Apologies, I believe I may have made some mistakes here. Yesterday, I encountered some merge conflicts in my pull request, and my attempt to resolve them seems to have caused this situation. Can you confirm if the deployment failure is on my end or with Vercel?

Unfortunately I don’t have access to LinkHub’s Vercel account @Shiva-Sai-ssb.

**Comment by Shiva-Sai-ssb** [comment]
> > > Hey @rupali-codes, there's a deployment issue. Can you fix it?
> > 
> > 
> > Apologies, I believe I may have made some mistakes here. Yesterday, I encountered some merge conflicts in my pull request, and my attempt to resolve them seems to have caused this situation. Can you confirm if the deployment failure is on my end or with Vercel?
> 
> Unfortunately I don’t have access to LinkHub’s Vercel account @Shiva-Sai-ssb.

I believe everything happened because of the pnpm-lock.yaml file, and it was my fault for including it. 😔

**Comment by CBID2** [comment]
> > > > Hey @rupali-codes, there's a deployment issue. Can you fix it?
> > > 
> > > 
> > > Apologies, I believe I may have made some mistakes here. Yesterday, I encountered some merge conflicts in my pull request, and my attempt to resolve them seems to have caused this situation. Can you confirm if the deployment failure is on my end or with Vercel?
> > 
> > 
> > Unfortunately I don’t have access to LinkHub’s Vercel account @Shiva-Sai-ssb.
> 
> I believe everything happened because of the pnpm-lock.yaml file, and it was my fault for including it. 😔

Aww don’t worry. You’ll get it :)

**Review by Anmol-Baranwal — COMMENTED** [review]
@Shiva-Sai-ssb 

Do this and check locally.

Rather than doing this.
image

Just include `[]`

Also, you have deleted pnpm-lock.yaml

Maybe just include it by downloading it from codebase.

It may resolve the error.

If it doesn't then maybe raise a new PR or wait for @rupali-codes insights.

**Review by Anmol-Baranwal — APPROVED** [review]
@Shiva-Sai-ssb 
Did it work without including pnpm-lock? 

🚀 Looks good to me.

**Comment by Shiva-Sai-ssb** [comment]
> @Shiva-Sai-ssb Did it work without including pnpm-lock?
> 
> 🚀 Looks good to me.

Yes, the app still worked even when there was no pnpm-lock.yaml file.

**Comment by Anmol-Baranwal** [comment]
I have fixed the merge conflict.

@rupali-codes @CBID2 
Please review it.

**Comment by CBID2** [comment]
> I have fixed the merge conflict.
> 
> 
> 
> @rupali-codes @CBID2 
> 
> Please review it.

Done @Anmol-Baranwal

**Review by rupali-codes — APPROVED** [review]
looks good to me

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Pull request merged**
