### PR TITLE
Added sitemap.xml

### PR DESCRIPTION
**Pull request by saikiranreddy201**
## Fixes Issue

**Closes** : #1171 

## Changes proposed

- I have added the sitemap.xml file in the public folder for improved SEO.

### CODE REVIEW

**Comment by saikiranreddy201** [comment]
Hey @CBID2, please add the **gssoc** and the **level** label. So that my pr score counts :)

**Review by CBID2 — COMMENTED** [review]
Looks good

**Review by k-deepak04 — APPROVED** [review]
looks fine

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Pull request merged**
