### PR TITLE
Feat: add skiplink

### LINKED ISSUE #498: [Feature] Add skip link
### Description

The navigation is quite long with many links to tab through for keyboard users. By adding a skip link before the navigation, keyboard users can bypass having to tab through the navigation every time to get to the main content.

This will ensure the site passes [WCAG criteria 2.4.1 Level A](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html )

### Screenshots

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by EmmaDawsonDev**
## Fixes Issue #498 

Closes #498 

## Changes proposed

Add a skip link component to the beginning of the layout, which is normally hidden but is the first thing in the tab order and becomes visible when a keyboard user focuses on it. Activating the link jumps to the main content and allows the user to skip over tabbing through all of the navigation links.

## Screenshots

My computer is misbehaving and won't let me take a screenshot right now. But to see the link just navigate to the site and start tabbing. It will appear as the first thing in the tab order in the top center of the page.

### CODE REVIEW

**Comment by rupali-codes** [comment]
I'm able to navigate through my keyboard but not seeing that main content in there

**Comment by EmmaDawsonDev** [comment]
I'm not sure what you mean Rupali. Can you explain a bit more as I haven't touched the main content so all pages should show as normal. 

The expected behaviour of a skip link is to bypass a list of navigation links so in this case if you tab to the skip link, press enter then continue tabbing the focus should move from the skip link to the next available link inside the main element instead of having to tab through the whole navigation every time. Let me know if you want me to record a short screen share (maybe it'll work better than screenshots)

**Comment by rupali-codes** [comment]
> I'm not sure what you mean Rupali. Can you explain a bit more as I haven't touched the main content so all pages should show as normal.
> 
> The expected behaviour of a skip link is to bypass a list of navigation links so in this case if you tab to the skip link, press enter then continue tabbing the focus should move from the skip link to the next available link inside the main element instead of having to tab through the whole navigation every time. Let me know if you want me to record a short screen share (maybe it'll work better than screenshots)

Oh, yeah sure :) that would be much helpful for me

**Comment by EmmaDawsonDev** [comment]
https://github.com/rupali-codes/LinksHub/assets/57045550/3694c48f-38a4-4006-9359-2297022cfb02

In the video I first show how it currently is, where you have to tab through all the navigation links to reach the first item in the main list of links (in this case Appshots) and then my changes  where you tab to the skip link, hit enter and focus moves directly to main and when you tab the focus is on Appshots without having to tab through all of the navigation. To highlight the different states I did the current version in dark mode and then switched to light mode to show my changes.

**Comment by rupali-codes** [comment]
I see, thanks a lot Emma

**Review by rupali-codes — APPROVED** [review]
lgtm

**Review by CBID2 — APPROVED** [review]
LGTM!

**Comment by CBID2** [comment]
@rupali-codes, you need to do force push again

**Pull request merged**
