### PR TITLE
#2246 fix search query value in breadcrumbs

### LINKED ISSUE #2246: [BUG] search query value in breadcrumbs
### Description

It will only happen when the search query matches the complete subcategory name, in this case, `colors`.

It will be as soon as someone enters the search query without clicking the subcategory name in the sidebar.

### Screenshots

image

### Any additional information?

It won't happen if the search query doesn't match the name.
For instance, `color` would show us no breadcrumbs, since there is no subcategory of `color`. 
image

The desired result would be.

image

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by sanjeevkumar321**
## Fixes Issue
Closes #2246 

## Changes proposed
fix bug  search query value in breadcrumbs

## Screenshots

image

image

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
You shouldn't make a PR without getting assigned. It is clearly mentioned in guidelines.

**Comment by Anmol-Baranwal** [comment]
@sanjeevkumar321 
We are neglecting this now, but in the future, you need to create an issue and allow us to assign you the issue before you start working and submit a PR. Not following this process will force us to close your pull request.

This is outlined in the contributing guidelines.
image

You need to follow a predefined flow in order to contribute to Open Source. You may be new, so it is important to understand this.
I hope you understand!

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by CBID2 — APPROVED** [review]
LGTM! :) You're turn @aftabrehan! :)

**Review by aftabrehan — APPROVED** [review]
Working fine 👍

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Review and merge :)

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
