### PR TITLE
chore: Update 'Contribute now' button link

### LINKED ISSUE #2544: [Feature] Navigate users who clicked on 'Contribute now' button to contribution guidelines direcly
### Description

Currently, the 'Contribute now' button is linked to the home page of the GitHub project. There are also a few other links for the same page, like the GitHub icon in the header and 'Give a star'. Therefore, it would be better if the 'Contribute now' button is linked to the contribution page. So users who would like to contribute get a sense of what it would be like to contribute to this project.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by amandee27**
Fixes #2544
## Screenshot

Screenshot 2024-10-14 at 14 54 14

### CODE REVIEW

**Comment by rupali-codes** [comment]
Hi @amandee27, is there any closing issue for PR?

**Comment by amandee27** [comment]
> Hi @amandee27, is there any closing issue for this PR? If so, please attach the issue.

Hi @rupali-codes, No, we don't have an issue for this. I directly created the PR because this is a small change. If necessary, I can create an issue and attach it here. Let me know.

**Comment by amandee27** [comment]
> > > Hi @amandee27, is there any closing issue for this PR? If so, please attach the issue.
> > 
> > 
> > Hi @rupali-codes, No, we don't have an issue for this. I directly created the PR because this is a small change. If necessary, I can create an issue and attach it here. Let me know.
> 
> Hey @amandee27, yes, please raise the issue and link that to this PR.

Sure I'll do it now

**Review by rupali-codes — APPROVED** [review]
Thanks @amandee27, looks good to me

**Pull request merged**
