### PR TITLE
chore(typo): rename our team button

### LINKED ISSUE #2438: [OTHER] Restructure Header
### What would you like to share or ask?

According to me, the header should be updated due to:

1. Cluttered Social Icons
Social icons are grouped with theme toggler, app links, and sponsor.

2. Inappropriate position of `Saved` link.
The right hand side of header belongs to external links.
We can add the link beside the logo.

We can add sponsor button at the bottom of the sidebar.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Jay-Karia**
## Issue
Closes #2438 

## Changes proposed

1. Rename "Our Team" to "Team", as the word "our" also includes the reader (which may or may not be the part of the team).

### CODE REVIEW

**Comment by rupali-codes** [comment]
@Jay-Karia please attach the issue in PR description.

**Comment by Jay-Karia** [comment]
Sorry for not follow the guidelines, I will take care of it in future.

**Comment by rupali-codes** [comment]
@Jay-Karia please do not make any changes without being assigned to the issue. Also, We have social icons in the navbar because, when the user moves to another page, they can still see the icons. 

@Anmol-Baranwal @CBID2 what are your views on this??

**Comment by Anmol-Baranwal** [comment]
> @Jay-Karia please do not make any changes without being assigned to the issue. Also, We have social icons in the navbar because, when the user moves to another page, they can still see the icons.
> 
> @Anmol-Baranwal @CBID2 what are your views on this??

Social links should be in the navbar. Adding them in different places is very effective because we don't know where the user lands from the Google (it can be any of the inner pages). For example, many YCombinator companies follow this practice.

I think it’s fine as it is because the desktop version is wide, and it's standard to find most of the relevant elements in the navbar. Replacing `Our team` with `Team` might be a good idea but it's not 100% necessary!

**Comment by Jay-Karia** [comment]
We can add social icons in the footer

**Comment by rupali-codes** [comment]
> We can add social icons in the footer

It's not necessary. We prefer to leave the icon as they are. Although, you can replace `our team` with `team`.

**Comment by Jay-Karia** [comment]
And what about the position of `"Saved"` link ?

**Comment by rupali-codes** [comment]
> And what about the position of `"Saved"` link ?

yeah, keep it as it is.

**Comment by Jay-Karia** [comment]
@rupali-codes, this pull is ready for review

**Review by rupali-codes — APPROVED** [review]

**Comment by Jay-Karia** [comment]
@rupali-codes what should we do here ?

**Pull request merged**
