### PR TITLE
Added one YouTube playlist for learning Data Structures.

### PR DESCRIPTION
**Pull request by TaeMochi12**
## Changes proposed

Added one YouTube playlist for learning Data Structures. 
Category- YouTube
Sub-Category- Data Structures

### CODE REVIEW

**Review by rupali-codes — DISMISSED** [review]

**Comment by rupali-codes** [comment]
@TaeMochi12 please reference the issue

**Comment by Anmol-Baranwal** [comment]
@TaeMochi12 
Please do it properly, I will remove the spam label. Just let us know.

We don't want you to be discouraged. Let me know if you need to know something.

**Comment by rupali-codes** [comment]
@TaeMochi12 are you still working on this?

**Comment by TaeMochi12** [comment]
Yes , I have created an issue #2037 , please check.

**Comment by Anmol-Baranwal** [comment]
Already completed in another PR raised by same author.

**Pull request closed without merging**
