### PR TITLE
Change threeJS subcategory name to 3d libraries and add resource links

### LINKED ISSUE #2270: Change threeJS subcategory name to 3d libraries and add resource links
### Category Name

Frontend

### Subcategory Name

Three JS      =>     3D libraries

### New or updated description of above subcategory

Rename the _`Three JS`_ subcategory to _**`3D libraries`**_ 

I would like to add additional content to the _**`3D libraries`**_ , such as:

- [Babylon.js](https://www.babylonjs.com/)
- [Play Canvas](https://playcanvas.com/)
- [A-Frame](https://aframe.io/)
- [p5.js](https://p5js.org/)

### Status of Description

- [ ] Adding new description
- [ ] Updating existing description

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by JuanPabloDiaz**
## Fixes Issue

Closes #2270 : Change threeJS subcategory name to 3d libraries and add resource links

## Changes proposed

- Change the subCategory called **threeJS** under the frontend _category_ to **3D Libraries**
- Modify the `CategoryDescriptions.ts` file to include 3D Libraries.
- Rename file called `three.json` in the frontend database folder to include all the URLs related to 3D Libraries.
- Modify the `index.ts` file in the database folder to include 3D Libraries.
- Modify the `data.ts` file in the database folder to include 3D Libraries.

## Screenshots

3D Libraries

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please deploy this.

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
@JuanPabloDiaz 
The subcategory description isn't showing up. It must be due to the incorrect naming in CategoryDescriptions.ts

Please fix that.
image

Everything else is good :)

**Comment by JuanPabloDiaz** [comment]
> @JuanPabloDiaz The subcategory description isn't showing up. It must be due to the incorrect naming in CategoryDescriptions.ts
> 
> Please fix that. image
> 
> Everything else is good :)

I think I found the root cause of the issue. It seems that the `CategoryDescriptions.ts` file has a bug in the function that parses the category names. It does not handle the cases where there is a hyphen (-) between two words, like in **3D Libraries** (which I label as 3d-libraries). This affects all the categories that have this format, not just one.

categoryDescription

I suggest we fix this function as soon as possible. What do you think?

**Comment by Anmol-Baranwal** [comment]
@JuanPabloDiaz @rupali-codes 
Try to fix it. Or I will see it in a couple of days.

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> @JuanPabloDiaz @rupali-codes 
I'm approving the PR. Let's fix the problem for category description in another PR.
I somehow get the feeling it's been handled, so ultimately it won't cause any conflicts.

**Review by CBID2 — APPROVED** [review]
Looks good on my end too! @Anmol-Baranwal. @rupali-codes, it's your turn

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
