### PR TITLE
chore: add workflow to check spam PRs in hacktoberfest

### LINKED ISSUE #1702: [Feature] <Spam PR Prevention workflow>
### Description

I've heard from other maintainers that spam PRs often occur during Hacktoberfest. I found this [GitHub Action](https://github.com/marketplace/actions/spamtoberfest-pull-request-spam-checker) that aids with this.  

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
> Reference: https://github.com/maximelafarie/spamtoberfest

> Can't find any other workflows.

## Fixes Issue

Closes #1702 

## Changes proposed

- I don't really how the workflow works, except that it will close the PR.
- Also, I don't think closing would be the right option, contributors can get a chance of correcting their mistakes.

## Note to reviewers

> Current option is `flag`, let me know if you want me to change it to `default`.

- There are two options as listed in the workflow:
   - `flag` - only adds a "Spam" label to the PR
   - `close` - adds a "Spam" label to the PR and closes it

- What does this means?

image

### CODE REVIEW

**Comment by CBID2** [comment]
@Anmol-Baranwal, I think it means it describes the ways the action monitors the spam PR

**Comment by CBID2** [comment]
I like the `flag` option @Anmol-Baranwal

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Review this workflow, as Hacktoberfest is started.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
