### PR TITLE
chore: add React 2025

### LINKED ISSUE #728: [Add] Free Resource Link for React Js under Frontend Category
### Site URL

https://react2025.com/

### Description of the above provided site

This is a completely free course, that teaches one how to build a SASS level application.

It covers some of the below topics:
- Firestore (Firebase)
- Subscription payment with Stripe
- React / Next.js

### Category

Frontend

### Sub Category

React Js

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

fixes #728 

## Changes proposed

- Add a resource of React under Frontend category

## Screenshots

image

### CODE REVIEW

**Review by CBID2 — DISMISSED** [review]
Great job @Anmol-Baranwal! You’ve improved on writing detailed yet clear descriptions! 😄 LGTM! 😄

**Review by rupali-codes — CHANGES_REQUESTED** [review]
could you please resolve conflicts and remove _languages_?

**Comment by Anmol-Baranwal** [comment]
> could you please resolve conflicts and remove _languages_?

Since I have made multiple pull requests on the same file, there will always be a merge conflict whenever one of them gets merged. 

To mitigate this, I will make a note of this situation and focus on making simultaneous contributions to different files to minimize the occurrence of unnecessary merge conflicts.

**Comment by rupali-codes** [comment]
> > could you please resolve conflicts and remove _languages_?
> 
> Since I have made multiple pull requests on the same file, there will always be a merge conflict whenever one of them gets merged.
> 
> To mitigate this, I will make a note of this situation and focus on making simultaneous contributions to different files to minimize the occurrence of unnecessary merge conflicts.

Oh, yeah right

**Pull request merged**
