### PR TITLE
feat: add Repo-rater GitHub Action

### LINKED ISSUE #2225: Feature: add GitHub Action for Repo-Rater
### Description

Krish recently created this GitHub Action in connection with Eddie Jaoude’s new project, Repo-Rater: https://github.com/marketplace/actions/repo-rater-action
This can help LinksHub gain more contributors.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by CBID2**
## Fixes Issue
Closes #2225 

## Changes proposed
This PR adds the Repo-Rater GitHub Action, which encourages contributors to rate their experience with our project on [Repo-Rater](https://repo-rater.eddiehub.io/). It'll help the project gain more visibility.  

## Screenshots
I tested this GitHub Action in a [test repo](https://github.com/CBID2/test-for-repo-rater/pull/1). Below is a screenshot of the result:
test-pr-for-repo-rater-github-action

### CODE REVIEW

**Comment by CBID2** [comment]
Hey @rupali-codes can you approve the deployment please?

**Comment by Anmol-Baranwal** [comment]
Seems to be good enough, don't really need deployment.

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> I haven't cross checked the action workflow. (Seems to be no syntax errors)

**Review by aftabrehan — APPROVED** [review]
lgtm 👍

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
