### PR TITLE
docs: Fixed Contributors Graph

### PR DESCRIPTION
**Pull request by Shiva-Sai-ssb**
## Fixes Issue
#814

## Changes proposed

I have successfully rectified the error that was impeding the proper functioning of the contributor graph.

## Screenshots

Screenshot (81)

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
Hey, thanks, could you please make some changes?
* Change the count to 50
* Update heading with _Top 50 contributors_
* Add something like a link displaying - _see all contributors_ and point the link it to [this page](https://github.com/rupali-codes/LinksHub/graphs/contributors).

Thanks a lot :)

**Comment by Shiva-Sai-ssb** [comment]
> Hey, thanks, could you please make some changes?
> 
> * Change the count to 50
> * Update heading with _Top 50 contributors_
> * Add something like a link displaying - _see all contributors_ and point the link it to [this page](https://github.com/rupali-codes/LinksHub/graphs/contributors).
> 
> Thanks a lot :)

Certainly, I will proceed with implementing the necessary modifications immediately.

**Review by CBID2 — DISMISSED** [review]
LGTM!

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
