### PR TITLE
[Added] all the color variables in the tailwind.config.js

### LINKED ISSUE #1191: [OTHER] Font Color
### What would you like to share or ask?

image

In the provided image, there are inconsistencies in the text colors that need to be addressed. Although these inconsistencies may be subtle and minute to observe, I would like to fix them to ensure a cohesive visual experience.

Light Mode:
Header: 111827
Footer: 000000

Dark Mode : 
Header : F3F4F6
Footer : E5E7EB

Suggestion: To ensure consistency across the UI, it would be beneficial to create a variable that represents all the colors used.

I have even check your style guide
image
image

If I have overlooked or omitted anything, please feel free to correct me.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by PriyansuMaurya**
## Fixes Issue
Closes #1191

### CODE REVIEW

**Comment by CBID2** [comment]
Can you add a screenshot of your changes @PriyansuMaurya ?

**Review by CBID2 — COMMENTED** [review]
Looks ok. @rupali-codes, what do you think? You too, @k-deepak04

**Comment by PriyansuMaurya** [comment]
image

Dark Mode

image


Light Mode

image

**Comment by CBID2** [comment]
I shall do that later

**Comment by rupali-codes** [comment]
> I shall do that later

alright. but we have actually put the colors in tailwind.config.js file so it would be better if we now add the colors based on accessibility

**Comment by CBID2** [comment]
> > I shall do that later
> 
> alright. but we have actually put the colors in tailwind.config.js file so it would be better if we now add the colors based on accessibility

Hey @rupali-codes. I'm struggling with getting the hex codes for the current colors. Can you list them here?

**Comment by PriyansuMaurya** [comment]
@CBID2, Can I help?

**Comment by CBID2** [comment]
> @CBID2, Can I help?

Sure @PriyansuMaurya

**Comment by PriyansuMaurya** [comment]
How can I help?

**Comment by CBID2** [comment]
> How can I help?

I think you can add the hex code names from the screenshot I presented @PriyansuMaurya.

**Comment by PriyansuMaurya** [comment]
Are you saying I should use this color as background color?

image

**Comment by CBID2** [comment]
> Are you saying I should use this color as background color?
> 
> 
> 
> image
> 
> 
> 
> 

Yes @PriyansuMaurya

**Comment by PriyansuMaurya** [comment]
Hey @CBID2, I'm a bit confused about what you exactly want to do.

Here's a clear guide on how you can make changes to my code: Create a branch from the `organize-colors-to-variables` branch in my fork, make your changes, and then create a pull request. I'll handle the merging process.

Alternatively, an even easier option would be to use **Live Share** or Meet.

Choose whichever option you feel most comfortable with.

**Comment by CBID2** [comment]
> Hey @CBID2, I'm a bit confused about what you exactly want to do.
> 
> 
> 
> Here's a clear guide on how you can make changes to my code: Create a branch from the `organize-colors-to-variables` branch in my fork, make your changes, and then create a pull request. I'll handle the merging process.
> 
> 
> 
> Alternatively, an even easier option would be to use **Live Share** or **Meet**.
> 
> 
> 
> Choose whichever option you feel most comfortable with.

I'll do a Live Share

**Comment by PriyansuMaurya** [comment]
@CBID2, What happend?

**Comment by CBID2** [comment]
> @CBID2, What happend?

I found way to add the hexcodes, but it'll take me a while

**Comment by PriyansuMaurya** [comment]
Please do it ASAP. 😅 I don't want to have to resolve a conflict again. 🙏

**Comment by CBID2** [comment]
> Please do it ASAP. 😅 I don't want to have to resolve a conflict again. 🙏

I'm trying @PriyansuMaurya

**Comment by CBID2** [comment]
> > Please do it ASAP. 😅 I don't want to have to resolve a conflict again. 🙏
> 
> I'm trying @PriyansuMaurya

I hit a roadblock again @PriyansuMaurya. @EmmaDawsonDev, can you help me? I'm trying to make the color variables accessible and got stuck. So far, I tried pairing them together in [this list](https://docs.google.com/document/d/1wPTwW7PcXhB0d9NWEu6zhxZVX6ey5le-yq6K6rmTPvQ/edit?usp=sharing) based on the screenshot in [here](https://github.com/rupali-codes/LinksHub/pull/1584#issuecomment-1674208863).

**Comment by PriyansuMaurya** [comment]
You are creating this to help others understand where to use each color, right?

image

How can I help you?

**Comment by Anmol-Baranwal** [comment]
@CBID2 @PriyansuMaurya 
What is the problem?

Are you not able to find accessible colors, or you are unable to add them?

**Comment by CBID2** [comment]
> @CBID2 @PriyansuMaurya 
> 
> What is the problem?
> 
> 
> 
> Are you not able to find accessible colors, or you are unable to add them?

I found them @Anmol-Baranwal. It's just finding a way to add them.

**Comment by Anmol-Baranwal** [comment]
> > @CBID2 @PriyansuMaurya
> > What is the problem?
> > Are you not able to find accessible colors, or you are unable to add them?
> 
> I found them @Anmol-Baranwal. It's just finding a way to add them.

Just tell the color codes to @PriyansuMaurya

He will add them. It's not really needed for you to add it yourself.

**Comment by CBID2** [comment]
> > > @CBID2 @PriyansuMaurya
> 
> > > What is the problem?
> 
> > > Are you not able to find accessible colors, or you are unable to add them?
> 
> > 
> 
> > I found them @Anmol-Baranwal. It's just finding a way to add them.
> 
> 
> 
> Just tell the color codes to @PriyansuMaurya
> 
> 
> 
> He will add them. It's not really needed for you to add it yourself.

Ok

**Comment by CBID2** [comment]
Hey @PriyansuMaurya! :) We made some updates since this PR was created, so can you solve the merge conflicts before I share the hexcodes with you?

**Comment by PriyansuMaurya** [comment]
Yeah, I'm on it

**Comment by PriyansuMaurya** [comment]
Hello @CBID2, I've completed the merge, please review it and, if possible, accept this PR for Hacktoberfest.

**Comment by CBID2** [comment]
@PriyansuMaurya, have you added the accessible hex codes though? I placed them in the Google Doc I mentioned last time. Also, it's not eligible for Hacktoberfest since this PR was made months before. Sorry 😞

**Comment by Anmol-Baranwal** [comment]
> @PriyansuMaurya, have you added the accessible hex codes though? I placed them in the Google Doc I mentioned last time. Also, it's not eligible for Hacktoberfest since this PR was made months before. Sorry 😞

Maybe raise a new PR if he wishes to do so.

**Comment by CBID2** [comment]
> > @PriyansuMaurya, have you added the accessible hex codes though? I placed them in the Google Doc I mentioned last time. Also, it's not eligible for Hacktoberfest since this PR was made months before. Sorry 😞
> 
> 
> 
> Maybe raise a new PR if he wishes to do so.

I don't know if that's a good idea @Anmol-Baranwal. It would be like starting over again. He could always do a Hacktoberfest PR for something else. I mean the event just started :)

**Comment by Anmol-Baranwal** [comment]
> > > @PriyansuMaurya, have you added the accessible hex codes though? I placed them in the Google Doc I mentioned last time. Also, it's not eligible for Hacktoberfest since this PR was made months before. Sorry 😞
> > 
> > 
> > 
> > Maybe raise a new PR if he wishes to do so.
> 
> I don't know if that's a good idea @Anmol-Baranwal. It would be like starting over again. He could always do a Hacktoberfest PR for something else. I mean the event just started :)

Yeah, I agree 😅

**Comment by PriyansuMaurya** [comment]
I don't see `tailwind.config.css`, Where should I put the colors variables now? additionally I don't understand what does "Accessible version" means? 

I real question is should I also make variables for the same?

**Comment by CBID2** [comment]
> I don't see `tailwind.config.css`, Where should I put the colors variables now? additionally I don't understand what does "Accessible version" means? 
> 
> 
> 
> my real question is should I also make variables for the Accessible color too?

Hi @PriyansuMaurya. Your real question is correct.

**Comment by PriyansuMaurya** [comment]
so where should I add color variables?

**Comment by CBID2** [comment]
> so where should I add color variables?

In [this file](https://github.com/rupali-codes/LinksHub/blob/main/tailwind.config.js) @PriyansuMaurya.

**Comment by rupali-codes** [comment]
@PriyansuMaurya any updates?

**Comment by PriyansuMaurya** [comment]
@CBID2, @rupali-codes, it would be amazing if you could provide the colors in this form instead of the current format:

https://docs.google.com/document/d/1wPTwW7PcXhB0d9NWEu6zhxZVX6ey5le-yq6K6rmTPvQ/edit

The current format is a little bit confusing in terms of knowing which color to use where.

Suggested format:

```

'primary-150': '#5b21b6',  /* violet-800 */
'primary-100': '#7c3aed',  /* violet-600 */
'primary-80': '#8b5cf6',   /* violet-500 */
'primary-60': '#a78bfa',   /* violet-400 */ /* mainly used for text */
'primary-40': '#c4b5fd',   /* violet-300 */

'secondary-200': '#111827',   /* gray-900 */  /* background */
'secondary-100': '#4b5563',   /* gray-600 */
'secondary-80': '#6b7280',    /* gray-500 */
'secondary-60': '#9ca3af',    /* gray-400 */
'secondary-40': '#d1d5db',    /* gray-300 */ /* for dark: card-text */
'secondary-20': '#e5e7eb',    /* gray-200 */
'secondary-10': '#F3F4F6',    /* gray-100 */

```

**Comment by Anmol-Baranwal** [comment]
Resolve the conflicts, or make a new PR if this is very complex conflict.

**Comment by CBID2** [comment]
Any updates @PriyansuMaurya?

**Comment by Anmol-Baranwal** [comment]
Why is this taking such a long time?

Do it fast, or we can assign someone else.

**Comment by CBID2** [comment]
Closed due to inactivity

**Pull request closed without merging**
