### PR TITLE
cloud added

### LINKED ISSUE #1279: [ADD] Whole new category cloud computing.
### Category Name

Cloud

### Subcategory Name

Microsoft Azure, AWS, GCP.

### Additional Context

i will add whole new category with three subcategories under it , as cloud computing is in boom nowadays and people often search for this which cloud to go with and proceed with certifications.
so i will add category cloud, and 3 subcategories under it , follwed by adding resources in all of them.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by k-deepak04**
## Screenshots

image

### CODE REVIEW

**Comment by k-deepak04** [comment]
@CBID2 @rupali-codes please review and merge also add proper labels :)

**Review by CBID2 — DISMISSED** [review]
Hi @k-deepak04! 😄 I just made a few tweaks to some of the descriptions but other than that, great job! 😄 👍🏾

**Comment by k-deepak04** [comment]
@CBID2 i have made quite a lot changes in this one, it's not just adding simple resources you can view the file change section and reconsider the level :)

**Comment by CBID2** [comment]
> @CBID2 I have made quite a lot of changes in this one, it's not just adding simple resources, this took quite an effort you can view the file change section and reconsider the level :)

Hi @k-deepak04. We're grateful for your support and effort. However, the rules state that adding links is level one.

**Review by rupali-codes — DISMISSED** [review]

**Comment by k-deepak04** [comment]
> @k-deepak04 please resolve merge conflicts

resolved :)

**Review by rupali-codes — APPROVED** [review]
thanks, lgtm

**Pull request merged**
