### PR TITLE
Create ChatBot.py

### PR DESCRIPTION
**Pull request by A11bert**
a basic chatbot to add in website or an app to get connected.

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@A11bert 
Let me be clear, first you need to read `Contributing.md` which is the contributing guidelines in the repository.
You will get proper instructions there.

We are neglecting this now, but in the future, you need to make a issues, then allow us to assign you the issue before you start working and submit a PR. Not following this process will require us to close your pull request.

This is outlined in the contributing guidelines.
image

**Comment by Anmol-Baranwal** [comment]
@A11bert 
I've converted this issue in a draft PR, others will just mark it as spam. We really want you to merge the PR, so just make a issue and tag me there for assigning.

**Comment by Anmol-Baranwal** [comment]
Also, the contribution is not proper for LinksHub. Let's discuss in the issue.

**Comment by rupali-codes** [comment]
@A11bert you must read & follow our CONTRIBUTING guidelines before making any contribution. As @Anmol-Baranwal mentioned above, we appreciate your time and efforts but please raise the issue first. I'm closing this PR for now, please feel free to raise another PR when you're done.

**Pull request closed without merging**
