### PR TITLE
feat: add section about our participation in open source outreach programs

### LINKED ISSUE #1593: [DOCS] <Adding Programs we participated in section>
### Issue Description

It would be helpful to add a "Programs We Participated Section" and add GSSOC in there. It'll help increase people's interest in contributing to LinksHub.   

### Additional Context

_No response_

### Screenshots or Examples (if applicable)

_No response_

### Proposed Solution (optional)

_No response_

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by CBID2**
## Fixes Issue
Closes #1593  

## Changes proposed
This PR adds a section about open source outreach programs that LinksHub has partaken in. It'll increase people's interest in the project.

## Screenshots
outreach

### CODE REVIEW

**Comment by CBID2** [comment]
Check this out @rupali-codes

**Review by Anmol-Baranwal — COMMENTED** [review]
I think the purpose should be different, because projects grow as well, and it could include mentors, project admins as well.

**Comment by CBID2** [comment]
> I think the purpose should be different, because projects grow as well, and it could include mentors, project admins as well.

Interesting point @Anmol-Baranwal, but I want to keep it simple and just mention the organizations

**Comment by Anmol-Baranwal** [comment]
> > I think the purpose should be different, because projects grow as well, and it could include mentors, project admins as well.
> 
> Interesting point @Anmol-Baranwal, but I want to keep it simple and just mention the organizations. What do you think @rupali-codes?

Yeah, that is okay as well.

**Comment by CBID2** [comment]
> > > I think the purpose should be different, because projects grow as well, and it could include mentors, project admins as well.
> 
> > 
> 
> > Interesting point @Anmol-Baranwal, but I want to keep it simple and just mention the organizations. What do you think @rupali-codes?
> 
> 
> 
> Yeah, that is okay as well.

Alrighty then. Can I get an approved review? :)

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by k-deepak04 — APPROVED** [review]

**Pull request merged**
