### PR TITLE
bookyard added

### LINKED ISSUE #1531: [Add] book yards
### Site URL

www.bookyards.com

### Description of the above provided site

'The Library to the World', in which books, education materials, information, reference materials, documents, and content will be provided freely 

### Category

Resources

### Sub Category

ebook

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by S-ishita**
## Fixes Issue
closes #1531 

## Screenshots
Screenshot from 2023-08-10 09-29-54

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by CBID2** [comment]
> @CBID2 please assign me other issues as well...or atleast provide remark if they do not seem valid to you so that I can raise other valid issues and be assigned to them.

Just assigned you to a couple @S-ishita. Work on them one at a time though

**Comment by CBID2** [comment]
> > > @CBID2 please assign me other issues as well...or atleast provide remark if they do not seem valid to you so that I can raise other valid issues and be assigned to them.
> 
> > 
> 
> > Just assigned you to a couple @S-ishita. Work on them one at a time though
> 
> 
> 
> Thanks for replying..here are the unassigned issues 1515 1502 1500  1483  1465 1396
Can you hyperlink each one

**Comment by CBID2** [comment]
> 
> 
> > > > > @CBID2 please assign me other issues as well...or atleast provide remark if they do not seem valid to you so that I can raise other valid issues and be assigned to them.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Just assigned you to a couple @S-ishita. Work on them one at a time though
> 
> > > 
> 
> > > 
> 
> > > Thanks for replying..here are the unassigned issues 1515 1502 1500  1483  1465 1396
> 
> > > Can you hyperlink each one @S-ishita?
> 
> 
> 
> done @CBID2 
> 
> 

No, I mean posting the link to The unassigned issues @S-ishita.

**Comment by CBID2** [comment]
Done @S-ishita

**Review by k-deepak04 — APPROVED** [review]

**Pull request merged**
