### PR TITLE
feat: [ADD]-Sub Category- Automation Tools #2345

### LINKED ISSUE #2345: [ADD] Include Ansible in DevOps
### Site URL

https://www.redhat.com/en/blog/ansible-101-ansible-beginners

## Description of the above provided site
Ansible is a popular automation tool known for its simplicity and versatility in infrastructure management and application deployment.

As a DevOps professional, Ansible is a powerful tool. Check the link above for detailed Ansible playbook tutorials, ideal for practicing and preparing for the RH-EX294 exam.

## Why Add Ansible?
- Provides educational value on modern DevOps practices.
- Showcases practical use cases for automation and orchestration.
- Engages DevOps professionals and enthusiasts.

### Category

DevOps

### Sub Category

Automation Tool

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by mdazfar2**
closes #2345 

## Add Sub Category
Adding a sub category named Automation Tools where, insert various tools in this category.

## Screenshots
image
---
image
---

## Links I have posted
- **Ansible Automation**- [view](https://www.ansible.com/)
- **Terraform Infrastructure**- [View](https://www.terraform.io/)
- **GitLab CI/CD**- [View](https://docs.gitlab.com/ee/ci/)
- **Configuration Management with Puppet and Chef**- [View](https://www.puppet.com/)

> @Anmol-Baranwal Anmol, is this correct, or should I post a link to another website? Please let me know if there are any issues with the tools.

### CODE REVIEW

**Comment by mdazfar2** [comment]
@CBID2 
@Anmol-Baranwal 
@rupali-codes 
Someone reply to my pull request, if I need to change anything then please tell me.

**Comment by Anmol-Baranwal** [comment]
> @CBID2 
> @Anmol-Baranwal 
> @rupali-codes 
> Someone reply to my pull request, if I need to change anything then please tell me.

Sure, I will review it till evening and let you know if there are any changes required.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please deploy this.

@mdazfar2 
Please link the issue to the PR so that when it merges, the issue would be automatically closed.
Read it [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). I've done it this time for you.

image

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by CBID2** [comment]
@Anmol-Baranwal, did you approve this PR?
@rupali-codes, can you approve it too?

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
