### PR TITLE
docs: update docs issue form with correct links

### LINKED ISSUE #958: [DOCS] Fix Docs Issue Form Error
### Issue Description

I will quickly create a pull request to address all the links and ensure they adhere to proper conventions.

@rupali-codes
I am tagging you because I believe these errors should be resolved promptly.

Some fields are mandatory, and will lead to major confusion to whoever submits the issue using this form.

### Additional Context

_No response_

### Screenshots or Examples (if applicable)

image

### Proposed Solution (optional)

_No response_

### Checklist

- [X] I have checked the existing [issues(https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines(https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #958 

## Changes proposed

- Made the `issue description` field mandatory.
- Fixed the links.
- Removed the checklist for `category` and `subcategory` as it is irrelevant.

## Screenshots

image

## Note to reviewers

> Followed proper conventions

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM!

**Comment by Anmol-Baranwal** [comment]
Hi, @ujjawaltyagii.
Am I allowed to create new issues and pull requests?

**Comment by ujjawaltyagii** [comment]
@Anmol-Baranwal yeah ! sure 👍

**Review by ujjawaltyagii — APPROVED** [review]
lgtm !

**Comment by Anmol-Baranwal** [comment]
> lgtm !

This should be a level 2 contribution, since it is related to documentation.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal yeah ! sure but what's going on with #890 ???

Nothing, you have to review it to make it ready to merge.

**Review by rupali-codes — APPROVED** [review]
lgtm, thanks

**Pull request merged**
