### PR TITLE
Issue/Link template updated

### LINKED ISSUE #1549: [BUG] Competitive programming is not in the issue template
### Description

while opening new issue and adding link we are not getting competitive programming as a category in the dropdown.
i will make sure to add that and also check if anything more is like this and add that too so that while opening an issue user can find the category properly

### Screenshots

image

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by k-deepak04**
## Fixes Issue 
Closes #1549 

## Changes proposed
verified the deployment and categoried section then updated the issue/add_link template to match with that categories

## Screenshots

image

image

image

## Note to reviewers
reviewed and verified all the source data from the deployment to codebase and added the remaining category and make sure things are proper everywhere

### CODE REVIEW

**Review by CBID2 — DISMISSED** [review]
LGTM

**Comment by k-deepak04** [comment]
> LGTM

can you please review again.....by mistakelny i have added commits in this and had to revert them back
so sorry for the inconvenience

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by CBID2** [comment]
> > LGTM
> 
> 
> 
> can you please review again.....by mistakelny i have added commits in this and had to revert them back
> 
> so sorry for the inconvenience

Done. Also mention the changes you made in the "Changes Proposed" section of the issue form.

**Pull request merged**
