### PR TITLE
Added a card in the resume builder - (Overleaf) .

### LINKED ISSUE #2191: [Add]: A Card in the Resume Building.
### Site URL

https://www.overleaf.com/latex/templates/tagged/cv

### Description of the above provided site

A resume or CV is like a fancy paper that tells others about your work and skills. The website provides tools and templates to make this process easier. So, if you're looking for a job or applying to school, Overleaf can help you make a professional-looking resume or CV.

Few sample templates:

image

### Category

Other

### Sub Category

Resume Building

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by the-shivam-gupta**
## Fixes Issue
Closes #2191

### CODE REVIEW

**Comment by the-shivam-gupta** [comment]
@Anmol-Baranwal  @CBID2  @rupali-codes

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Please review and add the label.

**Review by CBID2 — APPROVED** [review]
Looks great to me! 😁 @aftabrehan, your turn! 😁

**Review by aftabrehan — APPROVED** [review]
Looks good to me! 👍

**Comment by aftabrehan** [comment]
@rupali-codes, please, help merge this PR.

**Pull request merged**
