### PR TITLE
chore : Added Dsa subcategory under Resources category.

### LINKED ISSUE #1959: [ADD] <DSA Subcategory>
### Category Name

Resources

### Subcategory Name

DSA

### Additional Context

Adding 'Data Structures and Algorithms' Subcategory under 'Resources' category.

This section will contain various resources like DSA cheatsheets, DSA roadmaps, DSA problem sheets and much more everything related to Data Structures and Algorithms.

This subcategory will definitely be a great addition to the website and the resources. 

I have already worked before in adding a subcategory, so please assign me with this.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by aditya9277**
## Fixes Issue

Closes #1959 

## Changes proposed

Added DSA subcategory under Resources category.

## Screenshots

image
##
image

## Note to reviewers

It will be great addition to the resources.

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
What did you decide?

Dsa as a category or subcategory.

**Comment by rupali-codes** [comment]
> @rupali-codes What did you decide?
> 
> Dsa as a category or subcategory.

i guess lets make it category, bcz DSA is a huge topic, we can add blogs, youtube tutorials and other free courses in there

**Comment by Anmol-Baranwal** [comment]
> > @rupali-codes What did you decide?
> > Dsa as a category or subcategory.
> 
> i guess lets make it category, bcz DSA is a huge topic, we can add blogs, youtube tutorials and other free courses in there

Sure :)

**Comment by aditya9277** [comment]
> Hi @aditya9277! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

Thanks, committed your suggestion and from now onwards will surely keep a check on proofreading.

**Review by CBID2 — APPROVED** [review]
Looks good @aditya9277! :) @rupali-codes, @Anmol-Baranwal, you're up! :)

**Review by Anmol-Baranwal — COMMENTED** [review]
🚀 Looks good to me. 

@rupali-codes 
Let's merge this for now. We will change it once the dsa category has been added.

**Review by Anmol-Baranwal — APPROVED** [review]

**Comment by aditya9277** [comment]
Hey @CBID2, is there something more i have to do?
Cuz this PR is open since more than usual time ....

**Comment by Anmol-Baranwal** [comment]
@aditya9277 
It will be merged quickly. It needs 3 approvals.

**Review by rupali-codes — APPROVED** [review]
lgtm, thanks

**Pull request merged**
