### PR TITLE
Prettier fixed

### LINKED ISSUE #226: [CHORE] add prettier
### What would you like to share or ask?

As of now, we don't have prettier initialized and it's hard to tell people to format their code before they push it. Your task is to add `prettier` in this project so the code will be formatted. 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Abbeyafolaby**
## Fixes Issue

Closes #226

### CODE REVIEW

**Comment by Abbeyafolaby** [comment]
Hi @rupali-codes, Everything okay now?
Thank you for helping me find the errors.

**Comment by Abbeyafolaby** [comment]
I am so sorry for doing that without telling you first. but the lint was throwing an error that the files were declared but not used. but I think if I should remove the rule `@typescript-eslint/no-unused-vars` the error will go.

should I remove `@typescript-eslint/no-unused-vars` rule?

 
Screenshot (57)

**Comment by rupali-codes** [comment]
> Why you've deleted `index` file from Footer and TopBar?

yeah, idk why it's throwing that error

**Comment by Abbeyafolaby** [comment]
I added the file is back, I added the file back.
Is that okay?

**Comment by Abbeyafolaby** [comment]
> > Why you've deleted `index` file from Footer and TopBar?
> 
> yeah, idk why it's throwing that error

I added the file back, is that okay?

**Pull request closed without merging**
