### PR TITLE
Added Women-led-open-source sub-category

### LINKED ISSUE #657: [Add] <Women-Led-Open-Source>
### Site URL

https://github.com/amandamartin-dev/women-led-open-source

### Description of the above provided site

This is a living document that can serve as a resource for finding people including those identifying as women, transgender people, nonbinary people, and other underrepresented genders leading open source projects and companies, serving as maintainers, or otherwise supporting Open Source.

### Category

Other

### Sub Category

Open Source Projects

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Kushagra102**
## Fixes Issue
Closes #657 

## Changes proposed
- Added "women-led-open-source" link in "open-source-project" sub-category in other "category" 

## Screenshots
image
image
image

## Note to reviewers
Added the shown link.

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Hey, we already have _open source_ category and _open source projects_ as subcategory in there,  please consider adding this project in the respective category and subcategory.

You may add this [here](https://github.com/rupali-codes/LinksHub/blob/main/database/opensource/projects.json)

Also, make sure to remove this newly created subcategory. let us know if you need any kinda help

**Comment by k-deepak04** [comment]
@Kushagra102 resolve  the conflicts and updates the suggested changes by rupali
let us know if you are facing any issues....or any help needed from our side :)

**Comment by Kushagra102** [comment]
Yesss a little busy in exams will update and create a request on 2nd July 👍🏼

**Comment by k-deepak04** [comment]
> Yesss a little busy in exams will update and create a request on 2nd July 👍🏼

okay
Good Luck for your exams :)

**Comment by Kushagra102** [comment]
Hey @rupali-codes, @CBID2 added the required changes.

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by k-deepak04 — APPROVED** [review]

**Pull request merged**
