### PR TITLE
[Add] Dribbble

### LINKED ISSUE #85: [Add] Dribbble
### URL

https://dribbble.com

### Description of the above provided site

Explore the world’s leading design portfolios

### Category

Frontend

### Sub Category

"design inspiration"

### PR DESCRIPTION
**Pull request by jackz070**
Closes #85

### CODE REVIEW

**Comment by jackz070** [comment]
I have no idea what's the problem that vercel bot found, I can't access neither preview nor checks status inspect link (both give me 404).

**Comment by rupali-codes** [comment]
it's fine it was just a typo

**Comment by jackz070** [comment]
Oh, I see it now. I thought it's because I didn't set up my environment and used in-browser githubs editor with no type warnings (will do it properly I think anyway) but now I see that actually this typo is in Subcategory type definition in types. Will you fix it or should I do this?

**Comment by rupali-codes** [comment]
@jackz070 i fixed it no worry

**Pull request merged**
