### PR TITLE
Added additional styling to the Contributors page

### PR DESCRIPTION
**Pull request by karthiknadar1204**
## Changes proposed
I have added hover effect to the individual cards, add some border to the images in the cards along with hover effect to the images.
Increased the font size of the contents inside the cards by a few pixels to make it look more prominent.

## Screenshots

https://www.awesomescreenshot.com/video/18976128?key=50ca96dffaa23aada0c865e56b2fd196

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
So sorry,I did not realise I had staged the updated readme as well,will fix it and add the suggested changes

**Comment by CBID2** [comment]
There's some merge conflicts that need solving @karthiknadar1204

**Comment by karthiknadar1204** [comment]
@CBID2 #1288 is my second pr to clear this issue, this once can be closed as it was merged.

**Comment by CBID2** [comment]
> @CBID2 #1288 is my second pr to clear this issue, this once can be closed as it was merged.

Thanks for clarifying @karthiknadar1204

**Pull request closed without merging**
