### PR TITLE
fix: major bug of weird missing subcategory array

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Changes proposed

Reverting 

## Note to reviewers

@rupali-codes 
See if this works. 

I have reverted `c4504fe`

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 

I think previous works as intended.

image

It finds subcategories from main data.

image

What do you think?

In current version, the searchbar query inputs the subcategory including `-` which you can see here: #1746 

image

**Review by rupali-codes — COMMENTED** [review]
i think if it works fine, then we don't need to revert it? although we might need to change the names and add `-` it

Wdyt?

**Comment by Anmol-Baranwal** [comment]
> i think if it works fine, then we don't need to revert it? although we might need to change the names and add `-` it
> 
> Wdyt?

Why do we need to add `-`? Let's test this properly.

In future, this may generate bugs so we need to be clear of the approach.

**Review by CBID2 — APPROVED** [review]
Looks great on my end

**Comment by rupali-codes** [comment]
> > i think if it works fine, then we don't need to revert it? although we might need to change the names and add `-` it
> > Wdyt?
> 
> Why do we need to add `-`? Let's test this properly.
> 
> In future, this may generate bugs so we need to be clear of the approach.

Okay, lets test it properly

**Comment by CBID2** [comment]
Is this still being worked on @Anmol-Baranwal and @rupali-codes?

**Comment by Anmol-Baranwal** [comment]
@CBID2 @rupali-codes 
Closing this! As the current one works properly.

**Pull request closed without merging**
