### PR TITLE
Header redesign

### LINKED ISSUE #2171: feat: add new header design
> You can view the figma file [here](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?type=design&node-id=17-231&mode=design&t=29U3Qw0LktnVRteR-0).

image

> The design should be responsive. 

---

We recommend updating the styling of existing components, otherwise you can add extra components if there is a need.

- You also have to complete theme toggler

image

> Any changes to the above design are welcome. Please feel free to share your thoughts, and we will discuss them thoroughly.

---
### ⚠️ Make sure to push all the changes into `dev` branch

### PR DESCRIPTION
**Pull request by aftabrehan**
Relates to #2171 

### Preview

<div align="center">

 https://www.loom.com/share/a3f1ac4bb6e7415ba53f3479b1e63dda?sid=27592921-13c5-459e-9c5a-9aa4ad166d43

</div>

## Changes proposed

- [x] Update header design
- [x] Create button component
- [x] Configure `@svgr/webpack` to use Icons as React Element for adjusting colors dynamically.

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks awesome @aftabrehan! :) @Anmol-Baranwal and @rupali-codes, what do you think?

**Comment by Anmol-Baranwal** [comment]
> Looks awesome @aftabrehan! :) @Anmol-Baranwal and @rupali-codes, what do you think?

There is no deployment, so I can't check since there are so many files and changes.

**Comment by aftabrehan** [comment]
> > Looks awesome @aftabrehan! :) @Anmol-Baranwal and @rupali-codes, what do you think?
> 
> There is no deployment, so I can't check since there are so many files and changes.

@Anmol-Baranwal, I thought I already mentioned it in discord. You have to check my last commit.

**Comment by aftabrehan** [comment]
@Anmol-Baranwal, And of course, there is deployment. You can see it if you scroll above. 

https://github.com/rupali-codes/LinksHub/pull/2185#issuecomment-1806872013

**Review by Anmol-Baranwal — COMMENTED** [review]
> Sorry, I missed that.

These are some of the changes that I believe would be good. But discuss with @CBID2 & @rupali-codes before proceeding. If they agree, then do it otherwise it's good to go.

1. Hovering state of social icons. It seems good for dark mode. But I still prefer original ones.

| Original | Current |
|----------|----------|
| image | image |
| image | image |

2. I think font-style could be changed. Bold one looks better.

image

3. There is no nav menu to open sidebar in lower screen sizes.

image

---

I think it would be better to create PR from fork, unless we need collaboration. Because lots of these changes have already been made, and it just confuses me from the focused changes for this PR.

How would I even know which files are changed for just this PR. I was literally confused about codeowners file. Lemme know what you think.

**Comment by aftabrehan** [comment]
>How would I even know which files are changed for just this PR. I was literally confused about codeowners file. Lemme know what you think.

You can navigate to the [commit page](https://github.com/rupali-codes/LinksHub/pull/2185/commits) for that.  [ref](https://discord.com/channels/1064977356198006805/1109171192839012554/1172952802478264451).

**Comment by aftabrehan** [comment]
@Anmol-Baranwal, Feel free to hop onto Figma and drop any comments for UI adjustments you might need. It only takes a few seconds to tweak something in the design, and addressing UI changes after a PR is raised can be a bit time-consuming. Your input is super valuable! 😊

cc @CBID2 @rupali-codes

**Comment by aftabrehan** [comment]
>Because lots of these changes have already been made, and it just confuses me from the focused changes for this PR.

https://discord.com/channels/1064977356198006805/1109171192839012554/1172952802478264451

**Comment by aftabrehan** [comment]
> There is no nav menu to open sidebar in lower screen sizes.

@Anmol-Baranwal, we don't need the sidebar in mobile in our new design. The bottom navbar can do this job for us.

**Comment by Anmol-Baranwal** [comment]
Seems to be good. Let others review, then tag me. I will approve it.

**Review by CBID2 — APPROVED** [review]
Looks great to me

**Comment by aftabrehan** [comment]
> @aftabrehan the sidebar is hidden for mobile screens? I can't see it 👀

@rupali-codes, We don't need the sidebar to be visible according to the new UI.

**Comment by aftabrehan** [comment]
@rupali-codes, the conflicts are resolved for this PR. Can you help review & merge it?

**Comment by aftabrehan** [comment]
@rupali-codes, can you please merge it? It has no dependencies.

**Comment by CBID2** [comment]
> @rupali-codes, can you please merge it? It has no dependencies.

All done @aftabrehan

**Pull request merged**
