### PR TITLE
Added Appwrite for authentication and database

### LINKED ISSUE #1219: [Add]  Appwrite for database and authentication
### Site URL

https://appwrite.io/docs/authentication

### Description of the above provided site

Appwrite: The open-source backend server that simplifies application development with features like authentication, database management, and file storage.

### Category

Backend

### Sub Category

authentication, database

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Mihan786Chistie**
## Fixes Issue

Closes #1219 

## Changes proposed
Added Appwrite as database and authentication inside the database folder.

## Screenshots

Screenshot 2023-07-04 193718
Screenshot 2023-07-04 193758

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by Mihan786Chistie — COMMENTED** [review]
ok

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by k-deepak04 — APPROVED** [review]

**Comment by Mihan786Chistie** [comment]
@CBID2 please add the GSSOC tag on this PR

**Comment by CBID2** [comment]
> @CBID2 please add the GSSOC tag on this PR

Done @Mihan786Chistie

**Comment by Mihan786Chistie** [comment]
> > @CBID2 please add the GSSOC tag on this PR
> 
> Done @Mihan786Chistie 

Thanks @CBID2

**Pull request merged**
