### PR TITLE
fix: cpp-content

### LINKED ISSUE #1758: [Bugs] : Content not found
### Site URL

https://www.linkshub.dev/languages/cpp

### Description of the above provided site

No content found in `languages > c ++ programming` 

### Category

Languages

### Sub Category

c++ 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by rahulpandey70**
## Fixes Issue

Closes #1758 

## Changes proposed

This PR will fix CPP content not found.

## Screenshots

Screenshot from 2023-10-03 11-25-29

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Well done @rahulpandey70

**Comment by rahulpandey70** [comment]
> Well done @rahulpandey70

thank you

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Comment by rahulpandey70** [comment]
> 🚀 Looks good to me.

@Anmol-Baranwal @CBID2 can you add this issue under `hacktoberfest`?

**Comment by Anmol-Baranwal** [comment]
> > 🚀 Looks good to me.
> 
> @Anmol-Baranwal @CBID2 can you add this issue under `hacktoberfest`?

It should show up anyway, still we have added the labels.

**Comment by rahulpandey70** [comment]
> > > 🚀 Looks good to me.
> > 
> > 
> > @Anmol-Baranwal @CBID2 can you add this issue under `hacktoberfest`?
> 
> It should show up anyway, still we have added the labels.

ohh thank you

**Pull request merged**
