### PR TITLE
Added height animation for sub lists when opening and closing

### LINKED ISSUE #962: [Feature] Sub List when opening and closing
### Description

Hi,
I hope you are doing well.

There is something if we bring onto the website, it will look awesome and that is "adding animation when closing and opening each category".

### Screenshots

image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by AliReza1083**
## Fixes Issue
Close #962 

## Changes proposed
Added a new package (famer-motion)

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks ok to me

**Comment by ujjawaltyagii** [comment]
Please resolve merge conflicts first !

Second I dont know why but I see no changes when I compared the deployment to the actual website 👀
could you provide screenshot or screen recording of the changes

**Comment by ujjawaltyagii** [comment]
@rupali-codes Haven't we done similar kind of thing in #750 0_0

**Comment by CBID2** [comment]
> @rupali-codes Haven't we done similar kind of thing in #750 0_0

You're right @ujjawaltyagii. It seems strange

**Comment by rupali-codes** [comment]
> @rupali-codes Haven't we done similar kind of thing in #750 0_0

👀 ohh, yeah i just remembered... what should be do now @ujjawaltyagii @CBID2

**Comment by CBID2** [comment]
> > @rupali-codes Haven't we done similar kind of thing in #750 0_0
> 
> 
> 
> 👀 ohh, yeah i just remembered... what should be do now @ujjawaltyagii @CBID2 

Let's have @AliReza1083 explain their reasoning for this PR. Maybe they saw something that could be improved? 🤷🏽‍♀️

**Comment by rupali-codes** [comment]
> > > @rupali-codes Haven't we done similar kind of thing in #750 0_0
> > 
> > 
> > 👀 ohh, yeah i just remembered... what should be do now @ujjawaltyagii @CBID2
> 
> Let's have @AliReza1083 explain their reasoning for this PR. Maybe they saw something that could be improved? 🤷🏽‍♀️

Actually it was me, and that PR wasn't merged then. Misconflicts 🙂
@CBID2 can we add the animation anywhere else 👀

**Comment by AliReza1083** [comment]
I did not know that there was an issue for this.
When I saw their PR about adding animation when closing and opening each sub links, I noticed that mine is so similar to them, and You merged them and then removed the animation later.
May I know the reason?

**Comment by CBID2** [comment]
> > > > @rupali-codes Haven't we done similar kind of thing in #750 0_0
> 
> > > 
> 
> > > 
> 
> > > 👀 ohh, yeah i just remembered... what should be do now @ujjawaltyagii @CBID2
> 
> > 
> 
> > Let's have @AliReza1083 explain their reasoning for this PR. Maybe they saw something that could be improved? 🤷🏽‍♀️
> 
> 
> 
> Actually it was me, and that PR wasn't merged then. Misconflicts 🙂
> 
> @CBID2 can we add the animation anywhere else 👀
> 
> 

Hmm I'm not too sure

**Comment by ujjawaltyagii** [comment]
I saw it and I was like we did it just couple of days back now we are doing it again XD
But I don't see any place where we can add animation else right now :( 
Ig we have to close this issue and PR without merging or is there any other way ?

**Comment by CBID2** [comment]
> I saw it and I was like we did it just couple of days back now we are doing it again XD But I don't see any place where we can add animation else right now :( Ig we have to close this issue and PR without merging or is there any other way ?

Good point @ujjawaltyagii. As sad as it for me to say, I vote to close this pull request to avoid repetition. 😞  How about you? @rupali-codes, what do you think?

**Comment by AliReza1083** [comment]
> > I saw it and I was like we did it just couple of days back now we are doing it again XD But I don't see any place where we can add animation else right now :( Ig we have to close this issue and PR without merging or is there any other way ?
> 
> Good point @ujjawaltyagii. As sad as it for me to say, I vote to close this pull request to avoid repetition. 😞 How about you? @rupali-codes, what do you think?

Yes, I agree.

**Comment by rupali-codes** [comment]
@ujjawaltyagii & @CBID2  yeah, i agree. We need to close this PR :( 
@AliReza1083 We really appreciate your time and efforts 🙂. Hope to see you contributing on some other issues :)

**Pull request closed without merging**
