### PR TITLE
dipayan_branch

### PR DESCRIPTION
**Pull request by Dipayan23**
## Changes proposed

So As a flutter developer i need to use several animation so i use hero animation which is very easy to use and looks cool.

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@Dipayan23 
I wonder why the deployment got failed, maybe you can check it on your side. It might be due to description.

**Comment by CBID2** [comment]
There's some merge conflicts too.

**Comment by CBID2** [comment]
@Dipayan23, are you still working on this?

**Comment by Anmol-Baranwal** [comment]
> @Dipayan23, are you still working on this?

If he doesn't reply in 24hrs.

Close the PR and make issue open for others to grab.

**Comment by Anmol-Baranwal** [comment]
@CBID2 
There is no issue assigned so let us close this.

**Pull request closed without merging**
