### PR TITLE
[Add] Heroicons

### LINKED ISSUE #528: [Add] Heroicons
### Site URL

https://heroicons.com/

### Description of the above provided site

Heroicons is a comprehensive collection of high-quality SVG icons designed to enhance your web and mobile interfaces. With its extensive collection and easy integration, Heroicons empowers developers to add visually appealing and consistent icons to their projects effortlessly.

### Category

Frontend

### Sub Category

icons

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Oyebolade**
## Fixes Issue
Closes #528

## Changes proposed
Heroicons  link is added to frontend category

## Screenshots
Heroicons

### CODE REVIEW

**Review by ujjawaltyagii — APPROVED** [review]
Lgtm !!  👍

**Review by CBID2 — APPROVED** [review]
Looks great @Oyebolade! :) LGTM! :)

**Comment by Oyebolade** [comment]
Please, what's the meaning of "lgtm"

**Comment by Lucif3r-in** [comment]
> Please, what's the meaning of "lgtm"

Looks good to me

**Comment by Oyebolade** [comment]
> > Please, what's the meaning of "lgtm"
> 
> Looks good to me
Oh thanks

**Review by rupali-codes — APPROVED** [review]
lgtm too :)

**Pull request merged**
