### PR TITLE
Fixed navbar for mobile screen (specially for open-source section)

### LINKED ISSUE #832: [Feature] <Make navbar responsive>
### Description

Navbar is not responsive in open-source section for blogs and projects. Can you please assign it to me under GSSOC'23

### Screenshots

image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by kedar1998**
## Fixes Issue
Closed #832

## Changes proposed
Navbar width is fixed for open-source category

## Screenshots
image

image

## Note to reviewers
I have made changes according to issue mentioned in issue #832. Please merge it with main branch

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks good

**Review by rupali-codes — CHANGES_REQUESTED** [review]
hey, could you please unstage pnpn-lock.yml file?

**Comment by rupali-codes** [comment]
@kedar1998 are you still working on this?

**Comment by kedar1998** [comment]
@rupali-codes Deleted pnpm-lock.yaml file

**Pull request closed without merging**
