### PR TITLE
[ADD] Cybersecurity modules

### PR DESCRIPTION
**Pull request by Gobinath-B**
## Changes proposed
. I added a new module
. Module Name: Cybersecurity 
. Purpose: This module provides a central hub for curated cybersecurity resources, including articles, tools, and tutorials.
. Benefits: Access a one-stop source for enhancing your cybersecurity knowledge and skills.
. Add type for subcat in data.ts file.
. return the filtered items in UseDB.ts file

## Screenshots

Screenshot (195)

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@Gobinath-B 

Woah! Nicely done.

Just one more thing, add a description of cybersecurity. And the PR is good to go. I will check the resources and then if these are the valid ones, we will merge it quickly.

image

**Comment by Gobinath-B** [comment]
> @Gobinath-B
> 
> Woah! Nicely done.
> 
> Just one more thing, add a description of cybersecurity. And the PR is good to go. I will check the resources and then if these are the valid ones, we will merge it quickly.
> 
> image

@Anmol-Baranwal got it, i will work on this!

**Comment by CBID2** [comment]
Hey @Gobinath-B. Can you post a screenshot of the card having a description of cybersecurity? I can’t tap on i icon on my tablet

**Comment by Gobinath-B** [comment]
@Anmol-Baranwal  @CBID2 I  add a description for each subcategory of cyber security module and there is a bug #1837 in description card that mistakenly passes main category name instead of every sub category name. I resolved that bug too.

@CBID2 here is the Screenshot:

image

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
Remove these resources from respective subcategories:

image

image

A conference may not held up every year, and it is not suited for LinksHub.

**Comment by Gobinath-B** [comment]
@Anmol-Baranwal removed conference from resources. did you check this bug #1837 ? I resolved in this PR.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal removed conference from resources. did you check this bug #1837 ? I resolved in this PR.

Yeah, I was about to make the issue in a day or two.

Thanks for resolving it.

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Comment by Gobinath-B** [comment]
> 🚀 Looks good to me.

@CBID2 can you please review the code.

**Review by CBID2 — APPROVED** [review]
Well done @Gobinath-B

**Comment by Gobinath-B** [comment]
can you please add bug fixed label for this

**Comment by Anmol-Baranwal** [comment]
@Gobinath-B 
I just noticed.

Following the PR template is a must. It includes special words like 'fixes' or 'resolves' that connect your issue to the PR, as explained in the official docs.

If you don't link the issue correctly, even after the PR is merged, the issue might stay open, causing huge problems.

> You can see here. Corrected.
image

I'm doing it for you this time. Please ensure it next time.

Just a heads-up to help you link issue properly next time. Have a great day!

**Comment by Anmol-Baranwal** [comment]
> can you please add bug fixed label for this

How was this a bug?

**Comment by Gobinath-B** [comment]
#1837

**Comment by Anmol-Baranwal** [comment]
> #1837

Oh! You was talking about another issue. Thanks for pointing out.

Also, there is no bug fixed label😅

Wait, let me add it for you in the repo.

**Comment by Gobinath-B** [comment]
Thank you so much @Anmol-Baranwal . Happy to contribute with you.

**Pull request merged**
