### PR TITLE
fixed#247

### LINKED ISSUE #247: [BUG] Title header shifted below
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The title header in all section shifts below in the mobile view probably due to the addition of a new icon. I would like to work on this one 

### Screenshots

image
image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

Firefox, Chrome

### PR DESCRIPTION
**Pull request by pramodreddypandiri**
## Fixes Issue

Title header shifting down in mobile view has been fixed.
# Now
Screenshot 2023-02-25 at 7 36 32 PM
 # Before
image

### CODE REVIEW

**Comment by pramodreddypandiri** [comment]
Hey @rupali-codes, issue #247 has been fixed , please review

**Comment by pramodreddypandiri** [comment]
Hey @rupali-codes , Please review PR

**Comment by rupali-codes** [comment]
hi @pramodreddypandiri 
could you please resolve conflicts so i can see the preview. also we should decrease the font size for mobile devices a bit that would look much better and we can `truncate` if the text gets overflowed

**Comment by rupali-codes** [comment]
Hi Pradmod, why did you close the PR?

**Comment by pramodreddypandiri** [comment]
I did raise other PR. Please review it

**Pull request closed without merging**
