### PR TITLE
feat(frontend): #513 toggle sidebar menu

### LINKED ISSUE #513: [Feature] Toggle sidebar menu
### Description

Currently, user can open as many tabs as they want in the site, but since the sidebar is long, it causes accessibility issues. 

What we want to do is: 
Close the other opened tab when new tab is clicked OR keep a single tab opened at a time in the sidebar

### Screenshots

image

### Additional Information

This issue is a part of #409 issue

### PR DESCRIPTION
**Pull request by milan-lakhani**
## Fixes Issue
Closes #513 

## Changes proposed

- Now, the sidebar tabs behavior changed to "Only one tab open at a time".  
- Restructured the state management of open sidebar from individual component to the sidebarCategoryList component in order to close the other tabs.
- have handled the default open tab test case

## Screenshots

[Working screen capture](https://www.awesomescreenshot.com/video/17489435?key=b39540671563a23d53ea81a82afb36e2)

## Note to reviewers

I have restructured code in this way because I couldn't find any state management libs like redux. With redux, this could have been a bit easier and cleaner. But for now, according to me, this is the best approach without it. Still let me know if you have other ideas.

### CODE REVIEW

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hey @milan-lakhani! :) I'm not too well-versed on typescript, so I'm going to let @rupali-codes send her review and then I'll do another review.

**Review by rupali-codes — COMMENTED** [review]
looks great to me :)

**Comment by milan-lakhani** [comment]
@CBID2 I can see you have requested for changes. But, I am not able to see any comments. Am I missing something? Also it is open for review to me. Maybe was it supposed to be for @rupali-codes . Please let me know if you need any changes. Cheers!

**Comment by CBID2** [comment]
> @CBID2 I can see you have requested for changes. But, I am not able to see any comments. Am I missing something? Also it is open for review to me. Maybe was it supposed to be for @rupali-codes . Please let me know if you need any changes. Cheers!

Hey @milan-lakhani, check my comment to get context.:)

**Review by CBID2 — APPROVED** [review]
LGTM! 😊

**Comment by CBID2** [comment]
> @CBID2 I can see you have requested for changes. But, I am not able to see any comments. Am I missing something? Also it is open for review to me. Maybe was it supposed to be for @rupali-codes . Please let me know if you need any changes. Cheers!

Just approved it! :)

**Review by CBID2 — APPROVED** [review]
Merge time

**Comment by rupali-codes** [comment]
> @rupali-codes Hey, Thanks for that. I am interested in contributing to this project regularly. Let me know if you need me for anything specific. Or, I can always go through the Issues. Thanks!

Yes you can always go through issues :)

**Pull request merged**
