### PR TITLE
Add Trivy & Snyk

### LINKED ISSUE #2287: [Add] Trivy & Snyk
### Site URL

https://snyk.io & https://trivy.dev

### Description of the above provided site

I would like to add:
- _**[Snyk](https://snyk.io) `specializes in JavaScript security`**_
- [Trivy](https://trivy.dev) is a container security scanner designed specifically for `Docker images.`

### Category

cyber-security

### Sub Category

Web Security

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by JuanPabloDiaz**
## Fixes Issue

fixes #2287 

## Changes proposed

Add Trivy & Snyk to **cyber-security / Web Security** 

## Screenshots

image

## Note to reviewers

I only add those two but prettier indented the entire file.

```json
{
    "name": "Trivy",
    "description": "Trivy is the most popular open source security scanner, reliable, fast, and easy to use. It's a container security scanner designed specifically for Docker images.",
    "url": "https://trivy.dev",
    "category": "cyber-security",
    "subcategory": "web-security"
  },
  {
    "name": "Snyk",
    "description": "Snyk specializes in JavaScript security. It is a developer-first security solution that helps you use open source code and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.",
    "url": "https://snyk.io/",
    "category": "cyber-security",
    "subcategory": "web-security"
  }
```

### CODE REVIEW

**Review by rupali-codes — APPROVED** [review]
lgtm

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by CBID2** [comment]
Your turn @Anmol-Baranwal

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> @rupali-codes I think 1-2 reviews for contributions related to adding resources is more than enough.

**Pull request merged**
