### PR TITLE
Fix/theme transitions

### PR DESCRIPTION
**Pull request by allanlalangan**
## Changes proposed

Refactor Tailwind classes in GeneralLayout component, add transition classes
Add transition classes to LinkContainer component
Add transition classes to SideNavbar heading

## Screenshots

**Before**

https://user-images.githubusercontent.com/73400708/216802958-2ca6d667-177a-430a-a6e2-fc14ddd79d87.mov

**After**

https://user-images.githubusercontent.com/73400708/216802963-a6dceebb-8696-4759-980d-0fcf5eb15a21.mov

### CODE REVIEW

**Comment by rupali-codes** [comment]
@allanlalangan Thanks you rising PR, but please create a new [issue](https://github.com/rupali-codes/LinksHub/issues/new/choose) before rising PR. Also don't forget to take a look at our [contributing guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)

**Comment by allanlalangan** [comment]
> @allanlalangan Thanks you rising PR, but please create a new [issue](https://github.com/rupali-codes/LinksHub/issues/new/choose) before rising PR. Also don't forget to take a look at our [contributing guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)

Ah my apologies! I've added the issue and edited the PR comment.

**Comment by rupali-codes** [comment]
> > @allanlalangan Thanks you rising PR, but please create a new [issue](https://github.com/rupali-codes/LinksHub/issues/new/choose) before rising PR. Also don't forget to take a look at our [contributing guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
> 
> Ah my apologies! I've added the issue and edited the PR comment.

It's fine. Could you please resolve merge conflicts

**Comment by allanlalangan** [comment]
I'm going to close this PR. I forked the repo with all branches, then mistakenly created a new branch named dev. When I pushed my dev branch it seems to have included other commits from the original dev branch, which I assume is why I have merge conflits.

**Pull request closed without merging**
