### PR TITLE
Adding pagination feature

### LINKED ISSUE #1125: [Feature] Add Pagination to the Resources Cards
### Description

- Pagination could look better on the resources' cards.
- We could show no more than 9 cards on the page and load the others when user wants to switch it.
- Pagination could make it more professional and user friendly. 

### Screenshots

image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by CBID2**
## Issues

Closes #1125 

## Changes proposed
@chris-nowicki and I implemented code that adds page numbers to the cards, creating an easier navigation for users.

## Screenshots
pagination

## Note to reviewers
@rupali-codes and @Anmol-Baranwal, this is a better version of PR #1655.

### CODE REVIEW

**Comment by CBID2** [comment]
Hey @Anmol-Baranwal. Review this PR. Ignore the other ones. Same with you @rupali-codes

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
1. Whenever we move to a new category, it should reset to the initial page i.e. page 1.

The above change is necessary because of UX :)

Also, why did you close the other PRs? Was the conflict too much. I'm just asking.

> As mentioned, please attach a screenshot of both the variations (change white and purple on floating widget).

**Comment by CBID2** [comment]
> 1. Whenever we move to a new category, it should reset to the initial page i.e. page 1.
> 
> The above change is necessary because of UX :)
> 
> Also, why did you close the other PRs? Was the conflict too much. I'm just asking.
> 
> > As mentioned, please attach a screenshot of both the variations (change white and purple on floating widget).

Hey @Anmol-Baranwal. There were too many conflicts so I had to create a new PR.

**Comment by CBID2** [comment]
> 1. Whenever we move to a new category, it should reset to the initial page i.e. page 1.
> 
> The above change is necessary because of UX :)
> 
> Also, why did you close the other PRs? Was the conflict too much. I'm just asking.
> 
> > As mentioned, please attach a screenshot of both the variations (change white and purple on floating widget).

Hi @Anmol-Baranwal! :)  Here's the two options that @chris-nowicki and I came up with for the pagination colors. It's to make them stand out.
[option 1](https://github.com/rupali-codes/LinksHub/assets/105683440/6aadd63c-f011-414d-8dfe-7b45cca785fb)
option 2
Which do you like best?

**Comment by Anmol-Baranwal** [comment]
I think first one stands out much more, and second one just blends in.

It's up to you both, I just wanted to see the designs.

**Comment by CBID2** [comment]
> > 1. Whenever we move to a new category, it should reset to the initial page i.e. page 1.
> > 
> > The above change is necessary because of UX :)
> > Also, why did you close the other PRs? Was the conflict too much. I'm just asking.
> > > As mentioned, please attach a screenshot of both the variations (change white and purple on floating widget).
> 
> Hi @Anmol-Baranwal! :) Here's the two options that @chris-nowicki and I came up with for the pagination colors. It's to make them stand out.
> 
> ## Option # 1
> option 1
> 
> ## Option # 2
> option 2
> 
> Which do you like best?

**Comment by rupali-codes** [comment]
@CBID2 second one looks nice to me :)

**Comment by CBID2** [comment]
> @CBID2 second one looks nice to me :)

Thanks @rupali-codes, but we went with the first one. It makes the pagination easier to see

**Comment by rupali-codes** [comment]
> > @CBID2 second one looks nice to me :)
> 
> Thanks @rupali-codes, but we went with the first one. It makes the pagination easier to see

we aren't using pure white anywhere..

**Comment by Anmol-Baranwal** [comment]
> > > @CBID2 second one looks nice to me :)
> > 
> > 
> > Thanks @rupali-codes, but we went with the first one. It makes the pagination easier to see
> 
> we aren't using pure white anywhere..

In that case, we can use the white shade color that have been used everywhere. 

image

**Comment by CBID2** [comment]
> > > > @CBID2 second one looks nice to me :)
> 
> > > 
> 
> > > 
> 
> > > Thanks @rupali-codes, but we went with the first one. It makes the pagination easier to see
> 
> > 
> 
> > we aren't using pure white anywhere..
> 
> 
> 
> In that case, we can use the white shade color that have been used everywhere. 
> 
> 
> 
> image
> 
> 

Ahh ok

**Comment by chris-nowicki** [comment]
> > > > > @CBID2 second one looks nice to me :)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Thanks @rupali-codes, but we went with the first one. It makes the pagination easier to see
> > 
> > 
> > > 
> > 
> > 
> > > we aren't using pure white anywhere..
> > 
> > 
> > In that case, we can use the white shade color that have been used everywhere.
> > image
> 
> Ahh ok

Sorry for the delay in finishing this PR up! I thought I was going to be able to get to it today but alas my day job pulled me away more than I thought it would.  I'll get to this over the weekend and hopefully submit it sometime tomorrow for final approval with y'all :).

**Comment by Anmol-Baranwal** [comment]
> Sorry for the delay in finishing this PR up! I thought I was going to be able to get to it today but alas my day job pulled me away more than I thought it would. I'll get to this over the weekend and hopefully submit it sometime tomorrow for final approval with y'all :).

No worries, feel free to do this whenever you have time. Open Source in your free time.

**Comment by rahulpandey70** [comment]
@CBID2 @rupali-codes Why pagination? why not infinite scrolling?

**Comment by CBID2** [comment]
> @CBID2 @rupali-codes Why pagination? why not infinite scrolling?

Good question @rahulpandey70! We decided to go with pagination for the following reasons:

1. Risks accessibility violations
2. We want users who know what sources they want to easily find them, and infinite scrolling would most likely make it difficult.
3. It can cause viewers to lose track of the previous page(s) they were on, which is frustrating.

**Comment by Anmol-Baranwal** [comment]
> > @CBID2 @rupali-codes Why pagination? why not infinite scrolling?
> 
> Good question @rahulpandey70! We decided to go with pagination for the following reasons:
> 
> 1. There's too many accessibility violations. While there is accessible versions out there, the endless scroll effect makes it difficult for screen readers to see a website's parts (e.g. our footer).
> 2. We want users who know what sources they want to easily find them, and infinite scrolling would most likely make it difficult.
> 3. It can cause viewers to lose track of the previous page(s) they were on, which is frustrating.

Totally agree 💯

**Comment by Anmol-Baranwal** [comment]
I have resolved the conflicts. Still deployment has failed.

**Comment by rupali-codes** [comment]
@CBID2 

image

**Comment by CBID2** [comment]
> @CBID2 
> 
> 
> 
> image
> 
> 

How should I fix that @rupali-codes?

**Comment by chris-nowicki** [comment]
> > @CBID2
> > image
> 
> How should I fix that @rupali-codes?

@CBID2 There was duplicate code in there ... basically the <Footer> first section was there twice.  If you remove it then it builds correctly.  I just pushed a new version to your branch @CBID2 :)

**Comment by CBID2** [comment]
We're ready to go @Anmol-Baranwal and @rupali-codes! :)

**Comment by Anmol-Baranwal** [comment]
> We're ready to go @Anmol-Baranwal and @rupali-codes! :)

I will review it tomorrow evening.

**Comment by Anmol-Baranwal** [comment]
@CBID2 
You can see the bug here:
https://jam.dev/c/0109513b-4bef-4731-bca1-8297ff9a2c3a

I will review this after this is fixed.

image

**Comment by chris-nowicki** [comment]
I’ll work on this today and let you know when it is fixed :).  I totally forgot about that portion of the code!  Thanks for the reminder :)

**Comment by chris-nowicki** [comment]
> @CBID2 You can see the bug here: https://jam.dev/c/0109513b-4bef-4731-bca1-8297ff9a2c3a
> 
> I will review this after this is fixed.
> 
> image

@CBID2 @Anmol-Baranwal - I think I was able to fix it.  Can you verify?

**Comment by CBID2** [comment]
> https://jam.dev/c/0109513b-4bef-4731-bca1-8297ff9a2c3a

It works on my end @chris-nowicki! :)

**Comment by Anmol-Baranwal** [comment]
For me, it's still there at least in the latest deployment.

**Comment by chris-nowicki** [comment]
> For me, it's still there at least in the latest deployment.

Bummer! Where are you seeing it?  Can you give a screen shot so I can try and replicate.

**Comment by CBID2** [comment]
> For me, it's still there at least in the latest deployment.

Did you refresh it @Anmol-Baranwal?

**Comment by Anmol-Baranwal** [comment]
> Contributor

In frontend category, you can go to Design Inspirations subcategory, then click page number 2 and then go to Animations subcategory. See if the page number changes.

**Comment by CBID2** [comment]
> > Contributor
> 
> In frontend category, you can go to Design Inspirations subcategory, then click page number 2 and then go to Animations subcategory. See if the page number changes.
> 
> Yeah, I checked the code too, it should work but why is it with me.

The numbers change on both on my end @Anmol-Baranwal. Maybe you need to refresh your browser?

**Comment by Anmol-Baranwal** [comment]
It should change without refreshing the browser.

**Comment by CBID2** [comment]
> > @chris-nowicki I am saying about subcategory not category.
> > Yeah!
> 
> I am thinking it has something to do with State.
> 
> I am wondering if I should add the variables used in usePagination() to the Global Context?
> 
> @CBID2 - If you select Design Insipiration, go to page 2, and then select Animations you will see pagination stays on page 2 and doesn't reset to page 1.

Ohh I see @chris-nowicki. Maybe adding variables could work :)

**Comment by chris-nowicki** [comment]
@CBID2 @Anmol-Baranwal I think I fixed it!

I figured that anytime the totalNumberOfCards change is when the subcategory/category changes.  So when that happens the handlePageChange function should run and set the page back to 1.  I created a useEffect in the usePagination.tsx hook:

```js
  useEffect(() => {
    handlePageChange(1)
  }, [totalNumberOfCards])
```

I tested it out to see if it works and I think we are good to go :).

**Comment by CBID2** [comment]
Great @chris-nowicki. We're ready @rupali-codes! :)

**Review by Anmol-Baranwal — APPROVED** [review]
@chris-nowicki @CBID2 
Thank you very much. You have truly put in a lot of effort for this. I genuinely appreciate your contribution.

**Comment by CBID2** [comment]
Woohoo! We did it @chris-nowicki! 😊

**Comment by chris-nowicki** [comment]
> Woohoo! We did it @chris-nowicki! 😊

Woohoo! This was so fun to work on with y'all!

**Pull request merged**
