### PR TITLE
feat: Add a New Card in DevTools category

### PR DESCRIPTION
**Pull request by joyfinder**
## Changes proposed

- A new source of dev tools, HackMD, is added, and recommended. It is not only user-friendly in UI perspective, but also convenient for developers to organize notes etc.

## Screenshots

Screenshot 2024-10-07 at 9 59 15 PM

### CODE REVIEW

**Review by rupali-codes — APPROVED** [review]
lgtm

**Comment by rupali-codes** [comment]
@joyfinder please resolve the merge conflicts

**Comment by joyfinder** [comment]
> @joyfinder please resolve the merge conflicts

Yes, already fixed it. 

Thank you for letting me know,.

**Review by rupali-codes — COMMENTED** [review]
hey @joyfinder, you have removed the previous resource, you don't need to remove it, just keep of them

**Comment by joyfinder** [comment]
> hey @joyfinder, you have removed the previous resource, you don't need to remove it, just keep of them

So should I remove the previous commit instead? 

And would you clarify what's the main issue of branch conflict if the added content is fine? 

Thank you.

**Comment by rupali-codes** [comment]
> > hey @joyfinder, you have removed the previous resource, you don't need to remove it, just keep of them
> 
> So should I remove the previous commit instead?
> 
> And would you clarify what's the main issue of branch conflict if the added content is fine?
> 
> Thank you.

sure, the current commit will remove the previous resource (Uptime Kuma) this one

**Comment by joyfinder** [comment]
@rupali-codes 

Would you check it again whether it meets your requirement? 

Besides, I also opened the issue, and please assign it to me. 

Thank you.

**Review by rupali-codes — COMMENTED** [review]
@joyfinder still, it hasn't been added there

**Comment by joyfinder** [comment]
> @joyfinder still, it hasn't been added there

Yes, I figured out what you meant, and checked my previous commit again. 

Found out that I removed one's work before. 

Re-fixed it back. 

Thank you for the patience.

**Review by rupali-codes — APPROVED** [review]
Thank you @joyfinder, looks good to me

**Pull request merged**
