### PR TITLE
chore: Make navbar close on nav-link click or body click

### LINKED ISSUE #73: [OTHER] User Experience Improvement
### What would you like to share or ask?

I would like to ask for the navbar to be made to close when a user clicks outside of the navbar, or on a link in the navbar

### Additional information

I will love to add this feature as my first open source contribution

### PR DESCRIPTION
**Pull request by Leeyah-123**
Closes #73

## Changes proposed

Made the navigation bar to close on the click of a link or on click outside the navbar to improve user experience

### CODE REVIEW

**Comment by rupali-codes** [comment]
@Leeyah-123 it looks good to me, but it's not closing navbar when clicked on it's close icon, it's only closing when clicked outside. Could you fixed that too?

**Comment by Leeyah-123** [comment]
Okay, I didn't notice that
I'll fix it too

**Comment by Leeyah-123** [comment]
@rupali-codes Fixed that bug, it works now.

**Review by rupali-codes — CHANGES_REQUESTED** [review]
@Leeyah-123 thank you for the changes, just one other thing, it's showing github icon at two places, could you remove from topar and just leave in the heading just like we currently have in our site
this PR:
image

https://linkshub.vercel.app
image

**Comment by Leeyah-123** [comment]
Alright I'll do that now.

**Review by rupali-codes — APPROVED** [review]
LGTM. 
Just wanna know why we're replacing all double inverted commas("") with single inverted commas ('') is there any specific reason?

**Comment by Leeyah-123** [comment]
No reason, My VSCode's prettier automatically did that.

**Review by rupali-codes — COMMENTED** [review]
thank you  so much Aliyah, Looks perfect now!

**Pull request merged**
