### PR TITLE
feat: This commit adds the new subcategory js-chart-libraries to the …

### PR DESCRIPTION
**Pull request by Wambaforestin**
Adding a new **subcategory** ( _js-chart-libraries_ ) to the frontend category (#2278).
 
**Proposed changes**
 
Added the js-chart-libraries.json file, which contains the name, URL, category, and subcategory of each link.

Added it's into the index.ts file, as mentioned in the contribution.md file.

Added the name of the category to the database in the data.ts file

Added its description in the components/TopBar/CategoryDescriptions.ts file.

### CODE REVIEW

**Comment by Wambaforestin** [comment]
Hi @Anmol-Baranwal, This PR is ready for review

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please deploy.

**Comment by Wambaforestin** [comment]
Thank you to @Anmol-Baranwal  for reviewing and merging my pull request! I appreciate the collaboration and opportunity to contribute to the project.

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> @rupali-codes The category description isn't showing, but I believe that is being handled in other PR due to `-`.

**Comment by Anmol-Baranwal** [comment]
@Wambaforestin 
Why did you close the PR?

**Comment by Wambaforestin** [comment]
@Anmol-Baranwal I apologies for any confusion. I mistakenly thought that the branch associated with the PR had already been merged into the main branch.

**Review by rupali-codes — APPROVED** [review]
LGTM

**Pull request merged**
