### PR TITLE
chore: Add Virtual Coffee podcast link (#2479)

### LINKED ISSUE #2479: [Add] Virtual Coffee
### Site URL

virtualcoffee.io/podcast

### Description of the above provided site

[Virtual Coffee](https://virtualcoffee.io/) Virtual Coffee is an intimate community for developers at all stages of the journey. It is a place to ask questions, share knowledge, and build friendships.

### Category

Other

### Sub Category

podcasts

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by ryo-kozin**
## Fixes Issue

Closes #2479

## Changes proposed

- Added "Virtual Coffee" podcast link to `other/podcasts` category.

### [Before Changes]
Screenshot 2024-08-30 at 17 24 11

### [After Changes]
Screenshot 2024-08-30 at 17 22 27

## Note to reviewers

Please review the added link and ensure it follows the project's contribution guidelines.

### CODE REVIEW

**Comment by rupali-codes** [comment]
@ryo-kozin please resolve merge conflicts

**Comment by ryo-kozin** [comment]
Thank you for the heads up, @rupali-codes.

I have resolved the merge conflicts by merging the upstream/main branch into my working branch. Please review the changes when you have a moment.

If there are any additional adjustments needed, please let me know!

Thank you!

**Review by rupali-codes — APPROVED** [review]

**Comment by rupali-codes** [comment]
@ryo-kozin please resolve the merge conflicts

**Review by mohab-kamle — APPROVED** [review]

**Comment by ryo-kozin** [comment]
@rupali-codes 
Thanks again! I've resolved the conflict!
Screenshot 2024-09-14 at 21 55 22

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
