### PR TITLE
feat: Added a hover effect to the fork button

### LINKED ISSUE #1028: [Feature] Missing hover effect (Fork button)
### Description

Hi! I noticed that the fork button does not have a hover effect.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by zvolcsey**
@CBID2 @rupali-codes @ujjawaltyagii Hi! I noticed that the fork button does not have a hover effect, so I added one.

## Fixes Issue

Closes #1028 

## Changes proposed

I added a hover effect to the fork button. (light and dark mode)

### CODE REVIEW

**Review by CBID2 — DISMISSED** [review]
LGTM!

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Hey, thanks. Can you please a little transition just like the social icons?

**Comment by zvolcsey** [comment]
@rupali-codes @CBID2 Hi! Thanks for the feedback! I added transition for the fork button.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
