### PR TITLE
Fix:Text overflowing in top bar

### LINKED ISSUE #1218: [Bug] Text overlap in search result.
### Site URL

https://www.linkshub.dev/search?query=front+end+video+with+css+and+javascript

### Issues:
if we search something with long String like this "_front end video with css and javascript"_, it overlaps to all other elements.
 ### Suggestions 

1. if any searches doesn't meet from database, it should write only **no data found**.
2. another is remove that line cause it doesn't looks good when we search like _frame_ . Text appears on screen `SEARCH?QUERY=FRAME` . it seems weird on screen.
 
### Screenshot:
image
image

### Category

Frontend

### Sub Category

Search Result

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Semako123**
## Fixes Issue
Closes #1218

## Changes proposed
I made the text scroll in the container rather than overflowing on the other content of the top bar

### CODE REVIEW

**Comment by CBID2** [comment]
Can you add screenshot or screen recording of the changes you're proposing @Semako123? It'll give me an idea of what to look for.

**Comment by rupali-codes** [comment]
@Semako123 can u please add sceenshorts of your changes?

**Comment by CBID2** [comment]
Also solve the merge conflicts @Semako123

**Comment by rupali-codes** [comment]
@Semako123 any updates?

**Comment by Semako123** [comment]
https://github.com/rupali-codes/LinksHub/assets/105620665/09e1d0c2-201e-40ed-967d-680f31c86628

This is a preview of the change I made
Sorry for the delay.

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
This is not needed anymore. There was a PR that helped in showing the query: `Results Found` & `Results Not Found`

image

**Pull request closed without merging**
