### PR TITLE
feat: implement adaptive day/night browser bar theme 🚀🔥 

### LINKED ISSUE #1506: feat: Implement Browser Bar Theme Feature for Enhanced PWA Experience 🚀🔥
## Description
- I'm excited to announce a new feature for LinksHub - the Browser Bar Theme! 
- This addition aims to further enhance the Progressive Web App (PWA) experience by dynamically adapting the browser's address bar color to match the selected theme (dark or light). 
- The bar color can be switched dynamically during Dark/Light Toggling, Which looks immersive for Mobile Devices.

## Advantages of Browser Bar Theme:
1. Immersive User Experience: With the Browser Bar Theme, users will enjoy a more immersive and visually appealing experience when using LinksHub as a PWA. The seamless transition between the app's theme and the browser's address bar creates a cohesive and integrated user interface.

2. Consistency Across Platforms: The Browser Bar Theme ensures consistency across different devices and platforms. Whether users access LinksHub through their desktop browser or as an installed PWA on their mobile devices, the browser bar will adapt to match the selected theme.

3. Aesthetically Pleasing: The dynamic change in the browser's address bar color based on the chosen theme adds a touch of elegance to LinksHub. It elevates the overall design and visual aesthetics of the app, leaving a positive impression on users.

## Browser Bar Theme Feature & PWAs:
- Progressive Web Apps (PWAs) are designed to deliver a native app-like experience on the web. By incorporating the Browser Bar Theme feature, LinksHub aligns with the core principles of PWAs, creating a smoother and more enjoyable user journey. When users install LinksHub as a PWA on their devices, the Browser Bar Theme adds an extra layer of professionalism and authenticity to the application.

- The implementation of Dark/Light Adaptable Browser Bar Theme requires careful consideration of design and user experience. Our development team will work diligently to ensure compatibility across various browsers and devices, providing a consistent and delightful experience for all LinksHub users.

## Example Screenshots
image

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Fixes Issue

Close #1506 

## Description

- In this pull request, we've added an exciting enhancement to the LinksHub user experience. Recognizing the significance of immersive user interactions, especially within the context of Progressive Web Apps (PWAs), we've integrated a dynamic browser bar theme feature.

## Changes introduced

1. **Dynamic Browser Bar Color:** Depending on the selected theme (dark or light), the browser's address bar will adapt its color accordingly, providing a seamless visual transition and consistency.

2. **PWA Compatibility:** This feature is fully compatible with the PWA version of LinksHub, ensuring that users who've installed LinksHub on their devices get a consistent and immersive experience.

## Advantages

- **Enhanced User Experience:** The adaptation of the browser bar color according to the app theme offers users a unified and more engaging visual experience.
  
- **Consistency:** Whether accessing LinksHub from a desktop browser or as a PWA on mobile, users will experience a harmonious UI.

- **Aesthetic Appeal:** This subtle design change contributes significantly to the overall aesthetics of the platform, making the app not just functional, but visually pleasing.

## Impact on PWAs

- PWAs are all about delivering an app-like experience on the web. 
- This browser bar theme feature further bridges the gap between traditional web apps and native mobile apps, ensuring that our users get the best of both worlds. 

- This PR is a testament to our commitment to continuously improve and adapt to modern design principles, ensuring that LinksHub remains at the forefront of usability and design. We believe these changes will further solidify LinksHub's position as a leading platform in its domain.

## Screenshots (Mobile)

|LIGHT MODE|DARK MODE|
|:--:|:--:|
| image | Capture+_2023-08-10-19-01-18|

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Capture+_2023-08-10-18-51-24
Capture+_2023-08-10-18-50-53

**Comment by 0xabdulkhalid** [comment]
Capture+_2023-08-10-19-01-18

**Comment by 0xabdulkhalid** [comment]
@rupali-codes, @CBID2, @k-deepak04 👋🏻 

Please make sure to review this PR as soon as possible, Thank You!

**Comment by 0xabdulkhalid** [comment]
|LIGHT MODE|DARK MODE|
|:--:|:--:|
| image | Capture+_2023-08-10-19-01-18|

**Comment by 0xabdulkhalid** [comment]
You can test this deployment on your Mobile Chrome Browser, You must want to enable light theme for it.

Because using Dark theme on Chrome will enforce and overwrite site's theme.

**Comment by 0xabdulkhalid** [comment]
@rupali-codes, @CBID2, @k-deepak04 👋🏻 

Please make sure to review this PR as soon as possible, Thank You!

**Comment by CBID2** [comment]
Can you show a screenshot of this @0xabdulkhalid?

**Comment by 0xabdulkhalid** [comment]
@CBID2 PR Description has been updated now, You can check that out!

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by 0xabdulkhalid** [comment]
@rupali-codes your help is indeed now, Please merge this within 11.59 PM

**Comment by rupali-codes** [comment]
@CBID2 why is it label 3?

**Review by rupali-codes — APPROVED** [review]
looks awesome, thanks !

**Pull request merged**
