### PR TITLE
added new programs under Community sub-category

### LINKED ISSUE #1010: [ADD] add new section:  Student Partner program
### Category Name

OTHERS

### Subcategory Name

Student Partner program

### Additional Context

I want to add a new section under the 'OTHERS" Category, that contains all the  Campus Ambassador programs. that are initiatives taken by some big tech companies like Amazon, Google, Flipkart, GFG, Microsoft and many more.

**- Some programs are:**

- GitHub Campus Expert
- Microsoft Learn Student Ambassador program
- Developer Student Club
- and many more.

Please assign me under the gssoc23 label.

**Thank you
GSSOC23 Contributor**

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by gulshanjakhon**
Fixes #1010

## Changes proposed
Added 3 new Student Ambassador Programs under communities sub-section

### CODE REVIEW

**Comment by gulshanjakhon** [comment]
Please assign gssoc23 label 

Thank you
Gssoc contributor

**Review by rupali-codes — APPROVED** [review]
lgtm, thanks

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Comment by CBID2** [comment]
> lgtm, thanks

We're going to need another approval from you @rupali-codes.

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
