### PR TITLE
FIX: Card not displaying 

### LINKED ISSUE #1652: [BUG] Cards are not displaying in ui-generator,Next js , Three js Sub categories
### Description

JSON File have data but cards are not displaying.
For example : next.json file:-
[
    {
      "name": "NextJS",
      "description": "Used by some of the world's largest companies, Next.js enables you to create full-stack Web applications by extending the latest React features and integrating powerful Rust-based JavaScript tooling for the fastest builds.",
      "url": "https://nextjs.org/",
      "category": "frontend",
      "subcategory": "next-js"
    }
]

### Screenshots

Capture

### Any additional information?

I am willing to work on this issue.

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by pankajdharmik4**
## Fixes Issue
closes #1652

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @pankajdharmik4! :) Can you fill out the "Changes Proposed" and "Screenshot" sections please? It would help us gain a better understanding of your solution.

**Comment by pankajdharmik4** [comment]
**Changes Purposes:-** 
In data.js file url should be same as the  "subcategory" field in the json files.

changes



**Errors were (Even after having data they are not displaying in this section)  :-** 
Capture1 1
Capture2 1
Capture3 1

**Resolve ;-**
Capture1 2
Capture2 2
Capture3 2

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> Thanks for fixing this :)

**Pull request merged**
