### PR TITLE
chore: Added Link to Framer motion in category: Frontend, subcategory…

### LINKED ISSUE #71: Add Framer Motion
### URL

https://www.framer.com/motion

### Description of the above provided site

Framer Motion is a production-ready motion library for React from Framer (https://www.framer.com/).

It's simple yet powerful, allowing you to express complex user interactions with robust, semantic markup.

### Category

Frontend

### Sub Category

animations

### PR DESCRIPTION
**Pull request by Leeyah-123**
Closes #71

## Changes proposed

Added Link to Framer motion under Frontend category, animations subcategory

### CODE REVIEW

**Comment by rupali-codes** [comment]
@Leeyah-123 please resolve conflicts, thank you :)

**Comment by rupali-codes** [comment]
@Leeyah-123 thank you, could you please fix ids too?

**Comment by Leeyah-123** [comment]
Sorry for that, completely slipped my mind.
Fixed now.

**Comment by rupali-codes** [comment]
Thank you @Leeyah-123 for the contributions

**Pull request merged**
