### PR TITLE
feat: adding chart

### LINKED ISSUE #1612: [DOCS] <adding number chart>
### Issue Description

I was thinking of implementing a chart that describes the level system. It’ll give contributors an idea of how to contribute to LinksHub, especially if they struggle with proposing ideas. 

### Additional Context

_No response_

### Screenshots or Examples (if applicable)

_No response_

### Proposed Solution (optional)

_No response_

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by CBID2**
## Fixes Issue

Closes #1612 
## Changes proposed

This PR adds a number chart and a few revisions. This addition would help new contributors, especially those who are new to open source and tech, have an idea of how they can contribute to LinksHub's project.  
## Screenshots
chart

## Note to reviewers
I need help with hyperlinking the number chart in line 141.

### CODE REVIEW

**Review by Anmol-Baranwal — COMMENTED** [review]
Points system is not needed unless we plan to use these points to make a leaderboard or something. Since, GSSoC is over.

**Comment by CBID2** [comment]
> Points system is not needed unless we plan to use these points to make a leaderboard or something. Since, GSSoC is over.

Hey @Anmol-Baranwal. I was heavily inspired by what EddieHub did with them. It's for contributors to determine what they feel they can contribute to at the moment and to grow from there

**Comment by Anmol-Baranwal** [comment]
> > Points system is not needed unless we plan to use these points to make a leaderboard or something. Since, GSSoC is over.
> 
> Hey @Anmol-Baranwal. I was heavily inspired by what EddieHub did with them. It's for contributors to determine what they feel they can contribute to at the moment and to grow from there

Yeah, I have seen them implement this. Just discuss with @rupali-codes

**Comment by CBID2** [comment]
@rupali-codes, can you review this?

**Review by rupali-codes — COMMENTED** [review]
it looks fine tho, but can you add the labels we are using and place the table at the end. Also, i'd want to rename this variables like, `level 1` -> `priority: low` `level 2` -> `priority: medium` `level 3` -> `priority: high`

**Comment by CBID2** [comment]
> it looks fine tho, but can you add the labels we are using and place the table at the end. Also, i'd want to rename this variables like, `level 1` -> `priority: low` `level 2` -> `priority: medium` `level 3` -> `priority: high`

Can you put your suggestions as in-line comments @rupali-codes? I'm having trouble visualizing your ideas.

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Just replace the variables

image

From `level 1` to `priority low`, for other two as well.

**Comment by CBID2** [comment]
> @CBID2 Just replace the variables
> 
> image
> 
> From `level 1` to `priority low`, for other two as well.
> 
> image

Thanks for your advice @Anmol-Baranwal. Btw, I made a PR for #1464. Check out #1650

**Review by rupali-codes — APPROVED** [review]
sorry for being late, lgtm

**Comment by CBID2** [comment]
Now it's your turn @Anmol-Baranwal

**Comment by CBID2** [comment]
> sorry for being late, lgtm

It's ok @rupali-codes. What matters is that you're well! 😊

**Pull request merged**
