### PR TITLE
Add godly website

### LINKED ISSUE #87: [Add] godly.website
### URL

https://godly.website

### Description of the above provided site

A curated collection of good web design from all over the web

### Category

Frontend

### Sub Category

"design inspiration"

### PR DESCRIPTION
**Pull request by jackz070**
Closes #87 

Fixed my commit message to follow Conventional Commits website as suggested. The problem with subcategory type typo ("design inspirtion") is still there, my commit triggers TS warning on this, fix is needed in types/index.ts SubCategory type.

### CODE REVIEW

**Comment by rupali-codes** [comment]
could you please resolve merge conflicts, aslo update your code with main branch, it will fix this deployment issue. Thank you

**Comment by rupali-codes** [comment]
@jackz070 are you still working on it?

**Comment by jackz070** [comment]
@rupali-codes Yeah, I will get back to it!

**Comment by rupali-codes** [comment]
@jackz070 please resolve merge conflicts

**Comment by jackz070** [comment]
I'm closing this PR as this addition was added in PR #94, in which I mistakenly added two commits including this one and caused the merge conflict. Sorry for this and the time it took me to check it out.

**Comment by rupali-codes** [comment]
no issues :)

**Pull request closed without merging**
