### PR TITLE
added twitter link

### LINKED ISSUE #210: [CHORE] add twitter link in README and website
### What would you like to share or ask?

I have created a twitter account for LinksHub so people can tag us and share their experience. 

Add this link [https://twitter.com/the_linkshub](https://twitter.com/the_linkshub) in the README.md file as well in the site with twitter icon (You can also give us a follow ;)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yashnirmal**
## Fixes Issue

Closes #210 

## Changes proposed

added twitter link to website and readme

### CODE REVIEW

**Comment by yashnirmal** [comment]
@rupali-codes I have closed the previous PR and created a new one,as you said

**Comment by rupali-codes** [comment]
@yashnirmal you have added package-lock.json again 😓. Are you usin `git add .` ?

**Comment by priyankarpal** [comment]
This branch has also conflicts please resolve them.

**Comment by yashnirmal** [comment]
I don't know how it keeps getting added, even though it's present in my workspace(see in the screenshot). Can you delete it from your side?
Screenshot from 2023-02-22 13-55-34

**Comment by rupali-codes** [comment]
@yashnirmal i can not delete this. 
Here's what u can possibly do: 
1. in your main run `git pull upstream main`
2. from main branch, create a new branch with your name
3. add files one by one (please do NOT run `git add .`)
   run this command to add your files (you can also run this multiple times to add the files)
   `git add <file_name>` 
4. commit your changes
5. push the code to your branch
   `git push origin <your_branch_name>`

**Pull request closed without merging**
