### PR TITLE
sort side navbar

### LINKED ISSUE #106: [CHORE] sort side navbar list
### What would you like to share or ask?

Sidebar is not sorted as of yet, it would be nice if we will display this in Alphabetical ascending order.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by JoePorterDev**
Closes #106

### CODE REVIEW

**Comment by JoePorterDev** [comment]
@rupali-codes The deployment test has failed. I tried to login to Vercel to inspect it but it's throwing an error 'account not found'. Should I concerned about this?

**Comment by rupali-codes** [comment]
Hi @JoePorterDev, it's failing because you made some uncertain changes in type.ts, please don't change SubCategory, it will break the whole code.

**Comment by rupali-codes** [comment]
Hi, please resolve merge conflicts

**Comment by rupali-codes** [comment]
Hi, are you still working on it?

**Comment by rupali-codes** [comment]
@JoePorterDev any updates?

**Pull request closed without merging**
