### PR TITLE
Mobbin

### LINKED ISSUE #400: [Add] Mobbin
### URL

https://mobbin.com/

### Description of the above provided site

Mobbin is a hand-picked collection of latest design patterns from mobile apps that reflect the best in design.

### Category

Frontend

### Sub Category

design inspiration

### PR DESCRIPTION
**Pull request by parma1111**
## Fixes Issue

Closes #400 

## Changes proposed

mobbin gives more specific designs

## Screenshots

Screenshot (785)

## Note to reviewers

Any kind of feedback would be appreciated

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
Is it only for mobile, or we can use it in web also?

**Comment by parma1111** [comment]
> Is it only for mobile, or we can use it in web also?

It can be used in web also

**Comment by parma1111** [comment]
> Well done @parma111! :) It just needs one more edit and your PR is good to go! :)

now review the pr

**Comment by rupali-codes** [comment]
Thank you Chrissy

**Pull request merged**
