### PR TITLE
added opensource tutorial by freecodecamp

### LINKED ISSUE #1721: [Add] <write what you want to add>
### Site URL

https://www.youtube.com/watch?v=yzeVMecydCE&t=1792s&ab_channel=freeCodeCamp.org

### Description of the above provided site

Learn why and how to contribute to open source software. You will learn about how to find projects to contribute to, how to make issues and PRs, how to make money from open source, and more.

### Category

Resources

### Sub Category

video link

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by dfordp**
## Fixes Issue

Close #1721 

## Changes proposed

- Added FreeCodeCamp's Complete Guide to Open Source - How to Contribute Video to Resources

### CODE REVIEW

**Comment by CBID2** [comment]
@Anmol-Baranwal, can you check to see if the issue for this PR has been approved?

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Not assigned!

How about, we add the message here, for assigned part.

> image
image

what do you say?

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Should we add a workflow, to close PRs whose issues is not assigned?

And the bot will leave a message.

**Comment by CBID2** [comment]
> @CBID2 
> 
> Not assigned!
> 
> 
> 
> How about, we add the message here, for assigned part.
> 
> 
> 
> > image
> 
> image
> 
> 
> 
> what do you say?

I like that @Anmol-Baranwal. Raise that as an issue and I'll assign it to you.

**Comment by CBID2** [comment]
> @CBID2 
> 
> Should we add a workflow, to close PRs whose issues is not assigned?
> 
> 
> 
> And the bot will leave a message.

Definitely @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
@dfordp 
Please read contributing guidelines, and let us assign you the issue first.

You can read `contributing.md` and readme.md to see how to do these things.

If you have any doubt, let us know.

**Comment by dfordp** [comment]
this is my first time commiting actually sorry about any issue I caused :)

**Pull request closed without merging**
