### PR TITLE
added LinksHub GIF

### LINKED ISSUE #152: [CHORE] add LinksHub gif in README.md
### What would you like to share or ask?

Having a gif in README.md file which describes the functionality as well as how to use the site in a proper manner, leads to a great user experience. 

#### Specific requirements
* Add GIF which includes
 * Use of searchbar
 * How to open links (Visit Site buttons)
 * Changing theme

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by PiseAtharva**
## Fixes Issue

Closes #152 

## Changes proposed

* primarily includes a gif showcasing Linkshub site in action, few links related to Front End, search bar and the Theme toggle effect

## Screenshots
Adding the [Branch Link](https://github.com/PiseAtharva/LinksHub/tree/feat/add-LinksHub-GIF) for Better Clarity
image

### CODE REVIEW

**Comment by rupali-codes** [comment]
@PiseAtharva it looks blurred...

**Comment by PiseAtharva** [comment]
> @PiseAtharva it looks blurred...
yeah that's right, i will try to tackle this again today

**Comment by PiseAtharva** [comment]
Hi Rupali, i believe I cant improve the quality for the GIF, primarily cause of the compression and the duration its going for. I guess i can take on some other issue in future

**Comment by rupali-codes** [comment]
> Hi Rupali, i believe I cant improve the quality for the GIF, primarily cause of the compression and the duration its going for. I guess someone else can solve this issue in much better way

Ahh, okay thanks for your efforts Atharva. Appreciate it

**Pull request closed without merging**
