### PR TITLE
feat: add official docs of Laravel ✨

### LINKED ISSUE #1453: [Add] Add Official Docs for Laravel
### Site URL

https://laravel.com/

### Description of the above provided site

Laravel is a web application framework with expressive, elegant syntax. We’ve already laid the foundation — freeing you to create without sweating the small things.

### Category

Backend

### Sub Category

official backend 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Fixes Issue

Closes #1453

## Changes proposed

Add `JSON `data about `Laravel `

## Screenshots

image

## Note to reviewers

**kindly Review it And merge it happy hacking :)**

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by k-deepak04 — APPROVED** [review]

**Comment by k-deepak04** [comment]
@Nishitbaria please resolve the conflicts

**Review by k-deepak04 — APPROVED** [review]
LGTM!

**Review by CBID2 — APPROVED** [review]
LGTM

**Pull request merged**
