### PR TITLE
chore: added smooth transition for sidebar accordion

### LINKED ISSUE #596: [Style] Smooth transition for the sidebar accordion
### What would you like to share or ask?

The sidebar accordion on LinksHub kind of feels too janky on opening. So some ease-in, ease-out transition should be used for the accordion.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by bose-aritra2003**
## Fixes Issue

Closes #596 #747

## Changes proposed

I have added a smooth transition for the opening and closing of the accordion in the sidebar.

## Screenshots

https://github.com/rupali-codes/LinksHub/assets/77151837/fe6aa947-9f6f-47a9-ba32-0750e55607ff

## Note to reviewers

For the file where I did my changes, there is an "isOpen" prop that is no more needed. However, I did not remove it. And honestly speaking, this seemed a bit more than just a level 1 issue 😅

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks ok to me.

**Review by ujjawaltyagii — APPROVED** [review]
Looks fine to me !

**Review by rupali-codes — COMMENTED** [review]
it's actually showing a scrollbar at starting, then it gets disappeared, could you fix that?

**Comment by bose-aritra2003** [comment]
@rupali-codes Could you please elaborate the issue? Because I didn't notice any such thing when running on my machine.

**Comment by rupali-codes** [comment]
@bose-aritra2003 checkout [this](https://www.loom.com/share/f9e19f341598474fa096d9af087386e1)

**Comment by bose-aritra2003** [comment]
@rupali-codes @CBID2 I think this is related to the Operating System and not to the browser because I ran on both Chrome and Safari and did not notice that issue. I am currently on macOS 13.0.1. So could anyone please help me figure it out because I don't have access to any other operating system at this moment?

**Comment by rupali-codes** [comment]
> @rupali-codes @CBID2 I think this is related to the Operating System and not to the browser because I ran on both Chrome and Safari and did not notice that issue. I am currently on macOS 13.0.1. So could anyone please help me figure it out because I don't have access to any other operating system at this moment?

I'm experiencing this in chrome, brave and edge. What is your screen resolution?

**Comment by bose-aritra2003** [comment]
> > @rupali-codes @CBID2 I think this is related to the Operating System and not to the browser because I ran on both Chrome and Safari and did not notice that issue. I am currently on macOS 13.0.1. So could anyone please help me figure it out because I don't have access to any other operating system at this moment?
> 
> I'm experiencing this in chrome, brave and edge. What is your screen resolution?

@rupali-codes My screen resolution is 2560 × 1600

**Comment by rupali-codes** [comment]
> > > @rupali-codes @CBID2 I think this is related to the Operating System and not to the browser because I ran on both Chrome and Safari and did not notice that issue. I am currently on macOS 13.0.1. So could anyone please help me figure it out because I don't have access to any other operating system at this moment?
> > 
> > 
> > I'm experiencing this in chrome, brave and edge. What is your screen resolution?
> 
> @rupali-codes My screen resolution is 2560 × 1600

Maybe its screen size issue, not the browser ones

**Comment by bose-aritra2003** [comment]
Could @CBID2 confirm whether you are facing the same issue ? And @rupali-codes, have you tried opening the web app on other devices and seeing whether the issue persists or not? Because I have absolutely no idea why that scrollbar is appearing in the beginning.

**Comment by rupali-codes** [comment]
> Could @CBID2 confirm whether you are facing the same issue ? And @rupali-codes, have you tried opening the web app on other devices and seeing whether the issue persists or not? Because I have absolutely no idea why that scrollbar is appearing in the beginning.

I'm still seeing it in my phone and tab, though i don't know the exact issue. @ujjawaltyagii & @CBID2 do you guys have any idea?

**Comment by CBID2** [comment]
I don't see it on the mobile. I'll try it on desktop mode later and see the issue happens there @bose-aritra2003

**Comment by bose-aritra2003** [comment]
@CBID2 @rupali-codes any update on this PR ?

**Comment by CBID2** [comment]
> @CBID2 @rupali-codes any update on this PR ?

Hey sorry @bose-aritra2003. I didn't have a chance to check. Will do tomorrow

**Comment by rupali-codes** [comment]
@CBID2 let me know

**Review by ujjawaltyagii — COMMENTED** [review]
Yep !! I can also see this scrollbar on mobile as well as in brave/chrome/edge whenever we open any category

**Comment by bose-aritra2003** [comment]
> Yep !! I can also see this scrollbar on mobile as well as in brave/chrome/edge whenever we open any category 

Is there any fix you could suggest? Because I am unable to see that on my devices. Maybe because of different operating system (Mac and iOS)

**Comment by rupali-codes** [comment]
> Yep !! I can also see this scrollbar on mobile as well as in brave/chrome/edge whenever we open any category

Do you have any suggestions to fix this issue?

**Comment by ujjawaltyagii** [comment]
@rupali-codes how does it look ? (did some changes)

https://github.com/rupali-codes/LinksHub/assets/115401171/e55e6124-4af7-43af-bd25-61db7dbae0cc

**Comment by rupali-codes** [comment]
> @rupali-codes how does it look ? (did some changes)
> 
>  fixx.mp4

Looks great 👀

**Comment by ujjawaltyagii** [comment]
so basically idk if i will explain well or not but i tried and did bunch of things :
modified overflow property, added usestate hook to manage the expanded state, use of isExpanded variable to get this output.
(now i think i should have opened a PR for this :)

**Comment by rupali-codes** [comment]
> @rupali-codes so basically idk if i will explain well or not but i tried and did bunch of things : modified overflow property, added usestate hook to manage the expanded state, use of isExpanded variable to get this output. (now i wish i should have opened a PR for this :)

You have the rights to edit the files in here, or just suggest the changes :)

**Comment by rupali-codes** [comment]
Hey @bose-aritra2003 could you please update the description and add _closes #747_ as well

**Comment by bose-aritra2003** [comment]
> Hey @bose-aritra2003 could you please update the description and add _closes #747_ as well

@rupali-codes done

**Comment by ujjawaltyagii** [comment]
OOPs !! I accidently committed the changes instead of suggesting them :) @rupali-codes @bose-aritra2003 do check the deployment and feel free to modify the changes if you want !

**Comment by bose-aritra2003** [comment]
> OOPs !! I accidently committed the changes instead of suggesting them :) @rupali-codes @bose-aritra2003 do check the deployment and feel free to modify the changes if you want !

@ujjawaltyagii The accordion arrow symbol is reversed for the Frontend tab.

Screenshot 2023-06-04 at 19 02 36

**Comment by ujjawaltyagii** [comment]
@bose-aritra2003 Ig rest is working fine like that scroll-bar issue which was appearing when we were opening any category so you can commit the rest of the changes !

**Comment by rupali-codes** [comment]
@bose-aritra2003 are you still working on this?

**Comment by bose-aritra2003** [comment]
> @bose-aritra2003 are you still working on this?

Yes I am. I was actually very busy for the last few days and therefore couldn't work on it. I am going to fix that by tomorrow if possible.

**Comment by rupali-codes** [comment]
> > @bose-aritra2003 are you still working on this?
> 
> Yes I am. I was actually very busy for the last few days and therefore couldn't work on it. I am going to fix that by tomorrow if possible.

Umm... can we make this PR  just to resolve the opened frontend tab issue on starting? i guess that would be better, as the issue is being addressed in another PR

**Comment by bose-aritra2003** [comment]
> > > @bose-aritra2003 are you still working on this?
> > 
> > 
> > Yes I am. I was actually very busy for the last few days and therefore couldn't work on it. I am going to fix that by tomorrow if possible.
> 
> Umm... can we make this PR just to resolve the opened frontend tab issue on starting? i guess that would be better, as the issue is being addressed in another PR

@rupali-codes I just now added a commit and found out that it was actually a very simple fix. I think now it is alright. Please review it.

**Review by rupali-codes — APPROVED** [review]
finally! looks perfect to me :)

**Review by ujjawaltyagii — APPROVED** [review]
Lgtm 👍

**Pull request merged**
