### PR TITLE
add: techncial writing category and Docsify 

### LINKED ISSUE #1692: [Add] <Docsify>
### Site URL

https://docsify.js.org/#/?id=docsify

### Description of the above provided site

If you're looking for a static generator that makes it easier for you to create docs, you'll love Docsify. Unlike GitBook, it does not generate static HTML files. Instead, it loads and parses your Markdown files and displays them as a website.

### Category

Technical Writing. See #1693 for context 

### Sub Category

Tools 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### LINKED ISSUE #1693: [ADD] <Technical Writing/Tools>
### Category Name

Technical Writing

### Subcategory Name

Tools 

### Additional Context

This issue will be addressed in #1692 too. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by CBID2**
## Fixes Issue
Closes #1693 
Closes #1692 

## Changes proposed
I added a technical writing category with a "tools" subcategory with a link to Docsify 

## Note to reviewers
It's still a WIP

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
As I said, I don't know what is the problem with category, I need to add one myself in order to understand where is the problem.

@rupali-codes will be able to help with this.

**Comment by rupali-codes** [comment]
@CBID2 & @Anmol-Baranwal please review once

**Comment by CBID2** [comment]
> @CBID2 & @Anmol-Baranwal please review once

@rupali-codes, can you post a screenshot please? It still says deployment failed on the mobile app.

**Comment by rupali-codes** [comment]
> > @CBID2 & @Anmol-Baranwal please review once
> 
> @rupali-codes, can you post a screenshot please? It still says deployment failed on the mobile app.

Sure

**Comment by CBID2** [comment]
Looks great! :)

**Review by CBID2 — COMMENTED** [review]
LGTM

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
