### PR TITLE
Closes #2313 - Spelling Mistakes

### LINKED ISSUE #2313: [Refactor] Spelling Mistakes
### File Name

backend/testing.json, other/roadmaps.json, placement_prep/job-portals.json

### Reason for Refactoring the Code

These are few spelling mistakes which I noticied at first sight. 
LinkdedIn -> LinkedIn
plaform -> platform 
fronted -> frontend 
Backned -> Backend

Additionally I would suggest to add few extensions like code spell checker in LinksHub Contributing Guidelines. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).

### PR DESCRIPTION
**Pull request by anantgna**
## Fixes Issue 
Closes #2313 

## Changes proposed

Spelling Updates
1. Backned to Backend
2. Fronted to Frontend
3. LinkdedIn to LinkedIn
4. plaform to platform

## Note to reviewers

Adding i18n localization for multi-language support will be a nice option, if you guy's agree please let me know.

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by CBID2** [comment]
@Anmol-Baranwal, your turn

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by aftabrehan — APPROVED** [review]

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
