### PR TITLE
feat: Improved the site structure

### LINKED ISSUE #302: [Feature] Improve the site structure
### Description

Hi! I think it would be great to improve the site structure.

Improve the site layout with grid.

Improve html tag names.

Add `overlay-root` to the `_document.tsx`.
- Stores the active `popup` and `SideNavbar` component.

Improve SideNavbar
- Stores the social icons in mobile view.
- Improve the design of the `SideNavbar` in the mobile view and add an `aside` component from `lg`.

Add a fix header
- Has the logo, the  `category name`, the social icons, the theme toggle and the menu button.
- The `category` name is under the `header` in mobile view.

Improve the `popup` component
- Use the reusable `Backdrop` component.

### Screenshots

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by zvolcsey**
Hi! I improved the site structure

## Fixes Issue

Closes #302

## Changes proposed

Improved the site layout with grid.

Added `overlay-root` to the `_document.tsx`.
- Stores the active `popup` and `SideNavbar` component.

Improved SideNavbar
- Has the social icons in mobile view.
- Improved the design of the `SideNavbar` in mobile view and added an `aside` component from `lg`.

Added a fix header
- Stores the logo, the `category name`, the social icons, the theme toggle and the menu button.
- The `category` name is under the `header` in mobile view.

Improved the `popup` component
- Use the reusable Backdrop.

## Screenshots
SideNavbar_mobile
Home
Home2
SubCategory_Page
SubCategory_Page2
SubCategory_Page3

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks great

**Comment by rupali-codes** [comment]
Hi, it looks great though. But the heading isn't looking too nice. How about if we remove that for desktop?

image

**Comment by zvolcsey** [comment]
> Hi, it looks great though. But the heading isn't looking too nice. How about if we remove that for desktop?
> 
> image

@rupali-codes Hi! Thanks for the feedback! Working on it.

**Comment by zvolcsey** [comment]
@rupali-codes @CBID2 Hi! In my latest commits I made the following improvments.
- In mobile view the `TopBar` component's background color is the same color as the header's background color.
- Fixed the header. From `lg` it looks like the header is only `290px`.

**Review by CBID2 — APPROVED** [review]
Looks great! 😁

**Review by rupali-codes — COMMENTED** [review]
Hi, sidebar have lost the animation 🙄

**Comment by zvolcsey** [comment]
> Hi, sidebar have lost the animation 🙄

Thanks for the feedback. Working on it.

**Comment by zvolcsey** [comment]
@rupali-codes @CBID2 Hi! In my latest commits I made the following improvments.

- Merged the latest commits.
- Added animations to sidebar and popup. I added some delay to the unmount processes. The unmounted animations can also run.

**Review by rupali-codes — APPROVED** [review]
Looks perfect to me :D

**Pull request merged**
