### PR TITLE
feat: add official docs of tailwindcss ⚡

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Fixes Issue

#1237

## Changes proposed

Add `JSON `data about `Tailwind CSS `

## Screenshots

image

## Note to reviewers

**kindly Review it And merge it happy hacking :)**

### CODE REVIEW

**Review by CBID2 — DISMISSED** [review]
LGTM

**Review by CBID2 — DISMISSED** [review]
Hey @Nishitbaria. I found and fixed some merge conflicts! 😄 You just need a review from @rupali-codes or the other maintainers before we merge it! :)

**Comment by Nishitbaria** [comment]
> Hey @Nishitbaria. I found and fixed some merge conflicts! 😄 You just need a review from @rupali-codes or the other maintainers before we merge it! :)
Thanks for it

**Review by rupali-codes — COMMENTED** [review]
@CBID2 you have removed other resources...

**Comment by Nishitbaria** [comment]
> @CBID2 you have removed other resources...

Hey @rupali-codes I have again added the removed data again . you can merge

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by k-deepak04 — APPROVED** [review]

**Pull request merged**
