### PR TITLE
Change button to link for sidebar elements.

### PR DESCRIPTION
**Pull request by JoshHargreaves**
Fixes https://github.com/rupali-codes/LinksHub/issues/56

## Changes proposed

Changes the sidebar elements to use <Link> instead of A to correctly follow coding guidelines and remove HTML warnings.

### CODE REVIEW

**Comment by JoshHargreaves** [comment]
Apologies did not realise contributing guidelines have now been added.

**Comment by rupali-codes** [comment]
@JoshHargreaves thanks for quick changes, what's the difference between using <button> and <Link> ?

**Comment by JoshHargreaves** [comment]
The anchor tag generally represents a link to another page or section within a page whereas the button is more meant to represent an action resulting from a click. 

The Link tag I have added here is a Next JS element that enables client-side transitions and removes the need for custom routing code at the top of the page.

**Comment by rupali-codes** [comment]
Got it. Thank You

**Pull request merged**
