### PR TITLE
Added Descriptions to i button of categories.

### PR DESCRIPTION
**Pull request by PiyushK79**
Fixes issue #1284 .
I added the description of all categories so when we click on i button a small description is shown.

Screenshot-
image

@rupali-codes Please review my changes and add it to the main branch.
Thanks.

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hi @PiyushK79, the descriptions look great. However, there are some merging conflicts in your branch, so you need to solve them.

**Comment by rupali-codes** [comment]
@PiyushK79 you shouldn't over-do the work, your issue was specifically for adding description of _button_ category but you have added it for all.

**Comment by PiyushK79** [comment]
Sorry for the problem caused, I will create a new pull request for this issue.

**Comment by rupali-codes** [comment]
> Sorry for the problem caused, I will create a new pull request for this issue. @rupali-codes My issue was to add descriptions for all categories in the i button. Is there something else I need to change?
> 
> Someone removed the entire section on which I was working i.e Topbar and it got merged with the main branch first, that was the reason of the conflict.

Oh, my bad, i missunderstood the issue, you can add this, lemme check the PR

**Comment by rupali-codes** [comment]
@PiyushK79 you may either reopen this PR or create one, containing all the changes you've made. I'm sorry for missconflicts

**Comment by PiyushK79** [comment]
It's alright. But the section of the topbar is deleted completeley , So do I add it again aur just leave this issue?

**Comment by rupali-codes** [comment]
> It's alright. But the section of the topbar is deleted completeley , So do I add it again aur just leave this issue?

I have reverted the PR, it should be ok when you reopen or create a new PR

**Comment by PiyushK79** [comment]
Alright, I will create a new PR.

**Pull request closed without merging**
