### PR TITLE
Killercoda devtools branch

### LINKED ISSUE #1740: [Add] <add Killercoda>
### Site URL

https://killercoda.com/

### Description of the above provided site

Killercoda is an interactive learning platform which allows everyone to access Linux|Kubernetes based environments just in their browser.

### Category

Other

### Sub Category

Dev Tools

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Ayaan49**
## Fixes Issue 
--> Closes #1740 

## Changes proposed
--> Added link to Other category and Devtools sub-category.

### CODE REVIEW

**Comment by Ayaan49** [comment]
Hello @CBID2 , I mistakenly attached my previous branch, which I used to add the Golang link, to my new branch as well. How can I fix this?

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by CBID2** [comment]
> > LGTM
> 
> Okay! Btw it's showing merge conflict.
Ooh I see. I recommend that you fix it @Ayaan49. Here’s an article just in case you need help: https://css-tricks.com/merge-conflicts-what-they-are-and-how-to-deal-with-them/

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Pull request merged**
