### PR TITLE
[Add] Awesome-Design-Tools

### LINKED ISSUE #2424: [Add] Awesome-Design-Tools
### Site URL

https://github.com/goabstract/Awesome-Design-Tools

### Description of the above provided site

The best design tools and plugins for everything

### Category

Resources

### Sub Category

design

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by JuanPabloDiaz**
## Fixes Issue
closes #2424

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
@JuanPabloDiaz could you please enhance the description a bit

**Comment by JuanPabloDiaz** [comment]
> @JuanPabloDiaz could you please enhance the description a bit

image

**Review by CBID2 — APPROVED** [review]
LGTM! 😊Your turn @Anmol-Baranwal

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
