### PR TITLE
added technical writing

### LINKED ISSUE #1710: [OTHER] Missing Category
### What would you like to share or ask?

The Technical Writing category is not listed in the dropdown menu of the Add a New Link Issue template. 

Note: I tried doing this PR myself, but decided to close my PR in an effort to give other contributors a chance. This can be done for Hacktoberfest.

## Screenshot
Screenshot of technical writing not appearing

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by barkhaaroraa**
closes #1710

## Fixes Issue
i've added technical writing to the dropdown menu, if any other changes required please let me know

## Screenshots
image

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Well done @barkhaaroraa! :) @Anmol-Baranwal, @rupali-codes, can one of you review this?

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
@barkhaaroraa 
Please add `Cyber Security` as a option as well. It was recently added.

image

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
