### PR TITLE
Used .set() with { merge: true } to avoid overwriting the entire docu…

### PR DESCRIPTION
**Pull request by Sarthak0203**
…ment

### CODE REVIEW

**Comment by Sarthak0203** [comment]
## Description
This pull request modifies the `GET` function to avoid overwriting the entire document for each file in Firestore. 

## Fixes Issue
- Overwriting of data in Firestore documents.

## Changes proposed
- Use `.set()` with `{ merge: true }` to avoid overwriting the entire document in Firestore.

## Note to reviewers
Please test the updated `GET` function thoroughly to ensure it works as expected and doesn't overwrite the entire document in Firestore

**Comment by rupali-codes** [comment]
@Anmol-Baranwal can you review this..

**Review by Anmol-Baranwal — APPROVED** [review]
@rupali-codes
I'm not entirely sure about the Firestore document structure, but this PR works for cases where we update resources without affecting any other fields that might already exist in the document.

If this is only for the importing the documents the first time, then we can do the overwriting.

**Comment by CBID2** [comment]
> @rupali-codes I'm not entirely sure about the Firestore document structure, but this PR works for cases where we update resources without affecting any other fields that might already exist in the document.
> 
> If this is only for the importing the documents the first time, then we can do the overwriting.

Also @Anmol-Baranwal, Sarthak did not raise an issue for this, so in an effort to encourage open source etiquette, I highly think this PR should be closed, have them reread the contributing guide, and review their issue to see if it suits the project.

**Comment by rupali-codes** [comment]
@Anmol-Baranwal & @CBID2 we have temporarily put this feature on Hold. So, for now I'm closing this PR, we will look into it once we reactivate this feature.

**Pull request closed without merging**
