### PR TITLE
Add new JavaScript charting libraries

### LINKED ISSUE #2289: [Add] Tremor & Recharts
### Site URL

tremor.so & recharts.org

### Description of the above provided site

Opening this issue to complement the great work of issue #2278

- [Recharts](https://recharts.org) is a composable charting library built on React components. Redefined chart library built with React and D3.
- [Tremor](https://www.tremor.so/) is a React components to build charts and dashboards.

 I don't mind if someone else wants to take it and work on it. 

### Category

Frontend

### Sub Category

JavaScript Chart Libraries

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by JuanPabloDiaz**
## Fixes Issue

fixes #2289

## Changes proposed

Add new JavaScript charting libraries 

## Note to reviewers

In the interest of providing additional context, I've included some further resources.

Additional resources:

- [Vega](https://vega.github.io/vega/) is a visualization grammar, a declarative format for creating, saving, and sharing interactive visualization designs.
- [Victory](https://formidable.com/open-source/victory/) is a React.js components for modular charting and data visualization.
- [C3js](https://c3js.org/) is a D3-based reusable chart library.

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@JuanPabloDiaz 
Please link the issues to all of your PRs correctly, so it's easier for us.

use: `fixes #<issue_number>`

**Comment by JuanPabloDiaz** [comment]
I believe that's what I did @Anmol-Baranwal.

**Comment by Anmol-Baranwal** [comment]
image

This is the correct way. This will close the issues when the PRs are merged.

image

**Comment by JuanPabloDiaz** [comment]
Great to know, thanks!

**Review by rupali-codes — APPROVED** [review]
lgtm

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by aftabrehan — APPROVED** [review]

**Comment by CBID2** [comment]
Looks like there is a deployment issue @rupali-codes

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please merge this.

**Pull request merged**
