### PR TITLE
fix: OTHER-category at the end

### LINKED ISSUE #1627: [Bug] place OTHER category at the end in the sidebar
### Issue Description

As per the order, OTHER supposed to be placed at the end, but its appearing at last second. 

### Additional Context

_No response_

### Screenshots or Examples (if applicable)

image

### Proposed Solution (optional)

Place OTHER category at the end

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by URVESH1121**
## Fixes Issue

Closes #1627 

## Screenshots

image

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by Anmol-Baranwal — COMMENTED** [review]
🚀 Looks good to me.

**Comment by CBID2** [comment]
> 🚀 Looks good to me. 

Did you press the Agree option @Anmol-Baranwal? It won't let me merge the PR.

**Review by Anmol-Baranwal — APPROVED** [review]
> @CBID2 My bad.

Looks good to me. Ready to merge.

> My network is glitchy.

**Pull request merged**
