### PR TITLE
Added official documents for Go programming language

### LINKED ISSUE #2147: [Add] <Official doc of GO programming language>
### Site URL

https://go.dev/doc/

### Description of the above provided site

The official Go documentation is an essential resource for Go developers and contains comprehensive information about the language, libraries, and tools. It includes guides, tutorials, and detailed reference material for Go's standard library, making it a valuable reference for both beginners and experienced Go programmers. 

### Category

Resources

### Sub Category

documents

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by dalvishruti14**
## Fixes Issue
closes #2147 

## Changes proposed
This PR adds the official documentation for Go

## Note to reviewers

Please merge this pull request under hacktoberfest label.

### CODE REVIEW

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
Only do the changes mentioned in the PR and issue description.

image

Remove this `codewithharry` resource.

**Comment by CBID2** [comment]
Thanks for your Pull Request @dalvishruti14! We've merged in some new PRs since you submitted. Can you merge the latest changes and resolve conflicts? If you need some help with that, check out this post: [Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h).

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by aftabrehan — APPROVED** [review]
Looks good to me! 👍

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Pull request merged**
