### PR TITLE
Added frontend course by META

### LINKED ISSUE #2068: [ADD] Introduction to Frontend by META
### Category Name

Frontend

### Subcategory Name

React

### Additional Context

@anm

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by Ram-tyagi**
## Fixes Issue
Closes #2068

## Changes proposed

Added Free certificate course Introduction to frontend by META

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@Ram-tyagi 
We are neglecting this now, but in the future, you need to create an issue and allow us to assign you the issue before you start working and submit a PR. Not following this process will require us to close your pull request.

This is outlined in the contributing guidelines.
image

You need to follow a predefined flow in order to contribute to Open Source. You may be new, so it is important to understand this. Most of the maintainers will mark it as spam and close it. I'm converting this into a draft for now. 

Create an issue and tag me. You can read contributing guidelines to know more.

**Comment by Ram-tyagi** [comment]
@Anmol-Baranwal added issue #2068

**Review by CBID2 — APPROVED** [review]
Looks good to me

**Comment by CBID2** [comment]
@Anmol-Baranwal & @rupali-codes, you're up! :)

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
