### PR TITLE
chore:added striver's 79 dsa cheatsheet

### LINKED ISSUE #2079: [Add] Strivers 79 Last Moment DSA Sheet
### Site URL

https://takeuforward.org/interview-sheets/strivers-79-last-moment-dsa-sheet-ace-interviews/

### Description of the above provided site

The Striver’s 79 Sheet contains very handily crafted and picked top coding interview questions from different topics of Data Structures & Algorithms.

### Category

Resources

### Sub Category

Dsa

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by ankush-w17**
## Fixes Issue

closes #2079 

## Changes proposed

Added Strivers 79 Last Moment DSA Sheet to category : resources, sub-category : dsa

## Screenshots

linkshub striver's dsa cheatsheet

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Well done @ankush-w17! :)

**Comment by CBID2** [comment]
@Anmol-Baranwal and @rupali-codes, you're up! :)

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Comment by ankush-w17** [comment]
@rupali-codes, can you please review this PR?

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
