### PR TITLE
Closes #2296 [add] - remotely url

### LINKED ISSUE #2296: [Add] Remotely in Job-portals
### Site URL

https://www.remotely.jobs/

### Description of the above provided site

Remotely  is platform that helps you find full-time and part-time remote jobs. They have tech and as well as non-tech jobs

### Category

Placement Prep.

### Sub Category

Job-Portals

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by sarava338**
## Fixes Issue

Closes #2296 

## Changes proposed

Added remotely in placement-prep > jo-portals

## Screenshots

image

### CODE REVIEW

**Comment by rupali-codes** [comment]
@sarava338 please resolve the conflicts :)

**Comment by rupali-codes** [comment]
@sarava338 are you still working on this?

**Comment by Anmol-Baranwal** [comment]
@sarava338 
Why did you create a new pull request? Were there major conflicts.

Anyway, the new PR is #2326 for reference.

**Comment by sarava338** [comment]
> @sarava338 Why did you create a new pull request? Were there major conflicts.
> 
> Anyway, the new PR is #2326 for reference.

Hey @Anmol-Baranwal, actually this is my first time getting conflicts. So I don't know how to resolve this and I did not have time to search for i. So, I'e created a new PR. Sorry for the confusion...

**Comment by Anmol-Baranwal** [comment]
> > @sarava338 Why did you create a new pull request? Were there major conflicts.
> > Anyway, the new PR is #2326 for reference.
> 
> Hey @Anmol-Baranwal, actually this is my first time getting conflicts. So I don't know how to resolve this and I did not have time to search for i. So, I'e created a new PR. Sorry for the confusion...

No worries, you can resolve the conflicts here on GitHub itself if they are minor. I would recommend learning a bit because conflicts often occur in PRs.

**Pull request closed without merging**
