### PR TITLE
feat:adding the Rockect.Chat in open source project section

### LINKED ISSUE #1729: [Add] Add Rocket Chat
### Site URL

https://github.com/RocketChat/Rocket.Chat

### Description of the above provided site

[Rocket.Chat](https://rocket.chat/) is an open-source fully customizable communications platform developed in JavaScript for organizations with high standards of data protection.

### Category

Frontend

### Sub Category

open source project

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Manmit124**
Adding the Rocket.Chat in open source (project section ) 

## Fixes Issue
closes #1729 

## Screenshots
image

### CODE REVIEW

**Comment by CBID2** [comment]
Sorry @Manmit124. This issue hasn't been assigned to you, so I closed your PR. Please read our contributing guide to learn how to contribute effectively.

**Comment by Manmit124** [comment]
Thank you for your feedback regarding my recent pull request. 
So can you pls tell me what mistake i did ?

**Comment by CBID2** [comment]
> Thank you for your feedback regarding my recent pull request. 
> 
> So can you pls tell me what mistake i did ?
> 
> @CBID2 

That's the only issue @Manmit124. I think @dfordp wants to do this one, so I highly recommend either finding and requesting to be assigned to another issue or raise another one. Check out my [blog post](https://chrissycodes.hashnode.dev/how-to-make-your-issues-requests-come-true) to learn more.

**Comment by Manmit124** [comment]
Thanks for your wonderful feedback 😉 @CBID2

**Pull request closed without merging**
