### PR TITLE
chore: add jenkins subcategory in DevOps

### LINKED ISSUE #1931: [Add] Want to add Jenkins documentation.
### Site URL

https://www.jenkins.io/doc/

### Description of the above provided site

Jenkins is an open-source automation server that is widely used for building, deploying, and automating software development pipelines. Its documentation is a crucial resource for users, administrators, and developers who want to understand, install, configure, and utilize Jenkins effectively. The most effective and structured documentation I have ever gone is Jenkin's documentation.

### Category

DevOps

### Sub Category

Jenkins

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #1931 

## Note to reviewers

LOL! I created this myself.

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@goobric 
I created this, but I never thought I would be the author of the PR.

Maybe you can co-authored the PR with me. 

😑I thought, it would be raised by you. Sorry.

Or if you want, you can close the PR, and raise a new PR from a fresh branch. You already know the code changes so it will be quick.

**Comment by Anmol-Baranwal** [comment]
@goobric 
Comment here.

**Comment by AnmolB2** [comment]
hi @Anmol-Baranwal

**Comment by goobric** [comment]
hi @Anmol-Baranwal 
please merge this co-authored PR, thank you.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 
I cannot review this PR 😑 Since I've created it along with @goobric. 

I mistakenly opened a PR to test the changes, and now he has allowed me to be a co-author for the PR.

Please review it.

**Review by CBID2 — APPROVED** [review]
Looks good to me

**Review by rupali-codes — APPROVED** [review]

**Comment by goobric** [comment]
hi @CBID2 & @rupali-codes thank you so much for reviewing, approving and merging the PR
thank you @Anmol-Baranwal for your support and assistance.
Who now deletes the branch?

**Comment by goobric** [comment]
hi @rupali-codes @CBID2 @Anmol-Baranwal 
can you please explain something to me, if possible; I just checked my hacktoberfest-profile; and it states the the jenkins pr is not accepted! Is this an issue with the HF23 platform?
Again, I am confused!
Sorry for so many questions.
231015_linkhub_pr_hf23

**Comment by Anmol-Baranwal** [comment]
@goobric 
It may be due to because I created the PR. Sorry again.

Maybe you can create another simple issue, and I will assign you the issue. We will merge it quickly.

This way, your hacktoberfest 4 PRs will be completed.

**Comment by goobric** [comment]
hi @Anmol-Baranwal 
it is sad that HF23 does not accept co-authored PRs
I will see if it is possible to create a simple issue; if not; no problem.
Thanks again  :-)

**Comment by Anmol-Baranwal** [comment]
> hi @Anmol-Baranwal it is sad that HF23 does not accept co-authored PRs I will see if it is possible to create a simple issue; if not; no problem. Thanks again :-)

Yeah, they should allow it. It actually promotes the collaborative work of open source. If you can't create a issue, let me know.

I will do it for you.

**Comment by goobric** [comment]
@Anmol-Baranwal ; yes, please create an issue and assign it to me. Thank you once again.

**Comment by Anmol-Baranwal** [comment]
> hi @Anmol-Baranwal I hope that you are well; when it is convenient for you, and you have the opportunity, can you please create and assign an issue for me to work on. Thank you

I've already created the issue, and even tagged you there.

Comment on #2004 

I even have to tell others, as many were looking forward to contribute it.

**Pull request merged**
