### PR TITLE
chore: add color resource for frontend ✨

### LINKED ISSUE #1168: [Add]: COLOR RESOURCE 💡
### Site URL

https://instahues.com/

### Description of the above provided site

H

### Category

Frontend

### Sub Category

colors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Fixes Issue

Closes #1168 

## Changes proposed

- Added `Eva Colors` a color resource which can be used to generate colors using deep learning by AI

## Screenshots

image

## Note to reviewers 

- The resource mentioned on the issue `Instahues` is not working properly, I think the domain may be taken down for some sort of issues.
- Yesterday it was fine when i visited that, but i don't know what happened today.
- So i came with a new color resource `Eva Colors`

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Please review this PR @rupali-codes, @CBID2 & @ujjawaltyagii.

**Review by CBID2 — APPROVED** [review]
LGTM! 😀

**Review by ujjawaltyagii — APPROVED** [review]
LGTM !!

**Comment by 0xabdulkhalid** [comment]
Hello guys @rupali-codes, @CBID2 & @ujjawaltyagii, Thank you for merging this PR.
You forget to add lables

So please make sure to add `gssoc23` and `level1` labels so that Gssoc's Backend can count this contribution.

Happy contributing!

**Pull request merged**
