### PR TITLE
Adding LinksHub landing page style guide

### LINKED ISSUE #825: [OTHER] Design Style Guide
### What would you like to share or ask?

Created a style guide for the new LinksHub landing page design

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by AbyPurpleheart**
Closes #825

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @AbyPurpleheart! :) I closed this pull request because you haven't waited for the maintainers to confirm your participation in GSSoC per the[Contributing guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md). Once you do, this PR will be reopened.

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by CBID2 — APPROVED** [review]
LGTM!

**Comment by rupali-codes** [comment]
@AbyPurpleheart i'm not able to see the image for some reason. @CBID2 Are you able see that?

**Review by ujjawaltyagii — APPROVED** [review]
Lgtm !!

**Comment by ujjawaltyagii** [comment]
@rupali-codes for your reference 

LinksHub Styleguide

**Review by rupali-codes — APPROVED** [review]
looks beautiful!

**Pull request merged**
