### PR TITLE
Added Podcast/openSourceStories

### LINKED ISSUE #422: [Add] <Open Source Stories>
### URL

https://www.opensourcestories.org/

### Description of the above provided site

Founded by [Amanda Casari](https://twitter.com/amcasari) and [Julia Ferraioli](https://twitter.com/juliaferraioli), Open Source Stories is a podcast where individuals record their experiences about being in the open source community. In contrast to other podcasts, these stories are saved in the StoryCorps archive at the United States Congress! 😄 So what are you waiting for? Share your story! 😄 

### Category

Other

### Sub Category

design inspiration

### PR DESCRIPTION
**Pull request by MadhuMPandurangi**
## Fixes Issue
Closes #422 

## Changes proposed
Add Open Source Stories creating subcategory: podcast

## Screenshots
image

## Note to reviewers
Closing PR #423 since the branch name is design-inspiration

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
looks good to me

**Comment by MadhuMPandurangi** [comment]
@CBID2 as u changed the smiley emoji's to 'smile' text, it was displaying in the description as 
` Share your story smile!`
It was not looking appropriate, so I removed it. 
Is that ok?

**Review by CBID2 — APPROVED** [review]
LGTM!

**Review by MadhuMPandurangi — COMMENTED** [review]
@rupali-codes, Added a new line at the end of the file.

**Comment by MadhuMPandurangi** [comment]
@rupali-codes is there anything that requires changes?

**Comment by rupali-codes** [comment]
@MadhuMPandurangi Nh, looks great to me too :) thanks

**Pull request merged**
