### PR TITLE
Fix database config

### LINKED ISSUE #1607: [BUG] There is no resources present for "Testing" due to wrong configs
### Description

- There is no data present for the "Testing" while we have data inside database.

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by shreedhar37**
## Fixes Issue
Closes #1607, #1594 

## Changes proposed

I have updated the `url` and `resources` to correct values in `data.ts` which were causing issue previously.

## Screenshots

image

### CODE REVIEW

**Review by Anmol-Baranwal — COMMENTED** [review]
Hi @shreedhar37 

Why was the data.ts changed? What was wrong in the previous one. Let me know, then I will cross check it.

**Comment by shreedhar37** [comment]
Hi @Anmol-Baranwal previously the value for `url` was `/youtube-testing` and for  `resources` it was `DB.youtubeTesting`, which was causing the issue.

**Comment by Anmol-Baranwal** [comment]
@shreedhar37 

Change the value to something more unique. Because we already have a similar name `testing` for backend. You can check [here](https://github.com/rupali-codes/LinksHub/blob/main/database/data.ts).

**Comment by shreedhar37** [comment]
Ahh totally missed that @Anmol-Baranwal. Thanks for bringing that up. But I am confused now, there are some values inside `databases/youtube/testing.json` which are already present inside `databases/backend/testing.json`. Should I keep only unique values or is it okay to have the same values in both files ?

**Comment by Anmol-Baranwal** [comment]
> Ahh totally missed that @Anmol-Baranwal. Thanks for bringing that up. But I am confused now, there are some values inside `databases/youtube/testing.json` which are already present inside `databases/backend/testing.json`. Should I keep only unique values or is it okay to have the same values in both files ?

No worries, I will let you know soon. 

Please don't make any new changes, until we are sure what to do.

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by rupali-codes — APPROVED** [review]
looks good to me

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Comment by shreedhar37** [comment]
Thanks @Anmol-Baranwal @rupali-codes @CBID2  this is my first open source contribution in life.

**Comment by Anmol-Baranwal** [comment]
> Thanks @Anmol-Baranwal @rupali-codes @CBID2 this is my first open source contribution in life.

Nice :)

Wishing you the best on your open-source journey.

**Comment by rupali-codes** [comment]
> Thanks @Anmol-Baranwal @rupali-codes @CBID2 this is my first open source contribution in life.
glad to know. 
Happy open-sourceing!!!

**Pull request merged**
