### PR TITLE
chore: add Hacktoberfest in Outreach section

### LINKED ISSUE #1703: [DOCS] <add Hacktoberfest logo to outreach section>
### Issue Description

Since we're participating in this year's Hacktoberfest, let's add it to the [Outreach section](https://github.com/rupali-codes/LinksHub/blob/main/README.md#outreach). 

### Additional Context

_No response_

### Screenshots or Examples (if applicable)

_No response_

### Proposed Solution (optional)

_No response_

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #1703 

## Note to reviewers

@CBID2 
Please check the changes.

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by Anmol-Baranwal** [comment]
@CBID2 
We don't need to add labels, as topics for hacktoberfest is already added.

**Comment by CBID2** [comment]
Apparently we do @Anmol-Baranwal, says so here: https://hacktoberfest.com/participation/#pr-mr-details

**Comment by Anmol-Baranwal** [comment]
> Apparently we do @Anmol-Baranwal, says so here: https://hacktoberfest.com/participation/#pr-mr-details

We are on a mission to confuse each other. LOL!

See, here it is written `OR`.

>image
image

> We only need to add it later, I think. 
image

Let me know if I'm wrong.

**Comment by CBID2** [comment]
> > Apparently we do @Anmol-Baranwal, says so here: https://hacktoberfest.com/participation/#pr-mr-details
> 
> We are on a mission to confuse each other. LOL!
> 
> See, here it is written `OR`.
> 
> > image
> > image
> 
> > We only need to add it later, I think.
> > image
> 
> Let me know if I'm wrong.

Ohhh thanks

**Comment by rupali-codes** [comment]
@CBID2 & @Anmol-Baranwal please make sure to add `hacktoberfest-accepted` before merging any PR :)

**Comment by CBID2** [comment]
Done and the queen has returned! :)

**Comment by CBID2** [comment]
> @CBID2 & @Anmol-Baranwal please make sure to add `hacktoberfest-accepted` before merging any PR :)

Will this be merged @rupali-codes?

**Comment by Anmol-Baranwal** [comment]
> @CBID2 & @Anmol-Baranwal please make sure to add `hacktoberfest-accepted` before merging any PR :)

Okay, but it will show up anyway. Since, the topics have been included in the repo.

**Comment by Anmol-Baranwal** [comment]
image

preview

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
