### PR TITLE
fix: added theme-color meta tag

### LINKED ISSUE #444: fix: add theme-color
### Description

In the HTML file we need to add a theme color.

`Does not set a theme color for the address bar.Failures: No manifest was fetched, No `<meta name="theme-color">` tag found.`

### Screenshots

image

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by vikaskumar2703**
## Fixes Issue
Closes #444 

## Changes proposed
add

## Note to reviewers
i have added the theme-colour meta tag and used websites black colour code from css so it would change address bar to that colour in mobile browser but with change of dark or light mode by the user the colour of address would not change , it would remain the same black so suggest changes if u want

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
It's updating the color only for the landing page, and doesn't work when page changes. Could you fix it for all pages?
image

image

**Review by CBID2 — COMMENTED** [review]
Looks ok to me! :)

**Comment by TreciaKS** [comment]
> It's updating the color only for the landing page, and doesn't work when page changes. Could you fix it for all pages? image
> 
> image

It looks good for me as well. The tabs don't change colour according to toggle but all components and pages toggle smoothly.

**Review by CBID2 — APPROVED** [review]
Well done! 👍🏾 LGTM!

**Comment by vikaskumar2703** [comment]
> It's updating the color only for the landing page, and doesn't work when page changes. Could you fix it for all pages? image
> 
> image

i assumed this problem would occur . Actually i m unable to figure out a way to view the result on a mobile browser How u are able to do that ? and to have theme colour for all pages i think i have to add meta tag within a head to all the pages .

**Comment by rupali-codes** [comment]
@vikaskumar2703 just copy the deployment URL ([this](https://linkshub-cza45xslr-rupali-codes.vercel.app/)) and open in your phone

**Comment by TreciaKS** [comment]
@rupali-codes I just opened this on my mobile and it works just fine too.

I can't locate a static HTML file in the codebase, do we have it? Then we can place all the meta data in the index.html file so that changes happen throughout the application.

> @vikaskumar2703 just copy the deployment URL ([this](https://linkshub-cza45xslr-rupali-codes.vercel.app/)) and open in your phone

**Comment by vikaskumar2703** [comment]
@TreciaKS there is no static html file . i too was looking for that at first  but was not able to find it  . Nonetheless in my latest commit i was able to figure out a way to resolve @rupali-codes suggestions.

**Review by rupali-codes — APPROVED** [review]
looks perfect to me, thanks✨

**Pull request merged**
