### PR TITLE
Fix: Resolved conflicts and fixed typos in illustrations subcategory

### LINKED ISSUE #588: [Add] Open Doodles to illustrations
### Site URL

https://opendoodles.com/

### Description of the above provided site

Open Doodles is a vibrant collection of freely-usable illustrations that add personality to any project. With diverse hand-drawn characters, objects, and backgrounds, Open Doodles sparks creativity for designers, developers, and content creators. Enhance websites, presentations, and social media with these charming doodles. Let your imagination flow with the expressive world of Open Doodles.

### Category

Frontend

### Sub Category

illustrations

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Oyebolade**
## Fixes Issue
Closes #588

## Changes proposed
I resolved conflicts and fixed typos in illustrations subcategory

## Screenshots
i1
i2

### CODE REVIEW

**Review by rupali-codes — APPROVED** [review]
lgtm

**Comment by Oyebolade** [comment]
💃💃

> lgtm

💃💃

**Review by CBID2 — APPROVED** [review]
LGTM! 😄

**Comment by CBID2** [comment]
@rupali-codes, we need a force push.

**Pull request merged**
