### PR TITLE
Added new image resource

### PR DESCRIPTION
**Pull request by Abhinavcode13**
## Fixes Issue
closes issue number #971 

## Changes proposed

added image resource

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
image
deployed shutterstock @CBID2 & @rupali-codes please review now

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by ujjawaltyagii — COMMENTED** [review]
Changes look good but you mentioned different resource in your issue and added different resource in PR 👀. What's going on ?

**Comment by Abhinavcode13** [comment]
That website as some problem man :(( @ujjawaltyagii

**Comment by CBID2** [comment]
> That website has some problem man :(( @ujjawaltyagii

There's also branch conflicts on your end @Abhinavcode13.

**Comment by rupali-codes** [comment]
@Abhinavcode13 could you please resolve merge conflicts? :)

**Comment by ujjawaltyagii** [comment]
Please resolve this :
image

**Comment by Abhinavcode13** [comment]
image

@CBID2 @rupali-codes @ujjawaltyagii check now guys

**Review by CBID2 — APPROVED** [review]
LGTM!

**Review by rupali-codes — CHANGES_REQUESTED** [review]
@Abhinavcode13  Why did you remove the other resources?

**Comment by k-deepak04** [comment]
@Abhinavcode13 shall we close this issue 
please respond

**Pull request closed without merging**
