### PR TITLE
Adding pagination feature

### LINKED ISSUE #1125: [Feature] Add Pagination to the Resources Cards
### Description

- Pagination could look better on the resources' cards.
- We could show no more than 9 cards on the page and load the others when user wants to switch it.
- Pagination could make it more professional and user friendly. 

### Screenshots

image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by CBID2**
## Fixes Issue
Closes #1125 

## Changes proposed
@chris-nowicki and I implemented code that adds page numbers to the cards, creating an easier navigation for users. 

## Screenshots
pagination

## Note to reviewers
This PR is a work in progress.

### CODE REVIEW

**Comment by CBID2** [comment]
Hey @rupali-codes. The code @chris-nowicki and I worked on managed to work locally, but for some odd reason, the deployment has failed. Can you help us?

**Comment by chris-nowicki** [comment]
@rupali-codes, @Anmol-Baranwal ... @CBID2 and I have a working copy of the pagination ... before we continue would love your thoughts on the styling of the pagination buttons ... checkout the deployment and let us know what you think.

Right now I have it set to show 9 cards at a time.  Do you think 9 cards is okay in mobile view?

welcome to any and all suggestions :).

**Review by Anmol-Baranwal — COMMENTED** [review]
> I haven't reviewed the code, so I'm just commenting based on the preview.

1. There should be a disabled state that notifies users that when they are on the initial page, the previous icon `<` should be disabled. This will prevent confusion for users. The same applies to the last page and `>`.

   I understand that people are generally aware, but there is a concept called "Next Billion Users" which you can read about.

2. Let's suppose I need to visit the 10th resource.

   The steps would be as follows:
   - Scroll to the bottom of the page.
   - Click on the next icon or go to the second page.
   - Then, scroll back to the top to visit the 1st resource (which is the 10th in the current scenario).

   The number of steps increased instead of simply scrolling.

   In my opinion, it would be better to create a floating widget that is visible at all times. Whenever a new page is clicked, it should automatically scroll to the top. This approach would save users from scrolling up and down, and when they visit a new page, they would start from the top, which is a new resource.

> I really like the design; it fits well with the current theme.

Let me know your thoughts. @chris-nowicki

**Comment by chris-nowicki** [comment]
> > I haven't reviewed the code, so I'm just commenting based on the preview.
> 
> 1. There should be a disabled state that notifies users that when they are on the initial page, the previous icon `<` should be disabled. This will prevent confusion for users. The same applies to the last page and `>`.
>    I understand that people are generally aware, but there is a concept called "Next Billion Users" which you can read about.
> 2. Let's suppose I need to visit the 10th resource.
>    The steps would be as follows:
>    
>    * Scroll to the bottom of the page.
>    * Click on the next icon or go to the second page.
>    * Then, scroll back to the top to visit the 1st resource (which is the 10th in the current scenario).
>    
>    The number of steps increased instead of simply scrolling.
>    In my opinion, it would be better to create a floating widget that is visible at all times. Whenever a new page is clicked, it should automatically scroll to the top. This approach would save users from scrolling up and down, and when they visit a new page, they would start from the top, which is a new resource.
> 
> > I really like the design; it fits well with the current theme.
> 
> Let me know your thoughts. @chris-nowicki

@Anmol-Baranwal These are EXCELLENT suggestions and couldn't agree more.  I'll checkout "Next Billion Users" as I have never heard about it before and agree on the hover effect for the pagination as it would simplify the number of steps.

really appreciate your input :)

**Comment by chris-nowicki** [comment]
@Anmol-Baranwal @CBID2 I made some updates based on Anmol's feedback.  The pagination component is now fixed at bottom of card page.  I had to add some white border styling to make it stand out a bit as it overlaps some of the purple visit site buttons at times.

Not saying this is final yet at all ... a few problems I am having:

- On the final page of cards the layout shifts just a little bit
-  Need to add this to the card page when results are shown from a search (have not implemented this yet as I have been waiting to get this part done and then add it to that page).
- Need to test mobile view as this has really only been developed on lg screens
- One item to think about for FUTURE is what if a page has 100 pages??? Do we need to implement a ... feature to where the page displays 1, 2, 3, 4, 5 ... 100?

This has been fun to work on with y'all. :)

**Comment by CBID2** [comment]
> @Anmol-Baranwal @CBID2 I made some updates based on Anmol's feedback.  The pagination component is now fixed at bottom of card page.  I had to add some white border styling to make it stand out a bit as it overlaps some of the purple visit site buttons at times.
> 
>  
> 
> Screenshot 2023-09-10 at 1 08 31 PM
> 
> 
> 
> Not saying this is final yet at all ... a few problems I am having:
> 
> 
> 
> - On the final page of cards the layout shifts just a little bit
> 
> -  Need to add this to the card page when results are shown from a search (have not implemented this yet as I have been waiting to get this part done and then add it to that page).
> 
> - Need to test mobile view as this has really only been developed on lg screens
> 
> - One item to think about for FUTURE is what if a page has 100 pages??? Do we need to implement a ... feature to where the page displays 1, 2, 3, 4, 5 ... 100?
> 
> 
> 
> This has been fun to work on with y'all. :)

Hey @chris-nowicki. Adding a 100 feature would be cool! :)

**Comment by Anmol-Baranwal** [comment]
> * One item to think about for FUTURE is what if a page has 100 pages??? Do we need to implement a ... feature to where the page displays 1, 2, 3, 4, 5 ... 100?
> 
> This has been fun to work on with y'all. :)

In my opinion, it shouldn't be considered. There may be potential changes in the future, so we shouldn't give too much weight to this change.

The disabled state looks nice. You could try reversing the color palette, with a purple border and a white background on the floating widget. I'm not entirely sure, but I think it might make it stand out more. Perhaps you could attach a screenshot of both variations.

Also, if you want to implement the 100-page structure, feel free to do so. I can offer suggestions, but it might ultimately make this quite complex. 😅

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 

Please don't merge any more PRs to avoid any more conflicts :)

**Comment by CBID2** [comment]
> > * One item to think about for FUTURE is what if a page has 100 pages??? Do we need to implement a ... feature to where the page displays 1, 2, 3, 4, 5 ... 100?
> > 
> > This has been fun to work on with y'all. :)
> 
> In my opinion, it shouldn't be considered. There may be potential changes in the future, so we shouldn't give too much weight to this change.
> 
> The disabled state looks nice. You could try reversing the color palette, with a purple border and a white background on the floating widget. I'm not entirely sure, but I think it might make it stand out more. Perhaps you could attach a screenshot of both variations.
> 
> Also, if you want to implement the 100-page structure, feel free to do so. I can offer suggestions, but it might ultimately make this quite complex. 😅

Good point @Anmol-Baranwal. @chris-nowicki, I think this is ok for now.

**Pull request closed without merging**
