### PR TITLE
chore: Add CSS Grid Generator

### LINKED ISSUE #841: [Add] CSS Grid Generator
### Site URL

https://css-grid-generator.netlify.app/

### Description of the above provided site

This website facilitates efficient utilization of CSS Grid functionalities, enabling users to swiftly generate dynamic layouts.

### Category

Frontend

### Sub Category

UI Generators

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Shiva-Sai-ssb**
## Fixes Issue
Closes #841 

## Changes proposed

I have incorporated the CSS Grid Generator into the suite of UI Generators.

## Screenshots

Screenshot (82)

### CODE REVIEW

**Comment by rupali-codes** [comment]
Hi, please reference the issue properly, add _closes #issue_number_ in the description of this PR

**Comment by Shiva-Sai-ssb** [comment]
> Hi, please reference the issue properly, add _closes #issue_number_ in the description of this PR

Apologies, I have implemented the necessary modifications.

**Review by rupali-codes — APPROVED** [review]

**Review by ujjawaltyagii — APPROVED** [review]
Lgtm 👍

**Review by CBID2 — APPROVED** [review]
LGTM!

**Comment by CBID2** [comment]
@rupali-codes, we need a push merge

**Pull request merged**
