### PR TITLE
Life of Pix

### LINKED ISSUE #509: [Add] Life of Pix
### URL

https://www.lifeofpix.com/

### Description of the above provided site

Life of Pix is an online platform that provides free access to a remarkable assortment of premium images taken by skilled photographers worldwide. Its intuitive interface and absence of copyright limitations make it the ideal choice for individuals seeking attractive and genuine photographs.

### Category

Frontend

### Sub Category

images

### PR DESCRIPTION
**Pull request by parma1111**
## Fixes Issue

Closes #509 

## Changes proposed

Life of Pix provides free premium photos from skilled photographers worldwide with no copyright restrictions. It's perfect for genuine and attractive images.

## Screenshots

Screenshot (797)
Screenshot (798)

## Note to reviewers

Any kind of feedback would be appreciated.

### CODE REVIEW

**Review by rupali-codes — APPROVED** [review]
lgtm

**Review by ujjawaltyagii — APPROVED** [review]
Lgtm 👍

**Review by CBID2 — APPROVED** [review]
Great job @parma1111! LGTM! 😄

**Comment by rupali-codes** [comment]
Thanks Chrissy and Parma!

**Pull request merged**
