### PR TITLE
Added Codechef to competitive programming

### LINKED ISSUE #1842: [Add] Add codechef, one of the major cp platform
### Site URL

https://www.codechef.com/

### Description of the above provided site

Can i add codechef in competitive programming platform section, as it is one of the major and starting platform for cp journey.

### Category

Competitive Programming

### Sub Category

link, color, fonts, themes & templates, animation

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by rahul0x00**
## Fixes Issue
#1842 

Closes #1842 

## Changes proposed

Added CodeChef platform to the Competitive Programming db

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Well done. @Anmol-Baranwal, it's your turn.

**Comment by CBID2** [comment]
Hi @rahul0x00! :) I just realized that you were not assigned to this issue, so I placed your PR in draft mode for now. Can you tag yourself in the comment section of #1842, please?  You did really great with this PR and I don't want you to get a spam accusation.

**Comment by rahul0x00** [comment]
Sure, no issues @rahul0x00

**Review by CBID2 — APPROVED** [review]
Well done @rahul0x00

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Pull request merged**
