### PR TITLE
added twitter link to project

### LINKED ISSUE #210: [CHORE] add twitter link in README and website
### What would you like to share or ask?

I have created a twitter account for LinksHub so people can tag us and share their experience. 

Add this link [https://twitter.com/the_linkshub](https://twitter.com/the_linkshub) in the README.md file as well in the site with twitter icon (You can also give us a follow ;)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yashnirmal**
## Fixes Issue
Example: Closes #210 

## Changes proposed

Added twitter link with icon in the project and also changes the readme file

## Screenshots
Screenshot from 2023-02-17 18-33-57
Screenshot from 2023-02-17 18-41-17

### CODE REVIEW

**Review by rupali-codes — CHANGES_REQUESTED** [review]
could you please remove package-lock.json?

**Comment by yashnirmal** [comment]
> could you please remove package-lock.json?

Yeah sure

**Comment by yashnirmal** [comment]
@rupali-codes can you check now

**Review by rupali-codes — COMMENTED** [review]
Hi, this looks perfect tho, but having an issue, if we'll merge this PR then it's gonna packgae-lock.json from the repo. So could you please close PR and create a new one with the just file you have updated. 

You can add files one-by-one if they are multiple by using this command
```sh
git add <your_file_name>
```

**Comment by yashnirmal** [comment]
> Hi, this looks perfect tho, but having an issue, if we'll merge this PR then it's gonna packgae-lock.json from the repo. So could you please close PR and create a new one with the just file you have updated.
> 
> You can add files one-by-one if they are multiple by using this command
> 
> ```shell
> git add <your_file_name>
> ```

I have removed the package-lock.json file, it should not be visible in my latest PR.

**Review by rupali-codes — COMMENTED** [review]
Hi, thank you, could u please close this PR and create an new one. Because if we'll merge this then it will delete package-lock.json from the repo too. Just add the files u have made changes in.

**Pull request closed without merging**
