### PR TITLE
perf: add opengraph meta tags to enhance SEO

### LINKED ISSUE #504: Add open graph tags in website
## Issue Description
I would like to request that Open Graph tags be added to our website to improve the way it is shared on social media. These tags help provide information to social media platforms like Facebook, Twitter, and LinkedIn, and can improve the way our website appears when it is shared.

## Proposed Solution
I would like to add the following Open Graph tags to our website:

```html
<meta property="og:title" content="Website Title">
<meta property="og:description" content="Website description">
<meta property="og:image" content="https://example.com/image.jpg">
<meta property="og:url" content="https://example.com">
```

The `og:title` tag would be used to specify the title of the website, the `og:description` tag would be used to provide a brief description of the website, the `og:image` tag would be used to specify the image to use when the website is shared, and the `og:url` tag would be used to specify the URL of the website.

### Screenshots

_No response_

### Additional Information

Please let me know if you have any questions or concerns about adding these Open Graph tags. I believe that this change would improve the way, the website is shared on social media and help increase online presence.

### PR DESCRIPTION
**Pull request by Lucif3r-in**
##Fixes issue
Closes #504 

## Changes proposed
Added the open graph meta tags in the _document.tsx to improve the way our website looks when shared.

## Note to reviewers
The changes can be observed after pasting the deployed link on:
1. [LinkedIn post inspector](https://www.linkedin.com/post-inspector/inspect/)
2. [Twitter post validator](https://tweetpik.com/twitter-card-validator)

### CODE REVIEW

**Comment by Lucif3r-in** [comment]
@rupali-codes @CBID2 Can you please review?

**Review by CBID2 — APPROVED** [review]
Looks great @Lucif3r-in! :) LGTM!

**Comment by Lucif3r-in** [comment]
@rupali-codes Can you please review this?

**Comment by rupali-codes** [comment]
Hey @Lucif3r-in , for some reason it's not working for https://linkshub.vercel.app/ on twitter and linkedin Can you please have a look?

**Comment by Lucif3r-in** [comment]
> Hey @Lucif3r-in , for some reason it's not working for https://linkshub.vercel.app/ on twitter and linkedin Can you please have a look?

It is working I just checked!!

**Comment by rupali-codes** [comment]
Now it does, thanks 🎉🎉

**Comment by rupali-codes** [comment]
@Lucif3r-in it's not showing it on LinkedIn, checkout my post
https://www.linkedin.com/feed/update/urn:li:activity:7062744026810134528/

**Comment by Lucif3r-in** [comment]
> @Lucif3r-in it's not showing it on LinkedIn, checkout my post https://www.linkedin.com/feed/update/urn:li:activity:7062744026810134528/

Yes maam it is showing
Check this out
image

**Comment by rupali-codes** [comment]
> > @Lucif3r-in thanks, yeah it's taking so much time to prepare preview. But it works anyways :)
> 
> Ya it's always like that😅!! I hope everything is fine now.

Yep!!

**Pull request merged**
