### PR TITLE
chore: Update ui_libraries.json

### LINKED ISSUE #2492: [Add] Hartan Component Library
### Site URL

https://hartan.netlify.app

### Description of the above provided site

Hartan is a UI component library built on React JS and distributed as a NPM package. It offers a collection of independent, well-documented resources designed to facilitate rapid website development.

### Category

Frontend

### Sub Category

UI Libraries

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by akkshayTandon**
## Fixes Issue
 closes #2492 
## Changes Proposed
-  adds a new link in the UI libraries sub-category inside frontend category

### CODE REVIEW

**Review by rupali-codes — APPROVED** [review]
lgtm

**Comment by rupali-codes** [comment]
@akkshayTandon please attach the closing issue

**Review by akkshayTandon — COMMENTED** [review]
self-review

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
