### PR TITLE
feat: Made the categories collapsible

### LINKED ISSUE #206: [Feature] Made categories collapsible in the SideNavbar component
### Description

Hi! It would be nice if the categories in the SideNavbar would be collapsible. User can see all categories. By default, the frontend would be open.

### Screenshots

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by zvolcsey**
Hi! I made categories collapsible in the `SideNavbar` component.

## Fixes Issue

Closes #206

## Changes proposed

- Added `SideNavbarCategoryList` component with openByDefault property.
- Added `SideNavbarCategory` component with collapsible functionality.
- Added `hover` and `focus-visible` for the title of the category.
- I changed the order of CSS classes. (`SideNavbarCategoryList` , `SideNavbarCategory` and `SideNavbarElement`)

### CODE REVIEW

**Comment by Eugene44-hub** [comment]
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> 
> Name	Status	Preview	Comments	Updated
> **linkshub**	✅ Ready ([Inspect](https://vercel.com/rupali-codes/linkshub/DCD1UUQtNZ5VNAmzbRg48fStwRWJ))	[Visit Preview](https://linkshub-git-fork-zvolcsey-feature-collapsi-c32931-rupali-codes.vercel.app)	💬 [**Add your feedback**](https://vercel.live/open-feedback/linkshub-git-fork-zvolcsey-feature-collapsi-c32931-rupali-codes.vercel.app)	Feb 15, 2023 at 10:11PM (UTC)

**Comment by Eugene44-hub** [comment]
> > **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> > Name	Status	Preview	Comments	Updated
> > **linkshub**	✅ Ready ([Inspect](https://vercel.com/rupali-codes/linkshub/DCD1UUQtNZ5VNAmzbRg48fStwRWJ))	[Visit Preview](https://linkshub-git-fork-zvolcsey-feature-collapsi-c32931-rupali-codes.vercel.app)	💬 [**Add your feedback**](https://vercel.live/open-feedback/linkshub-git-fork-zvolcsey-feature-collapsi-c32931-rupali-codes.vercel.app)	Feb 15, 2023 at 10:11PM (UTC)

Really Excellent job you have done here. Looks so nice

**Review by rupali-codes — COMMENTED** [review]
Great job. Thank you so much.
can we reduce this space between this categories a bit? 
image

**Comment by zvolcsey** [comment]
> Great job. Thank you so much.
> can we reduce this space between this categories a bit? 
> image
> 

@rupali-codes Thanks for the feedback! Okay, working on it.

**Comment by zvolcsey** [comment]
@rupali-codes Hi! I fixed the gap between the categories. There is `gap-4` instead of `gap-8`.

**Review by rupali-codes — APPROVED** [review]
Looks perfect. tysm :)

**Pull request merged**
