### PR TITLE
BUG] Align pagination buttons to bottom

### LINKED ISSUE #2238: [BUG] Align pagination buttons to bottom
### Description

The pagination isn't aligned well when the last page have a few resources (less than 6)

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by mfrezghi**
## Fixes Issue

Closes #2238 

## Changes proposed

- Added a numberOfCards variable to [...subcategory.tsx] to track the number of cards on each page.
- Used numberOfCards within Pagination.tsx to calculate if there are 3 or less cards in a page.
- Added a div that adds padding above the pagination element if there are 3 or less cards on the page.

## Screenshots

Screenshot 2024-01-25 at 10 44 12 AM

## Note to reviewers

I am very new to this so please criticize.

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Need deployment authorization :)

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

@aftabrehan @CBID2 @rupali-codes

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Comment by CBID2** [comment]
@aftabrehan it's your turn to review! :)

**Review by aftabrehan — COMMENTED** [review]
This PR looks good to me. However, why are there still two pagination components?

Screenshot 2024-01-29 at 8 11 16 AM

cc @rupali-codes @CBID2 @Anmol-Baranwal

**Comment by CBID2** [comment]
> This PR looks good to me. However, why are there still two pagination components?
> 
> 
> 
> Screenshot 2024-01-29 at 8 11 16 AM
> 
> 
> 
> cc @rupali-codes @CBID2 @Anmol-Baranwal 

Ooh, good catch @aftabrehan. I'm not too sure

**Review by rupali-codes — APPROVED** [review]
lgtm

**Comment by mfrezghi** [comment]
Thank you!

**Comment by Anmol-Baranwal** [comment]
> Thank you!

Thank you for your contribution!
We was slightly busy due to rebranding, but we truly appreciate your contribution 🙌
There might be more issues now, be tuned!

**Comment by mfrezghi** [comment]
Will do. The rebranding looks amazing by the way 🙌

**Pull request merged**
