### PR TITLE
iot

### PR DESCRIPTION
**Pull request by k-deepak04**

### CODE REVIEW

**Comment by CBID2** [comment]
This was already merged in #1366 @k-deepak04

**Comment by k-deepak04** [comment]
> This was already merged in #1366 @k-deepak04

no this one is different christy, i have added one more subcategory named raspberry pi and added resources in that.

**Review by CBID2 — APPROVED** [review]
Hi @k-deepak04! 😄 Thanks for clarification! :)  I made a few tweaks to your descriptions, and now it looks pretty good.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
