### PR TITLE
added external link icon to visit site link

### LINKED ISSUE #150: [Feature] Add external link icon to the 'Visit site' link
### Description

Hi! The 'Visit site' links are external links, maybe would be a better UI/UX, if we add an external link icon to this links.

### Screenshots

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by yashnirmal**
## Fixes Issue

Closes #150

## Changes proposed

Added an external link icon to the 'visit site' link which is shown on hover

## Screenshots
Screenshot from 2023-02-09 19-33-15

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
Ig we should use display the icon regularly not only on `hover`.
also, use this icon `BsBoxArrowUpRight`
image

**Comment by yashnirmal** [comment]
> Ig we should use display the icon regularly not only on `hover`. also, use this icon `BsBoxArrowUpRight` image

Ok got it

**Comment by yashnirmal** [comment]
@rupali-codes can you check now, I made the changes. I should be good now

**Review by rupali-codes — APPROVED** [review]
Looks good, thank you

**Pull request merged**
