### PR TITLE
added postman and cypress to testing/backend

### LINKED ISSUE #1873: [Add] Postman and Cypress in subcategory testing / backend
### Site URL

https://www.postman.com/ , https://www.cypress.io/

### Description of the above provided site

Postman :- Postman is a popular API testing tool that simplifies the process of sending HTTP requests to test and analyze web services. It allows developers to create, organize, and automate API tests, making it a valuable tool for ensuring the functionality and reliability of web applications.

cypress :- Cypress is an end-to-end testing framework for JavaScript applications. It runs in the browser and provides a simple, yet powerful API for writing and running tests. Cypress is a good choice for teams that need to test their JavaScript applications quickly and easily.

### Category

Backend

### Sub Category

testing

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by Abhishek19-dev**
## Fixes Issue

closes #1873

## Changes proposed

a) Added links to Postman and Cypress resources in the "Testing" subcategory of the backend.
b) Updated the subcategory's content to include brief descriptions of Postman and Cypress.
c) Ensured that the new links are well-formatted and functional.
d) Organized the subcategory to maintain consistency with existing resources.
e) Verified that the links accurately direct users to the relevant Postman and Cypress resources.

## Screenshots
Screenshot 2023-10-07 at 2 43 48 AM

### CODE REVIEW

**Comment by CBID2** [comment]
@Abhishek19-dev, check this comment please: https://github.com/rupali-codes/LinksHub/issues/1873#issuecomment-1751438321

**Comment by Abhishek19-dev** [comment]
> @Abhishek19-dev, I placed your pull request in draft mode. Check this comment and let me know if you had reviewed it: [#1873 (comment)](https://github.com/rupali-codes/LinksHub/issues/1873#issuecomment-1751438321)

I will take care of this from the next time. Also I have reviewed it.

**Review by CBID2 — APPROVED** [review]
Well done @Abhishek19-dev! :) @Anmol-Baranwal, it's your turn

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Pull request merged**
