### PR TITLE
feat: Added New Resource of Resend in Backend Category (#2420)

### LINKED ISSUE #2420: [ADD] Backend -> Email Providers
Want to Add Resend resource Link

### PR DESCRIPTION
**Pull request by Rx-Metallica**
Closes #2420 
Added New Resource of Resend in Backend Category

"The best way to reach humans instead of spam folders. Deliver transactional and marketing emails at scale."

### CODE REVIEW

**Review by rupali-codes — APPROVED** [review]
lgtm

**Comment by Rx-Metallica** [comment]
Fixes closes #2422 
Hence added resources

**Comment by rupali-codes** [comment]
@Rx-Metallica could you please resolve merge conflicts?

**Comment by Rx-Metallica** [comment]
> @Rx-Metallica could you please resolve merge conflicts?

can you able to help me with the merge conflicts  pls?

**Comment by rupali-codes** [comment]
> > @Rx-Metallica could you please resolve merge conflicts?
> 
> can you able to help me with the merge conflicts pls?

A conflict occurs when you have made the changes in a line and that line got updated in the main branch. So, you will to select among the changes you have made and changes in the main branch, carefully. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Pull request closed without merging**
