### PR TITLE
Added dsa 90 days roadmap link in others category

### LINKED ISSUE #2200: [Add] Adding a 90-Day DSA Roadmap Article by Takeuforward in the "Others" Category
### Site URL

https://takeuforward.org/interviews/most-trusted-90-days-roadmap-to-placement-guaranteed/

### Description of the above provided site

**takeUForward** offers high quality articles on data structures and algorithms. They provide roadmaps to master DSA in given time. It also helps users to revise the concepts efficiently.

This article by takeUForward explains how to master and revise DSA for placement preparation with a roadmap for 90days

### Category

Other

### Sub Category

roadmaps

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Mathi-Alagan**
## Fixes Issue

Closes #2200 

## Changes proposed

To add the DSA 90 days roadmap to placement link in the others category roadmap section.

## Screenshots

image

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
What command did you run? Have you updated the dependencies? `pnpm-lock.yaml is changed`

**Comment by Mathi-Alagan** [comment]
> What command did you run? Have you updated the dependencies? `pnpm-lock.yaml is changed`

I installed pnpm, and ran the command **pnpm run dev**, but it throws exception. So I ran it using **npm run dev**. Now I have reverted the commit.

**Comment by Mathi-Alagan** [comment]
> @Mathi-Alagan can you please uncommit `pnpm-lock.yml`

@rupali-codes I have reverted the commit back, kindly review it once more and say any other changes to be made

**Review by CBID2 — APPROVED** [review]
LGTM! 😁 @Anmol-Baranwal, your turn

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Comment by Mathi-Alagan** [comment]
@rupali-codes could you review this pull request?

**Comment by Anmol-Baranwal** [comment]
> @rupali-codes could you review this pull request?

@rupali-codes @aftabrehan 
Please review and merge it :)

**Comment by CBID2** [comment]
@aftabrehan, can you review and merge this please?

**Review by aftabrehan — APPROVED** [review]
Excellent PR, @Mathi-Alagan 💯

**Pull request merged**
