### PR TITLE
search query

### LINKED ISSUE #1518: [BUG] searchbar query persist even after clearing the searchbar
### Description

after writien anything the searchbar query still persist there in the url

### Screenshots

https://github.com/rupali-codes/LinksHub/assets/96341431/2653b0f1-2450-4634-9b13-2fc5983511b3

### Any additional information?

there is one more issue that all dropdown open up after clearing the searched word.

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by k-deepak04**
## Fixes 
Closes #1518 

## Changes proposed
In our original code, we implemented a custom hook named useSidebarSearch to manage the functionality of searching within the sidebar. We encountered an issue where the search query remained in the URL even after users cleared the search bar. Our objective was to address this issue and ensure that the query parameter would be removed from the URL when the search bar was empty.

To tackle this problem, we introduced an else block within the `useEffect` of the `useSidebarSearch` hook. Within this else block, we checked whether the debouncedSearch (the search query) had a length greater than 0. If it did not, we used the `router.push` function to navigate to the same /search route, employing specific options:

We utilized `undefined` as the second argument. By doing so, we effectively cleared the existing query parameter from the URL.
We employed `shallow: true` as the third argument in order to ensure that the navigation remained shallow. This prevented the unmounting and remounting of page components, effectively avoiding a complete page reload.
By incorporating this else block, we successfully managed the scenario where the search bar was empty. Consequently, we were able to remove the query parameter from the URL. This resolution effectively addressed the issue of the search query persisting in the URL even after users cleared the search bar.

In summary, the modifications we made to the `useEffect` within the `useSidebarSearch` hook included an else block that efficiently cleared the query parameter from the URL when the search bar was empty. This modification successfully resolved the issue we encountered with the search query lingering in the URL.

## Screenshots

https://github.com/rupali-codes/LinksHub/assets/96341431/95797b5b-abd8-49bb-b4a0-562977c2b259

### CODE REVIEW

**Comment by rupali-codes** [comment]
@k-deepak04 please improve your PR title :)

**Review by rupali-codes — COMMENTED** [review]
@k-deepak04 can u please brief me about what changes you've made here

**Comment by k-deepak04** [comment]
> @k-deepak04 can u please brief me about what changes you've made here

In our original code, we implemented a custom hook named useSidebarSearch to manage the functionality of searching within the sidebar. We encountered an issue where the search query remained in the URL even after users cleared the search bar. Our objective was to address this issue and ensure that the query parameter would be removed from the URL when the search bar was empty.

To tackle this problem, we introduced an else block within the useEffect of the useSidebarSearch hook. Within this else block, we checked whether the debouncedSearch (the search query) had a length greater than 0. If it did not, we used the router.push function to navigate to the same /search route, employing specific options:

We utilized 'undefined' as the second argument. By doing so, we effectively cleared the existing query parameter from the URL.
We employed { shallow: true } as the third argument in order to ensure that the navigation remained shallow. This prevented the unmounting and remounting of page components, effectively avoiding a complete page reload.
By incorporating this else block, we successfully managed the scenario where the search bar was empty. Consequently, we were able to remove the query parameter from the URL. This resolution effectively addressed the issue of the search query persisting in the URL even after users cleared the search bar.

In summary, the modifications we made to the useEffect within the useSidebarSearch hook included an else block that efficiently cleared the query parameter from the URL when the search bar was empty. This modification successfully resolved the issue we encountered with the search query lingering in the URL.

**Comment by k-deepak04** [comment]
@rupali-codes hope this provides a clear overview of the change and the issue that was there. 
this one thing took me a lot of time to figure out where it was going wrong, able to debug this and still one issue persist of the opening dropdown of all categories if you can help me in that please do :)

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by abhijithmuthyala** [comment]
Query that the user types in is a *local* state i.e, it is only used to show suggestions as the user types. So from the user's perspective, clearing the input field is *not* equivalent to submitting the `form` and/or navigating to a different page. Navigation should only happen when the user *intentionally* submits the `form`. The user might have cleared the `input` with an intention to search for a different resource and that shouldn't trigger a page navigation.

Consider these user actions:  Visits home page -> Searches for 'ai' -> Clears the `input` -> Searches for 'frontend'.
Expected browser history: `/` <-> `/search?query=ai` <-> `/search?query=frontend`.
With this PR: `/` <-> `/search?query=ai` <-> `/` <-> `/search?query=frontend`.

When you load the page, it is initially rendering the `/` route, then rendering the `/search` route and then going back to `/` route. Whats even worse is that on smaller screens, every time the user opens the menu button, this is the sequence of rendering assuming the current url is `/search?query=frontend` - `/search?query=frontend` -> `/search` -> `/` -> `/search?query=frontend`. So much of unnecessary work just to open the side bar.

In my opinion, this actually unlocks a whole new range of bugs combined with the already existing bugs in the `Searchbar` and `SideNavbar`.

**Comment by rupali-codes** [comment]
@k-deepak04 could you please resolve the merge conflicts?

**Comment by k-deepak04** [comment]
@rupali-codes as explained by @abhijithmuthyala i also guess this isn't correct way to do the thing so please this PR.

**Comment by rupali-codes** [comment]
> @rupali-codes as explained by @abhijithmuthyala i also guess this isn't correct way to do the thing so please this PR.

alright..thanks

**Pull request closed without merging**
