### PR TITLE
chore: Added Quine Resources

### LINKED ISSUE #1188: [Add] Quine Resources
### Site URL

https://www.youtube.com/playlist?list=PLnCV5fTAsUgpaLMY_Z8FqPxZ89v-_pcfY

### Description of the above provided site

- Quine is a open source platform where user can add project and rank your project by getting likes and comments.
- Quine provide a platform where any newbie contributor can go for the `good first issue` and enter into the open source world.
- This playlist will help to those contributor who want to explore quine or new on the quine platform.
- Having a best content with best guidance.

### Category

Open Source

### Sub Category

Videos

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## Fixes Issue - 1188

Closes #1188 

## Changes proposed

Added quine resources

https://www.youtube.com/playlist?list=PLnCV5fTAsUgpaLMY_Z8FqPxZ89v-_pcfY

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@rupali-codes please review this pull request

**Comment by Avdhesh-Varshney** [comment]
@rupali-codes ma'am i requested to merge this pull request under gssoc'23

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by rupali-codes — CHANGES_REQUESTED** [review]
the codebase isn't updated, could you please update the code with `linkshub:main`?? we no longer have _opensource_blogs.json_ it this _database/open_source/blogs.json_

**Review by k-deepak04 — CHANGES_REQUESTED** [review]
@Avdhesh-Varshney please resolve the conflict as the code is changed, rebase the code with the main branch and work again on this.

**Pull request closed without merging**
