### PR TITLE
Updated: added different website

### PR DESCRIPTION
**Pull request by priyankarpal**
Added new websites.

image

image

### CODE REVIEW

**Comment by rupali-codes** [comment]
Hi, could you please resolve conflicts?

**Comment by priyankarpal** [comment]
> Hi, could you please resolve conflicts?

just creating another PR

**Comment by rupali-codes** [comment]
@priyankarpal You don't have to create a new PR. just try to resolve the conflicts, keep the changes you've made and remove other. and when showing which you haven't then just remove those and keep the changes of main branch

**Comment by priyankarpal** [comment]
Resolved.

**Review by rupali-codes — APPROVED** [review]
thanks

**Pull request merged**
