### PR TITLE
add: slaying the dragon youtube channel for web-development

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Changes proposed

- Added new youtube channel named `Slaying the dragon` under web development
- The `Slaying the dragon` is one if the best youtube resource on web development so i added this to the `json` file

## Screenshot
Screenshot 2023-05-27 at 21-02-24 LinksHub A hub of ready-to-use tech resources

### CODE REVIEW

**Review by pratyushmp — APPROVED** [review]
Looks good @0xabdulkhalid

**Comment by 0xabdulkhalid** [comment]
Glad to hear that @pratyushmp !

**Review by CBID2 — APPROVED** [review]
This is a lovely description @0xabdulkhalid! 😊 LGTM! 🙂

**Comment by 0xabdulkhalid** [comment]
@CBID2 can i know why GGSoC'23 and level-1 badge has not been added to this pr ?

Because in another project's pr the assignee added badges for pr also, you  can look at below screenshot

Screenshot 2023-05-28 at 08-21-52 Build software better together

-----
Regards

**Comment by CBID2** [comment]
Sorry for the mishap @0xabdulkhalid. I was out for the moment. The labels have been added

**Pull request merged**
