### PR TITLE
feat: add upvote system

### LINKED ISSUE #1853: feat: add upvoting system for resources & create firestore db
1. Add `database`, we would need database to store `user's data`, the `resources` and feedbacks in different documents

   - We will use Firestore with security rules.

2. Create `upvoting` system for resources so that LinksHub user's can filter out the resources and use LinksHub more effortlessly 

   - We will follow proper logic and it will be synced from firestore database
   - We will focus on two main things:
      - A authenticated user can only upvote a resource once
      - Keep count of how many times a resource has been updated
      - Keep count of upvoted resources by a user (not necessary depending upon the logic)

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
## Fixes Issue

Closes #1853 

## Changes proposed

I've added upvote system to all the resources using firebase firestore db. 

## Screenshots

https://github.com/rupali-codes/LinksHub/assets/91741581/37b1a6b6-c160-4132-a40c-dfd4c4d5c239

### CODE REVIEW

**Comment by CBID2** [comment]
Hmm...it seems that deployment failed. @rupali-codes, can you help fix this issue?

**Comment by Vidip-Ghosh** [comment]
> image
> 
> I'm sorry for being late

@rupali-codes please run `npm install firebase` in your system. 
I haven't pushed the changes of `package.json` that's why it gave error.

**Comment by Anmol-Baranwal** [comment]
> > image
> > I'm sorry for being late
> 
> @rupali-codes please run `npm install firebase` in your system. I haven't pushed the changes of `package.json` that's why it gave error.

Push all the changes, we will have to restructure this probably.

**Comment by Vidip-Ghosh** [comment]
> > > image
> > > I'm sorry for being late
> > 
> > 
> > @rupali-codes please run `npm install firebase` in your system. I haven't pushed the changes of `package.json` that's why it gave error.
> 
> Push all the changes, we will have to restructure this probably.

Yes I've pushed the changes. Please check now.

**Comment by rupali-codes** [comment]
@Vidip-Ghosh & @Anmol-Baranwal its showing this error

image

**Comment by Anmol-Baranwal** [comment]
Both needs to be updated. Env credentials in vercel, and this updating in local environment of @Vidip-Ghosh

**Comment by Vidip-Ghosh** [comment]
Screenshot 2023-10-29 at 19 32 56
@rupali-codes it even stopped working in my system also. I am using codespaces but it's showing this.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Is there any issue with deployment here as with vidip PR?

**Comment by Vidip-Ghosh** [comment]
https://github.com/rupali-codes/LinksHub/assets/91741581/9954681a-2b7c-44ea-93a6-fcc37be770cf

Working of upvote feature after change in logic

**Comment by Vidip-Ghosh** [comment]
> > LinksHub.mp4
> > Working of upvote feature after change in logic
> 
> After clicking, the icon's state should change to 'filled,' indicating to the user that the upvote feature has worked. Clicking again will remove the upvote and decrease the count. I gave you both the icons in the very start for this purpose.

Okay I got it

**Comment by Vidip-Ghosh** [comment]
https://github.com/rupali-codes/LinksHub/assets/91741581/37d6229a-d286-42bf-8aff-d650a97f6883

**Comment by Vidip-Ghosh** [comment]
https://github.com/rupali-codes/LinksHub/assets/91741581/10d5434c-af15-455c-8954-514a533f9a8f

Since `addDoc` method caused creation of same document multiple times when an API is hit, I changed the method to `setDoc` which maintained the uniqueness of the document & whenever an API is hit for upvote, it checks if the document exists & then upvotes the resources accordingly. If user clicks the button again, then upvote decreases.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please see the deployment error. We need to add those vars to vercel account.

**Comment by rupali-codes** [comment]
@Vidip-Ghosh are you done with this feature? because we wanna test it locally, its hard to see in vercel why the deployment is failing

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh are you done with this feature? because we wanna test it locally, its hard to see in vercel why the deployment is failing

Yes I have.

**Comment by Anmol-Baranwal** [comment]
I will check it tomorrow :)

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
@vidip @rupali-codes 

I reviewed it locally and this is what I noticed:

1. whenever we click upvote icon for any resource:

> Works correctly and the upvote count is synchronized.

image

> Unnecessary document: and the upvote count is not synchronized

Whenever we upvote, two documents with same data is created. So, we need to remove this one.

image

Console message says that, we are increasing upvote count, decreasing and then again increasing which maybe due to two documents.

image

2. I will try to fix these errors by myself, and it may resolve the issue.
image

---

I did a little change to firebaseConfig to check existing apps, which I thought would resolve the issue but it didn't.

image

**Comment by Anmol-Baranwal** [comment]
I will address the errors later (on 15th). If you can do it before then, please do it.

**Comment by rupali-codes** [comment]
image

**Comment by Vidip-Ghosh** [comment]
> @Vidip @rupali-codes
> 
> I reviewed it locally and this is what I noticed:
> 
> 1. whenever we click upvote icon for any resource:
> 
> > Works correctly and the upvote count is synchronized.
> 
> image
> 
> > Unnecessary document: and the upvote count is not synchronized
> 
> Whenever we upvote, two documents with same data is created. So, we need to remove this one.
> 
> image
> 
> Console message says that, we are increasing upvote count, decreasing and then again increasing which maybe due to two documents.
> 
> image
> 
> 2. I will try to fix these errors by myself, and it may resolve the issue.
>    image
> 
> I did a little change to firebaseConfig to check existing apps, which I thought would resolve the issue but it didn't.
> 
> image

Will look after duplicates and make changes as soon as I am free.

**Review by CBID2 — APPROVED** [review]
Looks pretty good on my end! :) @rupali-codes and @Anmol-Baranwa, what do you think?

**Review by Anmol-Baranwal — COMMENTED** [review]
@Vidip-Ghosh 
See if it's working, because upvote count is not updating even though the data is properly stored. 

Also, please remove console if it's not important.

Just a advice, no need to follow it.
You can create an environment variable and set it to a value that allows you to see console messages only during testing. This way, it won't be seen in the production state.

**Comment by Vidip-Ghosh** [comment]
Screenshot 2023-12-22 at 21 51 11
In deployed one, its showing this error. 

> @Vidip-Ghosh See if it's working, because upvote count is not updating even though the data is properly stored.
> 
> Also, please remove console if it's not important.
> 
> Just a advice, no need to follow it. You can create an environment variable and set it to a value that allows you to see console messages only during testing. This way, it won't be seen in the production state.

**Comment by Anmol-Baranwal** [comment]
It should work if you're using api serverless routes.

What do you think is the problem here?

**Comment by Vidip-Ghosh** [comment]
https://github.com/rupali-codes/LinksHub/assets/91741581/01c93f63-182a-4133-a566-850d7bc06959

**Comment by Vidip-Ghosh** [comment]
> It should work if you're using api serverless routes.
> 
> What do you think is the problem here?

I think env variables should be used in vercel deployment.

**Comment by Vidip-Ghosh** [comment]
@Anmol-Baranwal now what to do?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal now what to do?

One of us will check it locally. 
We just have to update the code, since I already setup the code earlier.

@rupali-codes 
If you can do it before 28th then do it. I will only be able to do it after exam.

**Comment by rupali-codes** [comment]
> > @Anmol-Baranwal now what to do?
> 
> One of us will check it locally. We just have to update the code, since I already setup the code earlier.
> 
> @rupali-codes If you can do it before 28th then do it. I will only be able to do it after exam.

are you able to do it now?

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Merge it and we can check the issues combines on auth_firebase.

Because we still have to match this and the new design `dev` branch.

There are going to be conflicts anyway.

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by CBID2** [comment]
Found some merge conflicts in here

**Comment by Vidip-Ghosh** [comment]
> Found some merge conflicts in here

I need to then synchronize this branch with main branch

**Comment by Anmol-Baranwal** [comment]
> > Found some merge conflicts in here
> 
> I need to then synchronize this branch with main branch

No worries, we will cover it next.

**Comment by Anmol-Baranwal** [comment]
@Vidip-Ghosh 
Is this ready.

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh Is this ready.

Yes, only few things are left.

**Comment by rupali-codes** [comment]
> > @Vidip-Ghosh Is this ready.
> 
> Yes, only few things are left.

Any updates on this Vidip

**Comment by Vidip-Ghosh** [comment]
> > > @Vidip-Ghosh Is this ready.
> > 
> > 
> > Yes, only few things are left.
> 
> Any updates on this Vidip

Upvote logic needs to be updated as per given scenario (i.e. migration to firestore). So I am working on that.

**Comment by Vidip-Ghosh** [comment]
@rupali-codes for now you can merge this PR. I tried to work on changing logic also, but couldn't get success.

**Comment by Vidip-Ghosh** [comment]
Screenshot 2024-03-22 at 18 38 39
Here is what I get whenever I call that `/api`. Currently datas are moved to firebase, but will change upvote logic in another PR.

**Comment by Anmol-Baranwal** [comment]
Yep, we shouldn't keep a Open PR for several months -> it degrades the algo.

**Review by rupali-codes — COMMENTED** [review]
image

**Comment by Vidip-Ghosh** [comment]
> image

Run `npm install`

**Comment by Vidip-Ghosh** [comment]
Screenshot 2024-04-01 at 18 03 55
See @rupali-codes database URL looks like this. Just have a look & let me know if any changes.

**Comment by Vidip-Ghosh** [comment]
@rupali-codes @Anmol-Baranwal any updates on this?

**Comment by rupali-codes** [comment]
> @rupali-codes @Anmol-Baranwal any updates on this?

can you please resolve conflicts?

**Comment by Vidip-Ghosh** [comment]
> > @rupali-codes @Anmol-Baranwal any updates on this?
> 
> can you please resolve conflicts?

Yes done

**Review by rupali-codes — APPROVED** [review]

**Comment by rupali-codes** [comment]
HI @Vidip-Ghosh and @Anmol-Baranwal, its throwing some unusual errors, but i'll merge it for now, and if it fails in production then we'll have to revert this PR

**Pull request merged**
