### PR TITLE
[DOCS]: Replace linkshub.vercel.app with linkshub.dev in SECURITY.md file

### PR DESCRIPTION
**Pull request by pankajdharmik4**
## Fixes Issue

Closes #1669

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @pankajdharmik4. Thanks for submitting your contribution! :) I temporarily closed your PR because Rupali assigned herself to do it, so I'm going to ask her if it's ok if you address this issue. If she accepts, you will be assigned to the issue and tag me or @Anmol-Baranwal to reopen your PR. If she refuses, then the PR will remain closed. In the future, please review [the Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#linkshub-contributing-guidelines) thoroughly before making a PR.

**Comment by pankajdharmik4** [comment]
Yaa please ask her else i have updated the security.md file and now it looks fine to me.

**Comment by Anmol-Baranwal** [comment]
@CBID2 

Please reopen this. Since, this is a minor change so it doesn't impact anything. @rupali-codes won't mind this.

**Comment by CBID2** [comment]
> @CBID2 
> 
> 
> 
> Please reopen this. Since, this is a minor change so it doesn't impact anything. @rupali-codes won't mind this.

Hi @Anmol-Baranwal. We haven't assigned it to them, which we stated in the Contributing Guide that we don't want that regardless if the issue is minor or major. By defying that rule, it sets a precedent to other contributors that can make pull requests without our approval.

**Comment by Anmol-Baranwal** [comment]
> > @CBID2 
> > 
> > 
> > 
> > Please reopen this. Since, this is a minor change so it doesn't impact anything. @rupali-codes won't mind this.
> 
> Hi @Anmol-Baranwal. We haven't assigned it to them, which we stated in the Contributing Guide that we don't want that regardless if the issue is minor or major. By defying that rule, it sets a precedent to other contributors that can make pull requests without our approval. 

Oh! 

Okay, I thought it was assigned to him.

**Comment by CBID2** [comment]
> > > @CBID2 
> > > 
> > > 
> > > 
> > > Please reopen this. Since, this is a minor change so it doesn't impact anything. @rupali-codes won't mind this.
> > 
> > Hi @Anmol-Baranwal. We haven't assigned it to them, which we stated in the Contributing Guide that we don't want that regardless if the issue is minor or major. By defying that rule, it sets a precedent to other contributors that can make pull requests without our approval. 
> 
> Oh! 
> 
> Okay, I thought it was assigned to him. 

No it wasn't

**Comment by rupali-codes** [comment]
@pankajdharmik4 & @CBID2 yeah it wasn't assigned to them, and as Chirssy, its against the rules, one shouldn't start working without the issue being assigned to them. 

@pankajdharmik4 Please ask the maintainers before start working on any issue. In case the issue is locked, kindly tag us in our [discord server](https://discord.gg/zxWTdcyC). 

Thanks

**Pull request closed without merging**
