### PR TITLE
Added hover effect on buttons of main page

### LINKED ISSUE #2409: [OTHER] Add hover effect on buttons of main page
### What would you like to share or ask?

Adding hover on the buttons will enhance the user experience. Please add a background colour transition on the following buttons:

image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by ompharate**
Closes #2409 

## Changes proposed
- Added a background color transition effect to the buttons on the main page to enhance user experience.
- Implemented dynamic styling for hover effects using inline styles with React `useState` for managing hover state.
- Ensured smooth transitions with a duration of 0.3s using the `transition` CSS property.

## Screenshots
 - on hover:

## Note to reviewers
Please review the hover effects added to the buttons on the main page. The background color transitions should provide a smooth visual feedback when hovered over.

### CODE REVIEW

**Comment by rupali-codes** [comment]
@ompharate please read and follow our Contributing guidelines before start to working on any issue. You can't work on any issue before getting assigned.

**Comment by ompharate** [comment]
@rupali-codes ok. Could you please assign this issue to me?

**Comment by rupali-codes** [comment]
> [ompharate](/ompharate)

Please comment on the issue to get assigned.

**Comment by ompharate** [comment]
@rupali-codes  do I recreate the pull request ?

**Comment by rupali-codes** [comment]
> @rupali-codes do I recreate the pull request ?

No, you don't have to

**Review by CBID2 — APPROVED** [review]
Looks good on my end @rupali-codes

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
