### PR TITLE
chore: Reduce copyright font-size for small screens

### LINKED ISSUE #1625: [OTHER] Reduce copyright font-size for small screens
### What would you like to share or ask?

The font-size of copyright text in footer doesn't look good. It would be better if we can add some spacing and styling to it

image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by hona9**
Closes #1625

## Fixes Issue
Reduce copyright font size for small screens

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks good on my end.

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
The main purpose of the issue was this:

> Image
image

> Changes pushed
image

Please adjust the code accordingly.

**Comment by hona9** [comment]
@Anmol-Baranwal Can you please check and let me know if it needs more fixing?

**Review by Anmol-Baranwal — COMMENTED** [review]
I think this is appropriate.

image

What about this?
image

**Comment by hona9** [comment]
I can put it in separate lines, but I don't think it will look that good. @Anmol-Baranwal 
What do I do?

**Comment by Anmol-Baranwal** [comment]
Yeah I agree. 

Let @rupali-codes decide.

**Comment by rupali-codes** [comment]
> Yeah I agree.
> 
> Let @rupali-codes decide.

@hona9 please do it, then we'll see

**Review by rupali-codes — CHANGES_REQUESTED** [review]
it looks nice though, could you please increase font-size a little. And make it same size for each screen :)

Thanks

**Review by rupali-codes — APPROVED** [review]
looks great to me :)

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Pull request merged**
