### PR TITLE
feat: add icons component and improve codebase structure

### LINKED ISSUE #2315: [Refactor] improve codebase structure & our team section
### File Name

Targeting whole codebase

### Reason for Refactoring the Code

- Refactoring our team section (using `clsx` & `tw-merge`) to write a better code.
- Creating a new Icons system so that we can use SVG icons with ease -> improves codebase structure. (using `lucide-icons`)
   - We won't have to use the small bundle in different components and we can just import at one place.
- Add priority loading to all the images and use the recent `next/legacy/image` components.
- fix all linting errors

@rupali-codes 
Should I add a classnames order plugin so it will automatically arrange the tailwind classnames in the correct order.

I want to do this myself. Which of the points do you think is relevant to the current codebase? Let me know and I will cover all of them in a single PR.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).

### LINKED ISSUE #2317: [OTHER] Missing Report a Bug
### What would you like to share or ask?

I was working on the icons component issue and I noticed something strange.

`Report a bug` is missing from the sidebar.

sidebar

You can view the [figma](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?type=design&node-id=17-231&mode=design&t=cyWeHoIr7pJt3LW2-0) here.

@rupali-codes @aftabrehan @CBID2 
What do you think? Did we miss it.

Because I can see the code in Sidebar component
image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

fixes #2317, fixes #2315 

## Changes proposed

- Created a new Icons component: `components/icons.tsx`

icons

Now:
- We directly avoid any duplicate imports from the same type of category like `fa`, and `fa6`.
- Anyone can easily add it there itself (a custom svg), or any imported one.
- We can keep track of what icons are used. Plus, the icons are only loaded once so it improves the time.
- Easier to debug, and this improves the whole structure. Now we can use normal `classNames` to style the icons.
- Removed the `assets/icons` other than `logo.svg`
- Fixed linting errors.
- Added `priority` for images so that they're loaded faster.

> I've properly checked from the original so that there are no visual changes but do check it from your side once.

## Note to reviewers

You can see that I've kept `assets/logo.svg` -> I've included it in the icons component but the viewport of the logo seems to be messy which is causing the issue.  So, I used the previous one.

### CODE REVIEW

**Review by aftabrehan — COMMENTED** [review]
Excellent PR, @Anmol-Baranwal 💪 🚀 💯 

Category content is not taking up full space of the sidebar. Could you please help to check that?

Screenshot 2024-03-23 at 10 11 44 PM

**Comment by Anmol-Baranwal** [comment]
@aftabrehan 
I can't see that unless I view the page at 65%. I've even checked in inspect.

Please check if the same issue is with the original URL, so we can solve it separately.
The problem seems to be with the fixed viewport height, or maybe the spacing of this `report a bug` button.

If you could provide the screen size and instructions on how to check it, I'd be able to solve it properly.

**Review by CBID2 — DISMISSED** [review]
LGTM

**Comment by aftabrehan** [comment]
>I can't see that unless I view the page at 65%. I've even checked in inspect.

I'm using large screen and I can see that on 100%. Let me check the code if I can help.

**Comment by aftabrehan** [comment]
@Anmol-Baranwal, the issue (sidebar category height) is fixed in [this commit](https://github.com/rupali-codes/LinksHub/pull/2318/commits/1bd05324e2c7487e80b39c9e522e082742d9165c).

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 @aftabrehan 
If everything is all right, please review and merge this!

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by rupali-codes — COMMENTED** [review]
Can we put the "Report a Bug" button at bottom-right corner? in the sidebar, there's already a lot for it.
image

Other than it looks fine to me :)

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Should it be sticky or floating in the right corner of the screen, or just at the very end?

Should it appear on all routes, including subcategories, or only on the landing page?

Let me know, and I will change it accordingly.

**Comment by rupali-codes** [comment]
> @rupali-codes Should it be sticky or floating in the right corner of the screen, or just at the very end?
> 
> Should it appear on all routes, including subcategories, or only on the landing page?
> 
> Let me know, and I will change it accordingly.

I think it should be sticky,

**Review by rupali-codes — COMMENTED** [review]
Hi Anmol, please make the button sticky, currently its only showing the button on hompage, but not on the other pages.

Also, make this button it bit smaller, or maybe just remove the text and keep the icon (question mark)

image

**Comment by Anmol-Baranwal** [comment]
> Hi Anmol, please make the button sticky, currently its only showing the button on hompage, but not on the other pages.
> 
> Also, make this button it bit smaller, or maybe just remove the text and keep the icon (question mark)
> 
> image

But removing the text might confuse users because it provides context. If you still want it removed, please let me know, and I'll take care of it.

Also, could you clarify what you mean by 'sticky'? Currently, it's floating (sticky) irrespective of scroll position, but are you suggesting it should be attached to the bottom of the page, visible to users as they scroll down?

**Comment by rupali-codes** [comment]
> > Hi Anmol, please make the button sticky, currently its only showing the button on hompage, but not on the other pages.
> > Also, make this button it bit smaller, or maybe just remove the text and keep the icon (question mark)
> > image
> 
> But removing the text might confuse users because it provides context. If you still want it removed, please let me know, and I'll take care of it.
> 
> Also, could you clarify what you mean by 'sticky'? Currently, it's floating (sticky) irrespective of scroll position, but are you suggesting it should be attached to the bottom of the page, visible to users as they scroll down?

For the first one, lets keep the text but make it smaller. And secondly, the button only showing on main/home page, its supposed to be shown on other pages as well, like category page and resource page.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Done! I've created a component because we're using it in several places, and please check the styling in the light theme. I tried various options, and this one seemed appropriate. Let me know if any changes are needed.

**Review by rupali-codes — COMMENTED** [review]
@Anmol-Baranwal it looks perfect, just one thing, there's a transition delay when changing the theme

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @aftabrehan @CBID2 
The changes are done and final. Please review and merge this to avoid any conflicts.

**Review by CBID2 — DISMISSED** [review]
Looks great

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I've resolved conflicts if that helps!

**Review by rupali-codes — COMMENTED** [review]
@Anmol-Baranwal there's a small bug, when you click on theme toggler on the resource page, and then click back on the toggler, its closing the sidebar menu

https://github.com/rupali-codes/LinksHub/assets/78981177/805cd06c-c439-4102-960f-7825c33eedf9

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal there's a small bug, when you click on theme toggler on the resource page, and then click back on the toggler, its closing the sidebar menu
> 
>  LinksHub.-.Brave.2024-04-20.12-33-02.mp4

Is this related to this PR?
It would be great if someone else can handle it in another PR.
Because this just improves the icon based system and little codebase structure (nothing related to functionality).

**Comment by rupali-codes** [comment]
> > @Anmol-Baranwal there's a small bug, when you click on theme toggler on the resource page, and then click back on the toggler, its closing the sidebar menu
> > LinksHub.-.Brave.2024-04-20.12-33-02.mp4
> 
> Is this related to this PR? It would be great if someone else can handle it in another PR. Because this just improves the icon based system and little codebase structure (nothing related to functionality).

it's not on the main side, it belongs to this PR only

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I don't see the bug and neither can I replicate it.

See the video [here](https://jam.dev/c/4aa8f16f-d649-4790-a8bd-90a84639b91c).

**Comment by rupali-codes** [comment]
> @rupali-codes I don't see the bug and neither can I replicate it.
> 
> See the video [here](https://jam.dev/c/4aa8f16f-d649-4790-a8bd-90a84639b91c).

Okay then, i'm merging this PR for now,

**Pull request merged**
