### PR TITLE
Saasinterface

### LINKED ISSUE #242: [Add] SaasInterface
### URL

https://saasinterface.com/

### Description of the above provided site

Save yourself hours of research and create beautiful apps by taking inspiration from the best SaaS products.

### Category

Frontend

### Sub Category

design inspirations

### PR DESCRIPTION
**Pull request by parma1111**
## Fixes Issue

Closes #242 

## Changes proposed

it will save the time for beautiful product design research

## Screenshots

Screenshot (788)

## Note to reviewers

Any kind of feedback will be appreciated

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Content-wise, your PR looks great! :) Branch wise, don't push into the main as it makes it difficult the PR to be merged.

**Comment by parma1111** [comment]
> Content-wise, your PR looks great! :) Branch wise, don't push into the main as it makes it difficult the PR to be merged.

now review the pr

**Review by CBID2 — APPROVED** [review]
LGTM! 😀

**Comment by parma1111** [comment]
> One more thing @Parma11111!:) Don't create PR direclty to base: main instead, select base:dev from the dropdown. Other than LGTM! 😀

From now I will push in base: dev

**Pull request merged**
