### PR TITLE
removed the underline and solved the issue1615

### LINKED ISSUE #1615: [Refactor] Remove the underline from the copyright section
### File Name

components/Footer/Footer.tsx

### Reason for Refactoring the Code

Screenshot 2023-08-22 at 9 38 35 AM

This does not look goof

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).

### PR DESCRIPTION
**Pull request by Sahilll15**
## Fixes Issue
Closes #1615 

## Changes proposed

Changes made:- removed the underline from the copyright text 
i.e from Rupali Haldaiya and Open Source Community

## Screenshots
Screenshot 2023-08-22 at 8 34 22 PM

## Note to reviewers
Made Changes in components/Footer/Footer.tsx

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
I would strongly oppose this change, as underlining provides the impression that a text is a hyperlink. Removing the underline could confuse many users, and it would have a negative impact on the user experience.

@rupali-codes
Please share your opinion as well.

**Comment by CBID2** [comment]
> I would strongly oppose this change, as underlining provides the impression that a text is a hyperlink. Removing the underline could confuse many users, and it would have a negative impact on the user experience.
> 
> @rupali-codes Please share your opinion as well.

Ooh interesting point @Anmol-Baranwal

**Comment by subhadeepbanerjee2003** [comment]
**I have a suggestion** : Instead of a standard underline, you can create custom underlines with various shapes or patterns.
if we add a `transition` it would give a different look i have tested it .
<br>
[Screencast from 23-08-23 03:19:30 AM IST.webm](https://github.com/rupali-codes/LinksHub/assets/116381157/d14ccf7c-3d0e-458f-afda-84caebf17606)
with small code base.

@Anmol-Baranwal @CBID2

**Comment by CBID2** [comment]
I> **I have a suggestion** : Instead of a standard underline, you can create custom underlines with various shapes or patterns.
> 
> if we add a `transition` it would give a different look i have tested it with small code base.
> 
> <br>
> 
> [Screencast from 23-08-23 03:19:30 AM IST.webm](https://github.com/rupali-codes/LinksHub/assets/116381157/d14ccf7c-3d0e-458f-afda-84caebf17606)  ` watch the video`
> 
> with small code base.
> 
> 
> 
> @Anmol-Baranwal @CBID2 
> 
> 

I can't watch the video @subhadeepbanerjee2003. Is there another way you can embed it here?

**Comment by subhadeepbanerjee2003** [comment]
@Anmol-Baranwal I have given directly from my files and I am not facing any problem. Which problem are you facing?

**Comment by CBID2** [comment]
> @CBID2 I have given directly from my files and I am not facing any problem. Which problem are you facing ? I can send it to your email

I downloaded it and can't view the video for some odd reason.

**Comment by CBID2** [comment]
> > @CBID2 I have given directly from my files and I am not facing any problem. Which problem are you facing ? I can send it to your email
> 
> I downloaded it and can't view the video for some odd reason. Maybe you can screenshot each frame and explain each part?

**Comment by subhadeepbanerjee2003** [comment]
@CBID2 ok sorry to hear that . My point was when any user hover to those part a underline will appear after that as a transition before that no underline will be there.

**Comment by CBID2** [comment]
> @CBID2 ok sorry to hear that . My point was when any user hover to those part a underline will appear after that as a transition before that no underline will be there.

I get that @subhadeepbanerjee2003. I'm just wondering if there's another way to use your video to highlight this idea. I'm having trouble visualizing it.

**Comment by subhadeepbanerjee2003** [comment]
@CBID2 can you give me your email id ?

**Comment by CBID2** [comment]
> @CBID2 can you give me your email id ? 

I don't feel comfortable doing that. Sorry

**Comment by subhadeepbanerjee2003** [comment]
@CBID2 is there any other way ?

**Comment by CBID2** [comment]
> @CBID2 is there any other way ? 

I managed to view the video. Anyway it looks promising

**Comment by subhadeepbanerjee2003** [comment]
@CBID2 nice to hear that and I can work on that

**Comment by Anmol-Baranwal** [comment]
> > @CBID2 can you give me your email id ?
> 
> I don't feel comfortable doing that. Sorry

You can directly tag me. @CBID2 

If there is any problem.

@shubhsharma19 
You can directly convert the video and upload it here. You can put screenshots, you can use extensions.

There are hundreds of solutions.

**Comment by subhadeepbanerjee2003** [comment]
@Anmol-Baranwal thanks for pointing out

**Comment by CBID2** [comment]
> @CBID2 
> 
> image
> 
> 
> 
> image
> 
> 
> 
> image
> 
> 
> 
> 
> 
> > It will be something like this.
> 
> 
> 
> 

What do you think of the issue @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
> > @CBID2
> > image
> > image
> > image
> > > It will be something like this.
> 
> What do you think of the issue @Anmol-Baranwal

I don't believe this will enhance the user experience. In fact, it's worse than having no hyperlink, as relying on aesthetics isn't the solution for most users. Additionally, there are considerations for motor accessibility.

Feel free to ask @rupali-codes for her opinion. She might provide valuable insights.

**Comment by CBID2** [comment]
> > > @CBID2
> 
> > > image
> 
> > > image
> 
> > > image
> 
> > > > It will be something like this.
> 
> > 
> 
> > What do you think of the issue @Anmol-Baranwal
> 
> 
> 
> I don't believe this will enhance the user experience. In fact, it's worse than having no hyperlink, as relying on aesthetics isn't the solution for most users. Additionally, there are considerations for motor accessibility.
> 
> 
> 
> Feel free to ask @rupali-codes for her opinion. She might provide valuable insights.

I was thinking this too. It also could also induce annoyance in the user.

**Comment by subhadeepbanerjee2003** [comment]
@Anmol-Baranwal I think it would be unique but yes opinions can be difference for individuals.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal I think it would be unique but yes opinions can be difference for individuals.

I totally agree.
But you can ask good UX designers, and they will say the same thing. 

If you want to learn more about UX laws: visit https://lawsofux.com/

**Comment by shubhsharma19** [comment]
> **I have a suggestion** : Instead of a standard underline, you can create custom underlines with various shapes or patterns. if we add a `transition` it would give a different look i have tested it with small code base. [Screencast from 23-08-23 03:19:30 AM IST.webm](https://github.com/rupali-codes/LinksHub/assets/116381157/d14ccf7c-3d0e-458f-afda-84caebf17606) ` watch the video` with small code base.
> 
> @Anmol-Baranwal @CBID2

Great suggestion!

**Comment by subhadeepbanerjee2003** [comment]
@Anmol-Baranwal thanks for your info

**Comment by subhadeepbanerjee2003** [comment]
@shubhsharma19 thanks for your appreciation but there are some laws as mentioned by @Anmol-Baranwal so we should follow those.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
What to do with this issue?

**Comment by rupali-codes** [comment]
> @rupali-codes What to do with this issue?

i didn't see the issue earlier, and i guess its better the way it is. Removing underline would confuse the users.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Closing this due to the mentioned reason.

@Sahilll15 
There are open issues with label `up for grabs`. Feel free to comment there, and I will assign you the issue. I hope you understand why we are closing this.

**Comment by subhadeepbanerjee2003** [comment]
I gained some knowledge through this conversation..no loss for me🙃

**Pull request closed without merging**
