### PR TITLE
[docs] Improve the Support Section

### PR DESCRIPTION
**Pull request by sarava338**
## Fixes Issue

Improved the Support Section #2242

## Changes proposed

README.md support section was updated.

## Screenshots

Before
Before

After
After

## Note to reviewers

Can I be a cotributor ?

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @sarava338. I closed your PR because it was not assigned to you yet. Please read our Contributing guide to get started.

**Comment by sarava338** [comment]
> Hi @sarava338. I closed your PR because it was not assigned to you yet. Please read our Contributing guide to get started.

Hi @CBID2, So May I know when #2242 be unlocked

**Comment by CBID2** [comment]
> > Hi @sarava338. I closed your PR because it was not assigned to you yet. Please read our Contributing guide to get started.
> 
> Hi @CBID2, So May I know when #2242 be unlocked and it can be assigned to me ?

I just unlocked it @sarava338. Just mention your name in the comment section.

**Comment by Anmol-Baranwal** [comment]
@sarava338 
Just to let you know, this isn't the correct way to link the issue.

image

What will happen is, even if this pull request is merged; the corresponding issue will not be closed.

You can read this: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by CBID2** [comment]
To add onto @Anmol-Baranwal's point @sarava338, I reopened this PR so no need to create a new one.

**Comment by sarava338** [comment]
> @sarava338 
> Just to let you know, this isn't the correct way to link the issue.
> 
> image
> 
> What will happen is, even if this pull request is merged; the corresponding issue will not be closed.
> 
> You can read this: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Hi @Anmol-Baranwal, oooh, I don't know about this. This is my first OSP. Thanks for letting me know.

**Review by CBID2 — APPROVED** [review]
Great job @sarava33! :) As you continue your open source journey remember the following
1. Read the contributing guide before you start your contribution 
2. Use keywords when linking your issue

**Comment by CBID2** [comment]
@rupali-codes, please approve deployment. 
@Anmol-Baranwal, it's your turn

**Comment by sarava338** [comment]
> Great job @Sarava33! :) As you continue your open source journey remember the following
> 
> 1. Read the contributing guide before you start your contribution
> 2. Use keywords when linking your issue

Yeah sure, Thanks for the advise 👍🏼

**Comment by CBID2** [comment]
@rupali-codes, can you deploy this? It won't merge if you don't.

**Pull request merged**
