### PR TITLE
chore: refactor copy and share components for better accessibility 🪄✨ 

### LINKED ISSUE #1479: [Refactor]: Share and Copy Button Components for Improved Accessibility ⚒️✨
### File Name

components/Share/Share.tsx & components/CopyToClipboard/CopyToClipboard.tsx

### Reason for Refactoring the Code

- Let's take the accessibility of our project to the next level by refactoring both the Share and Copy buttons used in the same component. 
- This refactoring aims to improve the user experience for all users, including those with disabilities, by enhancing accessibility and simplifying the implementation. Here are the improvements we plan to make:

1. Remove unnecessary elements and bloatware from both buttons.
2. Add `role="button"` and `aria-label` attributes for proper semantics and labeling.
3. Simplify the code while ensuring full functionality for both buttons.

### Why Refactor?

Refactoring the Share and Copy buttons will bring the following benefits:

1. **Enhanced Accessibility**: By adding proper attributes and semantics, we ensure that both buttons are accessible to all users, including those using screen readers and assistive technologies.

2. **Cleaner Code**: Removing unnecessary elements will result in cleaner and more maintainable code for the buttons.

3. **Improved User Experience**: A more streamlined and accessible Share and Copy buttons will enhance the overall user experience.

### Scope of Work 

1. Review the existing Share and Copy button implementations.
2. Remove the tooltip `div`, unnecessary event handlers, and any other bloatware.
3. Add `role="button"` and `aria-label` attributes to both button elements.
4. Test the Share and Copy buttons thoroughly for accessibility and functionality.

### Screenshots (Current State)
|COPY|SHARE|
|:---:|:---:|
|image|image|

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).
- [X] I am a GSSoC23 contributor.

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Fixes Issue
Closes #1479 

## Changes proposed
- This PR introduces several significant enhancements to the `CopyToClipboard.tsx` and `Share.tsx` files, focusing on code refactoring and accessibility improvements. The key changes are as follows:
  
  - Code Refactoring: Both `CopyToClipboard.tsx` and `Share.tsx` components have undergone code refactoring to remove unnecessary elements, such as wrapping divs, and improve code readability and maintainability.
 
  - Improved Accessibility: The accessibility of the components has been greatly enhanced. We replaced the `title` attributes with more descriptive and accessible `aria-label` attributes for the icons. Additionally, we introduced `aria-live="polite"` to announce changes to screen readers in a polite manner.

  - Styling Enhancement: The inline styles in the components have been removed, and we now rely on CSS classes for styling. This makes the code more organized and easier to manage.

  - Reduced Bloatware: We have trimmed unnecessary elements and styles, resulting in a leaner and more efficient codebase.

  - Icon Change on Success: When the copy action is successful, the copy icon now changes to a checkmark icon (`FaCheckSquare`). This gives users clear feedback on the success of the copy operation.

  - Resetting Copied Icon: The copied icon now resets back to the original copy icon (`FaRegCopy`) after 2 seconds, ensuring a smoother user experience.

  - With these improvements, the `CopyToClipboard` and `Share` components are now more accessible, efficient, and user-friendly. The PR contributes to the overall enhancement of the repository's codebase and user experience.

## Demonstrating Video

https://github.com/rupali-codes/LinksHub/assets/92252895/13dae5bd-9405-4c4f-ad61-fb23a36922e1

<div align=center>

[ This video will not demonstrates the accessibility feature, but it can demonstrate other changes made in this PR ]

[ My device didn't allow to record the internal audio during recording, So that i can't demonstrate the accessibility feature that announcing `Copy Link` and `Link Copied!` after copying the link. Sorry for the inconvenience.]

</div>

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Hi there @rupali-codes, @CBID2 👋🏻 

 I hope you're doing well. I wanted to let you know about the PR I've created for the `LinksHub`. Initially, I started with the intention of removing unwanted elements during the code refactoring process. However, my passion for accessibility and best practices drove me to dive deeper into enhancing both the `Copy` and `Share` components.

The changes made in this PR bring significant improvements in terms of accessibility, making the components more inclusive and user-friendly. Additionally, I've streamlined the code, removing unnecessary elements and optimizing the overall performance.

I believe these updates will greatly contribute to the core functionality and usability of the project. It would be amazing if you could review and consider merging this PR. Also, to support my work, I'd appreciate it if you could add the `level3` labels to recognize the impact of these enhancements.

Please let me know your thoughts, and I'm open to any feedback or suggestions.

Thank you for your time and consideration.

**Comment by k-deepak04** [comment]
@0xabdulkhalid you changed quite few behaviour , like hover effect also the pop-up that use to come on copying the link from clipboard that.

https://github.com/rupali-codes/LinksHub/assets/96341431/937f0c0d-ad47-4269-ae71-c3885ddcfcdb


@CBID2 @rupali-codes please look into this

**Comment by CBID2** [comment]
> Visit Preview

The accessibility feature works on my end @k-deepak04

**Comment by 0xabdulkhalid** [comment]
@k-deepak04, @CBID2 

You're saying about this Purple Colored Tooltip right ?

image

There's already `title` is present to do that Job, We don't want explicit `p` element to behave like `title`.

The `title` is enough to provide visual clue to the user who have low vision.

**Review by rupali-codes — COMMENTED** [review]
@0xabdulkhalid thanks,, could you also add _tooltip_ here saying **Copy** before user copies the link and **Copied** after clicking on _copy_?

**Comment by 0xabdulkhalid** [comment]
@rupali-codes Yeah, I removed the Tooltip.

Instead i changed icon, So if the user successfully copied the link then the icon with change to success and then after 2 seconds it will revert to normal state (copy icon).

You could investigate the demonstrating videos above.

**Comment by rupali-codes** [comment]
> @rupali-codes Yeah, I removed the Tooltip.
> 
> Instead i changed icon, So if the user successfully copied the link then the icon with change to success and then after 2 seconds it will revert to normal state (copy icon).
> 
> You could investigate the demonstrating videos above.

But its looking kinda confusing, could you please add the tooltip while changing the icon as well? that would be more helpful. And even you can use React-tooltip if you want to, or just add as it was before :) 

Thanks

**Comment by 0xabdulkhalid** [comment]
@rupali-codes as you wish, I will make the tooltip to be viewed once the user copied the link. It will say `Copied!`

**Comment by rupali-codes** [comment]
@0xabdulkhalid could you just make it _Copied_? also _Copy_ on hover :)

**Comment by 0xabdulkhalid** [comment]
Done as you requested @rupali-codes 👍🏻 


https://github.com/rupali-codes/LinksHub/assets/92252895/15a996c8-a2d2-42e9-a797-84030a0b87df

**Comment by rupali-codes** [comment]
its kinda cutting, could u add some margin to it?? then we are good to go

image

**Comment by 0xabdulkhalid** [comment]
## @rupali-codes 👀 


https://github.com/rupali-codes/LinksHub/assets/92252895/d344b333-831b-4749-99ba-d78ee35daabf

**Comment by 0xabdulkhalid** [comment]
## Is this ok @rupali-codes ?


https://github.com/rupali-codes/LinksHub/assets/92252895/d344b333-831b-4749-99ba-d78ee35daabf

**Comment by CBID2** [comment]
> ## Is this ok @rupali-codes ?
> 
> 
> 
> 
> 
> https://github.com/rupali-codes/LinksHub/assets/92252895/d344b333-831b-4749-99ba-d78ee35daabf
> 
> 
> 
> 

Looks better now in my opinion @rupali-codes

**Comment by 0xabdulkhalid** [comment]
@rupali-codes your review is appreciated to wrap this PR up!

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by CBID2 — CHANGES_REQUESTED** [review]
Ignore my previous comment @0xabdulkhalid. For some odd reason, the deployment failed. @rupali-codes, can you fix this?

**Comment by 0xabdulkhalid** [comment]
@CBID2 I think the `react-tooltip` has not installed.

I tried to install that on local, but it doesn't. There's some conflicts on packages.

**Review by k-deepak04 — COMMENTED** [review]
check, deploymnet is failing

**Comment by 0xabdulkhalid** [comment]
Guys @CBID2, @k-deepak04 I'm closing this.

For some reason i can't install `react-tooltip` on this branch, So i created a new branch a new pull.

Here's the new Pull #1517

**Pull request closed without merging**
