### PR TITLE
Fix : greetings.yml

### PR DESCRIPTION
**Pull request by ujjawaltyagii**
## Fixes Issue

Closes : #944 

#### - To fix this, I modified .YML file to include the correct variable for the author's name. Typically, the author's name can be accessed through the `github.event.issue.user.login` property.

Ig this should resolve the error !

Please add required labels of gssoc :)

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Comment by ujjawaltyagii** [comment]
Don't worry i just synchronized this change in my personal fork

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by rupali-codes — APPROVED** [review]
lgtm

**Comment by ujjawaltyagii** [comment]
Please add required <b>gssoc</b> labels :)

**Pull request merged**
