### PR TITLE
Changed Home Page UI

### PR DESCRIPTION
**Pull request by JoshiUtsav**
## Screenshots
Screenshot 2023-12-24 183258

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
You need to authorize the vercel deployment.

**Review by rupali-codes — CHANGES_REQUESTED** [review]
@JoshiUtsav please fix this

image

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Vercel deployment.

**Comment by rupali-codes** [comment]
@JoshiUtsav & @Anmol-Baranwal 

image

**Comment by Anmol-Baranwal** [comment]
> @JoshiUtsav & @Anmol-Baranwal

He is facing some errors, and I've asked him to consult to aftab. I was tired at that time due to exams.

Please tag us, if the problem is still not resolved.

**Comment by aftabrehan** [comment]
> > @JoshiUtsav & @Anmol-Baranwal
> 
> He is facing some errors, and I've asked him to consult to aftab. I was tired at that time due to exams.
> 
> Please tag us, if the problem is still not resolved.
> 

I have shared the solution with him.

**Review by rupali-codes — COMMENTED** [review]
@JoshiUtsav can you fix this??

image

**Review by rupali-codes — CHANGES_REQUESTED** [review]
@JoshiUtsav `pages/index.tsx` file have multitple exports for the same function, can you fix it please?

**Comment by JoshiUtsav** [comment]
@rupali-codes  Sure, I'll take care of fixing the multiple exports in the pages/index.tsx file.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Deployment :)

**Review by rupali-codes — CHANGES_REQUESTED** [review]
hey @JoshiUtsav

- Make the cards for same size (height & width)
image
 
- Its showing two scrollbar on the right side, please make it one
image

- The design is not responsive, please make it device friendly 
image


Thank you for contributing!

**Comment by Anmol-Baranwal** [comment]
@JoshiUtsav 

`For fixing scrollbar issue`

> 
image

**Comment by aftabrehan** [comment]
@JoshiUtsav are you still working on this PR?

**Comment by JoshiUtsav** [comment]
Yeah, I've been working on this pull request. @aftabrehan

**Comment by JoshiUtsav** [comment]
All the code is responsive,  except for the welcome section.
photo_2024-01-10_23-55-37

**Comment by Anmol-Baranwal** [comment]
@JoshiUtsav 
Please solve the conflicts. Rest, we would see whatever we can do.

**Comment by JoshiUtsav** [comment]
@rupali-codes Any update?

**Comment by CBID2** [comment]
> @rupali-codes Any update?

@JoshiUtsav, the merge conflicts need to be solved before we review your PR.

**Comment by JoshiUtsav** [comment]
@CBID2 Done.

**Review by rupali-codes — COMMENTED** [review]
@JoshiUtsav it's showing error

image

**Comment by JoshiUtsav** [comment]
I haven't made any modifications to the CategoryDescription.ts file. @rupali-codes

**Comment by aftabrehan** [comment]
@rupali-codes, I think [this error](https://github.com/rupali-codes/LinksHub/pull/2220#pullrequestreview-1822794573) is resolved now. Can you please help to deploy the changes?

**Comment by rupali-codes** [comment]
> @rupali-codes, I think [this error](https://github.com/rupali-codes/LinksHub/pull/2220#pullrequestreview-1822794573) is resolved now. Can you please help to deploy the changes?

Still failing

**Review by rupali-codes — COMMENTED** [review]
Hi @JoshiUtsav i've fixed the deployment, but why it isn't showing ay changes except the logo??

image

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please review and merge this if there are no changes required.

So, we can start working on #2234

**Comment by rupali-codes** [comment]
> @rupali-codes 
> Please review and merge this if there are no changes required.
> 
> So, we can start working on #2234 

Hey Anmol, the theme functionality isn't working well. Please look into it

**Comment by Anmol-Baranwal** [comment]
> Hey Anmol, the theme functionality isn't working well. Please look into it

Sure, will do it then.

**Comment by CBID2** [comment]
> > Hey Anmol, the theme functionality isn't working well. Please look into it
> 
> Sure, will do it then.

To @rupali-codes’ point @Anmol-Baranwal, some parts don’t match the design shown in the screenshot section 

Deployed version of the new homepage with errors

**Comment by CBID2** [comment]
> > Hey Anmol, the theme functionality isn't working well. Please look into it
> 
> Sure, will do it then.

It’s pretty squished in some sections 
IMG_0348

**Comment by Anmol-Baranwal** [comment]
> > > Hey Anmol, the theme functionality isn't working well. Please look into it
> > 
> > 
> > Sure, will do it then.
> 
> It’s pretty squished in some sections

@JoshiUtsav 
Make it responsive for mobile screens, for `md` devices it would be fixed on removing sidebar but at least do it for `xs`, `sm` devices.

@CBID2 
Thanks for pointing out.

**Comment by JoshiUtsav** [comment]
@Anmol-Baranwal Work in progress.

**Comment by rupali-codes** [comment]
> @Anmol-Baranwal Work in progress.

Any updates??

**Comment by CBID2** [comment]
It looks better structure-wise, but the words "Welcome" and "LinksHub" are hard to read. Is there a way we can make this darker @JoshiUtsav and @rupali-codes?
unreadable text

**Comment by JoshiUtsav** [comment]
@CBID2 & @rupali-codes Sorry for the delay, dealing with health issues. Need 2-3 more days

**Comment by Anmol-Baranwal** [comment]
Hi Utsav!

Prioritize your health and take some deep rest.

I've pushed responsive code, so don't stress about this PR.
Meanwhile, Rupali will handle the theme bug, so most probably this will be resolved by tomorrow.

I hope you understand. Just thought I should let you know.
See ya :)

**Comment by rupali-codes** [comment]
Hey @JoshiUtsav, the pr had lots of issues we have tried to fix whatever we could, and still merged the PR, but issues still affecting the dev branch so we're reverting the changes back.

**Pull request merged**
