### PR TITLE
added '/' as search shortcut

### LINKED ISSUE #1781: [Feature] Adding a quicksearch shortcut.
### Description

It feels difficult for a user to click on the search bar every time. So I suggest adding a shortcut key like '/' to navigate to search bar whenever pressed.

ps : I am willing to contribute this under hacktoberfest ' 23

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by raghav1030**
## Fixes Issue 

Solved : [Feature] Adding a quicksearch shortcut. #1781 

Closes #1781 

## Changes proposed

Made a custom hook  called useSearchShortcut that helps focusing the input field for quicksearch on an input command "/".

### CODE REVIEW

**Comment by raghav1030** [comment]
For now I have just added the quicksearch shortcut functionality. I will be doing some css changes in another issue to maintain the organizability of the repo.

**Comment by CBID2** [comment]
> Visit Preview

Can you show a screenshot or short clip of your proposed changes @raghav1030? It'll add more context to your PR.

**Comment by Anmol-Baranwal** [comment]
> > Visit Preview
> 
> Can you show a screenshot or short clip of your proposed changes @raghav1030? It'll add more context to your PR.

What this does is, whenever you click `/` it will automatically help you write the search query, as the cursor would behave like you clicked the searchbar.

just type `/`

image

It will turn to this. 

image

> I hope you understand.

**Comment by raghav1030** [comment]
> > > Visit Preview
> > 
> > 
> > Can you show a screenshot or short clip of your proposed changes @raghav1030? It'll add more context to your PR.
> 
> What this does is, whenever you click `/` it will automatically help you write the search query, as the cursor would behave like you clicked the searchbar.
> 
> just type `/`
> 
> image
> 
> It will turn to this.
> 
> image
> 
> > I hope you understand.

Yeah It goes the same way as you just mentioned. We can merge this one if everything's good and can work on adding other shortcuts as needed in other issues? 

I will be super interested to implement such features in the future.

**Review by CBID2 — APPROVED** [review]
Well done @raghav1030! :)

**Pull request merged**
