### PR TITLE
Update Header UI

### LINKED ISSUE #2171: feat: add new header design
> You can view the figma file [here](https://www.figma.com/file/ntisIxc9QHwOZ828CH5G3a/LinksHub?type=design&node-id=17-231&mode=design&t=29U3Qw0LktnVRteR-0).

image

> The design should be responsive. 

---

We recommend updating the styling of existing components, otherwise you can add extra components if there is a need.

- You also have to complete theme toggler

image

> Any changes to the above design are welcome. Please feel free to share your thoughts, and we will discuss them thoroughly.

---
### ⚠️ Make sure to push all the changes into `dev` branch

### PR DESCRIPTION
**Pull request by aftabrehan**
Fixes #2171 

### Preview

<div align="center">

 https://www.loom.com/share/a3f1ac4bb6e7415ba53f3479b1e63dda?sid=27592921-13c5-459e-9c5a-9aa4ad166d43

</div>

## Changes proposed

- [x] Update header design
- [x] Create button component
- [x] Configure `@svgr/webpack` to use Icons as React Element for adjusting colors dynamically.

### CODE REVIEW

**Comment by rupali-codes** [comment]
@aftabrehan please raise the PR to `dev` branch

**Comment by aftabrehan** [comment]
> @aftabrehan please raise the PR to `dev` branch 

@rupali-codes, I don't need to raise a new PR, I have switched the branch to the dev. So it can be merged in the dev.

**Comment by Anmol-Baranwal** [comment]
@aftabrehan 
Check for local errors and warnings using lint. Even small warnings can cause deployment errors.

**Comment by aftabrehan** [comment]
> Check for local errors and warnings using lint. Even small warnings can cause deployment errors.

I have checked locally, there is no issue in the build. Things messed up after switching the base branch (from `main` to `dev`). @rupali-codes, could you please help me check the deployment logs?


> This could also be because of updating pnpm although I am not sure.

I don't think so, because the `pnpm` was updated in the first commit, which has a green check. You can check the [old preview here](https://linkshub-git-header-redesign-rupali-codes.vercel.app/).

**Pull request closed without merging**
