### PR TITLE
feat: add modal to show descriptions of subcategories

### LINKED ISSUE #972: [Feature] Modal to show description about subcategories
### Description

- A simple modal to show a description for each subcategory.
- The modal will be triggered by clicking an icon next to the subcategory name.
- I will style it consistently across all viewports.
- This feature was suggested in the LinksHub Discord community.

### Screenshots

image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Resolves #972 

## Changes proposed

- Instead of making the field optional in `IData`, I have created a new interface.
- I have thoroughly checked and organized everything in a clean structure.
- I have placed `CategoryDescriptions.ts` in the `TopBar` components.

> I just realized that this work is worth two Level 3 PRs, LOL.

@rupali-codes 
Could you please review the code and merge the PRs? It becomes challenging when there are multiple PRs, so merging them after reviewing would be greatly appreciated.

## Screenshots

> Large Screen
image

> Small Screen
image

## Note to reviewers

If you would like to know something, please feel free to ask.

@CBID2
Do you happen to know who the mentor of LinksHub is, and if they are currently active?

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks pretty good to me! :)

**Review by ujjawaltyagii — APPROVED** [review]
lgtm

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Please let @rupali-codes review these types of PRs too before merging the PR because she can mention or improve the approach of these specific technical codes. I am just suggesting it for code improvement. I hope you understand.

**Comment by CBID2** [comment]
> @CBID2 
> 
> Please let @rupali-codes review these types of PRs too before merging the PR because she can mention or improve the approach of these specific technical codes. I am just suggesting it for code improvement. I hope you understand.
Hi @Anmol-Baranwal. Sure will, I guess using the General feature would be best.

**Comment by Anmol-Baranwal** [comment]
@CBID2 @rupali-codes 
Please add the `level3` label to the issue. The label is necessary for the accurate final leaderboard.

**Comment by CBID2** [comment]
> @CBID2 @rupali-codes 
> 
> Please add the `level3`, `gssoc23` label to the issue. The label is necessary for the accurate final leaderboard.
> 
> 
Done

**Pull request merged**
