### PR TITLE
feat: make search bar sticky and adjust scrollable area

### LINKED ISSUE #1418: [Feature] remove search bar from scrollable area
### Description

> For better clarity of the idea, see [here](https://jam.dev/c/96a311aa-681c-42d7-b9e7-335c24e3faeb)

Avoiding this would have several benefits including the emphasis of easy searching.

> Search bar is scrollable
image

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #1418 

## Changes proposed

> Why search bar should be sticky.

- Users can keep their search query visible while exploring different categories. This helps them remember their search context and makes it easy to refine or modify their search without losing sight of the results.
- With a sticky search bar, users can focus on interacting with the search input without distractions, as it remains in a fixed position regardless of their scrolling behavior.

## Screenshots

> Sticky search bar
image

## Note to reviewers

- I initially attempted different styling approaches but later changed my approach after trying various options, as this one appeared to be the most sophisticated and easy to understand.

### CODE REVIEW

**Review by CBID2 — COMMENTED** [review]
Looks ok

**Comment by rupali-codes** [comment]
@Anmol-Baranwal can we reduce the space between this two?

image

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal can we reduce the space between this two?
> 
> image

Done.

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
