### PR TITLE
Remove Unnecessary Description Popup

### LINKED ISSUE #1945: [BUG] Remove description revealing popup (and show it in a tooltip)
### Description

Why display a popup upon clicking it? Simply hovering over it should reveal the description, and opening a popup on click seems like unnecessary complexity.

### Screenshots

Screenshot 2023-10-11 at 2 45 49 PM

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by aftabrehan**
## Issue 
Closes #1945

## Changes proposed

Mainly, I've removed the description popup. Just used the tooltip instead. Additionally, I've added a few missing descriptions and refactored the code.

## Screenshots
<div align="center">
 Screenshot 2023-10-11 at 11 14 26 PM
</div>

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks good @aftabrehan. @rupali-codes, @Anmol-Baranwal, you're up! :)

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
The opacity is not appropriate:

We should make it 100% because background text would just be a distraction on this.

image


@rupali-codes 
We need to review this carefully. Also, can't we do it using another tooltip component.

Why bother changing the logic.

**Review by rupali-codes — COMMENTED** [review]
Please make ONLY changes related to the issue, don't over-do it. 

Why have you removed this file?
image

**Comment by aftabrehan** [comment]
> The opacity is not appropriate:

We should make it 100% because background text would just be a distraction on this.

Indeed, you're correct, @Anmol-Baranwal. I would have made style updates if that was the focus of this pull request. These styles are from an older version, and I'm not particularly fond of the current tooltip styles. For the time being, I'll eliminate the opacity and introduce a shadow instead. We can consider further enhancements in the future.

>Why bother changing the logic.

Previously, the code contained redundancies with unnecessary props ('results') being passed and half of it was repeated ('TopBar.tsx'). I've since streamlined the logic to simplify it.

cc @rupali-codes 

<div align="center">
 Screenshot 2023-10-12 at 4 18 34 PM
</div>

**Comment by aftabrehan** [comment]
>Please make ONLY changes related to the issue, don't over-do it.

Sure thing @rupali-codes.

>Why have you removed this file?

In fact, the title was "Tutorials," but the URL was "/os-tutorials," which prevented us from extracting the description correctly using the appropriate regex and resource name.

Please don't hesitate to inform me if there's anything you'd like me to undo. I'll follow your recommendations.

cc @Anmol-Baranwal

**Comment by aftabrehan** [comment]
@Anmol-Baranwal, does it appear acceptable now?

Screenshot 2023-10-12 at 5 17 44 PM

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal, does it appear acceptable now?
> 
> Screenshot 2023-10-12 at 5 17 44 PM

Yeah. It's perfect.

image

We all 3 maintainers will see your logic, and we will approve accordingly.

**Comment by aftabrehan** [comment]
@Anmol-Baranwal, Please don't hesitate to inform me if you'd like a summary of these changes. It could help save you some time.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please review this.

**Comment by aftabrehan** [comment]
@rupali-codes, I would greatly appreciate your assistance in reviewing this PR. Your feedback will inspire and motivate me to continue working on closing other issues.


### Summary of the PR Changes

#### `components/Header/Header.tsx`
- Removed the 'result' prop that was previously passed to the TopBar component.

#### `components/TopBar/CategoryDescriptions.ts`
- Added descriptions for a few items in this file.

#### `components/TopBar/TopBar.tsx`
- Significant changes made in this component:
  - Replaced the usage of the 'result' prop with router.query to obtain the search value, a more straightforward approach.
  - Eliminated redundant code sections.
  - Introduced a function to validate whether the search resource name is a valid subcategory name. If valid, it displays the subcategory name in the header with an information icon for viewing the description.
  - Implemented a box shadow and removed transparency as per the suggestion by @Anmol-Baranwal.

#### `components/TopBar/utils.ts`
- Imported sidebar data, ran a forEach function to extract all subcategory names into an array, and filtered to check if the searched value exists in the database and is valid. This determines whether the item is shown in the Topbar instead of displaying "No result found."

#### `components/popup/popupCategoryDesc.tsx`
- Deleted this component since it's no longer in use, as the category information is now displayed upon hovering.

#### `database/data.ts`
- Updated the URL from '/os-tutorials' to '/tutorials' to access descriptions and maintain consistency (removing the 'os' prefix as it wasn't used for other open-source resources).

#### `database/open_source/os-tutorials.json`
- Renamed this file to 'database/open_source/tutorials.json' for data retrieval.

#### `pages/[category]/[...subcategory].tsx` and `pages/search.tsx`
- Removed the 'result' prop from both of these files as it's no longer required.


cc @CBID2

**Comment by CBID2** [comment]
There's a few merge conflicts @aftabrehan. Can you solve those?

**Comment by aftabrehan** [comment]
> There's a few merge conflicts @aftabrehan. Can you solve those?

@CBID2, I'll address them all at once once the PR is approved. Otherwise, I'll continuously encounter conflicts.

**Comment by aftabrehan** [comment]
> It only shows the description when the cursor is on the 'i' button; the moment I move it, the description disappears. This makes it hard to read, and for small devices, users won't be able to read it properly.

I don't think we use a cursor on small devices. For touch devices, the description won't disappear as the hover effect remains until users tap on other elements. So, it'll work as a click, and the user can easily read it.

> Also, there are no click effects, like when a user clicks on the 'i' button, and even moves their cursor, it should remain visible until the user clicks somewhere else.

For desktop devices, we're currently displaying the description on hover. If you want to add a delay or prevent it from disappearing when hovering over the tooltip container, we'd need to consider using a different tooltip component.

I believe it's acceptable as is for now. @Anmol-Baranwal, could you please assist with testing and share your thoughts on this?

cc @rupali-codes

**Review by Anmol-Baranwal — COMMENTED** [review]
When we click on it. It shouldn't be focused, maybe change the styling a bit even if you want a focus state.

image

@rupali-codes 
I checked it on mobile devices. It works fine. 

The code seems fine as well. He created a utilility for finding regex and valid resource.

@aftabrehan 
What do you think about the focus state?

**Comment by aftabrehan** [comment]
@Anmol-Baranwal, In reality, this is excessive because we plan to update this, considering it's not an ideal UI. However, the focus of this PR isn't on the UI. I'd like to request the removal of the description popup, using only the tooltip instead. If everything looks good, could you please approve this PR so I can address the conflicts and you can proceed with the merge?

cc @rupali-codes

**Review by Anmol-Baranwal — DISMISSED** [review]
@rupali-codes 
🚀 Looks good to me.

**Comment by aftabrehan** [comment]
@Anmol-Baranwal, the PR conflicts are resolved and ready to be merged.

cc @CBID2 @rupali-codes

**Review by CBID2 — DISMISSED** [review]
Looks good to me

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Whenever we click on icon, it redirects to the home page. Can we neglect the hook for this.

**Comment by aftabrehan** [comment]
> @rupali-codes Whenever we click on icon, it redirects to the home page. Can we neglect the hook for this.

@Anmol-Baranwal, this issue isn't linked to the icon, TopBar, or even the header. It occurs when clicking on elements other than the cards. This matter isn't pertinent to the current PR; it's a separate issue. Can we proceed with the merge, please?

**Review by Anmol-Baranwal — DISMISSED** [review]
🚀 Looks good to me. 

@rupali-codes 
After clicking the icon, it redirects to the home page. This is due to the PR by raghav. This is intended and maybe we can remove the hook effect on click.

Otherwise, this works in mobile devices as I checked it.

It's up to you.

**Comment by rupali-codes** [comment]
@aftabrehan @Anmol-Baranwal @CBID2 any updates guys? the PR seems so inactive

**Comment by Anmol-Baranwal** [comment]
> @aftabrehan @Anmol-Baranwal @CBID2 any updates guys? the PR seems so inactive 

I've approved the changes.

**Comment by CBID2** [comment]
Hey @aftabrehan, there are merge conflicts that need to be resolved

**Comment by CBID2** [comment]
> > There's a few merge conflicts @aftabrehan. Can you solve those?
> 
> 
> 
> @CBID2, I'll address them all at once once the PR is approved. Otherwise, I'll continuously encounter conflicts.

@rupali-codes, here's your answer

**Comment by aftabrehan** [comment]
Okay, I'll resolve these conflicts. But please, help it merge then.

**Comment by aftabrehan** [comment]
@CBID2, @Anmol-Baranwal, @rupali-codes, The PR conflicts have been resolved. Please, have a look and get it merged. Thank you!

**Review by CBID2 — APPROVED** [review]
Looks good to me

**Comment by CBID2** [comment]
@Anmol-Baranwal & @rupali-codes, you're up! 😊

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
