### PR TITLE
feat: add Docusaurus

### LINKED ISSUE #2212: [Add] <Docusaurus>
### Site URL

https://docusaurus.io/

### Description of the above provided site

If you need a static generator to help you build your product’s documentation site, Docusaurus is your tool! :) Not only does it provide you with fast-side client navigation that takes interactivity to new heights, but also out-of-the-box documentation features that can help make your site stand out from the others.

### Category

Technical Writing

### Sub Category

“Tools”

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by CBID2**
## Fixes Issue
Closes #2212

## Changes proposed
This PR adds Docusaurus to the Technical writing tools section.

### CODE REVIEW

**Comment by CBID2** [comment]
@rupali-codes, can you authorize the deploy please?

**Review by aftabrehan — APPROVED** [review]
Looks good to me! 👍

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Review and merge :)

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
