### PR TITLE
added negative space for stock images

### LINKED ISSUE #1723: [Add] Added Negative Space
### Site URL

https://negativespace.co/

### Description of the above provided site

Beautiful free images for personal and commercial use.

### Category

Frontend

### Sub Category

images

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by dfordp**
## Fixes Issue

Closes #1723 

## Changes proposed

Added Negative Space .co in images resources section

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @dfordp. Welcome to LinksHub! :) we don’t accept unassigned PRS, so I'm closing this pull request for now. Remember, refer to our [Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) to learn how to effectively contribute to the project! 😊

**Comment by dfordp** [comment]
Hi thanks for telling me 
Can you please check for pull requests #1718 and #1722 they were assigned to me by github actions

**Comment by CBID2** [comment]
> Hi thanks for telling me 
> Can you please check for pull requests #1718 and #1722 they were assigned to me by github actions

Just assigned you to #1718 and approved its corresponding PR. You just need a second approval in order for it to be merged. As far as #1722, we gotta check it out.

**Comment by Anmol-Baranwal** [comment]
> Hi thanks for telling me Can you please check for pull requests #1718 and #1722 they were assigned to me by github actions

The issues should be assigned, not PRs. I have explained you the things in the other issue.

**Comment by dfordp** [comment]
I did this before you told me about the same

**Pull request closed without merging**
