### PR TITLE
Chore: Added Shadow Generator in ui-generator

### LINKED ISSUE #675: [Add] <Shadow Generator>
### Site URL

https://shadows.brumm.af/

### Description of the above provided site

an amazing site that helps you to create smooth shadows

### Category

Frontend

### Sub Category

UI-GENERATOR

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by parma1111**
## Fixes Issue

Closes #675 

## Changes proposed

An amazing site that helps you to create smooth shadows

## Screenshots

Screenshot (819)

## Note to reviewers

Any kind of feedback would be appreciated.

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
I don't know why your PRs always showing changes of your previous PR

**Comment by parma1111** [comment]
> I don't know why your PRs always showing changes of your previous PR

> I did 
git add .
git commit -m "message"
git push origin branch_name
then I get the error , after that I did
> I make new branch
git add .
git commit -m "message"
git push origin branch_name
@rupali-codes :)

**Comment by rupali-codes** [comment]
Please DON'T use **git add .**, you can add files manually by using this command **git add <file name>** (i'm telling you this 4th time :))

**Comment by parma1111** [comment]
> Please DON'T use **git add .**, you can add files manually by using this command **git add _file name_** (i'm telling you this 4th time :))

> Oh Sorry @rupali-codes , next time I will not write like this , please last time tell me what is _file name_ here , गुस्सा मत करना अबकी बार

**Review by CBID2 — APPROVED** [review]
Looks great @parma1111! :) LGTM! :)

**Comment by parma1111** [comment]
> Please DON'T use **git add .**, you can add files manually by using this command **git add _file name_** (i'm telling you this 4th time :))

> Sorry @rupali-codes , next time I will not do this mistake , just tell me here what is file-name

**Comment by parma1111** [comment]
> Please DON'T use **git add .**, you can add files manually by using this command **git add _file name_** (i'm telling you this 4th time :))

> Sorry @rupali-codes, next time I will not do this mistake , in this PR I should write **git add ui-generator.json or whatever file name is there** Is it correct ?

**Pull request merged**
