### PR TITLE
Fix incorrect alignment of header links

### LINKED ISSUE #1680: [BUG] Incorrect alignment of github stats & social media handles
### Description

Comment on this issue, if anyone wants to work on this issue.

### Screenshots

image

### Any additional information?

You will have to achieve this structure:

image

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by sohaibsalman**
## Fixes Issue
Closes #1680 

## Changes proposed
Fixed the header links alignment by tweaking HTML elements hierarchy.

## Screenshots
linkhub

## Note to reviewers
Kindly let me know if any changes are required. Open to suggestions

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks great @sohaibsalman! :)

**Review by rupali-codes — DISMISSED** [review]
It looks on desktop though, could you please fix this for small screens as well?

image

**Comment by sohaibsalman** [comment]
Hi @rupali-codes thank you for your feedback.

For small screens, the width of the sidebar restricts the icons and GitHub stats link from being aligned in the same line. Here is what I came up with:

image

I have centered aligned the icons and GitHub stats and moved them into two different lines for small screens.

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> For small screens, it looks visually appealing and clean.

Thanks for taking up the issue.

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Pull request merged**
