### PR TITLE
Fix SSG not generating the actual page content on initial load

### LINKED ISSUE #1477: [BUG] Static generation only generates a `Spinner`, not the actual content
### Description

Initial load of the pages at  `/` and `/[category]` routes render just the `Spinner` component, not the actual content of that page. This defeats the purpose of using the framework Next.js in the first place and is bad for SEO.

Here is the issue. Since we are only returning the `Spinner` on initial load, the content doesn't show up in the statically generated pages.

https://github.com/rupali-codes/LinksHub/blob/0830451643de35579d7998c6d147da355b1f42cc/components/Loader/Preloader.tsx#L14-L22

This should fix it.
```js
const { showLoader} = useLoader() 

return (
  <>
    {children}
    {showLoader && (
      <div
        className={`loader ${backgroundColor} fixed top-0 left-0 w-full h-screen flex justify-center items-center`}
      >
        <Spinner {...rest} />
      </div>
    )}
  </>
)
```

Also, to statically generate the dynamic `/[category]` routes, `getStaticPaths` and `getStaticProps` will have to be used. 

I'd like to implement this.

### Screenshots

https://github.com/rupali-codes/LinksHub/assets/73361366/24d65f44-c17f-4151-96cb-4e4db9c297d6

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by abhijithmuthyala**
## Fixes Issue

Closes #1477 

## Changes proposed

- Generate the actual page content on initial load (`/` and `/[subcategory]` routes), not just the `Spinner />`. 
- Fallback to `404` for the `/[subcategoryThatsNotInTheDatabase]` routes.

## Screenshots

Before

https://user-images.githubusercontent.com/73361366/258185040-24d65f44-c17f-4151-96cb-4e4db9c297d6.mp4

After

https://github.com/rupali-codes/LinksHub/assets/73361366/fb433c7d-b3d9-4145-b6c1-e67001d94d46

## Note to reviewers

Currently, the route for a subcategory that isn't in the database (`/cat` for example) behaves *almost* as if a search query with that name is submitted (`/search?query=cat`), which certainly is a bug. In this PR I had to choose a fallback, and I went with a `404` page (`fallback: false`). If it's preferred to retain the current behaviour, `fallback: 'blocking'` can be temporarily used.

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@abhijithmuthyala 
Post a video on what is changed. It will help us reviewing this quickly.

**Review by CBID2 — DISMISSED** [review]
LGTM

**Comment by Anmol-Baranwal** [comment]
@CBID2 
I don't think level is needed anymore, since it was specific for GSSoC'23. Feel free to add it, if you think otherwise.

**Comment by CBID2** [comment]
> @CBID2 
> 
> I don't think level is needed anymore, since it was specific for GSSoC'23. Feel free to add it, if you think otherwise.

Let's see what @rupali-codes thinks.

**Comment by rupali-codes** [comment]
> @CBID2 I don't think level is needed anymore, since it was specific for GSSoC'23. Feel free to add it, if you think otherwise.
it would be better if we can rename the labels,

**Comment by CBID2** [comment]
> > @CBID2 I don't think level is needed anymore, since it was specific for GSSoC'23. Feel free to add it, if you think otherwise.
> 
> it would be better if we can rename the labels,

So...do you agree or not @rupali-codes?

**Comment by rupali-codes** [comment]
> > > @CBID2 I don't think level is needed anymore, since it was specific for GSSoC'23. Feel free to add it, if you think otherwise.
> > 
> > 
> > it would be better if we can rename the labels,
> 
> So...do you agree or not @rupali-codes?

i do..remove the labels for now

**Comment by abhijithmuthyala** [comment]
> @abhijithmuthyala Post a video on what is changed. It will help us reviewing this quickly.

Video posted in the linked issue is the bug and the one in this PR is the fix. I thought it would be unnecessary to duplicate the bug video both in the issue and in the PR. If it is preferred to have it in both the places, I'll keep that in mind for future contributions.

**Comment by Anmol-Baranwal** [comment]
> > @abhijithmuthyala Post a video on what is changed. It will help us reviewing this quickly.
> 
> Video posted in the linked issue is the bug and the one in this PR is the fix. I thought it would be unnecessary to duplicate the bug video both in the issue and in the PR. If it is preferred to have it in both the places, I'll keep that in mind for future contributions.

No, you shouldn't add a duplicate video. You can simply reference it.

I asked what the change was. It would be helpful to see it visually in the video.

**Comment by abhijithmuthyala** [comment]
> I asked what the change was. It would be helpful to see it visually in the video.

Hmm, I already posted the bug video in the issue and the fix video in the PR though? Anyways, if it is helpful to repeat the bug video here, sure. I updated the PR description, please check.

**Comment by Anmol-Baranwal** [comment]
> > I asked what the change was. It would be helpful to see it visually in the video.
> 
> Hmm, I already posted the bug video in the issue and the fix video in the PR though? Anyways, if it is helpful to repeat the bug video here, sure. I updated the PR description, please check.

I thought the PR one was the bug video. My bad😅 That's why I was suggesting that you post a video solution, but without repeating the bug video. No worries. I will check it out soon.

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

> It will be better if you can also describe the approach of the code from next time. Because reviewing it without that would take a lot of time.

@rupali-codes 
Please review this.

**Pull request merged**
