### PR TITLE
bootstrap is added

### PR DESCRIPTION
**Pull request by Sushilverma002**
close issue -> #1370 
## Screenshots

image

### CODE REVIEW

**Comment by Sushilverma002** [comment]
@CBID2 please review

**Comment by CBID2** [comment]
Please be patient @Sushilverma002

**Comment by k-deepak04** [comment]
@Sushilverma002 please resolve the conflicts

**Comment by Sushilverma002** [comment]
@k-deepak04 conflict resolved. @CBID2

**Comment by k-deepak04** [comment]
@Sushilverma002 conflict resolved.

**Comment by Sushilverma002** [comment]
@k-deepak04 how can i resolve this .

**Comment by k-deepak04** [comment]
@rupali-codes please provide the ss of whats going wrong

**Comment by Sushilverma002** [comment]
when i click to check what's going wrong it shows:
image
@k-deepak04

**Comment by k-deepak04** [comment]
> when i click to check what's going wrong it shows: image @k-deepak04

only project admin @rupali-codes has the access , be patient she will be helping you out in this.

**Comment by Sushilverma002** [comment]
Okay @k-deepak04

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by CBID2 — COMMENTED** [review]
I fixed a grammar error, but still work on this PR

**Comment by Sushilverma002** [comment]
any update @CBID2 ?

**Comment by CBID2** [comment]
> any update @CBID2 ?

Did you resolve the merge conflicts?

**Comment by Sushilverma002** [comment]
i don't know the exact reason of fail deployment.see

https://github.com/rupali-codes/LinksHub/assets/114687502/19352298-1377-4338-9197-511dfc806a18

**Comment by CBID2** [comment]
> i don't know the exact reason of fail deployment. see @CBID2
> 
>  bootstrap.is.added.by.Sushilverma002.Pull.Request.1381.rupali-codes_LinksHub.-.Google.Chrome.2023-07-28.23-05-46.mp4

To move things quickly, I think you should do a new version of this PR with a different branch @Sushilverma002

**Pull request closed without merging**
