### PR TITLE
Fix height issue in card

### LINKED ISSUE #50: [CHORE] add a fixed height on Link Card
### What would you like to share or ask?

I just noticed, when card have a long description it's increasing card length, which is not good.

### Specific requirements  
- add fixed length to link card
- hide description if it contains more than 12-15 words

### Additional information

image

### PR DESCRIPTION
**Pull request by haldaranup**
## Note to reviewers
This might not be the correct way, please let me know the better approach.

### CODE REVIEW

**Comment by rupali-codes** [comment]
@haldaranup Hi, could you please resolve merge conflicts

**Comment by haldaranup** [comment]
> @haldaranup Hi, could you please resolve merge conflicts

@rupali-codes Yeah sure

**Comment by rupali-codes** [comment]
@haldaranup thank you

**Comment by haldaranup** [comment]
> @haldaranup thank you

🙂

**Pull request merged**
