### PR TITLE
added issue and pr templates

### PR DESCRIPTION
**Pull request by Aadarsh805**
issue #23

### CODE REVIEW

**Comment by Aadarsh805** [comment]
> LGTM, can we also add template for adding LINKS in database/data.ts file, along with the existing format?

Through issues ?

**Comment by Aadarsh805** [comment]
Or through the pr

**Comment by Aadarsh805** [comment]
Can you elaborate

**Comment by rupali-codes** [comment]
No, just a simple template for making issue

**Comment by Aadarsh805** [comment]
> No, just a simple template for making issue

Making an issue asking to add a link in the database/data.ts file, template for this right?

**Comment by rupali-codes** [comment]
@Aadarsh805 yup

**Comment by Aadarsh805** [comment]
We can make sub-categories a select dropdown as well, we can have multiple option like these

 options:
        - images
        - illustration
        - icons
        - etc

**Review by rupali-codes — CHANGES_REQUESTED** [review]
its nice, but i'd like to add some changes, also remove id
just add these fields,

name
description
url
category
subcategory

all the rest is perfect

**Comment by Aadarsh805** [comment]
> its nice, but i'd like to add some changes, also remove id just add these fields,
> 
> name description url category subcategory
> 
> all the rest is perfect

image

is this good? 
should i remove all those examples, or should i make a dropdown as well but frontend and backend subcategories will get mixed up if we do that

**Comment by rupali-codes** [comment]
@Aadarsh805 that's perfect, push it :)

**Comment by rohitdasu** [comment]
why we need sub category in issue template? just curious to know

**Comment by rupali-codes** [comment]
@rohitdasu to filter array, cz as of yet, we storing everything in a single file/array, so we need filter it based on the element clicked :)

**Comment by rohitdasu** [comment]
> @rohitdasu to filter array, cz as of yet, we storing everything in a single file/array, so we need filter it based on the element clicked :)

that i understand but i don't think it is necessary to put it as a separate field in `issue template`?

**Comment by rupali-codes** [comment]
> > @rohitdasu to filter array, cz as of yet, we storing everything in a single file/array, so we need filter it based on the element clicked :)
> 
> that i understand but i don't think it is necessary to put it as a separate field in `issue template`?

How do we get to know then which category it belongs to? Frontend itself would have tones of subcategories :)

**Comment by rohitdasu** [comment]
> 

is there any issue will come for one sub-category and not for others? i mean if a sub-category has issue then it would be the case with other ones as well. also if you are referring to the data that provided by the user is correct or not, we are using Typescript, so user won't be adding any wrong data there. :)

**Review by rupali-codes — APPROVED** [review]
LGTM, thanks for contributing

**Pull request merged**
