### PR TITLE
feat: Added Roadmaps #1387

### PR DESCRIPTION
**Pull request by Suraj-kumar00**
It's a draft PR

### CODE REVIEW

**Review by CBID2 — CHANGES_REQUESTED** [review]
Found some typos and implemented some suggestions on how to improve them @Suraj-kumar00. Maybe that can help with the commit issue.

**Comment by CBID2** [comment]
> Hi @CBID2 thanks for the addition, as I shared in the screenshot I got the error in the data.ts tile after pulling the upstream branch
> 
> how to resolve that?

Have you tried using the Merge Editor on VSCode: https://learn.microsoft.com/en-us/visualstudio/version-control/git-resolve-conflicts?view=vs-2022

**Comment by Suraj-kumar00** [comment]
Hi @CBID2, after pulling the changes from the upstream branch I resolved the conflicts but as I shared in the screenshot I got the error in the data.ts tile after pulling the upstream branch how do i resolve that? 
I don't know why it occurs but it occurs after pulling the upstream changes..., please help me with that!

**Comment by Suraj-kumar00** [comment]
> Hi @CBID2, after pulling the changes from the upstream branch I resolved the conflicts but as I shared in the screenshot I got the error in the data.ts tile after pulling the upstream branch how do i resolve that? I don't know why it occurs but it occurs after pulling the upstream changes..., please help me with that!

**Comment by CBID2** [comment]
> Hi @rupali-codes, how are you!
> 
> Now please tell me what to do now, I've read the guidelines and i forked the repo,  it's updated from upstream and i have created a Roadamp category in the database folder but after doing git pull upstream main i get this error please tell me how to resolve this..
> 
> Screenshot (59)
> 
> 

@Anmol-Baranwal, can you help?

**Comment by Anmol-Baranwal** [comment]
I will see this in the evening. 

I will let you know proper steps, so that you can implement the same.

**Comment by Suraj-kumar00** [comment]
> I will see this in the evening.
> 
> I will let you know proper steps, so that you can implement the same.

thanks @Anmol-Baranwal

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
@Suraj-kumar00 

I changed this to an actual PR. 

You can follow below screenshots for reference.

image

image


image

image

> database/data.ts

image

image

> I think this would do the work. Complete this, and let me know if there are any more errors.

> Just remember the name `frontend-roadmap` would be similar to other places and in the subcategory json data. Also, check the contributing guidelines if you need to double check anything.

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00
> 
> I changed this to an actual PR.
> 
> You can follow below screenshots for reference.
> 
> image
> 
> image
> 
> image
> 
> image
> 
> > database/data.ts
> 
> image
> 
> image
> 
> > I think this would do the work. Complete this, and let me know if there are any more errors.
> 
> > Just remember the name `frontend-roadmap` would be similar to other places and in the subcategory json data. Also, check the contributing guidelines if you need to double check anything.

I followed every step you have listed above but I didn't find in database/data.ts where is export type category and where in database/data.ts I write frontend-roadmap, and devops-roadmap? 
Screenshot (65)

**Comment by Anmol-Baranwal** [comment]
> > @Suraj-kumar00
> > I changed this to an actual PR.
> > You can follow below screenshots for reference.
> > image
> > image
> > image
> > image
> > > database/data.ts
> > 
> > 
> > image
> > image
> > > I think this would do the work. Complete this, and let me know if there are any more errors.
> > 
> > 
> > > Just remember the name `frontend-roadmap` would be similar to other places and in the subcategory json data. Also, check the contributing guidelines if you need to double check anything.
> 
> I followed every step you have listed above but I didn't find in database/data.ts where is export type category and where in database/data.ts I write frontend-roadmap, and devops-roadmap? Same error I'm getting in the data.ts file!!! Screenshot (65)

You would have to make a new category, and add subcategories option based on the json file naming you chose.

**Comment by Suraj-kumar00** [comment]
> > I followed every step you have listed above but I didn't find in database/data.ts where is export type category and where in database/data.ts I write frontend-roadmap, and devops-roadmap? Same error I'm getting in the data.ts file!!! Screenshot (65)
> 
> You would have to make a new category, and add subcategories option based on the json file naming you chose. As shown in the structure, just pick one subcategory & category, and study the specific details on what code is written where. You will get a better idea.

Even if i include category and subcategory but it's still giving errors i searched about it and found that problem may be in "DB.___" so please tell how to resolve this every problem I'm getting is in data.ts file....?
Screenshot (66)

**Comment by Anmol-Baranwal** [comment]
> > > I followed every step you have listed above but I didn't find in database/data.ts where is export type category and where in database/data.ts I write frontend-roadmap, and devops-roadmap? Same error I'm getting in the data.ts file!!! Screenshot (65)
> > 
> > 
> > You would have to make a new category, and add subcategories option based on the json file naming you chose. As shown in the structure, just pick one subcategory & category, and study the specific details on what code is written where. You will get a better idea.
> 
> Even if i include category and subcategory but it's still giving errors i searched about it and found that problem may be in "DB.___" so please tell how to resolve this every problem I'm getting is in data.ts file....? Screenshot (66)

@rupali-codes 
Maybe you can tell what is going wrong. I would have to thoroughly check this, and is this DB one included in the contributing guidelines? It is for sidebar data for searching, right?

You are more suitable to answer this, as you know the structure better than me.

**Comment by Anmol-Baranwal** [comment]
@Suraj-kumar00 
Give me time of 2 days. I will revert back to you here with proper instructions.

I will add the category locally, and will let you know.

**Comment by Suraj-kumar00** [comment]
> @Suraj-kumar00 Give me time of 2 days. I will revert back to you here with proper instructions.
> 
> I will add the category locally, and will let you know.

Hello @Anmol-Baranwal are you free now? And if anyone free here please help me to understand this issue?

**Comment by Anmol-Baranwal** [comment]
> > @Suraj-kumar00 Give me time of 2 days. I will revert back to you here with proper instructions.
> > I will add the category locally, and will let you know.
> 
> Hello @Anmol-Baranwal are you free now? And if anyone free here please help me to understand this issue?

Hi, I tried this. I even messaged on discord. Kindly check.

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
