### PR TITLE
Added DSA-Courses subcategory in DSA Section

### LINKED ISSUE #2007: [ADD] DSA Resources subcategory
### Category Name

DSA

### Subcategory Name

DSA Resources

### Additional Context

Like any website dsa course, youtube playlist of dsa

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by thatdamncoder**
**DSA section original-** 
DSA articles
DSA tutorials

**Added- DSA Courses**

Closes #2007 

## Changes proposed

1. Included Courses for DSA section (dsa-courses.json)
2. For example- Coding Ninjas Online 4-5 month course etc
3. A total of 8 courses included

## Screenshots

**BEFORE**

Screenshot 2023-10-20 235124

**AFTER**

Screenshot 2023-10-22 015021

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
Hey @thatdamncoder we're currently not adding any paid resources, could you please remove the paid courses?

**Comment by thatdamncoder** [comment]
> Hey @thatdamncoder we're currently not adding any paid resources, could you please remove the paid courses?

Done @rupali-codes

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
@thatdamncoder 
Please add a description.

image

**Comment by thatdamncoder** [comment]
> @thatdamncoder Please add a description.
> 
> image

I think we don't have descriptions for any of the subsections in any of the categories. Only the main sections/categories are provided with the description.

**Comment by CBID2** [comment]
There's some merge conflicts too

**Comment by thatdamncoder** [comment]
> > @thatdamncoder Please add a description.
> > image
> 
> I think we don't have descriptions for any of the subsections in this category. Only the main sections/categories are provided with the description.

**Comment by thatdamncoder** [comment]
I've tried but could you please tell me what to include to make the
changes? I've written according to the guidelines many times but the result
is not showing up.

**Comment by Anmol-Baranwal** [comment]
@thatdamncoder 

What is the problem, you just need to take care of the name, which will be same as json file. Check it locally.

**Comment by thatdamncoder** [comment]
Screenshot 2023-10-26 142920

**Comment by thatdamncoder** [comment]
Hello @rupali-codes 
Could you please guide me on where is the issue arising in the conflicting files?

**Comment by thatdamncoder** [comment]
> > > @thatdamncoder Please add a description.
> > > image
> > 
> > 
> > I think we don't have descriptions for any of the subsections in any of the categories. Only the main sections/categories are provided with the description.
> 
> Just go the official website, see how many subcategories in Frontend section has descriptions. Each has a description.
> 
> Simply add it, it is clearly mentioned in the contributing guidelines.
> 
> If you're not willing to do so, let me know.

@Anmol-Baranwal 

Do you want me to add descriptions in other categories too?

**Review by thatdamncoder — COMMENTED** [review]
Added description in sub categories and resolved merge conflicts
waiting for review and any further corrections

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
Descriptions not showing up.

image

**Comment by thatdamncoder** [comment]
> Descriptions not showing up.
> 
> image

@Anmol-Baranwal 
Apologies for the description not showing
please check now and let me know


**FOR ARTICLES**

Screenshot 2023-10-27 012349


**FOR COURSES**

Screenshot 2023-10-27 012407


**FOR TUTORIALS**

Screenshot 2023-10-27 012420

@CBID2 @rupali-codes please do check and review for any more changes
apologies for the chaos

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by CBID2 — APPROVED** [review]
Looks good to me @thatdamncoder! :) @rupali-codes, it's your turn now! :)

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
