### PR TITLE
Adding direct links to dsa playlists

### LINKED ISSUE #565: [OTHER] Adding direct link of playlist in instead of their channel link
### What would you like to share or ask?

In YouTube resources section there should be direct playlist link of each playlist instead of their channel link.

Please assign this task to me .

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by noobtuber20103152**
## Issue
Fixes #565 
## Changes proposed

Adding direct links of  data strucure and algorithm playlist instead of their channel links. 
@CBID2 
## Screenshots

image

### CODE REVIEW

**Comment by rupali-codes** [comment]
@noobtuber20103152 Hey, please follow our [CONTRIBUTING](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) guidelines and don't create pull request without creating issue. We are closing this PR for now, will reopen this when you are done :)

**Comment by rupali-codes** [comment]
hey thanks for creating the issue, could you please point the issue here in this PR?

**Comment by noobtuber20103152** [comment]
Issue no #565

**Review by rupali-codes — APPROVED** [review]
Hey, thanks looks good to me

**Comment by rupali-codes** [comment]
@noobtuber20103152 are you a GSSoC contributor?

**Comment by noobtuber20103152** [comment]
yess, I am a GSSoC contributor.

**Comment by rupali-codes** [comment]
> yess, I am a GSSoC contributor. @rupali-codes

Cool, thanks

**Review by CBID2 — APPROVED** [review]
LGTM! 😊

**Pull request merged**
