### PR TITLE
Fixed the behavior of dropdownlist when clicked outside of its scope.

### LINKED ISSUE #1829: [BUG] Category list doesn't get closed when clicked outside its scope
### Description

When you click on a category, the dropdown list opens. If you click on another category, the previous one automatically closes. However, if you click outside the category list, the dropdown doesn't close. For instance, if a specific category is active and you click on the linkshub logo button, the outlet renders the index page of linkshub, but the dropdown stays open.

Steps to Reproduce the Issue:

Click on a category (e.g., Frontend).
Next, click on the linkshub logo button.
Result: The outlet renders the linkshub index page, but the dropdown menu remains open.

### Screenshots

**Actual Behavior**

https://github.com/rupali-codes/LinksHub/assets/94848646/7a344e53-2ecd-4925-8f0e-74a1ce8ef081

**Expected Behavior**

https://github.com/rupali-codes/LinksHub/assets/94848646/995afecc-e142-4c47-8e75-3c55923524bf

### Any additional information?

I am willing to contribute this under hacktoberfest :)

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by raghav1030**
## Fixes 

Closes #1829

## Changes proposed

1. Added a useOnClickOutside Hook to capture mouse events when clicked outside the scope of any element.
2. Implemented useOnClickOutside hook on dropdown list for category section

## Screenshots

Same behavior as quoted in #1829

### CODE REVIEW

**Comment by CBID2** [comment]
Can you post a screenshot of your solution in the screenshot form @raghav1030?

**Review by CBID2 — APPROVED** [review]
Well done @raghav1030! @Anmol-Baranwal, you're up! :)

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
Remove console log.

image


image

**Comment by raghav1030** [comment]
Removed the unnecessary console.log(). Please tell if there's any other room for improvement?

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
@raghav1030 

After clicking the header: where social icons are present.

image

The category sidebar closes, but it doesn't redirect to home page. Please make the change to incorporate this.

**Review by rupali-codes — CHANGES_REQUESTED** [review]
I'm experiencing this bug here, not just outside of the sidebar, it closing the category dropdown when I'm clicking anywhere, can we fix this?

https://github.com/rupali-codes/LinksHub/assets/78981177/bde95d4f-9985-432f-a0d6-925a1345c521

**Comment by raghav1030** [comment]
> @raghav1030
> 
> After clicking the header: where social icons are present.
> 
> image
> 
> The category sidebar closes, but it doesn't redirect to home page. Please make the change to incorporate this.

I just want to know what changes do you expect when a user clicks outside and the dropdown closes?

Possible Behaviors : 

1. Navigate to home page whenever the dropdown is closed no matter what user is doing.

OR

2. Retain the page state and navigate to home page only when the logo is clicked.

**Comment by raghav1030** [comment]
> I'm experiencing this bug here, not just outside of the sidebar, it closing the category dropdown when I'm clicking anywhere, can we fix this?
> 
>  LinksHub.-.Frontend_animations.-.Brave.2023-10-08.16-00-49.mp4

Thanks for noticing, I have fixed this issue and will commit changes once I get clarity on the previous comment. :)

**Comment by rupali-codes** [comment]
@raghav1030 it should close the dropdown when clicked outside of the sidebar, but not when clicking on buttons or icons

**Comment by raghav1030** [comment]
> @raghav1030 it should close the dropdown when clicked outside of the sidebar, but not when clicking on buttons or icons

Yeah I have solved that bug, I am talking about the changes as requested by @Anmol-Baranwal.
What should be rendered on the outlet when clicked on navbar where social links are present?

**Comment by raghav1030** [comment]
> @raghav1030
> 
> After clicking the header: where social icons are present.
> 
> image
> 
> The category sidebar closes, but it doesn't redirect to home page. Please make the change to incorporate this.

This comment :)

**Comment by Anmol-Baranwal** [comment]
> This comment :)

I clearly said, redirect to the home page. Either it shouldn't close drop-down menu, or if it does then redirect to home page screen.

image

**Comment by raghav1030** [comment]
I have made all the necessary changes. Please check if the issue still persists in any case. I have restricted all potential elements to inherit this click outside behavior where it could have misbehaved.

Fyi : I have added a "data-custom='restrict-click-outside'  " attribute in each component where i want to restrict the onClickOutside hook's functionality. I have made such a change that if anyone needs to restrict any component, then one has to add this attribute to the parent HTML element and the property will be applied to its each and every child element/component. In short, on applying this custom data attribute, the element and its children will not allow the dropdown list to close.

**Comment by raghav1030** [comment]
> @rupali-codes Check on clicking the logo icon, is it behaving correctly. It isn't visible in the screen recording, but it's there when I clicked it.
> 
> Let me know, I will approve it.

Sure, here it is.

https://github.com/rupali-codes/LinksHub/assets/94848646/4a61d3d5-c66d-4337-843e-0e14d2a1aa56

**Comment by rupali-codes** [comment]
@raghav1030 it works fine for the card and its popup. Can you do the same for topbar icons?

**Comment by raghav1030** [comment]
> @raghav1030 it works fine for the card and its popup. Can you do the same for topbar icons?




Just added the required functionality. In this commit I restricted the topbar icons to close the dropdown list upon clicking.


You can check how it works now : 

https://github.com/rupali-codes/LinksHub/assets/94848646/1efb79bc-5c41-4aa9-b30b-695e82615b20

Please tell if there's any room for improvement?

**Comment by Anmol-Baranwal** [comment]
@raghav1030 
Please solve the merge conflicts carefully by cross checking the code from the current codebase, or if you are unsure. Let me know, I will do it whenever I'm free.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I think, this works fine. So, maybe we can go ahead.

**Comment by CBID2** [comment]
> @rupali-codes I think, this works fine. So, maybe we can go ahead.

After the merge conflicts are solved of course @raghav1030! :)

**Review by rupali-codes — APPROVED** [review]
looks perfect to me

**Comment by rupali-codes** [comment]
@raghav1030 we are experiencing some bugs,, when i click on this pagination buttons, its closing the dropdown and never going to the other page. so fix it, can you one thing, just close the dropdown when clicked on the Topbar only, not anywhere else. Please me or @Anmol-Baranwal if you need any assistance, and we want this to be fixed ASAP.

**Comment by rupali-codes** [comment]
@raghav1030 this is breaking the current codebase, we'll have to revert this PR in order to fix the current situation, please raise a NEW PR containing all the changes of this PR and the suggested one (pagination bug).

**Pull request merged**
