### PR TITLE
Added variables for different colors

### LINKED ISSUE #1191: [OTHER] Font Color
### What would you like to share or ask?

image

In the provided image, there are inconsistencies in the text colors that need to be addressed. Although these inconsistencies may be subtle and minute to observe, I would like to fix them to ensure a cohesive visual experience.

Light Mode:
Header: 111827
Footer: 000000

Dark Mode : 
Header : F3F4F6
Footer : E5E7EB

Suggestion: To ensure consistency across the UI, it would be beneficial to create a variable that represents all the colors used.

I have even check your style guide
image
image

If I have overlooked or omitted anything, please feel free to correct me.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by PriyansuMaurya**
## Fixes Issue
Closes #1191

## Screenshots
image

image

image

image

### CODE REVIEW

**Comment by rupali-codes** [comment]
@PriyansuMaurya Not acutally, a day before yesterday we have put the colors in _tailwind.config.css_ file and just change the colors value in there, isn't your local codebase updated?

**Comment by PriyansuMaurya** [comment]
No, its not. I forgot to update 😓. 

what should I do now?

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hi @PriyansuMaurya. Consider placing the colors in the file @rupali-codes mentioned. Also, solve the merge conflicts in your branch.

**Comment by rupali-codes** [comment]
> No, its not. I forgot to update 😓.
> 
> what should I do now?

* close this PR
* update your local repo with `linkshub:main`
* make changes in only tailwind.config.js file as we've gathered all the colors in there

please let us know for any kinda help

**Comment by PriyansuMaurya** [comment]
> please let us know for any kinda help

sure

**Comment by PriyansuMaurya** [comment]
I don't see `tailwind.config.css`, Where should I put the colors variables now? additionally I don't understand what does "Accessible version" means? 

I real question is should I also make variables for the same?

**Pull request closed without merging**
