### PR TITLE
 Added Prettier

### LINKED ISSUE #226: [CHORE] add prettier
### What would you like to share or ask?

As of now, we don't have prettier initialized and it's hard to tell people to format their code before they push it. Your task is to add `prettier` in this project so the code will be formatted. 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Abbeyafolaby**
## Fixes Issue

Closes #226

### CODE REVIEW

**Comment by Abbeyafolaby** [comment]
Hi, I couldn't detect the reason for the failed compilation. do you have any suggestion please?

**Comment by rupali-codes** [comment]
@Abbeyafolaby I can help you finding the error,
image

**Comment by Abbeyafolaby** [comment]
Alright, Thaknks, I'd try to fix it

**Comment by Abbeyafolaby** [comment]
> @Abbeyafolaby I can help you finding the error, image

Alright, Thanks. I'd work on it now

**Pull request closed without merging**
