### PR TITLE
add Kubernate TechWorld with Nana course

### LINKED ISSUE #2086: [Add] <Kubernetes Youtube tutorial>
### Site URL

https://youtu.be/X48VuDVv0do?si=VUaShrqe0PuMrfl4

### Description of the above provided site

This link contains a comprehensive and beginner-friendly resource for Kubernetes by a well-known tutor Nana.

### Category

DevOps

### Sub Category

Kubernetes

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by Priyanshuthapliyal2005**
Add Kubernate TechWorld with Nana Full course

## Fixes Issue
Closes #2086 

## Changes proposed
Added new course content: Kubernetes in TechWorld with Nana.

## Screenshots

image

## Note to reviewers
The Kubernetes TechWorld with Nana Full Course provides a comprehensive overview of Kubernetes, covering main components, architecture, local setup, and essential commands. It explores YAML configuration files, demonstrates a MongoDB and Mongo Express project, and delves into organizing components with Kubernetes namespaces. The course explains Ingress, Helm as a package manager, persisting data with volumes, deploying stateful apps using StatefulSet, and various Kubernetes services. Each section is accompanied by detailed timestamps, making it easy to navigate. The course balances theoretical concepts with practical demonstrations, making it suitable for beginners and those looking to deepen their understanding of Kubernetes.

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks great. @Anmol-Baranwal & @rupali-codes, you're turn

**Review by CBID2 — CHANGES_REQUESTED** [review]
Ignore my previous comment @Priyanshuthapliyal2005. The deployment failed. @rupali-codes, can you figure out what happened?

**Comment by Priyanshuthapliyal2005** [comment]
@Anmol-Baranwal @rupali-codes @CBID2 
I sort out the deployment error now you can merge it

**Review by CBID2 — APPROVED** [review]
Looks great

**Comment by Anmol-Baranwal** [comment]
@CBID2 
This issue is not assigned to him.

This is the PR created by the author who is assigned the issue.

https://github.com/rupali-codes/LinksHub/pull/2087

**Comment by Anmol-Baranwal** [comment]
@Priyanshuthapliyal2005 

You cannot work on issues which isn't assigned to you.

We are neglecting this now, but in the future, you need to create an issue and allow us to assign you the issue before you start working and submit a PR. Not following this process will require us to close your pull request.

This is outlined in the contributing guidelines.
image

You need to follow a predefined flow in order to contribute to Open Source. You may be new, so it is important to understand this. Most of the maintainers will mark it as spam and close it. I'm converting this into a draft for now.

**Comment by Priyanshuthapliyal2005** [comment]
@Anmol-Baranwal

I understand the importance of following the contribution process. However, I'd like to point out that the author of the issue isn't actively working on resolving the problem. Instead, they submitted a pull request without attempting to address the issue.

While I appreciate the established flow for contributing to open source, I believe it's equally crucial for contributors to take ownership of the issues they create. Perhaps we can encourage the original issue creator to actively engage in resolving the problem or, if they're unable to do so, allow others to take up the task.

Best,
Priyanshu Thapliyal

**Comment by Priyanshuthapliyal2005** [comment]
@Anmol-Baranwal

I acknowledge that my pull request may not strictly adhere to the contributor guidelines, and I appreciate your guidance on this matter. However, I want to highlight that the changes made in my pull request effectively solve the issue at hand.

I understand the significance of following the established guidelines and I'm open to making adjustments as needed to ensure compliance. At the same time, my primary aim is to contribute meaningfully to the project and provide a resolution to the reported issue.

If it aligns with the project's policies, I would appreciate your consideration of my pull request to close this issue. I'm committed to collaborating and refining the changes as necessary.

Thank you for your understanding.

Best,
Priyanshu Thapliyal

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal
> 
> I understand the importance of following the contribution process. However, I'd like to point out that the author of the issue isn't actively working on resolving the problem. Instead, they submitted a pull request without attempting to address the issue.
> 
> While I appreciate the established flow for contributing to open source, I believe it's equally crucial for contributors to take ownership of the issues they create. Perhaps we can encourage the original issue creator to actively engage in resolving the problem or, if they're unable to do so, allow others to take up the task.
> 
> Best, Priyanshu Thapliyal

But he did create a PR before than you. Also, we don't restrict authors with deadline, they are free to do in even 2 weeks.

We do open the issue for others once the author isn't interested, there is even a label: `up for grabs`

**Comment by Priyanshuthapliyal2005** [comment]
ok

**Comment by Priyanshuthapliyal2005** [comment]
> > @Anmol-Baranwal
> > I understand the importance of following the contribution process. However, I'd like to point out that the author of the issue isn't actively working on resolving the problem. Instead, they submitted a pull request without attempting to address the issue.
> > While I appreciate the established flow for contributing to open source, I believe it's equally crucial for contributors to take ownership of the issues they create. Perhaps we can encourage the original issue creator to actively engage in resolving the problem or, if they're unable to do so, allow others to take up the task.
> > Best, Priyanshu Thapliyal
> 
> But he did create a PR before than you. Also, we don't restrict authors with deadline, they are free to do in even 2 weeks.
> 
> We do open the issue for others once the author isn't interested, there is even a label: `up for grabs`
I appreciate your understanding. I want to provide more context on my actions. When I came across the issue, I noticed it had no associated pull request, and the author hadn't tagged their pull request with the issue. In my eagerness to contribute and thinking the issue was unclaimed, I submitted a pull request.

I now understand that the original author had indeed created a pull request a day before mine. I apologize for any confusion caused by my oversight.

I am committed to learning from this experience and will ensure to be more diligent in checking for existing pull requests in the future.

Thank you for your guidance and patience.

**Comment by Anmol-Baranwal** [comment]
@Priyanshuthapliyal2005 
No worries, I was just letting you know. Sometimes, even we miss these things. So, it's important to have a mutual understanding.

**Pull request closed without merging**
