### PR TITLE
Dropdown bug

### LINKED ISSUE #1829: [BUG] Category list doesn't get closed when clicked outside its scope
### Description

When you click on a category, the dropdown list opens. If you click on another category, the previous one automatically closes. However, if you click outside the category list, the dropdown doesn't close. For instance, if a specific category is active and you click on the linkshub logo button, the outlet renders the index page of linkshub, but the dropdown stays open.

Steps to Reproduce the Issue:

Click on a category (e.g., Frontend).
Next, click on the linkshub logo button.
Result: The outlet renders the linkshub index page, but the dropdown menu remains open.

### Screenshots

**Actual Behavior**

https://github.com/rupali-codes/LinksHub/assets/94848646/7a344e53-2ecd-4925-8f0e-74a1ce8ef081

**Expected Behavior**

https://github.com/rupali-codes/LinksHub/assets/94848646/995afecc-e142-4c47-8e75-3c55923524bf

### Any additional information?

I am willing to contribute this under hacktoberfest :)

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by raghav1030**
## Fixes Issue 
Closes #1829 (Recreated the PR due to some bugs)

## Changes proposed

1. Added a useOnClickOutside Hook to capture mouse events when clicked outside the scope of any element.
2. Implemented useOnClickOutside hook on dropdown list for category section

ps : It is a new PR that fixes some of the bugs that were getting produced in #1838.

## Screenshots

Please check the video for better understanding on how these changes reflect on the website.
Due to large video size I have uploaded the zip file.

[Linkshub_dropdown_bug.zip](https://github.com/rupali-codes/LinksHub/files/12886731/Linkshub_dropdown_bug.zip)

## Note to reviewers

Please do let me know if there's any room for improvement?

### CODE REVIEW

**Comment by raghav1030** [comment]
One thing I want to add is when I search anything from the search bar and a particular dropdown list gets open, then on clicking outside of the main scope to close the dropdown list, closes the dropdown list but lets the input value to remain searched. 
This causes a scenario where the outlet is redirected to home page but the side navbar still remains in the previous state when the search happened.
I suggest to erase the input value as well when the event is called outside of the scope of ref element., i.e., while closing the dropdown list, get the original state of side navbar as well (obviously by erasing the input value).

You can check exactly what I'm talking about in the instance where I searched for "Next js" in the video I shared above.

**Review by CBID2 — COMMENTED** [review]
Thanks for the improvement @raghav1030. It looks ok to me, but let's see what @rupali-codes and @Anmol-Baranwal think.

**Comment by Anmol-Baranwal** [comment]
> One thing I want to add is when I search anything from the search bar and a particular dropdown list gets open, then on clicking outside of the main scope to close the dropdown list, it closes the dropdown list but lets the input value to remain searched. This causes a scenario where the outlet is redirected to home page but the side navbar still remains in the previous state when the search happened. I suggest to erase the input value as well when the event is called outside of the scope of ref element., i.e., while closing the dropdown list, get the original state of side navbar as well (obviously by erasing the input value).
> 
> You can check exactly what I'm talking about in the instance when I searched for "Next js" in the video I shared above.

Yeah, please do it.

image

The pagination works fine for this case.

**Comment by raghav1030** [comment]
> > One thing I want to add is when I search anything from the search bar and a particular dropdown list gets open, then on clicking outside of the main scope to close the dropdown list, it closes the dropdown list but lets the input value to remain searched. This causes a scenario where the outlet is redirected to home page but the side navbar still remains in the previous state when the search happened. I suggest to erase the input value as well when the event is called outside of the scope of ref element., i.e., while closing the dropdown list, get the original state of side navbar as well (obviously by erasing the input value).
> > You can check exactly what I'm talking about in the instance when I searched for "Next js" in the video I shared above.
> 
> Yeah, please do it.
> 
> image
> 
> The pagination works fine for this case.

Just updated some changes. 

This is how it works now. 

https://github.com/rupali-codes/LinksHub/assets/94848646/b4b42b65-c0ef-4669-acf9-41ef032fc023

Please do let me know if there's anything to improve on.

**Review by rupali-codes — COMMENTED** [review]
looks fine to me, all good

**Review by CBID2 — APPROVED** [review]
Looks good to me too!

**Review by rupali-codes — APPROVED** [review]

**Comment by rupali-codes** [comment]
@Anmol-Baranwal your turn!

**Comment by raghav1030** [comment]
Can we merge this one if everything works fine?

**Comment by Anmol-Baranwal** [comment]
@raghav1030 
Done!

**Pull request merged**
