### PR TITLE
chore : Added link for CSS Pattern Generator

### LINKED ISSUE #1111: [Add] CSS Pattern Generator
### Site URL

https://patternizer.com/

### Description of the above provided site

This website will generate CSS code for Patterns

### Category

Frontend

### Sub Category

UI Generators

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Killer2OP**
## Fixes Issue
CLOSES #1111 

## Changes proposed
Added a link which can generate CSS code for Patterns

## Screenshots
image

### CODE REVIEW

**Comment by Killer2OP** [comment]
@CBID2 @rupali-codes Can you please review my PR.

**Comment by rupali-codes** [comment]
@Killer2OP your vercel deployment is getting failed bcz of the following errors, please resolve them

image

**Comment by Killer2OP** [comment]
> @Killer2OP your vercel deployment is getting failed bcz of the following errors, please resolve them
> 
> image

Now resolved,
Kindly merge it

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by k-deepak04 — APPROVED** [review]
Looks good!
Also, Tailwind CSS is in demand

**Pull request merged**
