### PR TITLE
fix : Default font-family

### LINKED ISSUE #208: Font-family
### Description

Linkshub does not have a specific font family, linkshub needs a font family to make it look nice on all devices.  

### Screenshots

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Jittojoyes98**
## Fixes Issue

 Closes #208 

## Changes proposed

Default font-family changed

## Screenshots

Screenshot from 2023-02-18 12-07-25

## Note to reviewers

None

### CODE REVIEW

**Comment by Eugene44-hub** [comment]
> ## Fixes Issue
> Closes #208
> 
> ## Changes proposed
> Default font-family changed
> 
> ## Screenshots
> Screenshot from 2023-02-18 12-07-25
> 
> ## Note to reviewers
> None

Nice work. So me and owner had a review and it wasn't looking that good. So we went for something much visible and nice to users.

**Review by rupali-codes — APPROVED** [review]
looks great to me :)

**Review by Eugene44-hub — APPROVED** [review]

**Comment by Eugene44-hub** [comment]
Nice, looks ok.

**Review by rupali-codes — APPROVED** [review]
tysm. lgtm

**Pull request merged**
