### PR TITLE
Create C programming

### PR DESCRIPTION
**Pull request by anjalisoni12**

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @anjalisoni12. Welcome to LinksHub! :) We don't accept spam pull requests, so I'm putting yours in draft mode for now. In the future, please raise an issue and wait until it's been approved and assigned to you before making a pull request. Refer to our [Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) to learn how to effectively contribute to the project. Happy Contributing! 😊

**Comment by rupali-codes** [comment]
@CBID2 just close this kind of PRs having no issue attached which them

**Comment by rupali-codes** [comment]
@anjalisoni12 please follow CONTRIBUTING guidelines before making any contribution.

**Comment by Anmol-Baranwal** [comment]
@anjalisoni12 
Sorry, but we review so many PRs already. So, it kinds of get tough to make you understand everything.

You can read: [Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)

You will find all the information on how to contribute to LinksHub.

@rupali-codes 
I'm removing the spam label, because it is permanent and we certainly don't want them to feel bad just because they don't know the flow.

**Pull request closed without merging**
