### PR TITLE
added new awesome opensource project

### PR DESCRIPTION
**Pull request by ujjawaltyagii**
## Fixes Issue

Closes : #817 

## Screenshots

image

### CODE REVIEW

**Comment by ujjawaltyagii** [comment]
please add labels and assignee !

**Review by rupali-codes — COMMENTED** [review]
looks good though, but the project is neither active nor accepting contributors..should we still keep it in _open source projects_?

**Comment by CBID2** [comment]
> looks good though, but the project is neither active nor accepting contributors..should we still keep it in _open source projects?

Hi @ujjawaltyagii. I just checked out the project. I agree with @rupali-codes. It probably won't be best to put an inactive open source project. Maybe you can replace it with a more active project?

**Comment by ujjawaltyagii** [comment]
okay ! will update it with an active project

**Review by CBID2 — APPROVED** [review]
LGTM!

**Review by rupali-codes — APPROVED** [review]
looks perfect to me

**Pull request merged**
