### PR TITLE
Auto close menu

### LINKED ISSUE #1757: [Feature] Make menu auto closing
### Description

On small devices when a user choose an option from the menu, the menu doesn't close automatically. The user has to manually do it. I want to fix that.

### Screenshots

Screenshot 2023-10-02 225607

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Palakkgoyal**
## Fixes Issue
Closes #1757 

## Changes proposed
I have made the menu auto closing. I created a issues as adding a new feature but in the code I checked later that the feature is already implemented but there was a small bug due to which it was not working. Hence, I fixed that.

### CODE REVIEW

**Comment by Palakkgoyal** [comment]
> @Palakkgoyal, can you post a screenshot of your contribution please?

Yes, sure

**Comment by Palakkgoyal** [comment]
https://github.com/rupali-codes/LinksHub/assets/116902573/74e279e3-6662-4182-a45d-3354b6b95cad

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> Thanks for the critical contribution.

**Review by rupali-codes — APPROVED** [review]
@Palakkgoyal thanks. LGTM

**Pull request merged**
