### PR TITLE
Added a YouTube sub category under DSA category and added a YouTube playlist.

### LINKED ISSUE #2037: Added a YouTube playlist for learning DSA.
### Site URL

https://www.youtube.com/playlist?list=PLIY8eNdw5tW_zX3OCzX7NJ8bL1p6pWfgG

### Description of the above provided site

A YouTube playlist for learning Data Structures and Algorithms with C++ practical implementation (Full Course for Beginners).

### Category

Youtube

### Sub Category

data-structures

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by TaeMochi12**
## Fixes Issue
Closes #2037 

## Changes proposed

Added a YouTube sub category under DSA category and added a YouTube playlist.

### CODE REVIEW

**Comment by TaeMochi12** [comment]
@Anmol-Baranwal  Please review the PR for issue #2037 .

**Review by CBID2 — APPROVED** [review]
Looks great @TaeMochi12! @Anmol-Baranwal, please review this! :)

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
@TaeMochi12 
Just creating the json file wouldn't make the subcategory.

image

Follow clear instructions as mentioned in contributing guidelines.

**Review by CBID2 — CHANGES_REQUESTED** [review]
Ooh good catch @Anmol-Baranwal. @TaeMochi12, refer to the Contribution guide to learn how to add the other files.

**Comment by TaeMochi12** [comment]
Hey , I think @rupali-codes  has already implemented the subcategory. I think I need to work on another issue.

**Review by CBID2 — APPROVED** [review]
Looks good to me @Anmol-Baranwal

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
