### PR TITLE
fix bug: search query overlaps

### PR DESCRIPTION
**Pull request by harmeetsingh11**
## Changes proposed

The `SEARCH?QUERY=....`  will not be displayed as it was not looking good. 
When the user searches for the query, the clicked sub-category will be displayed on the top bar. 

### Files modified
- `components/TopBar/TopBar.tsx`

### Before this PR
image

### After this PR
[LinksHub.webm](https://github.com/rupali-codes/LinksHub/assets/130365071/134bb49d-b25c-4782-9a9a-8388ae004fe0)

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.

## Note to reviewers
Hey @rupali-codes, @CBID2, @ujjawaltyagii  please review this PR.
Thanks.

### CODE REVIEW

**Review by k-deepak04 — APPROVED** [review]
Looks good to me, @rupali-codes will this work the query isn't displayed there but when user selects the particular item it's displayed at the top

**Comment by Anmol-Baranwal** [comment]
We can also do one thing:

Simply display `#Search: Results Not Found` or `#Search: Results Found`, and it will change based on the click or further interactions. This approach will help avoid excessive negative space.

> `I looked at this issue, because this was pinned`

**Comment by rupali-codes** [comment]
> We can also do one thing:
> 
> Simply display `#Search: Results Not Found` or `#Search: Results Found`, and it will change based on the click or further interactions. This approach will help avoid excessive negative space.
> 
> > `I looked at this issue, because this was pinned`

Ig that would be nice, thanks Anmol!

**Comment by rupali-codes** [comment]
> We can also do one thing:
> 
> Simply display `#Search: Results Not Found` or `#Search: Results Found`, and it will change based on the click or further interactions. This approach will help avoid excessive negative space.
> 
> > `I looked at this issue, because this was pinned`

Do you mean, making the search when user hits the keys, not when clicks on the search button?

**Comment by Anmol-Baranwal** [comment]
> > We can also do one thing:
> > Simply display `#Search: Results Not Found` or `#Search: Results Found`, and it will change based on the click or further interactions. This approach will help avoid excessive negative space.
> > > `I looked at this issue, because this was pinned`
> 
> Do you mean, making the search when user hits the keys, not when clicks on the search button?

Yeah, this could be good for accessibility. And this already works in the current codebase.

<hr>

> Searched query
image

Instead of displaying what we searched for, we can simply show `#Search: Results Not Found` or `#Search: Results Found`. When a subcategory is clicked, it will automatically update accordingly.

> I am talking about this. We can simply show the details here.
image

> As per video in the PR description, there is a empty space
image

**Comment by rupali-codes** [comment]
@Anmol-Baranwal gotcha, @harmeetsingh11 could you please make the changes suggested by @Anmol-Baranwal. Let us know if you need any kinda help

**Comment by harmeetsingh11** [comment]
Ok. I'll try to make the suggested changes.

**Comment by harmeetsingh11** [comment]
@rupali-codes I sincerely apologize for not successfully implement the suggested changes despite my efforts.

**Comment by Anmol-Baranwal** [comment]
> @rupali-codes I sincerely apologize for not successfully implement the suggested changes despite my efforts.

We are all here to make open source better, so there's no need to worry. If you face any difficulties with the code, feel free to ask mentors or anyone for help.

Some things are insanely tough, or can't be implemented without correct approach. So, just let us know.

**Comment by harmeetsingh11** [comment]
Thank you so much @Anmol-Baranwal for consoling me. Here's my approach (not sure it is right or not) how I am solving the issue but eventually got stuck-

**Approach**: I am passing the `data` object to `TopBar` component, and `if data.length > 0` then it displays `'Search: Found'`. Explanation with code is as follows:

1. In `pages/search.tsx`, the `data` object  was passed to the `<TopBar data={data} .../>` component.
2. Now In `TopBar component`, I imported the data object 
```
**import type { IData } from 'types'**

export const TopBar: FC<{
  className?: string | undefined
  data: IData[]
}> = (props) => {
  const { className, data } = props
```
3. Next, I have checked for this if `data` object is not empty and undefined `const searchResultFound = data !== undefined && data.length > 0`. It is working fine, It is showing true or false. OR if I try to print the `data.length`, it works as expected.

4. The problem is when I try to access `data.length` or `searchResultFound` const inside the `return()` block, it is not accessible and also not changing based on the search results. I have also tried using `useState` hook, it was not working. 
5. The  string `Search: Found` or `Search: not found` would be based on this parameter.

Can anyone help me in solving this problem? or suggest me some other approach.
Thanks

**Comment by Anmol-Baranwal** [comment]
> Thank you so much @Anmol-Baranwal for consoling me. Here's my approach (not sure it is right or not)-
> 
> **Approach**: I am passing the `data` object to `TopBar` component, and `if data.length > 0` then it displays `'Search: Found'`. Explanation with code is as follows:
> 
> 1. In `pages/search.tsx`, the `data` object  was passed to the `<TopBar data={data} .../>` component.
> 2. Now In `TopBar component`, I imported the data object 
> ```
> **import type { IData } from 'types'**
> 
> export const TopBar: FC<{
>   className?: string | undefined
>   data: IData[]
> }> = (props) => {
>   const { className, data } = props
> ```
> 3. Next, I have checked for this if `data` object is not empty and undefined `const searchResultFound = data !== undefined && data.length > 0`. It is working fine, It is showing true or false. OR if I try to print the `data.length`, it works as expected.
> 
> 4. The problem is when I try to access `data.length` or `searchResultFound` const inside the `return()` block, it is not accessible and also not changing based on the search results. I have also tried using `useState` hook, it was not working. 
> 5. The  string `Search: Found` or `Search: not found` would be based on this parameter.
> 
> Can anyone help me in solving this problem? or suggest me some other approach.
> Thanks 
> 

Give some time, we will look into it.

**Comment by Anmol-Baranwal** [comment]
@harmeetsingh11 
Apologies, I rarely get time to contribute, so I cannot help due to a lack of time. Maybe someone else can.

**Pull request closed without merging**
