### PR TITLE
feat: workflow to add labels based on title and comment

### LINKED ISSUE #1056: [Feature] Docs workflow for main codebase code and conditions
## Related Issue
#966 

Hi @ujjawaltyagii 
Since I am planning to add another workflow, I would like to provide it to you first, considering that I have already submitted a pull request for this issue. Please let me know if you plan to add this workflow, as it will undoubtedly be great for the project.

This workflow will be an automated PR labeling system that will greatly simplify the pull request management process. By analyzing the titles of PRs, it will automatically assign appropriate labels based on predefined criteria such as status, goals, and aspects. It will use `regexs`, `events`, `targets`. Since I haven't come across this workflow before, it will be a significant contribution, and I encourage you to discuss it further with @CBID2 and @rupali-codes.

To implement this workflow, you will need to use two separate workflows: one for the main code and another for defining the conditions or values of different criteria. By dividing the workflow into these two parts, it allows for better organization and maintainability of the codebase. 

Originally posted by @Anmol-Baranwal in his https://github.com/rupali-codes/LinksHub/pull/1023#issuecomment-1587853563_

## Disclaimer 
This part of the docs workflow only needs **1** pull request.

### Checklist

- [ ] I have checked the existing issues
- [ ] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
@rupali-codes 

Reference: https://github.com/hoho4190/issue-pr-labeler

## Fixes Issue

Closes #1056 

## About Regex Expression

You can test it here: https://regex101.com/

I am taking two examples, which you must read so that you can properly review the PR.

- `/\bfeat\b/`: This regular expression matches the exact word "feat" with word boundaries (`\b`). It will match strings that contain the word "feat" as a whole word, but not if it's part of another word (e.g., "defeat" or "feature").

- `/feature/i`: This regular expression matches the word "feature" (case-insensitive) anywhere within a string. It will match strings that contain "feature" in any combination of uppercase and lowercase letters (e.g., "Feature", "FEATURE", "feature").

## What you need to

1. This is the only label `goal: build` that I have used since there was none. So, you can create them, or it will automatically be created during the analysis, but it will not be permanently stored in the labels of the repository.

```yml
- label: 'goal: build'
    regexs:
      - /build/i
    events: [pull_request]
    targets: [title]
```

2. Double check the issue forms, and the labels in the repository, because it will be a huge mess if the label is wrong.

3. I don't really know how `comment` would work. I have written a workflow that can read comments on a PR, but is this the description of the issue or PR? I am not sure, so please check at your end.

```yml
  - label: 'accessibility'
    regexs:
      - /\baccessibility\b/
      - /accessibility/i
    events: [issues, pull_request] # default
    targets: [title, comment] # default
```

## Changes proposed

- I have checked issue forms and corresponding labels to properly use the config workflow.
- I have not made this workflow for analyzing issues, so let me know.
- I didn't found anything related to adding multiple labels at once, so I have used 1 label for 1 set.

```yml
- label: 'chore'
    regexs:
      - /\blink\b/
      - /link/i
    events: [pull_request]
    targets: [title]
  - label: 'goal: new-link'
    regexs:
      - /\blink\b/
      - /link/i
    events: [pull_request]
    targets: [title]
```

## Reference

There are two workflows that I found to implement this:
1. https://github.com/TimonVS/pr-labeler-action
2. https://github.com/hoho4190/issue-pr-labeler (used this due to recent release and no issues on the repository)

## Note to reviewers

- Let me know if you need anything.
- Good luck :)

### CODE REVIEW

**Review by k-deepak04 — DISMISSED** [review]

**Comment by Anmol-Baranwal** [comment]
@k-deepak04 Did you cross-check all the things properly.

**Comment by k-deepak04** [comment]
> @k-deepak04 Did you cross-check all the things properly.

yes, the code seems okay to me. so merged that i didn't test it though. can we test it without merging?
in one file you have written regex and labels to target the title and in otherworkflow you are using that to tackle the open pr's and add this automatically.

**Comment by Anmol-Baranwal** [comment]
> > @k-deepak04 Did you cross-check all the things properly.
> 
> yes, the code seems okay to me. so merged that i didn't test it though. can we test it without merging?
> in one file you have written regex and labels to target the title and in otherworkflow you are using that to tackle the open pr's and add this automatically.

Yeah, we cannot test it without merging. But we can see if there are repositories that use this to understand the working.

**Review by CBID2 — COMMENTED** [review]
Looks ok to me. Let's see what the others think.

**Comment by Anmol-Baranwal** [comment]
> looks nice to me, but i wanted to know, if the contributor adds wrong title and then correct that later, will also modify the labels?


No, it will only check when the PR/Issue is opened or re-opened.

image

Suppose a contributor changes the title, then the workflow would need to check the comment to see if the title has been changed. However, checking every comment on every issue or PR would not be appropriate, especially if there are 100+ issues. This could lead to a warning from GitHub Actions.

@rupali-codes 
Also, please let me know if we need to include issues as well. Currently, the `events` section only includes `pull_request`. I can make the necessary changes if we need to include issues, or we can remove this if it's not intended for issues.

```yml
issues:
    types:
      - opened
      - edited
``` 
Please confirm whether we should include this for issues or not.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal alright, i guess we should keep it to PRs only, as we already adding labels to issues via templates,

Done.

**Comment by CBID2** [comment]
Hey @rupali-codes. Are we going to merge this PR or??

**Comment by Anmol-Baranwal** [comment]
If you want to see an example, I have contributed the same workflow in another repository.

You can take a look at the recent PR here: `https://github.com/Opentek-Org/opentek/pull/569`

> Based on the title
image

**Comment by rupali-codes** [comment]
@CBID2 lets merge it

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
