### PR TITLE
[Added] Adding 3D CSS editor to UI Generators sub-category in frontend

### LINKED ISSUE #1665: [Add] Adding a link for a 3D Css Generator to UI generator Category
### Site URL

http://tridiv.com/

### Description of the above provided site

A platform where you can generate 3D UI components based on CSS.

### Category

Frontend

### Sub Category

UI Generators

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by MarquisTheCoder**
… Thu Sep 14 23:42:52 CDT 2023

## Fixes Issue
Closes  #1665

### CODE REVIEW

**Comment by MarquisTheCoder** [comment]
@CBID2

**Review by CBID2 — APPROVED** [review]
Well done! :)

**Review by Anmol-Baranwal — COMMENTED** [review]
First of all, the website doesn't use https encryption.

image


And I wouldn't really recommend it. Still, @CBID2 let me know and I will approve the PR.

**Comment by CBID2** [comment]
> First of all, the website doesn't use https encryption.
> 
> 
> 
> image
> 
> 
> 
> 
> 
> And I wouldn't really recommend it. Still, @CBID2 let me know and I will approve the PR.

Ooh good looking out @Anmol-Baranwal. @MarquisTheCoder, I think you should look for a different source

**Review by CBID2 — CHANGES_REQUESTED** [review]
See my reply to @Anmol-Baranwal's review for context @MarquisTheCoder

**Comment by MarquisTheCoder** [comment]
Ok, thanks for the review I'll continue looking.

**Review by CBID2 — APPROVED** [review]
Looks pretty legit to me @Anmol-Baranwal! :) Great job @MarquisTheCoder! :)

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by rupali-codes — APPROVED** [review]
lgtm too

**Pull request merged**
