### PR TITLE
updated blog section

### PR DESCRIPTION
**Pull request by anjaliSilawat**
## Fixes Issue

 I  added  content in the blog section #630

### CODE REVIEW

**Comment by anjaliSilawat** [comment]
@rupali-codes please review my pull request, provide me feedback, and merge it as well 😊

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by rupali-codes — APPROVED** [review]
looks good

**Comment by rupali-codes** [comment]
could you please resolve conflicts and format the code?

**Comment by anjaliSilawat** [comment]
> could you please resolve conflicts and format the code?

@rupali-codes I have resolved the conflicts and formatted the code. Please review and merge it.😊

**Pull request merged**
