### PR TITLE
Fix: Capitalize YouTube correctly in sidebar (#2445)

### LINKED ISSUE #2445: [OTHER] Typo in sidebar
### What would you like to share or ask?

There is a typo in the side bar `Youtube` should be `YouTube` to follow proper naming documentation.

YouTube

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by A1josa**
Closes #2445

## Fixes Issue
Capitalize YouTube correctly in sidebar

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks good to me! :)

**Comment by CBID2** [comment]
@Anmol-Baranwal and @rupali-codes, can you review this?

**Review by Jay-Karia — COMMENTED** [review]
It seems that the code is being formatted.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
