### PR TITLE
feat: Add Cloud Service Links

### LINKED ISSUE #2549: [Add] <Cloud Service Links>
### Site URL

https://www.alibabacloud.com

### Cloud Service Links

1. **Alibaba Cloud**  
   - URL:(https://www.alibabacloud.com)  
   - Description: Comprehensive suite of global cloud computing services.

2. **Strapi Cloud**  
   - URL:(https://cloud.strapi.io)  
   - Description: Headless CMS service designed for building APIs.

3. **F5 Cloud Docs**  
   - URL:(https://clouddocs.f5.com)  
   - Description: Documentation for F5 Networks’ cloud services.

4. **Clouddocs.biz**  
   - URL:(https://clouddocs.biz)  
   - Description: Cloud documentation portal with resources and guides.

5. **Grafana Cloud Docs**  
   - URL:(https://grafana.com/docs/grafana-cloud)  
   - Description: Documentation for Grafana's cloud-based observability suite.

6. **Spring Cloud**  
   - URL:(https://spring.io/projects/spring-cloud)  
   - Description: Tools for building distributed systems and microservices.

7. **Intel Cloud**  
   - URL:(https://www.intel.com/cloud)  
   - Description: Cloud services focused on performance optimization and security.

8. **Redis Cloud**  
   - URL:(https://redis.com/redis-enterprise-cloud)  
   - Description: Managed Redis database services for real-time data processing.

9. **Meta Cloud**  
   - URL:(https://cloud.meta.com)  
   - Description: Cloud infrastructure services for Meta's platforms.

10. **VMWare Cloud**  
    - URL:(https://cloud.vmware.com)  
    - Description: Hybrid cloud platform for virtualization solutions.

### Category

Cloud Computing

### Sub Category

Cloud Computing

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Nikshinde7**
## Fixes Issue

Closes #2549

## Changes proposed

- Added the new JSON files that were needed for the new cloud computing content
- Updated the categories and sidebar for the new content

## Screenshots

image
image

## Note to reviewers

The links to the following services are not working for me. Can you please check it & share the updated links that need to be there, I will update those and the PR should be good for review! 

- Clouddocs.biz URL:(https://clouddocs.biz/)
- Meta Cloud URL:(https://cloud.meta.com/)
- Cloud VMWare URL:(https://cloud.vmware.com/)

### CODE REVIEW

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Hi @Nikshinde7, please do not create a JSON file for each resource, create a single JSON file and add these resources in that file. For more details, kindly follow our contributing guidelines.

**Comment by Nikshinde7** [comment]
> Hi @Nikshinde7, please do not create a JSON file for each resource, create a single JSON file and add these resources in that file. For more details, kindly follow our contributing guidelines.

Heya @rupali-codes, I think we have a separate JSON file for each resource, so I followed the same approach. However, if we don't want it to be that way, I'll update the PR with the same! Ty!
image

**Comment by rupali-codes** [comment]
> > Hi @Nikshinde7, please do not create a JSON file for each resource, create a single JSON file and add these resources in that file. For more details, kindly follow our contributing guidelines.
> 
> Heya @rupali-codes, I think we have a separate JSON file for each resource, so I followed the same approach. However, if we don't want it to be that way, I'll update the PR with the same! Please let me know! Ty!
> 
> image

Hey @Nikshinde7, its not for each resource, its just cloud platforms like aws, orcale etc, are very huge so we created a separate subcategory for them, although we would add more resources to it later on. Please summarize the resources you're adding in a single subcategory.

**Comment by Nikshinde7** [comment]
Hey @rupali-codes I have added the necessary changes you mentioned, removed the newly created json files for each category.

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Hey @Nikshinde7, you don't have to create different subcategories.
As we already have `cloud computing` category, you just have to create a JSON file in the `cloud computing` category and name it `cloud_computing_platforms.json` then add all these resources in that file.

Let me know if you need any help

**Comment by Nikshinde7** [comment]
@rupali-codes I have renamed the subcategories to `platforms`. Thanks!

**Pull request closed without merging**
