### PR TITLE
chore: added new youtube link in subcategory web-development

### LINKED ISSUE #635: [Add] Hyperplexed youtube channel for web development
### Site URL

https://www.youtube.com/@Hyperplexed

### Description of the above provided site

This YouTuber has a very intuitive way of teaching web development by redesigning websites along with various effect tutorials in smaller and simpler ways.

### Category

Youtube

### Sub Category

web development, frontend, design inspiration, CSS 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Atharva-3000**
## Fixes Issue
Closes #635   

## Changes proposed
I added a new link for Youtube in the sub-category of web development.

### CODE REVIEW

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hey, @Atharva-3000! :) Aside from the proofreading error in the inline comment, you're off to a great start! :)

**Comment by Atharva-3000** [comment]
@CBID2 can you check this once, sorry for the silly mistake, and thank you for proofreading it.
Appreciate it 🙌.

**Review by CBID2 — APPROVED** [review]
Great job @Atharva-3000! 😊 LGTM! 😊

**Review by rupali-codes — APPROVED** [review]
looks good

**Pull request merged**
