### PR TITLE
Beautify contributors page

### PR DESCRIPTION
**Pull request by karthiknadar1204**
## Changes proposed

I have added hover effect to the individual cards, add some border to the images in the cards along with hover effect to the images.
Increased the font size of the contents inside the cards by a few pixels to make it look more prominent.

## Screenshots

https://www.awesomescreenshot.com/video/18976128?key=50ca96dffaa23aada0c865e56b2fd196

Subset of pr #1262 

Had trouble pushing more changes on the same branch, so opened a new pr

## Note to reviewers

Added the same styling as I added while making the previous pr along with the changes proposed that was to add margin between the cards.

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
can u put some margin around the components 

image

like this 
image

**Comment by karthiknadar1204** [comment]
I added some around the individual cards @rupali-codes , Are you talking about components inside the cards like the button and the name, commits.

Will push the changes today itself

**Comment by karthiknadar1204** [comment]
Done @rupali-codes

**Review by rupali-codes — APPROVED** [review]
lgtm :)

**Pull request merged**
