### PR TITLE
Added new links in defensive security category

### PR DESCRIPTION
**Pull request by Vedashri0**

### CODE REVIEW

**Comment by rupali-codes** [comment]
Hi @Vedashri0, please raise the issue and then attach the issue to this PR. 

Thanks.

**Comment by rupali-codes** [comment]
Closing the PR due to inactvity

**Comment by Vedashri0** [comment]
### Description
This PR adds resources for various cybersecurity subcategories such as threat intelligence and cloud security.

Fixes #2541

### Checklist
- [x] I have checked the existing issues.
- [x] I have read the Contributing Guidelines.

**Comment by Vedashri0** [comment]
I have updated the PR title and description to include an issue reference and provide clarity on the changes made. Could you please review it again? Thank you!

**Pull request closed without merging**
