### PR TITLE
[RESOLVED]: Sidebar not scrolling upto bottom in mobile devices 

### LINKED ISSUE #2069: [BUG] Sidebar not scrolling upto bottom in mobile devices
### Description

I'm not able see `other` category because it's not scrolling upto bottom in my phone 

### Screenshots

IMG_20231022_172159

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by Killer2OP**
## Fixes Issue
Closes #2069 

## Changes proposed

Made modification in the code.

## Note to reviewers
@Anmol-Baranwal Can you review the PR.

### CODE REVIEW

**Comment by CBID2** [comment]
Can you post a screenshot of your proposed changes @Killer2OP? It'll make it easier for us to review your PR.

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
Making it absolute is bound to create unnecessary gap.

image

Try other approach.

**Comment by Anmol-Baranwal** [comment]
> Can you post a screenshot of your proposed changes @Killer2OP? It'll make it easier for us to review your PR.

He is trying to fix the issue, like the sidebar is not scrollable to the bottom in mobile size devices, so the below categories are not visible. 

image

**Review by rupali-codes — APPROVED** [review]
lgtm

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by CBID2** [comment]
Can you approve this @Anmol-Baranwal?

**Comment by Anmol-Baranwal** [comment]
> Can you approve this @Anmol-Baranwal?

There is a huge gap in the main section when we scroll.

image

If that is okay, let me know. I will approve the PR.

**Comment by rupali-codes** [comment]
@Killer2OP can we fix this gap??

**Comment by Killer2OP** [comment]
> @Killer2OP can we fix this gap??

@rupali-codes So, the thing is that when i viewed in the mobile device the gap is not visible but when we check the code by going in inspect then the gap is visible because the screen is wide enough.

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> It works as mentioned by @Killer2OP. No gap in mobile devices.

**Pull request merged**
