### PR TITLE
IOT

### LINKED ISSUE #1280: [ADD] Internet of things (IOT)
### Category Name

IOT

### Subcategory Name

ESP32, Raspberry pi

### Additional Context

As i have experienced in IOT with esp32 and raspberry pi and it's modules like light sensor,touch sensor,ultrasonic sensor i can add the relevant resources.
Also IOT is now in boom every other device is using this and amazing projects are being made on this tech. so i think we should add this in our project.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by k-deepak04**

### CODE REVIEW

**Comment by k-deepak04** [comment]
@rupali-codes please help me with this, i have added the thing guide me where i went wrong as i'm not able to see the output.

**Review by CBID2 — DISMISSED** [review]
LGTM!

**Comment by k-deepak04** [comment]
@Anmol-Baranwal @rupali-codes can you please check and see why i'm unable to get the output on screen after adding the resources

**Comment by k-deepak04** [comment]
please check the deployment 5 hrs before one and see the code, what did i miss or done wrong, help me with that

**Comment by rupali-codes** [comment]
@abhijithmuthyala thanks

@k-deepak04 its working pefectey now

**Comment by k-deepak04** [comment]
@rupali-codes @CBID2 it will plz add label also to the pr

**Pull request merged**
