### PR TITLE
Update database.json

### LINKED ISSUE #2076: Add new database category
### Category Name

PouchDB, RethinkDB Database

### Subcategory Name

NoSQL Database

### Additional Context

RethinkDB is an open-source, distributed NoSQL database designed for real-time web applications. It's suitable for applications that require real-time data updates and dynamic queries.

 PouchDB is an open-source JavaScript database that's designed for building offline-first web and mobile applications. It allows developers to create applications that can work both online and offline while syncing data seamlessly.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by SoulNikhar**
RethinkDB: RethinkDB is an open-source database, and it's free to use. It's designed for real-time web applications.

PouchDB: PouchDB is an open-source JavaScript database that is free to use. It's particularly suitable for building offline-first web and mobile applications.

Closes #2076

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@SoulNikhar 
It is necessary to fill details in the PR template, otherwise it will always take time.

That is why there is a PR template in the first place. Please ensure it every time you create a PR.

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Comment by SoulNikhar** [comment]
> @SoulNikhar It is necessary to fill details in the PR template, otherwise it will always take time.
> 
> That is why there is a PR template in the first place. Please ensure it every time you create a PR.
> 
> Like, what someone will understand from this PR.
> 
> image
> 
> They delay reviewing the PR if there is no context.


Well, that's why I mentioned the issue number, and in the issue description, I explained all the necessary details.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
