### PR TITLE
feat: add search button in searchbar

### LINKED ISSUE #793: [Feature] <Search button added and error message generated>
### Description

- I have added the **search button** for searching queries in the website beside the search bar.

- User can submit the search from now by clicking on the search button or clicking enter button in desktops.

- I have also generated a ***custom error message*** for null query field

I am submitting the screen-shots below: 
Please assign me in this issue if you find this feature useful 😃 
Thank You :please

### Screenshots

Screenshot 2023-05-28 105829
<br>
Screenshot 2023-05-28 104418
<br>
Screenshot 2023-05-28 104402

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Soumyajit2825**
## Fixes Issue
This closes #793 

## Changes proposed

Added the search button and add validate in the search-box

## Screenshots

Screenshot 2023-05-28 104418

### CODE REVIEW

**Comment by rupali-codes** [comment]
@Soumyajit2825 let me help you out, your vercel deployment is getting failed bcz of the following error

image

**Comment by Soumyajit2825** [comment]
Ok working on it

**Review by rupali-codes — COMMENTED** [review]
why did you delete _web-development.json_ file?

**Comment by Soumyajit2825** [comment]
There was some merge conflicts issues
I have mistakenly deleted the whole file
😢

**Review by CBID2 — DISMISSED** [review]
LGTM

**Comment by rupali-codes** [comment]
@Soumyajit2825 the same issue, you shouldn't have deleted that. Try to commit it back anyways :). Otherwise you will have to close this PR nd create a new one

**Comment by Soumyajit2825** [comment]
@rupali-codes I have fixed the issue
Can you check once?
What's the error now?

**Comment by Soumyajit2825** [comment]
In my local device the website is running smoothly :)

**Comment by Soumyajit2825** [comment]
@rupali-codes I'm closing this PR and making a new one

**Pull request closed without merging**
