### PR TITLE
#2071-Side pagination

### PR DESCRIPTION
**Pull request by Raj100679**

### CODE REVIEW

**Comment by Raj100679** [comment]
@CBID2 @rupali-codes @aftabrehan Done the requested changes, Can you check this

**Comment by Anmol-Baranwal** [comment]
Replacement of #2071.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please deploy this. We will review and merge it quickly.

**Review by rupali-codes — COMMENTED** [review]
The deployment is failing
image

**Comment by Raj100679** [comment]
@rupali-codes I will look into it

**Comment by rupali-codes** [comment]
> @rupali-codes I will look into it

you working on it..

**Comment by Raj100679** [comment]
@rupali-codes Yeah, I dont know somewhing is breaking my code, I will raise a new pr or will try to fix this one

**Comment by aftabrehan** [comment]
> @rupali-codes Yeah, I dont know somewhing is breaking my code, I will raise a new pr or will try to fix this one

Let me know if you need any help.

**Comment by Raj100679** [comment]
@rupali-codes @aftabrehan Can you check if it is deploying properly

**Comment by rupali-codes** [comment]
> @rupali-codes @aftabrehan Can you check if it is deploying properly

Sure, thanks for the changes

**Review by rupali-codes — APPROVED** [review]
looks good to me

**Review by aftabrehan — APPROVED** [review]
Looks good to me! 🚀

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> @rupali-codes I'm approving, but there are two navigation and on the last page, both are shown in single screen.

**Pull request merged**
