### PR TITLE
feat: add workflow to prevent multiple issues 🔐

### LINKED ISSUE #1274: [Feature]: ADD WORKFLOW SCRIPT TO PREVENT MULTIPLE ISSUES 🔐
### Description

- We want to add a workflow script regarding closing the issues.
-  This script will look into the contributor created issue and checks if he already created an issue, If an issue exists the new issue will be closed.
-  According the GSSoC Contributing guidelines, A contributor must want to finish one issue before creating another issue.
- But in this repository the contributors are spamming multiple issues, This is strictly against the contributing guidelines.
- After adding this script you don't want to state that `please create one issue at a time` for every contributor who creates more than one issue at a time. This script will automate the process and closes the new one if already an existing one is found.
- Please assign this issue to me @rupali-codes, @CBID2 to make the work done.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Fixes Issue

Closes #1274 

## Changes proposed

- This PR is about adding workflow script which helps us to prevent multiple issues created by a single contributer.
- The script will look for existing issue whenever a contributor creates a new issue, if existing issue is already there to work then the newly created issue will be closed.
- This will ensure us to follow the Open Source Contributing guidelines, and make the game more fair by providing chance for every contributors out there to make their first contribution.

# Important thing to note
- This script needs your personal token to work, @rupali-codes you need to provide a valid GitHub personal access token as a secret named `PERSONAL_ACCESS_TOKEN` in your repository. Here's how you can do it:

-  Generate a GitHub personal access token:
    -  Go to your GitHub account settings.
    -  Select "Developer settings" from the sidebar.
    -  Click on "Personal access tokens."
    -  Click "Generate new token."
    -  Give your token a description and select the appropriate scopes or permissions (they are showed in a screenshot below).
    -  Click "Generate token" at the bottom.
    -  **Important**: Make sure to copy the generated token. Once you leave the page, you won't be able to see it again.

-  Add the personal access token as a secret in your repository:
    -  Go to your repository on GitHub.
    -  Click on "Settings" at the top right.
    -  In the sidebar, click on "Secrets."
    -  Click on "New repository secret."
    -  Provide a name for the secret, that must should be named as `PERSONAL_ACCESS_TOKEN`.
    -  Paste the personal access token you generated in the "Value" field.
    -  Click "Add secret" to save it.

| SCREENSHOT ABOUT THE SCOPES AND PERMISSIONS YOU WANT TO ENABLE  |
| :--: |
| image |

## Screenshots

| EXAMPLE SCREENSHOT OF CLOSING MY SECOND ISSUE BY WORKFLOW |
| :--: |
| image |

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Hey there @rupali-codes & @CBID2, please make sure to review this PR.

I can understand that this PR requires some work from your side, but it's definitely worth it.

Let's make open source for accessible for everyone!

**Review by CBID2 — APPROVED** [review]
Hi @0xabdulkhalid! :) I revised the comment in the GH but overall, it's great! :)

**Comment by rupali-codes** [comment]
@k-deepak04 what do you think of it? i don't think this would be the correct way, as we are already locking the issues?

**Comment by k-deepak04** [comment]
> @k-deepak04 what do you think of it? i don't think this would be the correct way, as we are already locking the issues?

yes @rupali-codes we don't need this right now also a contributor like us can go through the code open 2-3 issues and take the next week to work on those, so i also think it's not proper also it will reduce the contributors that are contributing to our website

**Review by k-deepak04 — COMMENTED** [review]
sorry does not align with our idea

**Pull request closed without merging**
