### PR TITLE
fix: the Broken link of Language/general_web_fundamental/hitesh choudhary youtube

### PR DESCRIPTION
**Pull request by akashchoudhary436**
-fix bug
The Broken link of the Language/general_web_fundamental/hitesh choudhary youtube is been fixed 
Changes made is 
Before fix link is : https://www.youtube.com/@HiteshChoudharydotcom
After Link fix : https://www.youtube.com/@HiteshCodeLab
Screenshot 2024-10-02 004529
Screenshot 2024-10-02 004516

### CODE REVIEW

**Comment by rupali-codes** [comment]
@akashchoudhary436 why have you closed it?

**Comment by rajneesh-18** [comment]
@akashchoudhary436 there is 3 failing checks. So, update your pr with all the changes.

**Comment by akashchoudhary436** [comment]
@rupali-codes the link had been fixed kindly review it and merge the PR

**Comment by rupali-codes** [comment]
> @rupali-codes the link had been fixed kindly review it and merge the PR

Is there any issue to be closed with this PR?

**Comment by akashchoudhary436** [comment]
@rupali-codes  No issue

**Comment by akashchoudhary436** [comment]
@rupali-codes No issue

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
