### PR TITLE
ADD : Custom Scrollbar

### LINKED ISSUE #905: [Feature] Custom scrollbar for whole website
### Description

The website has native scrollbar.
The scrollbar can be customized to match the website theme and to improve UI.

We can two type of custom scrollbar generally :
- like https://www.krashish.live/about : where scrollbar disappear and is visible during scrolling only.
- like https://xomoy144.netlify.app/ : where scrollbar is always visible but is customized according to website theme only.

---

I can see you have implemented the **custom scrollbar** on your website, _but only for the left panel_
I am taking about the **whole website**, just _like https://www.krashish.live_

**_If in place of browser's default scrollbar, we use the custom scrollbar used in left panel, for the whole website, then the overall UI of website will be enhanced_** 

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by dev-AshishRanjan**
## Fixes Issue #905 

Closes #905 

## Changes proposed
The website has native scrollbar as overall
The scrollbar can be customized to match the website theme and to improve UI.
_If in place of browser's default scrollbar, we use the custom scrollbar used in left panel, for the whole website, then the overall UI of website will be enhanced_

## Screenshots
|Light mode |Dark mode |
|---- |---- |
|Screenshot 2023-06-04 015847 | Screenshot 2023-06-04 015832

## Note to reviewers
The Main scrollbar has been changed according to scrollbar present in left panel

### CODE REVIEW

**Comment by ujjawaltyagii** [comment]
@CBID2  We were both assigned this issue ? After getting assigned I was done with my changes too for scroll-bar and then saw this PR  :)
It's 3:24 wasted efforts ? :)

image

#### Output :
image

**Comment by CBID2** [comment]
I thought you wanted to volunteer @ujjawaltyagii

**Comment by dev-AshishRanjan** [comment]
Hi @ujjawaltyagii ,
I am sorry for the confusion
As I was assigned the issue, and there were only few lines of codes to be written,
So I worked on the issue and raised the PR

I am extremely sorry for your wasted time

**Comment by CBID2** [comment]
> Ooh I misread your message in the Issue @ujjawaltyagii. Sorry

**Review by CBID2 — APPROVED** [review]
Looks good to me! :) LGTM! :)

**Comment by CBID2** [comment]
> Hi @ujjawaltyagii , I am sorry for the confusion As I was assigned the issue, and there were only few lines of codes to be written, So I worked on the issue and raised the PR
> 
> I am extremely sorry for your wasted time

**Comment by CBID2** [comment]
@ujjawaltyagii, I added you as a reviewer for @dev-AshishRanjan's pull request. You can add your suggestions there if you find things to improve! :)

**Comment by ujjawaltyagii** [comment]
@CBID2 just wanted to know if two people were assigned with the same issue then the PR submitted for <b>gssoc</b> will be submitted with "collab-tag" with both assignees or the person who opens PR first will get to submit ?

**Comment by CBID2** [comment]
> @CBID2 just wanted to know if two people were assigned with the same issue then the PR submitted for <b>gssoc</b> will be submitted with "collab-tag" with both assignees or the person who opens PR first will get to submit ?
 Ooh good question @ujjawaltyagii. I think it's the latter.

**Comment by rupali-codes** [comment]
> @CBID2 just wanted to know if two people were assigned with the same issue then the PR submitted for gssoc will be submitted with "collab-tag" with both assignees or the person who opens PR first will get to submit ?

That's for when the issue is too large and hard for one person to manage :)

**Review by rupali-codes — APPROVED** [review]
looks good to me

**Pull request merged**
