### PR TITLE
fix: removed duplicate Screeenlane link

### PR DESCRIPTION
**Pull request by sonylomo**
## Changes proposed

Remove duplicate link

## Screenshots

Screenshot 2023-04-06 at 3 49 24 PM

## Note to reviewers

Maybe we should add a check for duplicate links? Wdyt 🤔

### CODE REVIEW

**Comment by rupali-codes** [comment]
Yeah, you are right, we can go through it once

**Review by ujjawaltyagii — COMMENTED** [review]
Thanks for observing and I totally agree that we should add functionality to check whether the resource has already been added or not. (I will try to come up with a solution and when i am done i will probably raise a PR)

**Comment by sonylomo** [comment]
Is it OK if I make the link checker issue and work on it instead? I wanted to confirm that it was a credible idea first.  🙂

**Comment by ujjawaltyagii** [comment]
@sonylomo Sure ! It is indeed a credible idea. One way to implement this would be to have the system check the links that users enter against the existing links in the database. If a user tries to add a link that already exists in the database, the system can then display a message or warning that the resource has already been added. To implement this you could write a script that checks the link or related date to the entered data.

**Comment by rupali-codes** [comment]
> @sonylomo Sure ! It is indeed a credible idea. One way to implement this would be to have the system check the links that users enter against the existing links in the database. If a user tries to add a link that already exists in the database, the system can then display a message or warning that the resource has already been added. To implement this you could write a script that checks the link or related date to the entered data.

For now, we can merge this PR and create a new issue for checking duplicacy

**Pull request merged**
