### PR TITLE
feat: add Community subcategory in Resources

### LINKED ISSUE #895: [ADD] Communities under Resources
### Category Name

none

### Subcategory Name

Communities

### Additional Context

- I was planning to add this as a category, so feel free to share your views on whether it should be included and in which category it should be placed
- Like `showwcase`, `product hunt`, `LinkedIn`

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #895 

## Screenshots

communities

### CODE REVIEW

**Review by rupali-codes — CHANGES_REQUESTED** [review]
should be _communities_ right? 🙃

**Comment by Anmol-Baranwal** [comment]
> should be _communities_ right? 🙃

I thought it was strange to include `communities` as a category since it is already listed under `resources.` Therefore, I intentionally changed it. Thank you for clarifying.

**Comment by rupali-codes** [comment]
> > should be _communities_ right? 🙃
> 
> I thought it was strange to include `communities` as a category since it is already listed under `resources.` Therefore, I intentionally changed it. Thank you for clarifying.

Oh, yeah you are right, it does not match with Resources, we should place it inside Other. right?

**Comment by Anmol-Baranwal** [comment]
> > > should be _communities_ right? 🙃
> > 
> > 
> > I thought it was strange to include `communities` as a category since it is already listed under `resources.` Therefore, I intentionally changed it. Thank you for clarifying.
> 
> Oh, yeah you are right, it does not match with Resources, we should place it inside Other. right?

Done!
image

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
