### PR TITLE
Added the search button beside the SearchBar and added validation 

### LINKED ISSUE #793: [Feature] <Search button added and error message generated>
### Description

- I have added the **search button** for searching queries in the website beside the search bar.

- User can submit the search from now by clicking on the search button or clicking enter button in desktops.

- I have also generated a ***custom error message*** for null query field

I am submitting the screen-shots below: 
Please assign me in this issue if you find this feature useful 😃 
Thank You :please

### Screenshots

Screenshot 2023-05-28 105829
<br>
Screenshot 2023-05-28 104418
<br>
Screenshot 2023-05-28 104402

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Soumyajit2825**
## Fixes Issue
This closes #793 

## Changes proposed

Added the search button and add validate in the search-box

## Screenshots

Screenshot 2023-05-28 104418

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
@rupali-codes Again the errors are coming
Can you tell me in which file the error is?

**Review by CBID2 — COMMENTED** [review]
Hi @Soumyajit2825. I'm not too sure what the error is, so I highly recommend waiting for @rupali-codes to respond so we can discuss it together.

**Comment by rupali-codes** [comment]
@Soumyajit2825 
image

**Comment by rupali-codes** [comment]
Also, please update the PR title to something meaningful :)

**Comment by Soumyajit2825** [comment]
@rupali-codes Finally it works!!!!!
You can check the changes in the preview now

**Comment by Soumyajit2825** [comment]
@CBID2 Have you checked my work ? 😀

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Comment by CBID2** [comment]
Just saw it @rupali-codes! Looks great @Soumyajit2825

**Comment by Soumyajit2825** [comment]
> Just saw it @rupali-codes! Looks great @Soumyajit2825

Thanks 😄 
I am happy to work with you in this project

**Comment by ujjawaltyagii** [comment]
@rupali-codes @CBID2 It looks good in web view and normal mobile view but I think for medium screen size and desktop view in mobile, there is a issue if i am not wrong ! 
Like the search button should be aligned right taking a specific max-width of total side-menu and in remaining space we should have the search bar.

But when I am trying to open this in medium size screens it looks like this :

image

<b>So ideally, shouldn't the search bar and button be stretched to cover the side menu ? specially, the search button should be aligned on the right side like the other icons (roll-up/roll down, close icon)</b>

what do you think about it ?

**Review by ujjawaltyagii — COMMENTED** [review]
@rupali-codes @CBID2 It looks good in web view and normal mobile view but I think for medium screen size and desktop view in mobile, there is a issue if i am not wrong ! 

Like the search button should be aligned right taking a specific max-width of total side-menu and in remaining space we should have the search bar.

But when I am trying to open this in medium size screens it looks like this :

image

<b>So ideally, shouldn't the search bar and button be stretched to cover the side menu ? specially, the search button should be aligned on the right side like the other icons (roll-up/roll down, close icon)</b>

what do you think about it ?

**Comment by CBID2** [comment]
> @rupali-codes @CBID2 It looks good in web view and normal mobile view but I think for medium screen size and desktop view in mobile, there is a issue if i am not wrong ! 
> 
> 
> 
> Like the search button should be aligned right taking a specific max-width of total side-menu and in remaining space we should have the search bar.
> 
> 
> 
> But when I am trying to open this in medium size screens it looks like this :
> 
> 
> 
> image
> 
> 
> 
> <b>So ideally, shouldn't the search bar and button be stretched to cover the side menu ? specially, the search button should be aligned on the right side like the other icons (roll-up/roll down, close icon)</b>
> 
> 
> 
> what do you think about it ?

That does make sense

**Comment by Soumyajit2825** [comment]
@ujjawaltyagii @CBID2 @rupali-codes I don't think that it will look good if I aligned the search button in the right side 
Now it's upto you
I will make changes according too you

**Review by CBID2 — APPROVED** [review]
LGTM!

**Comment by CBID2** [comment]
> > @rupali-codes @CBID2 It looks good in web view and normal mobile view but I think for medium screen size and desktop view in mobile, there is a issue if i am not wrong !
> > Like the search button should be aligned right taking a specific max-width of total side-menu and in remaining space we should have the search bar.
> > But when I am trying to open this in medium size screens it looks like this :
> > image
> > So ideally, shouldn't the search bar and button be stretched to cover the side menu ? specially, the search button should be aligned on the right side like the other icons (roll-up/roll down, close icon)
> > what do you think about it ?
> 
> That does make sense

Hey @ujjawaltyagii! :) I just checked out the button on both screens and I changed my mind. Having it stretched out would look unattractive, so I agree with @Soumyajit2825's current design.

**Comment by Soumyajit2825** [comment]
😀

**Review by ujjawaltyagii — APPROVED** [review]
okay !! then it looks good to me 👍 \

**Comment by Soumyajit2825** [comment]
> okay !! then it looks good to me 👍

@rupali-codes waiting for your review now!

**Comment by rupali-codes** [comment]
> > okay !! then it looks good to me 👍
> 
> @rupali-codes waiting for your review now!

I guess it's still better the way it is, as of now we are making the search when user starts typing, after adding the button they would have to click on button to perform the search which may not be good for user experience

**Comment by Soumyajit2825** [comment]
> > > okay !! then it looks good to me 👍
> > 
> > 
> > @rupali-codes waiting for your review now!
> 
> I guess it's still better the way it is, as of now we are making the search when user starts typing, after adding the button they would have to click on button to perform the search which may not be good for user experience

As of user experience there is button for searching in most of the cases.
😞 OK then invalid contribution it is
I said to you previously then all said that it's looking great 😀

**Comment by Soumyajit2825** [comment]
@rupali-codes This is also good
But this is also a button right !!
You just change the design of the button to a logo and added placeholder text ❓

**Comment by ujjawaltyagii** [comment]
> @Soumyajit2825 @CBID2 @ujjawaltyagii how's lookin' now?
> 
> image

It's looking great !! 💯

**Comment by Soumyajit2825** [comment]
> > @Soumyajit2825 @CBID2 @ujjawaltyagii how's lookin' now?
> > image
> 
> It's looking great @rupali-codes !! 💯

@rupali-codes @CBID2 @ujjawaltyagii So what I have to now?
Remake the button as you have made?

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Comment by rupali-codes** [comment]
> LGTM! :)

We were about to make some changes Chrissy, the button color also doesn't match with our theme 🙂

**Comment by Soumyajit2825** [comment]
Screenshot 2023-06-02 223828

I tried this @rupali-codes @CBID2 

Thanks for merging 😄

**Comment by CBID2** [comment]
> > LGTM! :)
> 
> 
> 
> We were about to make some changes Chrissy, the button color also doesn't match with our theme 🙂

Oops

**Comment by CBID2** [comment]
> > LGTM! :)
> 
> We were about to make some changes Chrissy, the button color also doesn't match with our theme 🙂

I tried to revert the changes but couldn't @rupali-codes.

**Comment by Soumyajit2825** [comment]
> > > LGTM! :)
> > 
> > 
> > We were about to make some changes Chrissy, the button color also doesn't match with our theme 🙂
> 
> I tried to revert the changes but couldn't @rupali-codes.

@CBID2 @rupali-codes I have done the changes
Should I create a new issue on this?
If yes the please let me know I have already done the changes

**Comment by CBID2** [comment]
> > > > LGTM! :)
> 
> > > 
> 
> > > 
> 
> > > We were about to make some changes Chrissy, the button color also doesn't match with our theme 🙂
> 
> > 
> 
> > I tried to revert the changes but couldn't @rupali-codes.
> 
> 
> 
> @CBID2 @rupali-codes I have done the changes
> 
> Should I create a new issue on this?
> 
> If yes the please let me know I have already done the changes

That would help

**Comment by Soumyajit2825** [comment]
Ok @CBID2 I'm creating new issue
Please assign me

**Comment by CBID2** [comment]
> Ok @CBID2 I'm creating new issue
> 
> Please assign me
> 
> 

Make sure you reference this one in your new issue. It's for context

**Comment by Soumyajit2825** [comment]
@CBID2 I have created the issue describing what the prblm is!
Should I have to edit anything?

**Comment by CBID2** [comment]
> @CBID2 I have created the issue describing what the prblm is!
> 
> Should I have to edit anything?

In the issue report?

**Comment by Soumyajit2825** [comment]
> > @CBID2 I have created the issue describing what the prblm is!
> > Should I have to edit anything?
> 
> In the issue report?

Yes

**Comment by CBID2** [comment]
> > > @CBID2 I have created the issue describing what the prblm is!
> > > Should I have to edit anything?
> > 
> > 
> > In the issue report?
> 
> Yes

Adding [Rupali's comment](https://github.com/rupali-codes/LinksHub/pull/823#issuecomment-1574043314) to the issue would suffice @Soumyajit2825.

**Comment by Soumyajit2825** [comment]
@CBID2 PR done please check the changes

**Comment by CBID2** [comment]
> > LGTM! :)
> 
> 
> 
> We were about to make some changes Chrissy, the button color also doesn't match with our theme 🙂

Hey @rupali-codes. @Soumyajit2825 created a new issue for the button. Check it out [here](https://github.com/rupali-codes/LinksHub/pull/904)

**Pull request merged**
