### PR TITLE
[fix] add GitHub fork button

### LINKED ISSUE #774: [Feature] Add GitHub fork button
### Description

I was inspired by #768, so I’m going to create a fork button to display how many copies LinksHub has. 
**Note:** **I am eager to work on this feature with a GSSOC’23 contributor.**
**Update**: I created the button using [this website](https://buttons.github.io/)

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by CBID2**
## Fixes Issue
Closes #774 

## Changes proposed

I added a script link in the <head> section to create a GitHub Fork button.

## Note to reviewers

This my first time creating this feature, so constructive feedback is appreciated.

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Please write the complete code as this is just the script file, and kindly assign me this issue.

```html
<a class="github-button" href="https://github.com/rupali-codes/LinksHub/fork" data-icon="octicon-repo-forked" data-size="large" data-show-count="true" aria-label="Fork rupali-codes/LinksHub on GitHub">Fork</a>
```

image

**Comment by Anmol-Baranwal** [comment]
@rupali-codes @CBID2 
There are two approaches to making this possible, depending on your decision. 
Only the first approach, which involves dynamically loading the script in a component using `useEffect`, works. 

Now, you can either suggest the problem with the other approaches, or we can proceed with the first approach.

## First Approach

> works :)

```typescript

... import statements

export const Header: FC<{}> = () => {
  const { toggleNav } = useContext(GlobalContext)

 <-------------------------------ADDED THIS CODE BEGIN------------------------------->
  useEffect(() => {
    const script = document.createElement('script')
    script.src = 'https://buttons.github.io/buttons.js'
    script.async = true
    script.defer = true
    document.head.appendChild(script)
    return () => {
      document.head.removeChild(script)
    }
  }, [])
<-------------------------------ADDED THIS CODE END------------------------------->
  return (
    <header className="fixed top-0 left-0 z-30 row-start-1 row-end-2 flex h-[76px] w-screen items-center justify-between">
      <div className="bg-base-200 relative h-full grow px-8 dark:bg-gray-900 lg:bg-gray-100 lg:dark:bg-[#101623]">
        
        <-------------------------------ADDED THIS CODE BEGIN------------------------------->
        <Link
          className="github-button"
          href="https://github.com/rupali-codes/LinksHub"
          data-icon="octicon-repo-forked"
          data-size="large"
          data-show-count="true"
          aria-label="Fork rupali-codes/LinksHub on GitHub"
        >
          Fork
        </Link>
       <-------------------------------ADDED THIS CODE END------------------------------->
    </header>
  )
}
```

<br>

This dynamically add the script only when it's needed (e.g., in the `Header` component), it allows to defer the loading of the script until it's necessary. This can help reduce the initial load time of your application by avoiding unnecessary script loading for pages that don't use the GitHub Buttons.

If the script is only needed on specific pages or components, dynamically loading it when required can help reduce the initial load time and bundle size for pages that don't use the GitHub Buttons.

image

> It is generally recommended to include scripts dynamically within the components or layout files for better control and compatibility with server-side rendering.

## Second Approach

> In _document.js `failed` :(

I don't know for certain, but one possible reason could be that Next.js does not execute JavaScript code within the `_document.js` file during server-side rendering. Therefore, including the script directly in the `_document.js` file might not work as expected.

If we can include the script directly in the `_document.js` file, it will be loaded and cached by the browser when the page is first rendered. This can improve subsequent page loads since the script will be retrieved from the cache instead of making an additional network request.

## Third Approach

> In _app.js `failed` :(

```typescript
// _app.js
import 'styles/globals.css'
import type { AppProps } from 'next/app'
import GeneralLayout from 'layouts/GeneralLayout'
import { GlobalProvider } from 'context/GlobalContext'
import { Preloader } from 'components/Loader/Preloader'
import { ThemeProvider } from 'next-themes'
import Head from 'next/head' // Import the Head component

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider defaultTheme="dark">
      <GlobalProvider>
        <Preloader backgroundColor="bg-violet-800" color="#8b5cf6" size={40}>
          <GeneralLayout>
            <Component {...pageProps} />
          </GeneralLayout>
        </Preloader>
      </GlobalProvider>

      <Head>
        <script async defer src="https://buttons.github.io/buttons.js"></script>
      </Head>
    </ThemeProvider>
  )
}
```

**Comment by Anmol-Baranwal** [comment]
> I go with the first method @Anmol-Baranwal

What is the update?

**Comment by CBID2** [comment]
> > I go with the first method @Anmol-Baranwal
> 
> 
> 
> What is the update?

I picked the first method @Anmol-Baranwal. I was under the impression that you'd add the code there.

**Comment by Anmol-Baranwal** [comment]
> > > I go with the first method @Anmol-Baranwal
> > 
> > 
> > What is the update?
> 
> I picked the first method @Anmol-Baranwal. I was under the impression that you'd add the code there.

I thought you would do that, LOL. Just add the code in any component you want; `header.tsx` would be appropriate.

Please write the code that is signified between the comments.
```
<-------------------------------ADDED THIS CODE BEGIN------------------------------->
add this code in the component as suggested above
<-------------------------------ADDED THIS CODE END------------------------------->
```

**Comment by CBID2** [comment]
> > > > I go with the first method @Anmol-Baranwal
> 
> > > 
> 
> > > 
> 
> > > What is the update?
> 
> > 
> 
> > I picked the first method @Anmol-Baranwal. I was under the impression that you'd add the code there.
> 
> 
> 
> I thought you would do that, LOL. Just add the code in any component you want; `header.tsx` would be appropriate.
> 
> 
> 
> Please write the code that is signified between the comments.
> 
> ```
> 
> <-------------------------------ADDED THIS CODE BEGIN------------------------------->
> 
> add this code in the component as suggested above
> 
> <-------------------------------ADDED THIS CODE END------------------------------->
> 
> ```
> 
> 
> 
> > You can use Tailwind CSS utility classes to write the style you want.

I'll try it and then you can review it again. Sound good @Anmol-Baranwal?

**Comment by CBID2** [comment]
> ```ts
> <Link
>           className="github-button"
>           href="https://github.com/rupali-codes/LinksHub"
>           data-icon="octicon-repo-forked"
>           data-size="large"
>           data-show-count="true"
>           aria-label="Fork rupali-codes/LinksHub on GitHub"
>         >
>           Fork
>         </Link>
> ```

Hi @Anmol-Baranwal. I ended up creating a new pull request. Here it is: #929

**Comment by Anmol-Baranwal** [comment]
> > ```ts
> > <Link
> >           className="github-button"
> >           href="https://github.com/rupali-codes/LinksHub"
> >           data-icon="octicon-repo-forked"
> >           data-size="large"
> >           data-show-count="true"
> >           aria-label="Fork rupali-codes/LinksHub on GitHub"
> >         >
> >           Fork
> >         </Link>
> > ```
> 
> Hi @Anmol-Baranwal. I ended up creating a new pull request. Here it is: #929

Why did you create a new PR? Please refrain from creating any additional PRs than these two. I will incorporate the changes into PR #929.

**Comment by rupali-codes** [comment]
This issues has been addressed in #774 PR!

**Pull request closed without merging**
