### PR TITLE
Stockvault

### LINKED ISSUE #510: [Add] Stockvault
### URL

https://www.stockvault.net/

### Description of the above provided site

Stockvault is a comprehensive online resource for quality stock photos and graphics, perfect for designers, bloggers, and marketers seeking to enhance their visual content. Discover a vast collection of free stock images and vectors on Stockvault, the ultimate destination for creative professionals and hobbyists alike.

### Category

Frontend

### Sub Category

images

### PR DESCRIPTION
**Pull request by parma1111**
## Fixes Issue

Closes #510

## Changes proposed

This website purpose is to collect and archive high resolution photographs.

## Screenshots

Screenshot (792)

Screenshot (793)

## Note to reviewers

Any kind of feedback would be appreciated.

### CODE REVIEW

**Review by ujjawaltyagii — COMMENTED** [review]
lgtm but can we improve description a little : "Stockvault is a platform for high-quality photographs for personal and non-commercial design projects, curated for photographers, designers, and students."

**Comment by parma1111** [comment]
> lgtm but can we improve description a little : "Stockvault is a platform for high-quality photographs for personal and non-commercial design projects, curated for photographers, designers, and students."

> Now review the PR

**Review by ujjawaltyagii — APPROVED** [review]
Perfect !! lgtm 👍

**Review by rupali-codes — COMMENTED** [review]
lgtm

**Pull request merged**
