### PR TITLE
add gate smashers #479

### LINKED ISSUE #479: [Add] add gate smashers
### URL

https://www.youtube.com/@GateSmashers

### Description of the above provided site

Gate Smashers provides content for Computer science subjects such as Operating System, DBMS, Computer Architecture, Software Engineering and more.

### Category

Youtube

### Sub Category

For this issue, create a new Subcategory named _Computer Science_ and this channel in that category

### PR DESCRIPTION
**Pull request by imbeshat**
## Fixes Issue
Closes #479 

## Changes proposed
Added Gate Smashers in Youtube section (sub-category Computer Science)

## Screenshots
image

### CODE REVIEW

**Review by Harsh-2909 — COMMENTED** [review]
I think that you need to make some more changes in `types/index.ts` file when you are adding new category.

**Review by rupali-codes — APPROVED** [review]
thanks, looks good to me

**Comment by rupali-codes** [comment]
> I think that you need to make some more changes in `types/index.ts` file when you are adding new category.

It's when we are new category such as YouTube, but here we are adding new Subcategory in Youtube category

**Comment by Harsh-2909** [comment]
Oh i see. Thanks for clearing my confusion.

**Pull request merged**
