### PR TITLE
new sub category added in youtube folder

### PR DESCRIPTION
**Pull request by raghav1030**

### CODE REVIEW

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Hi, as per the updates, we have removed ids from subcategories, so please remove them and also remove package-locck.json file

**Comment by raghav1030** [comment]
I have to remove the ids from the newly added subcategory and then push it back....right?

**Comment by rupali-codes** [comment]
> I have to remove the ids from the newly added subcategory and then push it back....right?

yes, and make sure to commit only those files u r making changes in

**Comment by raghav1030** [comment]
I've already made the commit... please let me know if there's any room for improvement.

**Comment by rupali-codes** [comment]
> I've already made the commit... please let me know if there's any room for improvement.

It's showing conflicts in package-lock.json file. And i can't either resolve them nor merge this PR.

**Comment by raghav1030** [comment]
I'm just restarting the whole process as to solve the conflicts in the package.json file... this ig is due to the different build versions of npm being installed in the process and i'm not being able to find them so no worries

**Pull request closed without merging**
