### PR TITLE
Added CPP playlist to cpp.json

### LINKED ISSUE #1958: [Add] <Adding CPP Video Tutorial link>
### Site URL

https://www.youtube.com/watch?v=z9bZufPHFLU&list=PLfqMhTWNBTe0b2nM6JHVCnAkhQRGiZMSJ

### Description of the above provided site

Exclusive C++ Programming playlist by Apna College. Beginner to Advanced

### Category

Languages

### Sub Category

c++ programming

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by Kritika30032002**
## Fixes Issue

Closes #1958

## Changes proposed

Added CPP playlist

### CODE REVIEW

**Review by Anmol-Baranwal — DISMISSED** [review]
🚀 Looks good to me.

**Comment by Anmol-Baranwal** [comment]
@CBID2 @rupali-codes 

Please review the PR.

Also, why did we not get the notifications? It must have been done by CODEOWNERS file right?

**Comment by CBID2** [comment]
> @CBID2 @rupali-codes 
> 
> 
> 
> Please review the PR.
> 
> 
> 
> Also, why did we not get the notifications? It must have been done by CODEOWNERS file right?

I think it's because it works with specific issues @Anmol-Baranwal.

**Review by CBID2 — APPROVED** [review]
Looks good to me

**Pull request merged**
