### PR TITLE
Kage - Closes [Add] Beecrowd @2322 and Tech News @2323

### LINKED ISSUE #2322: [Add] Beecrowd
### Site URL

judge.beecrowd.com

### Description of the above provided site

Beecrowd is a platform for competitive programming.

"We are a global community of developers committed to keep evolving as students and professionals. Train algorithms and programming challenges and become the expert you always dreamed to be."

### Category

Competitive Programming

### Sub Category

platforms

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### LINKED ISSUE #2323: [ADD] Tech News
### Category Name

Resources

### Subcategory Name

Tech News

### Additional Context

- [Hacker Tab](https://hackertab.dev/) is a handy extension designed to help developers stay up-to-date with the latest tech happenings. Whether you’re a frontend wizard, a backend sorcerer, a full-stack magician, a mobile app conjurer, or a data scientist spellcaster, Hackertab has got you covered! 🧙‍♂️🔮
- [Reddit Programming](https://www.reddit.com/r/programming/)
- [TLDR Newsletter](https://tldr.tech/)
- [GitHub trending](https://github.com/trending)

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by KKaged**
## Fixes Issue
Closes #2322, Closes #2323 

## Changes proposed

Adds Beecrowd to the Database, resulting it being displayed on the site.

## Screenshots

Screenshot 2024-03-26 at 19 29 16

## Note to reviewers

If any mistakes or issues, DM me on discord.
@ kkage.

### CODE REVIEW

**Comment by KKaged** [comment]
New commit adds Tech News under resources with 4 cards that display information to the resources.

Screenshot 2024-03-28 at 15 41 24

Screenshot 2024-03-28 at 15 41 43

**Review by KKaged — COMMENTED** [review]
@CBID2 This is where the commits of my previous pull request are.

**Comment by rupali-codes** [comment]
@KKaged can you please resolve the conflicts :)

**Comment by Anmol-Baranwal** [comment]
@KKaged 
Please let us know if you encounter any problems or if you're unsure how to resolve conflicts. I recommend watching a simple tutorial that can guide you through the process, as conflicts often arise when creating a PR. If you continue to face difficulties, please inform us, and one of us will help you.

**Comment by rupali-codes** [comment]
@KKaged any updates?

**Comment by rupali-codes** [comment]
@KKaged closing this PR as no activity shown..

**Pull request closed without merging**
