### PR TITLE
added dev tools

### PR DESCRIPTION
**Pull request by ujjawaltyagii**
## Fixes Issue
Added new sub-category "Dev Tools" for adding dev related resources like Vim commands

Made changes to ``>types>index.ts`` , ``>database>index.ts`` , ``>database>data.ts`` , ``created devtools.json``

- Added resources like ``VSCodium`` and ``Postman``

## Screenshots
image

image

### CODE REVIEW

**Comment by ujjawaltyagii** [comment]
@rupali-codes @CBID2 done !!

**Review by rupali-codes — COMMENTED** [review]
lgtm :)

**Comment by ujjawaltyagii** [comment]
@CBID2 it would be great if you review my PR so we can merge it :)

**Review by CBID2 — APPROVED** [review]
LGTM! 👍🏾 😄

**Comment by rupali-codes** [comment]
thank you @ujjawaltyagii & @CBID2 :)

**Pull request merged**
