### PR TITLE
Feat restyle sidebar

### LINKED ISSUE #308: [Feature] improve the sidebar style
### Description

Improve the sidenavbar ui for a better experience.

### Screenshots

chrome-capture-2023-2-5
chrome-capture-2023-2-5
chrome-capture-2023-2-5 (1)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Lourvens**
Closes #308

### CODE REVIEW

**Review by rupali-codes — COMMENTED** [review]
Hi, can we just make the background color like before? 

image

**Comment by Lourvens** [comment]
Hi I made the change you requested

**Review by rupali-codes — APPROVED** [review]
thank you so much! looks great to me

**Review by CBID2 — APPROVED** [review]
Looks great to me! 😊

**Pull request merged**
