### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by Noothan-am**
related to #605 
created landing page

### CODE REVIEW

**Comment by CBID2** [comment]
Can you post a screenshot of the landing page @Noothan-am? It'll make the reviews easier

**Review by CBID2 — COMMENTED** [review]
It looks good

**Comment by CBID2** [comment]
For some reason, the deployment check failed

**Comment by Noothan-am** [comment]
> For some reason, the deployment check failed. @Noothan-am, I think you need to resolve the conflicts on your branch

this is a complete different app. so all the files in linkshub websites are missing in this, that is why build has failed.

**Comment by Noothan-am** [comment]
> > > For some reason, the deployment check failed. @Noothan-am, I think you need to resolve the conflicts on your branch
> > 
> > 
> > this is a complete different app. so all the files in linkshub websites are missing in this, that is why build has failed.
> 
> Ohhh

hey, what next??

**Comment by CBID2** [comment]
> > > > For some reason, the deployment check failed. @Noothan-am, I think you need to resolve the conflicts on your branch
> 
> > > 
> 
> > > 
> 
> > > this is a complete different app. so all the files in linkshub websites are missing in this, that is why build has failed.
> 
> > 
> 
> > Ohhh
> 
> 
> 
> hey @CBID2, what next??

Wait for @rupali-codes review.

**Comment by Noothan-am** [comment]
> @Noothan-am You can not create the PR like this, if we going to merge it, then we will lost the whole site, there should be some other ways. Create a folder in components and name it LandingPage, after that, put all the necessary files related to landingpage in that directory. What we need is, when user visits _https://linkshub.dev_ they should see the landing page and when they click on _get started_ then they should be redirected to the main site

ok i will add it soon

**Pull request closed without merging**
