### PR TITLE
Added Kinde auth

### LINKED ISSUE #1811: Kinde Auth
### Site URL

https://kinde.com/

### Description of the above provided site

Everything you need for authentication in one platform
Reduce friction with passwordless authentication
Free your users from passwords and remove the hassle of password resets with one click sign up and sign in.

### Category

Backend

### Sub Category

Authen

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by Toyin5**
Added kinde auth
Closes #1811

### CODE REVIEW

**Comment by Toyin5** [comment]
@rupali-codes pls review

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Comment by Anmol-Baranwal** [comment]
@Toyin5 
There is a workflow, so if you read contribution guidelines. There are conventions for making PR title such as `chore` and other stuff. It's not mandatory, but the workflow add labels and automatically calls us for reviews whenever that is done.

I would highly recommend using it. It just improves credibility.
https://www.conventionalcommits.org/en/v1.0.0/

@CBID2 
Ready for review.

**Review by CBID2 — APPROVED** [review]
Well done @Toyin5

**Pull request merged**
