### PR TITLE
Add FreeImages

### LINKED ISSUE #1569: [Add] Image Resource
### Site URL

https://www.freeimages.com/

### Description of the above provided site

FreeImages is a one-stop shop for high-quality free photos and icons.

### Category

Frontend

### Sub Category

images

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Sriparno08**
## Fixes Issue

Closes #1569

## Changes proposed

I have added a new image resource to the website.

## Screenshots

image

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

> A unique description would definitely be appreciated, as this can be described for other resources as well.

**Comment by CBID2** [comment]
> 🚀 Looks good to me.
> 
> 
> 
> > A unique description would definitely be appreciated, as this can be described for other resources as well.

If you feel this way @Anmol-Baranwal, I highly recommend changing your review to request changes and implement some in-line comments to the description. It'll exemplify your idea clearly

**Comment by CBID2** [comment]
Forget it @Anmol-Baranwal. I merged it! :) looks ok

**Pull request merged**
