### PR TITLE
Add Paletton to Colors

### LINKED ISSUE #1039: [Add] Paletton
### Site URL

https://paletton.com/

### Description of the above provided site

This is a go-to platform for developers and designers, offering an intuitive interface to effortlessly explore, generate, and visualize stunning color schemes for your projects.

### Category

Frontend

### Sub Category

colors

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Oyebolade**
## Fixes Issue

Closes #1039

## Changes proposed

Paletton links was added to colors category

## Screenshots
paletton

### CODE REVIEW

**Review by k-deepak04 — APPROVED** [review]
LGTM

**Review by CBID2 — APPROVED** [review]
LGTM!

**Comment by CBID2** [comment]
> LGTM

You're going to have to approve it again @k-deepak04. The merge didn't automatically happen once I gave my approval.

**Review by k-deepak04 — APPROVED** [review]

**Comment by k-deepak04** [comment]
> > LGTM
> 
> You're going to have to approve it again @k-deepak04. The merge didn't automatically happen once I gave my approval.

approved but still not getting the option to merge.

**Pull request merged**
