### PR TITLE
Created Dart Subcategory in The Languages Category

### LINKED ISSUE #1331: [ADD] <Languages/Dart>
### Category Name

Languages

### Subcategory Name

Dart

### Additional Context

I'd like to add a subcategory for the Dart programming language under the Languages category.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by tayyab-ilyas**
## Fixes Issue

Closes #1331 

## Changes proposed

Created subcategory for Dart programming language in the 'Languages' category.

## Screenshots
Screenshot 2023-07-23 074803

### CODE REVIEW

**Comment by tayyab-ilyas** [comment]
hey @CBID2 @k-deepak04 can you review this? please don't forget to add the Gssoc'23 label. Thanks!

**Comment by CBID2** [comment]
> hey @CBID2 @k-deepak04 can you review this? please don't forget to add the Gssoc'23 label. Thanks!

Done @tayyab-ilyas

**Comment by tayyab-ilyas** [comment]
> > hey @CBID2 @k-deepak04 can you review this? please don't forget to add the Gssoc'23 label. Thanks!
> 
> Done @tayyab-ilyas

thanks! please give your approval as well

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by k-deepak04 — APPROVED** [review]

**Pull request merged**
