### PR TITLE
fix of the footer bug

### LINKED ISSUE #199: [BUG] FOOTER
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

Footer is not clearly visible in light mode

### Screenshots

image

### Any additional information?

If you observe keenly then only you can see footer.

### What browser are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by hparashar27**
## issue #199 

Closes #199 

## Changes proposed

In order to fix the footer bug , the text color changes from gray-200 to gray color

## Screenshots

dark
light

### CODE REVIEW

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Hi, could you please fix the underline color? Should be as same as text color
It looks whitish in dark mode

image

and doesn't look so good in light mode

image

**Comment by hparashar27** [comment]
@rupali-codes what about these ones -
chrome_2sBGpYb2T0
chrome_LJq7Xv12RZ

**Comment by hparashar27** [comment]
@rupali-codes have a look on this -
chrome_CsRDUnoinT
chrome_2sBGpYb2T0

**Review by rupali-codes — APPROVED** [review]
Looks perfect. Thank you so much :)

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Hi, could you please remove REAME.md and package-lock.json form this PR?

**Comment by hparashar27** [comment]
ok sure i am getting an error in removing these files ,ok i do one thing i make a new and clean pr for this issues and close this one,what do you think ?

**Comment by rupali-codes** [comment]
> ok sure i am getting an error in removing these files ,ok i do one thing i make a new and clean pr for this issues and close this one,what do you think ?

yes do so :)

**Comment by hparashar27** [comment]
i make a new pr for this issue  #217

**Pull request closed without merging**
