### PR TITLE
feat: show maintainers/contributors state in contributors section

### LINKED ISSUE #1300: [Feature] Showing tags in contributors page
### Description

> To differentiate between maintainers and contributors

As per suggestion in https://github.com/rupali-codes/LinksHub/issues/500#issuecomment-1635570981

### Screenshots

image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #1300

> I created a new issue, because I believe we need to implement one more section just for maintainers.

## Screenshots

Same for maintainers, showing `M` and for Contributors showing `C`

I implemented the hover part, because tool tip would not be great for custom styling.

> Hover
image

> Normal
image

## Note to reviewers

@rupali-codes 
This should be a level 3 PR since it was very tough to implement and it's a new feature.

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
What do you think, should we separate the data as in present code, or we can strictly specify the types and use it in the file.
Separating data can be useful, if we have to use it in multiple locations.

**Comment by rupali-codes** [comment]
> @rupali-codes What do you think, should we separate the data as in present code, or we can strictly specify the types and use it in the file. Separating data can be useful, if we have to use it in multiple locations.

I think we should sperate the data, that would make the code more readable

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
I believe this should be Level 3 due to its complexity, and it took me several iterations to achieve the desired result.

**Review by rupali-codes — APPROVED** [review]
looks great to me

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
What about #500?

> Should there be a different section just for maintainers. If not, then please close that issue.

**Pull request merged**
