### PR TITLE
added AWS Amplify for database and authentication

### LINKED ISSUE #1259: [Add] AWS Amplify for  database and authentication
### Site URL

https://aws.amazon.com/amplify/

### Description of the above provided site

AWS Amplify is a comprehensive development platform that simplifies building scalable and secure web and mobile applications with AWS services.

### Category

Backend

### Sub Category

authentication, database

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Mihan786Chistie**
## Fixes Issue

Closes #1259

## Changes proposed

Added AWS Amplify as database and authentication inside the database folder.

## Screenshots

awsAmplify
awsAmplifyAuth

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM!

**Comment by k-deepak04** [comment]
@Mihan786Chistie please resolve the conflicts

**Review by CBID2 — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Comment by Mihan786Chistie** [comment]
Please check it @CBID2, @k-deepak04, @rupali-codes

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by CBID2 — DISMISSED** [review]
LGTM

**Review by rupali-codes — CHANGES_REQUESTED** [review]
you've removed the previous resources, you have to keep both

**Comment by Mihan786Chistie** [comment]
> you've removed the previous resources, you have to keep both

Ok👍

**Review by CBID2 — APPROVED** [review]
LGTM

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
