### PR TITLE
add dsa roadmap in category other under roadmaps

### LINKED ISSUE #1939: [Add] add dsa roadmap in category other under roadmaps
### Site URL

https://www.guvi.in/blog/dsa-roadmap-beginners-should-know/

### Description of the above provided site

GUVI offers free and paid learning courses on various IT and tech domains in Indian vernacular languages .GUVI's mission is "to make technical education available to all in their native languages" .This EdTech company provides diverse professional and certificate tech courses to students, graduates, and working professionals who wish to upskill themselves.

### Category

Other

### Sub Category

roadmaps

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by psqaure11**
closes #1939 

## Note to reviewers

 Kindly look into the PR and please let me know if any further change is needed

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks good to me! :) @rupali-codes, you're turn! :)

**Review by rupali-codes — COMMENTED** [review]
@psqaure11 can you please reference the issue? or you haven't raised it?

**Comment by Anmol-Baranwal** [comment]
@psqaure11 
Following the PR template is a must. It includes special words like 'fixes' or 'resolves' that connect your issue to the PR, as explained in the official docs.

If you don't link the issue correctly, even after the PR is merged, the issue might stay open, causing huge problems.

> You can see here. I've done it.
image

I'm doing it for you this time. Please ensure it next time.

Just a heads-up to help you link issue properly next time. Have a great day!

**Comment by psqaure11** [comment]
@Anmol-Baranwal Thanks for correcting this on my part will keep this in mind from now onwards.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Pull request merged**
