### PR TITLE
chore: wrapped Aside component with nav

### LINKED ISSUE #855: Semantic suggestion
### What would you like to share or ask?

Current Semantic :
```html
<div>
        <aside></aside>
        <main></main>
</div>
``` 
Supposedly correct semantic :
```html
<nav>
        <!-- here the content wrapped in <aside> should be added -->
        <!-- Reason this part of the page is common to every page -->
</nav>
<main></main>
``` 

[----MDN Reference](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure#html_layout_elements_in_more_detail)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #855 

## Changes proposed

- according to MDN semantic reference

## Note to reviewers

- I'm not sure if this is all that needs to be done. I'm open to any changes.

### CODE REVIEW

**Review by CBID2 — CHANGES_REQUESTED** [review]
Check [this](https://stackoverflow.com/questions/42113846/using-an-aside-inside-of-a-nav-element)for reference @Anmol-Baranwal.

**Comment by Anmol-Baranwal** [comment]
> Check [this](https://stackoverflow.com/questions/42113846/using-an-aside-inside-of-a-nav-element)for reference @Anmol-Baranwal.

As referenced here, I have already wrapped the `Aside` component in the `nav`

**Review by rupali-codes — APPROVED** [review]
lgtm

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 

Please provide clarification on why this is considered a Level 1 contribution?

image

**Comment by rupali-codes** [comment]
> @rupali-codes
> 
> Please provide clarification on why this is considered a Level 1 contribution?
> 
> image

we have updated the label descriptions, level1 issues tends to add new resources/categories or performing any small tasks

**Review by rupali-codes — APPROVED** [review]

**Comment by rupali-codes** [comment]
@CBID2 could you review the PR please

**Comment by Anmol-Baranwal** [comment]
@CBID2 
Could you please review this pull request :)

**Review by ujjawaltyagii — APPROVED** [review]
lgtm 👀

**Pull request merged**
