### PR TITLE
chore: add open source projects

### LINKED ISSUE #2011: [Add] My open source projects
### Site URL

https://github.com/oyepriyansh/DevTweet , https://github.com/oyepriyansh/DevProfiles

### Description of the above provided site

About DevTweet - DevTweet is an exciting open-source project designed exclusively for developers. It serves as a microblogging platform, allowing developers to post their thoughts and updates through contributions. It's a space where developers can freely share their ideas and connect with the community.

About DevProfiles - DevProfiles is a platform for developers to easily share their profiles, spotlight your skills, and connect with fellow developers in the community.

### Category

Open Source

### Sub Category

projects

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by oyepriyansh**
## Fixes Issue

Closes #2011 

## Changes proposed

Added:
- DevProfiles - https://devprofiles.is-an.app
- DevTweet - https://devtweet.is-an.app

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks good to me @oyepriyansh!

**Review by CBID2 — APPROVED** [review]
👍🏾

**Comment by CBID2** [comment]
@rupali-codes, @Anmol-Baranwal, your turn! :)

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Comment by Anmol-Baranwal** [comment]
@oyepriyansh 
You shouldn't start working on the PR, if the issue isn't assigned.

Keep this in mind in the future PRs. Just a heads up!

**Comment by oyepriyansh** [comment]
> @oyepriyansh You shouldn't start working on the PR, if the issue isn't assigned.
> 
> Keep this in mind in the future PRs. Just a heads up!

My bad, I thought this was not an enhancement or bug-fix pull request, so I can start working on it.

**Comment by Anmol-Baranwal** [comment]
> > @oyepriyansh You shouldn't start working on the PR, if the issue isn't assigned.
> > Keep this in mind in the future PRs. Just a heads up!
> 
> My bad, I thought this was not an enhancement or bug-fix pull request, so I can start working on it.

The flow is for every PR, and this flow is followed everywhere in Open Source. You must be aware of it considering you manage so many good projects😅

**Comment by oyepriyansh** [comment]
> > > @oyepriyansh You shouldn't start working on the PR, if the issue isn't assigned.
> > > Keep this in mind in the future PRs. Just a heads up!
> > 
> > 
> > My bad, I thought this was not an enhancement or bug-fix pull request, so I can start working on it.
> 
> The flow is for every PR, and this flow is followed everywhere in Open Source. You must be aware of it considering you manage so many good projects😅

sure, i will keep that in mind next time.

**Pull request merged**
