### PR TITLE
feat(navbar): Created a subcategory Hacktoberfest under open-source c…

### LINKED ISSUE #2515: [OTHER] Create new subcategory Hacktoberfest
### What would you like to share or ask?

Create a subcategory `Hacktoberfest` under `open-source` category. Also, add a highlighted _new_ tag on `open-source` category.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by RJPalmer**
…ategory  (#2515)

## Fixes Issue

Fixes #2515 
## Changes proposed

* adds 'Hacktoberfest' subcategory to data.ts
* adds 'Hacktoberfest' subcategory to index.ts
* adds 'Hacktoberfest' subcategory to CategoryDescriptions.ts
* adds 'new' text to 'open-source' category in SideNavBar

### CODE REVIEW

**Comment by rupali-codes** [comment]
@RJPalmer could you please resolve the error?
image

**Comment by RJPalmer** [comment]
Will do

**Comment by RJPalmer** [comment]
@rupali-codes  The changes have been made. Please review

**Review by rupali-codes — COMMENTED** [review]
@RJPalmer please remove the new tag

**Comment by RJPalmer** [comment]
> @RJPalmer please remove the new tag

This has been completed

**Review by rupali-codes — APPROVED** [review]
lgtm

**Comment by RJPalmer** [comment]
@Anmol-Baranwal @CBID2 @aftabrehan Please review & let me know if any further changes are needed

**Pull request merged**
