### PR TITLE
docs: fix formatting issues in CONTRIBUTING.md

### LINKED ISSUE #2111: [DOCS] <formatting issues>
### Issue Description

I was scrolling through the [Examples of Valid Commit Messages subsection of the Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#%EF%B8%8F-examples-of-valid-commit-messages)and noticed that some of the examples are missing backticks(see screenshot for reference). This causes contributors, especially those who are new to open source, to be confused.  

### Screenshots or Examples (if applicable)

docs issue

### Proposed Solution (optional)

_No response_

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am participating in Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by 0scvr**
## Fixes Issue

Closes #2111

## Changes proposed
Fixed the formatting of some of the commit message examples in the contributing guidelines.

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @0scvr. Welcome to LinksHub! :) We don't accept unassigned pull requests, so I'm putting yours in draft mode for now. In the future, please wait until you have been assigned to the issue before you submit a pull request. Refer to our [Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) to learn how to effectively contribute to the project. Happy Contributing! 😊

**Comment by Anmol-Baranwal** [comment]
@0scvr 
Comment on the issue to get assigned.

**Comment by 0scvr** [comment]
Please assign me 😀

**Comment by Anmol-Baranwal** [comment]
@0scvr 
This is PR. Comment on issue or I'm going to assign it to someone else. Do it on priority basis.

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hi @0scvr. The hyperlink in line 283 is not working. Can you fix it please? Here's the link: https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md#commits-message-guidelines-

**Review by Anmol-Baranwal — APPROVED** [review]
@0scvr 
Thanks so much for the changes. Appreciate it buddy.

**Review by rupali-codes — APPROVED** [review]
awesome, lgtm

**Pull request merged**
