### PR TITLE
Android development playlist link added

### LINKED ISSUE #813: [Add] add link of android development playlist created  by Saumya Singh
### Site URL

https://youtube.com/playlist?list=PLTV_nsuD2lf4UCTV6xwvNPvFdmCNKyhc8&feature=share8

### Description of the above provided site

It is the 30 days bootcamp playlist by Saumya Singh on android development in which she covers each and every topic of android development. It is beginner friendly tutorial which contains topics like installation, studio tool , interactive UI, layouts , web view ,data base, notifications and much more.

### Category

Youtube

### Sub Category

Android

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by singhishika02**
## Fixes Issue
Close #813 

## Changes proposed
Link of the playlist added

### CODE REVIEW

**Review by rupali-codes — CHANGES_REQUESTED** [review]
please add _languages_ in the category
and remove package.json, you don't have to commit it, :)

**Comment by singhishika02** [comment]
@rupali-codes 
I have made the required changes.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Review by ujjawaltyagii — APPROVED** [review]
@singhishika02  Great start ! Changes look good to me 👍

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Pull request merged**
