### PR TITLE
Fix: [BUG] category name in the breadcrumbs

### LINKED ISSUE #2263: [BUG] category name in the breadcrumbs
### Description

The category name having two words adds extra space in the name when clicking on the category name, thus, it redirects to an error page.

### Solution
Add a dash (-) in between the words, for example: for `competitive programming` it should be `competitive-programming`. Remember, you only have to do this in the link not the heading showing in breadcrumbs.

### Screenshots

image

It's redirecting to `https://www.linkshub.dev/competitive programming`

### Any additional information?

Please let us know if you need any kinda help.

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by heysolomon**
## Fixes Issue
Closes #2263 

## Changes proposed
Fixed the breadcrumbs category link error. Added a dash(-) in between the two words. 

## Screenshots
image

image

## Note to reviewers
image

I noticed that the word in the breadcrumbs in mobile view had a dash(-), so I removed it. Please let me know if it's okay or I should revert that change

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please deploy this :)

**Review by Anmol-Baranwal — DISMISSED** [review]
🚀 Looks good to me. 

> The change with Competitive programming is good enough. Everything works!

**Review by aftabrehan — DISMISSED** [review]
Looks good to me! 🚀

**Comment by rupali-codes** [comment]
@heysolomon can you please resolve the conflicts?

**Comment by heysolomon** [comment]
> @heysolomon Resolve the conflicts :)

Okay, sorry I missed this. I thought it got resolved. Working on it now

**Comment by heysolomon** [comment]
> @heysolomon can you please resolve the conflicts?

Okay

**Comment by heysolomon** [comment]
@Anmol-Baranwal, @rupali-codes  see what it shows me. I can't seem to resolve the conflicts because of access rights.
image

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal, @rupali-codes see what it shows me. I can't seem to resolve the conflicts because of access rights. 
You cannot use web editor since the conflicts are huge.
You can resolve it through the terminal itself.

**Comment by heysolomon** [comment]
> > @Anmol-Baranwal, @rupali-codes see what it shows me. I can't seem to resolve the conflicts because of access rights.
> 
> You cannot use web editor since the conflicts are huge. You can resolve it through the terminal itself.

Okay

**Comment by heysolomon** [comment]
@Anmol-Baranwal, I can't seem to see the conflicts on my own end. I have done `git pull`, still nothing. When I get conflicts like this, I run `git pull` on my terminal all the affected files and areas get flagged in my IDE, but it's not working for this for some reason; I might be doing something wrong I wouldn't know. Is there something I need to do? or should I close the PR and create another one?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal, I can't seem to see the conflicts on my own end. I have done `git pull`, still nothing. When I get conflicts like this, I run `git pull` on my terminal all the affected files and areas get flagged in my IDE, but it's not working for this for some reason; I might be doing something wrong I wouldn't know. Is there something I need to do? or should I close the PR and create another one?

The instructions are clearly mentioned.

image

Otherwise, you can manually compare your file changes with the original file in the repo to understand and ultimately resolve it accordingly.

**Comment by heysolomon** [comment]
> > @Anmol-Baranwal, I can't seem to see the conflicts on my own end. I have done `git pull`, still nothing. When I get conflicts like this, I run `git pull` on my terminal all the affected files and areas get flagged in my IDE, but it's not working for this for some reason; I might be doing something wrong I wouldn't know. Is there something I need to do? or should I close the PR and create another one?
> 
> The instructions are clearly mentioned.
> 
> image
> 
> Otherwise, you can manually compare your file changes with the original file in the repo to understand and ultimately resolve it accordingly.

okay, thank you.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
Please deploy and let's merge this before any other PR to avoid creating conflicts.

**Review by rupali-codes — APPROVED** [review]
lgtm

**Review by aftabrehan — APPROVED** [review]
Looks good to me! 👍

**Comment by CBID2** [comment]
@rupali-codes, I can't merge it

**Pull request merged**
