### PR TITLE
Broken Link Checker - Github Action

### LINKED ISSUE #2357: [Feature] Broken Link Checker - Github Action
### Description

I believe that it will be a great idea to setup a GitHub action that runs periodically and checks for broken links.

I just implemented it in my project and I would like to share my knowledge and received feedback to make it better.

### Screenshots

here is an example from my own project:
image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by JuanPabloDiaz**
* Check links #2357

## Fixes Issue

Closes #2357

## Changes proposed

https://github.com/JuanPabloDiaz/LinksHub/issues/39

## Screenshots
image

### CODE REVIEW

**Comment by rupali-codes** [comment]
@Anmol-Baranwal @CBID2  could you please review it

**Review by CBID2 — APPROVED** [review]
Looks good to me. What do you think @Anmol-Baranwal?

**Comment by JuanPabloDiaz** [comment]
After completing the pull request, I realized it would be beneficial to extend the functionality by running the workflow whenever a pull request is opened to check the URLs as well. This feature is likely already configured in my workflow, but I haven't found a way to test it yet.

**Comment by Anmol-Baranwal** [comment]
> After completing the pull request, I realized it would be beneficial to extend the functionality by running the workflow whenever a pull request is opened to check the URLs as well. This feature is likely already configured in my workflow, but I haven't found a way to test it yet.

I want a clear overview of how it works and what exactly you are trying to do.

Will it open a PR if there are broken URLs in the repo? What exactly will happen? Just let me know so I can check the docs and necessary links to help.

**Comment by JuanPabloDiaz** [comment]
In addition...

### Link Checker:

The Link Checker step reads the `.lycheeignore` file specified by the --exclude-file .lycheeignore argument to determine which links or files should be excluded from the link checking process. 

### What Happens if Broken Links are Found

If broken links are detected during any of the trigger events, the workflow will:

1. Check if there is an existing open issue with the label `automated-link-issue`.
2. If an existing issue is found, it will update this issue with the details of the broken links.
3. If no existing issue is found, it will create a new issue with the details of the broken links.
4. The issue will be labeled with `automated-link-issue`, `broken-link`, and `docs` for easy identification and tracking.

**Comment by Anmol-Baranwal** [comment]
@JuanPabloDiaz 
Thank you! I will check the docs and necessary workflows in a day or two.

**Comment by JuanPabloDiaz** [comment]
@Anmol-Baranwal, I found a [simpler workflow](https://github.com/emmabostian/developer-portfolios/blob/master/.github/workflows/link-checker.yml) that we could use instead (it is clean and easy to understand). I test it in one of my projects and it does the job.

**Comment by Anmol-Baranwal** [comment]
Sure. I will check it out. 

Let's proceed with this one then.

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
New workflow seems better. I think it's safe to proceed.

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
