### PR TITLE
feat: add technical writing category and link to Docsify 

### LINKED ISSUE #1692: [Add] <Docsify>
### Site URL

https://docsify.js.org/#/?id=docsify

### Description of the above provided site

If you're looking for a static generator that makes it easier for you to create docs, you'll love Docsify. Unlike GitBook, it does not generate static HTML files. Instead, it loads and parses your Markdown files and displays them as a website.

### Category

Technical Writing. See #1693 for context 

### Sub Category

Tools 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### LINKED ISSUE #1693: [ADD] <Technical Writing/Tools>
### Category Name

Technical Writing

### Subcategory Name

Tools 

### Additional Context

This issue will be addressed in #1692 too. 

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by CBID2**
## Fixes Issue
Closes #1693 
Closes #1692 

## Changes proposed
I added a technical writing category with a "tools" subcategory with a link to Docsify 

## Note to reviewers
It's still a WIP

### CODE REVIEW

**Review by Anmol-Baranwal — COMMENTED** [review]
I think the category with the dir name doesn't match as shown in the image.

Do it `technical-writing` rather than `technical writing` in json file.

image

Let me know if it resolves the issue.

**Comment by CBID2** [comment]
> I think the category with the dir name doesn't match as shown in the image.
> 
> Do it `technical-writing` rather than `technical writing` in json file.
> 
> image
> 
> Let me know if it resolves the issue.

The issue remains @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
LOL!
You added so many new changes. @rupali-codes will help you with this.

I will have to add one category myself, to understand the codebase since it has changed much.

**Comment by CBID2** [comment]
> LOL! You added so many new changes. @rupali-codes will help you with this.
> 
> I will have to add one category myself, to understand the codebase since it has changed much.

She will. She's just feeling sick at the moment.

**Review by rupali-codes — COMMENTED** [review]
why its showing the file names like this? 

image

**Comment by CBID2** [comment]
> why its showing the file names like this? 
> 
> 
> 
> image
> 
> 

These were mostly likely commits from other merged PRs.

**Comment by rupali-codes** [comment]
@CBID2 we will have to close this PR, and please raise a fresh PR containing the changes related to only this 2 issues.

**Comment by CBID2** [comment]
> @CBID2 we will have to close this PR, and please raise a fresh PR containing the changes related to only this 2 issues. 

Ok @rupali-codes

**Pull request closed without merging**
