### PR TITLE
React icons link

### LINKED ISSUE #66: [Add] React Icons
### URL

https://react-icons.github.io/react-icons/

### Description of the above provided site

React-icons is a small library that helps you add icons to your React apps. All of the icons are SVG.

### Category

Frontend

### Sub Category

"icons"

### PR DESCRIPTION
**Pull request by haldaranup**
## Note to reviewers
Fixed the id issue, two objects having the same id.

### CODE REVIEW

**Comment by rupali-codes** [comment]
@haldaranup can we use these icons outside of react?

**Comment by haldaranup** [comment]
> @haldaranup can we use these icons outside of react?

Yes, we can but it would require some additional setup and configuration.

**Comment by rupali-codes** [comment]
okay, nice

**Comment by VenkataBhaskarr** [comment]
I think the react-icons is specifically for react projects only and we can't use them outside react projects as they are to be called as components(syntax of react).

**Comment by haldaranup** [comment]
> I think the react-icons is specifically for react projects only and we can't use them outside react projects as they are to be called as components(syntax of react).

Oh, thanks for pointing this out @VenkataBhaskarr

**Comment by rupali-codes** [comment]
@haldaranup we can not add this, cause we are adding common, library or framework free resources. Please make a new PR if you have anything else to add. Thank you

**Pull request closed without merging**
