### PR TITLE
chore: add link digitomize in cp/cp-helpers

### LINKED ISSUE #2206: [Add] Digitomize
### Site URL

https://www.digitomize.com/

### Description of the above provided site

A platform for CP enthusiasts to explore coding contests (LeetCode, Codeforces, CodeChef, etc.) and showcase skills through dynamic portfolios, displaying updated ratings, achievements, and coding history.

### Category

Competitive Programming

### Sub Category

cp-helper

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by sarava338**
## Fixes Issue

closes #2206

## Changes proposed

added digitomize link in the

category -> Competitive Programming
subcategory -> Helpers

## Screenshots

image

### CODE REVIEW

**Comment by Anmol-Baranwal** [comment]
@rupali-codes 
The changes are fine, but need deployment to double check.

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
Hi @sarava338 

Please add the category description for the subcategory `cp-helpers`.

> You can find the component in `TopBar/categoryDescriptions.ts`

image

**Comment by sarava338** [comment]
> Hi @sarava338 
> 
> Please add the category description for the subcategory `cp-helpers`.
> 
> > You can find the component in `TopBar/categoryDescriptions.ts`
> 
> image
> 

oops, I missed it out. 😅

**Comment by sarava338** [comment]
Hey @Anmol-Baranwal, But I don't have any description for the sub category cp-helpers ?
Do you have any ? Or I will pick up something myself?

**Comment by Anmol-Baranwal** [comment]
@sarava338 
You can add something that fits the description. Please write a brief one yourself :)

**Comment by sarava338** [comment]
Ok, There is no description for other CP sub categories too. Does it require a new issue ? Or May i proceed to add them here as well ?

**Comment by Anmol-Baranwal** [comment]
> Ok, There is no description for other CP sub categories too. Does it require a new issue ? Or May i proceed to add them here as well ?
> 

If you want, you can add them. Just check if there are no category descriptions for them, maybe with an incorrect name.

**Comment by CBID2** [comment]
> > Ok, There is no description for other CP sub categories too. Does it require a new issue ? Or May i proceed to add them here as well ?
> 
> If you want, you can add them. Just check if there are no category descriptions for them, maybe with an incorrect name.

I think you can add them in @Anmol-Baranwal. It'll make the process go quickly.

**Comment by sarava338** [comment]
Upated with the description of my choice.

- cp-platforms: Online platforms such as Codeforces, HackerRank, and LeetCode provide a virtual arena for programmers to engage in competitive programming challenges, honing their problem-solving skills.

- cp-tutorials: Various online resources offer tutorials on algorithms, data structures, and problem-solving techniques, assisting aspiring competitive programmers in enhancing their coding proficiency and strategic thinking.

- cp-helpers: Coding libraries, templates, and community forums serve as valuable aids for competitive programmers, offering pre-written code snippets, discussions, and collaborative support to optimize problem-solving efficiency.

image

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> @sarava338 Thanks so much for the extra changes :D 

@CBID2 @rupali-codes @aftabrehan 
Review this :)

**Review by aftabrehan — APPROVED** [review]
Excellent PR, @sarava338 💪 🚀 💯

**Review by CBID2 — APPROVED** [review]
LTGM

**Comment by CBID2** [comment]
I can't merge this. @rupali-codes, can you help me?

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
