### PR TITLE
fix bug: search query overlaps search result

### PR DESCRIPTION
**Pull request by harmeetsingh11**
## Changes proposed
Removed TopBar component as it was impractical.
 
### Files deleted
- `components/TopBar/CategoryDescriptions.ts`
- `components/TopBar/TopBar.tsx`
- `components/TopBar/index.ts` 

### Files modified
- `components/Header/Header.tsx`
- `pages/[subcategory]/index.tsx`
- `pages/search.tsx`

### Before this PR
image

### After this PR
[LinksHub.webm](https://github.com/rupali-codes/LinksHub/assets/130365071/783c7d28-0f79-4549-a24c-d72846e2e73e)

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.

## Note to reviewers
Hey @rupali-codes, @CBID2, @ujjawaltyagii  please review this PR.
Thanks.

### CODE REVIEW

**Review by CBID2 — COMMENTED** [review]
Looks ok to me

**Review by k-deepak04 — APPROVED** [review]
Looks good

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by harmeetsingh11** [comment]
Thanks for merging the PR.
Please add gssoc23 label and level to the PR, otherwise my PR won't count.

**Comment by CBID2** [comment]
Ohh sorry. You didn't check the GSOC box in the issue form. That's why I didn't pick it @harmeetsingh11

**Comment by rupali-codes** [comment]
@CBID2 & @k-deepak04 you guys should be a little careful, they have removed the entier section of topbar

image

I'm reverting this PR because of the glitched have been made, @harmeetsingh11 please make a sperate PR and be careful

**Comment by harmeetsingh11** [comment]
@rupali-codes I'm sorry for the inconvenience caused by the glitches in the PR. 
I have made a fresh PR, please review it.
Thanks

**Comment by k-deepak04** [comment]
> @CBID2 & @k-deepak04 you guys should be a little careful while merging the PRs, they have removed the entier section of topbar
> 
> image
> 
> I'm reverting this PR because of the glitched have been made, @harmeetsingh11 please make a sperate PR and be careful

i noticed that he removed the thing query ="typed in the search box", but i thought it was okay to remove that as user knows what he typed and not that relevant.
i'll make sure to ask you before making decesion myself, soory for the inconvinence :(
won't happen again

**Comment by rupali-codes** [comment]
@k-deepak04 its fine, you don't have to be sorry, just be a little careful :)

**Pull request merged**
