### PR TITLE
feat: add videos subcategory in frontend

### LINKED ISSUE #889: [ADD] Videos under frontend
### Category Name

none

### Subcategory Name

Videos

### Additional Context

- It would be similar to images, just that the resources where free stock videos are available, like https://pixabay.com/videos/.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [ ] I have checked that this category does not exist
- [X] I have checked that this subcategory does not exist
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #889 

## Screenshots

image

### CODE REVIEW

**Comment by rupali-codes** [comment]
@Anmol-Baranwal what kinda videos you are going to add there?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal what kinda videos you are going to add there?

It is similar to images: websites that provide stock videos, as I already mentioned in the issue.

image

**Comment by rupali-codes** [comment]
> > @Anmol-Baranwal what kinda videos you are going to add there?
> 
> It is similar to images: websites that provide stock videos, as I already mentioned in the issue.
> 
> It should be categorized under the frontend category because many websites utilize short videos as backgrounds or incorporate them to create a slightly interactive experience.
> 
> image

i see, thanks. could you please add the resource you have mentioned in issue in this subcategory?

**Comment by Anmol-Baranwal** [comment]
> > > @Anmol-Baranwal what kinda videos you are going to add there?
> > 
> > 
> > It is similar to images: websites that provide stock videos, as I already mentioned in the issue.
> > It should be categorized under the frontend category because many websites utilize short videos as backgrounds or incorporate them to create a slightly interactive experience.
> > image
> 
> i see, thanks. could you please add the resource you have mentioned in issue in this subcategory?

Done!

**Review by rupali-codes — APPROVED** [review]
looks awesome

**Review by ujjawaltyagii — APPROVED** [review]
Looks good to me 💯

**Pull request merged**
