### PR TITLE
added react state management tools like redux and recoil

### PR DESCRIPTION
**Pull request by surajmaurya0**
## Changes proposed
Add State management tool in react js section

##ScreenShot
image

## Changes proposed
Added Rust language

##ScreenShot
image

### CODE REVIEW

**Comment by rupali-codes** [comment]
Hey @surajmaurya0 can you please reference the the respective issue and also resolve merge conflicts

**Comment by surajmaurya0** [comment]
> resolve merge conflicts

## Added two card in React js section 
 #### react-redux
  #### recoil
### both are help for state management in react 

## Added One New language in language section
#### Rust 
###  Rust is used for  performance, safety, and memory management

**Comment by k-deepak04** [comment]
@surajmaurya0 please add closes #issue number so that issue linked to it closes automatically

**Review by k-deepak04 — DISMISSED** [review]
LGTM

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by k-deepak04 — APPROVED** [review]
looks, fine to me

**Pull request merged**
