### PR TITLE
fix: overflowing content bug

### LINKED ISSUE #732: [BUG] Overflow of content in small devices
### Description

I have attached a screenshot, and the box is overflowing horizontally due to a lack of responsiveness.

What I can do is check the responsiveness of each category on very small devices.

### Screenshots

responsiveness

### Any additional information?

I will make sure to review the code for the necessary conventions and code style to ensure I follow the same.

Additionally, if you require me to adjust the font size very specifically, please let me know in advance.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Fixes Issue

Closes #732 

## Changes proposed

- I have fixed the responsive bug.

## Screenshots

|  Before | Updated |
|:--------:|:----------:|
| before | after |

## Note to reviewers

- I have properly tested, and I believe this is the sole reason for the bug.
- I have checked; other contents are not impacted.
- I have verified this by increasing the header text and adding other custom values.

### CODE REVIEW

**Comment by rupali-codes** [comment]
@Anmol-Baranwal i can not see this overflowing issue in linkshub.dev for some reason, could you please tell me what is the screen resolution are having?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal i can not see this overflowing issue in linkshub.dev for some reason, could you please tell me what is the screen resolution are having?

It only occurs for `https://www.linkshub.dev/open-source-blogs`, specifically, starting from a width of 616px or less.

> I am using the Chrome browser.

**Review by CBID2 — DISMISSED** [review]
LGTM!

**Comment by Anmol-Baranwal** [comment]
Done as per suggestion, this commit fixes a bug where text is being truncated on small devices.

|  Small Devices | Large Devices |
|:----------------:|:----------------:|
| small screen | large screen |

**Comment by rupali-codes** [comment]
> Done as per suggestion, this commit fixes a bug where text is being truncated on small devices.
> 
> Small Screen Size	Medium & Higher Screen Size
> small screen	large screen

Thanks, looks perfect to me

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
