### PR TITLE
add new links

### LINKED ISSUE #173: [Add] Behance
### URL

https://www.behance.net/

### Description of the above provided site

Behance is the world's largest creative network for showcasing and discovering creative work.

### Category

Frontend

### Sub Category

Design Inspiration

### LINKED ISSUE #174: [Add] Refero Design
### URL

https://refero.design/

### Description of the above provided site

Get inspired by the best examples of product design

### Category

Frontend

### Sub Category

Design Inspiration

### LINKED ISSUE #175: [Add] Page Collective
### URL

https://pagecollective.com/

### Description of the above provided site

Get inspired and keep up with the latest landing page design trends.

### Category

Frontend

### Sub Category

Design Inspiration

### LINKED ISSUE #176: [Add] Landingfolio
### URL

https://www.landingfolio.com/

### Description of the above provided site

 Landingfolio features the best landing page designs, templates, component and more on the web. Get inspired by real landing page examples curated by us to ensure the highest quality.

### Category

Frontend

### Sub Category

Design Inspiration

### LINKED ISSUE #177: [Add] Land-book
### URL

https://land-book.com/

### Description of the above provided site

Find the best hand-picked website design inspiration.

### Category

Frontend

### Sub Category

Design Inspiration

### LINKED ISSUE #178: [Add] Lapa Ninja
### URL

https://www.lapa.ninja/

### Description of the above provided site

Lapa Ninja is a gallery featuring the best 5443 landing page examples, free books for designers and free UI kits from around the web.

### Category

Frontend

### Sub Category

Design Inspiration

### LINKED ISSUE #179: [Add] Landings dev
### URL

https://landings.dev/

### Description of the above provided site

Discover hundreds of landing pages created by leading companies for your design inspiration. Landings

### Category

Frontend

### Sub Category

Design Inspiration

### LINKED ISSUE #180: [Add] Awwwards
### URL

https://www.awwwards.com/

### Description of the above provided site

Awwwards are the Website Awards that recognize and promote the talent and effort of the best developers, designers and web agencies in the world.

### Category

Frontend

### Sub Category

Design Inspiration

### LINKED ISSUE #182: [Add] SaaS Landing Page
### URL

https://saaslandingpage.com/

### Description of the above provided site

SaaS Landing Page showcases the best landing page examples created by top-class SaaS companies. Get ideas and inspirations for your next design project.

### Category

Frontend

### Sub Category

Design Inspiration

### LINKED ISSUE #185: [Add] SiteInspire
### URL

https://www.siteinspire.com/

### Description of the above provided site

Siteinspire is a showcase of the finest web and interactive design.

### Category

Frontend

### Sub Category

Design Inspiration

### LINKED ISSUE #186: [Add] Best Website Gallery
### URL

https://bestwebsite.gallery/

### Description of the above provided site

The most beautiful websites handpicked for you — since 2008!

### Category

Frontend

### Sub Category

Design Inspiration

### PR DESCRIPTION
**Pull request by Oyebolade**
## Fixes Issue
Closes #173 
Closes #174 
Closes #175 
Closes #176 
Closes #177 
Closes #178 
Closes #179 
Closes #180 
Closes #182 
Closes #185 
Closes #186

## Changes proposed
I added new links to design inspiration(Behance, Refero Design, Page Collective, Landingfolio, Land-book, Lapa Ninja, Landings dev, Awwwards, SaaS Landing Page, SiteInspire and Best Website Gallery.)

## Screenshots

design inspiration1
design inspiration2
design inspiration3

### CODE REVIEW

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Thank you so much, looks perfect, could you please format the code?

**Comment by Oyebolade** [comment]
You are welcome, I don't understand you, which code should e format and how will I format it?

**Comment by rupali-codes** [comment]
> You are welcome, I don't understand you, which code should e format and how will I format it?

You can use prettier, a vs code extension. Let's know for any issues

**Review by Eugene44-hub — APPROVED** [review]

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Hi, Thank you so much,
could you please remove the ids? we have updated the structure for sub categories..

**Pull request merged**
