### PR TITLE
chore: added WilliamFiset link under dsa youtube

### LINKED ISSUE #707: [Add] <Add WilliamFiset Channel link to Youtube/Data Structures>
### Site URL

https://www.youtube.com/@WilliamFiset-videos/featured

### Description of the above provided site

One of the best channels to understand DSA concepts and mathematics that will be helpful for Competitive Programming.

### Category

Youtube

### Sub Category

Data Structures

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by azmi-nabeel**
## Fixes Issue

Closes #707 

## Changes proposed

Added link to WilliamFiset Youtube channel to dsa subcategory under youtube category.

## Screenshots

Screenshot 2023-05-24 184658

## Note to reviewers

Please review my PR. 
Thank you.

### CODE REVIEW

**Review by rupali-codes — CHANGES_REQUESTED** [review]
Please remove unnecessary spaces

**Comment by azmi-nabeel** [comment]
I have made the suggested changes.

**Review by CBID2 — CHANGES_REQUESTED** [review]
Hi @azmi-nabeel! :) I pointed out a proofreading error in my inline comment. In the future, consider running your descriptions through Grammarly or Spellcheck before making a pull request. Other than that, you're off to a great start! :)

**Comment by azmi-nabeel** [comment]
Will make sure to proofread before making PRs next time onwards.👍

**Review by rupali-codes — APPROVED** [review]
looks good

**Review by CBID2 — APPROVED** [review]
Great job @azmi-nabeel! 😄 LGTM! 😄

**Comment by CBID2** [comment]
@rupali-codes, we're going to need your force push.

**Pull request merged**
