### PR TITLE
added chai aur react youtube channel for webdev #hacktoberfest2023

### PR DESCRIPTION
**Pull request by pratikkumar399**
## Changes proposed

Added Chai aur React Youtube channel for awesome content around React and Javascript

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @pratikkumar399. Welcome to LinksHub! :) We don't accept spam pull requests, so I'm putting yours in draft mode for now. In the future, please wait until your issue has been approved and assigned to you before you submit a pull request. Refer to our [Contributing Guide](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md) to learn how to effectively contribute to the project. Happy Contributing! 😊

**Comment by Anmol-Baranwal** [comment]
@pratikkumar399 
Please do it properly, if you need to know anything let us know. We will remove the spam label if you do things properly.

**Comment by Anmol-Baranwal** [comment]
Removing the spam label. He has created #2018

**Comment by CBID2** [comment]
> Removing the spam label. He has created #2018 

I can't reopen the PR @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
@CBID2 
He has deleted the branch, he will create a new one.

**Pull request closed without merging**
