### PR TITLE
 maintainer updated

### LINKED ISSUE #1488: [BUG] Update the maintainers data
### Description

Update the maintainers database, and add my github there

image

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by k-deepak04**
## Issue

closes #1488 

## Screenshots

image

### CODE REVIEW

**Comment by k-deepak04** [comment]
@CBID2 please review and merge

**Review by CBID2 — APPROVED** [review]
LGTM

**Comment by k-deepak04** [comment]
Thanks, any other things to work on?, i'm also discovering thing to fix this weekend.
Let me know if you have any idea @CBID2

**Comment by CBID2** [comment]
> Thanks, any other things to work on?, i'm also discovering thing to fix this weekend.
> 
> Let me know if you have any idea @CBID2 

I'm still stuck on this one @k-deepak04: https://github.com/rupali-codes/LinksHub/issues/1080

**Comment by k-deepak04** [comment]
> > Thanks, any other things to work on?, i'm also discovering thing to fix this weekend.
> > Let me know if you have any idea @CBID2
> 
> I'm still stuck on this one @k-deepak04: #1080

Error 404 :) lol I'm not that good using automations, maybe Anmol can help you with that.

**Review by rupali-codes — APPROVED** [review]

**Pull request merged**
